  <table border=0 cellpadding=0 cellspacing=6>
  <tr>
  <td><img src="/images/spacer.gif" height=1 width=2 alt="spacer"></td>
  <td>
    <font size=-1>

    <img src="/images/webding.png" height=8 width=8 border=0 alt="dot">&nbsp;
    <a href="/fr/links.phtml">Logiciels Financiers</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0 alt="dot">&nbsp;
    <a href="/en/articles.phtml">GnuCash dans la presse</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0 alt="dot">&nbsp;
    <a href="/en/promote.phtml">Bannieres GnuCash !</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0 alt="dot">&nbsp;
    <a href="/en/history.phtml">Historiquee &amp; Remerciements</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0 alt="dot">&nbsp;
    <a href="/en/quiz-results.phtml">Resultats des Sondages</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0 alt="dot">&nbsp;
    <a href="/en/sizing.phtml">Dimensionnement</a><br>

    </font>

  </td>
  </tr>
  </table>
