  <table border=0 cellpadding=0 cellspacing=6 width='100%'>
  <tr>
  <td><img src="/images/spacer.gif" height=1 width=2 alt="spacer"></td>
  <td>
    <font size=-1>

    <img src="/images/webding.png" height=8 width=8 border=0 alt="dot">&nbsp;
    <a href="/en/architecture.phtml">Architecture du Systeme</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0 alt="dot">&nbsp;
    <a href="/fr/roadmap.phtml">Orientations du projet</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0 alt="dot">&nbsp;
    <a href="http://linas.org/linux/gnucash/projects.html">Buts du projet</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0 alt="dot">&nbsp;
    <a href="https://cvs.gnucash.org/cgi-bin/cvsweb.cgi/">Parcourir le code source</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0 alt="dot">&nbsp;
    <a href="/en/hacking.phtml">acces CVS</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0 alt="dot">&nbsp;
    <a href="/trans/">Traduction</a><br>

    </font>

  </td>
  </tr>
  </table>
