  <table border=0 cellpadding=0 cellspacing=6>
  <tr>
  <td><img src="/images/spacer.gif" height=1 width=2 alt="spacer"></td>
  <td>

      <form action="/en/search.phtml" method="get" enctype="application/x-www-form-urlencoded">
      <input type=text name=words size=15>
      <br><font size="-2">Methode de tri :</font>
      <select name="sort">
      <option value="sort">Standard
      <option value="time">Chronologique
      <option value="revtime">Chronologique (inversée)
      </select>
      </form>


  </td>
  </tr>
  </table>
