<!-- MENU:START -->

<table border=0 cellpadding=4 cellspacing=0 width="100%">
<tr><td bgcolor="#cacaf7">
  <img border=0 src="/images/webding.png" alt="dot"> <b>Informations Generales</b>
  <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/menu/menu-general.phtml"); ?>
  </td></tr>
<tr><td>
  <img border=0 src="/images/webding.png" alt="dot"> <b>Documentation</b>
  <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/menu/menu-documentation.phtml"); ?>
  </td></tr>
<tr><td>
  <img border=0 src="/images/webding.png" alt="dot"> <b>Aide</b>
  <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/menu/menu-help.phtml"); ?>
  </td></tr>
<tr><td>
  <img border=0 src="/images/webding.png" alt="dot"> <b>Telechargement</b>
  <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/menu/menu-downloads.phtml"); ?>
  </td> </tr>
<tr><td>
  <img border=0 src="/images/webding.png" alt="dot"> <b>Informations Developpeur</b>
  <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/menu/menu-developer.phtml"); ?>
  </td></tr>
<tr><td>
  <img border=0 src="/images/webding.png" alt="dot"> <b>Autres Informations</b>
  <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/menu/menu-other.phtml"); ?>
  </td></tr>
<tr><td>
  <img border=0 src="/images/webding.png" alt="dot"> <b>Recherche</b>
  <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/menu/menu-search.phtml"); ?>
  </td></tr>
</table>

<!-- MENU:END -->
