  <table border=0 cellpadding=0 cellspacing=6>
  <tr>
  <td><img src="/images/spacer.gif" height=1 width=2 alt="spacer"></td>
  <td>
    <font size=-1>

    <img src="/images/webding.png" height=8 width=8 border=0 alt="dot">&nbsp;
    <a href="/fr/index.phtml">Sommaire / Actualités </a><br>

    <img src="/images/webding.png" height=8 width=8 border=0 alt="dot">&nbsp;
    <a href="/fr/features.phtml">Fonctionnalités</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0 alt="dot">&nbsp;
    <a href="/fr/screenshots.phtml">Capture D'ecran</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0 alt="dot">&nbsp;
    <a href="/fr/contribute.phtml">Comment Aider</a><br>

<!--
    <img src="/images/webding.png" height=8 width=8 border=0 alt="dot">&nbsp;
    <a href="/fr/quiz.phtml">Sondages Utilisateurs</a><br>
-->
 
    <img src="/images/webding.png" height=8 width=8 border=0 alt="dot">&nbsp;
    <a href="/fr/required.phtml">Logiciels Requis</a><br>
 
    </font>
 
  </td>
  </tr>
  </table>
