<?php $title = "Architecture"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-main-developer.phtml"); ?>

</td>
<td valign=top width=75%>

<h1>Architectural Overview</h1>

<font size=-1>
GnuCash is written primarily in two languages: C and Scheme.  
The engine/server is written in C primarily for speed, 
portability, stability and historical purposes.  Much of the
day-to-day workhorse code is written in Scheme, primarily
for its power, expressiveness and ease of development.
The user interface is GTK/gnome, some of it done up in C,
some in scheme, and some with the 
GUI designer tool <a href="http://glade.pn.org">glade</a>.

<p>
GnuCash is modular, thereby allowing separate individuals
to maintain, develop and enhance certain modules without
disturbing the overall development.  (Never mind that 
modules help avoid spaghetti code and nasty, ugly hacks).
The interfaces between modules are documented, and, for the 
most part, stable and unchanging.
<a href="/images/diagrams/components.png">This block diagram 
shows major components.</a>

<br><br><b>
GnuCash currently consists of the following modules:</b>
<br><br>
</font>

<table border=0 cellpadding=1 cellspacing=0 width="100%">
  <tr>
  <td valign=middle align=center bgcolor=#666699>
   <table border=0 cellpadding=5 cellspacing=1 bgcolor=#cccccc width="100%">
   <tr>
     <td bgcolor=#666699 width=25%><font color=#ffffff><b>Module</b></td>
     <td bgcolor=#666699 width=50%><font color=#ffffff><b>Description</b></td>
   </tr>
   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><b>Engine</b></td>
       </tr>
       </table>
     </td>
     <td valign=top>
<p>The <dfn>Engine</dfn> (located under the <code>src/engine/</code> 
directory in the
GnuCash codebase) provides an interface for creating, manipulating, and
destroying three basic financial entities: Accounts, Transactions (known
as Ledger Entries in accounting practice), and Splits (known as Journal
Entries). These three entities are the central data structures of the
GnuCash financial data model,
<a href="/images/diagrams/structures.png">as illustrated in this diagram.</a>

<p>The Engine code contains no GUI code whatsoever, and is essentially
OS-neutral. It is written entirely in C.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><b>Query</b></td>
       </tr>
       </table>
     </td>
     <td valign=top>
<p>The <dfn>Query</dfn> module (<code>src/engine/Query*</code>) provides an interface
into the engine for finding transactions based on a set of criteria,
such as description, date posted, account membership, etc. Simple
queries can be combined using standard boolean operators.
		 </td>
   </tr>
   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><b>Storage Backend</b></td>
       </tr>
       </table>
     </td>
     <td valign=top>
<p>The <dfn>Storage Backend</dfn> module (<code>src/backend/</code>) 
defines a generic interface for storing GnuCash data (into files or 
databases) or for communicating with a remote GnuCash storage server
(by any server-defined protocol).
Currently implemented and supported are the XML file backend, which
stores GnuCash data in its native XML file format, and the Postgres SQL
backend, which supports multiple simultaneous users of GnuCash.  
Additionally, there are several experimental backends (currently 
broken/unsupported): one for communicating with a GnuCash storage 
server via RPC, and another that chats, via XML across HTTP, with 
a GnuCash server.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><b>Register</b></td>
       </tr>
       </table>
     </td>
     <td valign=top>
<p>The <dfn>Register</dfn> (<code>src/register/</code>) implements a ledger-like
GUI that allows the user to dynamically enter dates, prices, memos
descriptions, etc. in an intuitive fashion that should be obvious to
anyone who's used a checkbook register. The code is highly configurable,
allowing the ledger columns and rows to be laid out in any way, with no
restrictions on the function, type, and number of columns/rows. For
example, one can define a ledger with three date fields, one price
field, and four memo fields in a straightforward fashion. Cell handling
objects support and automatically validate date entry, memo entry
(w/auto-completion), prices, combo-boxes (pull-down menus), and
multi-state check-boxes. Cells can be marked read-write, or
output-only. Cells can be assigned unique colors. The currently
active ledger row-block can be highlighted with a unique color.

<p>The register code is completely independent of the engine code, knows
nothing about accounting or any of the other GnuCash subsystems. It
can be used in independent projects that have nothing to do with
accounting.
		 </td>
   </tr>
   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><b>Reports &amp; Graphs</b></td>
       </tr>
       </table>
     </td>
     <td valign=top>
<p>The <dfn>Reports &amp Graphs</dfn> module (<code>src/report/</code>)
is a scheme (guile) based system to create balance sheets, profit &amp; 
loss statements, barcharts, piecharts, <i>etc.</i>  It uses the Query
API to fetch and format data, which is then converted into HTML and 
displayed with the gtkhtml widget.  Graphs are implemented in Guppi,
(&lt;<code>http://www.gnome.org/guppi</code>&gt;).
and are embedded (as live graphs) directly in the HTML.

		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><b>Price Quotes</b></td>
       </tr>
       </table>
     </td>
     <td valign=top>
<p>The <dfn>Price Quotes</dfn> module (<code>src/quotes</code>) is 
a wrapper around the Finance::Quote Perl module, used to 
fetch stock price data off the Internet and insert it into the GnuCash
Engine. The Finance::Quote module is available at SourceForge (or 
through CPAN). This module can fetch
price quotes from many different sources including Yahoo, Yahoo Europe,
and some international exchanges. Before a new data source can be
added to GnuCash, it must be added to Finance::Quote first.

<p>The Finance::Quote module also supports fetching currency exchange
rates. GnuCash will be extended to allow the fetching and use of
currency exchange rates.
		 </td>
   </tr>
   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><b>User Preferences</b></td>
       </tr>
       </table>
     </td>
     <td valign=top>
<p>The <dfn>User Preferences</dfn> module (<code>src/app-utils/</code>)
provides an infrastructure for defining both
user-configurable and internal preferences. Preferences are defined in
scheme using several predefined preference types such as boolean,
string, date, etc. Preferences are 'implemented' by providing a GUI
which allows the user to see and change preference values. An API
is provided to query preference values and to register callbacks
which will be invoked when preferences change.

<p>Preference values which are different from the default values
are stored as scheme forms in a user-specific preferences file
(<code>~/.gnucash/config.auto</code>). This file is automatically
loaded upon startup.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><b>Data Import &amp; Export</b></td>
       </tr>
       </table>
     </td>
     <td valign=top>
<p>The <dfn>Import</dfn> module (<code>src/import-export/</code>) provides
functionality for importing QIF (Quicken Interchange Format) data files and
OFX (Open Financial Exchange) files into GnuCash.  One of the difficult 
aspects of importing data from a file is what to do if the file contains
some data that has already been entered into GnuCash.  This can happen
when the imported file is a bank statement obtained periodically
from a website: each time it is fetched, it might contain transactions 
that were previously reported.  Thus, to perform file import correctly,
one must have a fairly sophisticated transaction matcher that can
detect and properly handle (ignore) duplicate transactions.  This
pattern matching is generically useful, and is used by the HCBI
subsystem.  (HCBI is an online banking system available to residents
of Germany).


		 </td>
   </tr>
   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><b>Small Business Features</b></td>
       </tr>
       </table>
     </td>
     <td valign=top>
<p>Business features (<code>src/business/</code>)
     (To Be Written)


		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><b>Recurring Transactions</b></td>
       </tr>
       </table>
     </td>
     <td valign=top>
     (To Be Written)


		 </td>
   </tr>
   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><b>GnuCash</b></td>
       </tr>
       </table>
     </td>
     <td valign=top>
<p>The GnuCash module (<code>src/gnome</code> and other directories)
is the main GUI application. It consists of a
collection of miscellaneous GUI code to glue together all of the pieces
above into a coherent, point-and-click whole. It is meant to be easy to
use and intuitive to the novice user without sacrificing the power and
flexibility that a professional might expect. When people say that
GnuCash is trying to be a "Quicken or MS Money look/work/act-alike",
this is the piece that they are referring to. It really is meant to
be a personal-finance manager with enough power for the power user
and the ease of use for the beginner.

<p>Currently, the Gnome interface is the only operational interface. 
An obsolete Motif interface can be fished out of historical CVS;
but this interface has been deleted in the current CVS.
		 </td>
   </tr>
   </table>
</tr>
</table>


</td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/footer.phtml"); ?>
