<?php $title = "Contribute"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-developer-main.phtml"); ?>

<td valign=top>
<h1>How to Contribute</h1>
<font size=1>

<p>
GnuCash is an Free Software development project and the 
dynamics of contributing to it is much like any other.
What you contribute to it depends very much on your skill, 
the time you have available, and what you enjoy doing.
GnuCash is looking for beta-testers, programmers, writers, 
question-answerers, translators and all-around nice people.   

<br><br>
<table>
<tr><td>
<b>Select your talent to see where you might fit in:</b></td>
<td>
<form method=post>
<select name=contribute>
  <option value=programmer>I am a programmer</option>
  <option value=translator>I am a translator</option>
  <option value=fan>I am a fan</option>
  <option value=webmaster>I am a webmaster</option>
  <option value=writer>I am a writer/reporter</option>
</select>
<input type=submit value=Go>
</td>
</table>
</form>

<?php
  if ($contribute != "") { 
		include($GLOBALS['DOCUMENT_ROOT']."/en/contribute/contribute-".$contribute.".phtml");
  }
?>

</font>

</td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/footer.phtml"); ?>
