<?php $title = "Contribute"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-main-general.phtml"); ?>
</td>

<td valign=top>
<h1>How to Contribute</h1>

<p>
<div class='text' align='justify'>
GnuCash is an Free Software development project and the 
dynamics of contributing to it is much like any other.
What you contribute to it depends very much on your skill, 
the time you have available, and what you enjoy doing.
GnuCash is looking for beta-testers, programmers, writers, 
question-answerers, translators and all-around nice people.   
</div>

<p>

<table>
<tr><td>
<b>Select your talent to see where you might fit in:</b></td>
<td>
<form method="post" action="/en/contribute.phtml">
<select name=contribute>
  <option value=programmer
   <?php if ($contribute == "programmer") { echo ("selected"); } ?>
  >I am a programmer</option>
  <option value=translator
   <?php if ($contribute == "translator") { echo ("selected"); } ?>
  >I am a translator</option>
  <option value=fan
   <?php if ($contribute == "fan") { echo ("selected"); } ?>
  >I am a fan</option>
  <option value=webmaster
   <?php if ($contribute == "webmaster") { echo ("selected"); } ?>
  >I am a webmaster</option>
  <option value=writer
   <?php if ($contribute == "writer") { echo ("selected"); } ?>
  >I am a writer/reporter</option>
</select>
<input type=submit value=Go>
</form>

</td>
</table>

<hr noshade>
<?php
  if ($contribute != "") { 
		include($GLOBALS['DOCUMENT_ROOT']."/en/contribute/contribute-".$contribute.".phtml");
  }
?>


</td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/footer.phtml"); ?>
