<?php 
$title = "Documentation Project";
include("../emulate_globals_on.php");
include($toppath."/externals/en/header.phtml");
include($toppath."/en/menu/menu-main-documentation.phtml");
?>
<div id="content">

<h1>GnuCash Documentation Project</h1>

<p>This page is the home of the Gnucash Documentation Project, our goal is to
maintain a community of people working towards creation of high quality 
documentation for GnuCash.</p>

<p>Everything you need concerning GnuCash documentation should be here, if you 
notice something missing, email <a href='mailto:gnucash-devel@lists.gnucash.org'>
gnucash-devel</a> and we will add it.</p>

<div class="tblborder">
     <div class="frametitle">
         <img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
           <b>GnuCash v1.8 (current stable release)</b>
     </div>
     <div class="newsinner">
	<p>If you have a question about how to use GnuCash, 
        you are in the right place. The first thing you should do is read 
        the Help Manual and the Concepts Guide, most of your questions 
        can probably be answered by these documents.</p>
	<p>The Help Manual is designed to be a quick reference of how to
        accomplish specific tasks and how to use the features in GnuCash. The
        Concepts Guide is designed to be an in depth guide to the
        concepts behind using GnuCash with a tutorial to show how to put those
        concepts into practice.</p>
        <div style="margin-left:30%;margin-right:30%;">
        <table border=0 cellpadding=2 cellspacing=2>
	<colgroup><col width="50%"><col width="50%"></colgroup>
	<tr><td align="center" class="tblbanner">
        <span class="smalltext"><b>Help Manual</b><br>
        HTML: <a href="../docs/v1.8/C/gnucash-help/help.html">English</a> | 
        <a href="../docs/v1.8/de_DE/gnucash-help/help.html">Deutsch</a><br>
        PDF: <a href="../docs/gnucash-help.pdf">English</a></span></td>
        <td align="center" class="tblbanner">
        <span class="smalltext"><b>Concepts Guide</b><br>
        HTML: <a href="../docs/v1.8/C/gnucash-guide/">English</a><br>
        PDF: <a href="../docs/gnucash-guide.pdf">English</a>
	</span></td></tr></table>
        </div>
	<p>Please send an email to the 
	<a href='mailto:gnucash-user@lists.gnucash.org'>gnucash-user</a>
        mailing list if you cannot find a satisfactory answer to your 
	question within either the Help Manual or the Concepts Guide. 
	We <b>want</b> feedback from you, it is only through your comments 
	that we know how to modify the documentation.</p>
	<p>Additionally, you can talk to someone via IRC at irc.gnome.org 
	channel "gnucash" about your question.  Another resource is the 
        <a href='http://gnomesupport.org/wiki/index.php/GnuCash'>English</a> 
        or
        <a href='http://linuxwiki.de/GnuCash'>Deutsch</a> 
        GnuCash wikis.  A wiki is an interactive 
        website where registered users can ask and answer questions.</p>
   </div>
</div>

<div>&nbsp;</div>

<div class="tblborder">
     <div class="frametitle">
        <img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
         <b>User Contributed Documentation</b>
     </div>
     <div class="newsinner">
	<p>Some people have written HOWTO guides or tutorials.  
	Note: the information presented in these sources may or may not 
	be updated to the most recent version of GnuCash. If you are 
	interested in doing development work on these documents, you should 
        contact the original authors.</p>
    <ul>
    <li><a href="http://code.neil.williamsleesmill.me.uk/otherdocs.html">Neil Williams GnuCash documentation</a>
    <li><a href="http://www.aerospacesoftware.com/GNU_Cash_for_Business_users_Howto_Guide.html">GnuCash for Business Users</a> 
    (<a href="http://www.linas.org/mirrors/www.aerospacesoftware.com/2003.06.21/GNU_Cash_for_Business_users_Howto_Guide.html">mirror</a>)
    <li><a href="http://www.ncsysadmin.org/july2001/ncsa-gnucash-talk.html">Joe Mack's Tutorial</a>
    <li><a href="http://www.object-refinery.com/gnucash/index.html">Dave Gilbert's User Guide (PDF)</a>
    </ul>
    </div>
</div>

<div>&nbsp;</div>

<div class="tblborder">
     <div class="frametitle">
         <img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
           <b>Older GnuCash Documentation</b>
     </div>
     <div class="newsinner">
	<p>This section contains all the older GnuCash documentation.  
	If you are using one of these old versions of GnuCash, it is 
	highly recommended that you upgrade 
        to the latest stable version.</p>
        <ul>
        <li><b>GnuCash v1.6</b>: 
        <a href="../docs/v1.6/C/">English</a> | 
        <a href="../docs/v1.6/de_DE/">Deutsch</a> | 
        <a href="../docs/v1.6/es/">Espagnol</a> | 
        <a href="../docs/v1.6/pt_PT/">Portugu&ecirc;s</a></li>
        </ul>
        <ul>
        <li><b>GnuCash v1.4</b>:
        <a href="../docs/fr/">Fran&ccedil;ais</a></li>
        </ul>
   </div>
</div>

<div>&nbsp;</div>

<div class="tblborder">
     <div class="frametitle">
         <img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
         <b>Documentation Development</b>
     </div>
     <div class="newsinner">
        <!--
        This is the current snapshot of the documentation in development.  
	This is only valid for the future version of GnuCash, please do not 
	use with the current stable release.  
        <br>
        HTML: <a href="../docs/v1.10/C/gnucash-guide/">Concepts Guide</a>
        or the <a href="../docs/v1.10/C/gnucash-help/help.html">Help Manual</a>.
`        -->
        <p>We track bugs and feature requests in <a href='http://bugzilla.gnome.org/'>gnome's bugzilla</a>,
        maybe you would like to see a list of all open 
        <a href="http://bugzilla.gnome.org/buglist.cgi?product=GnuCash&amp;component=Documentation&amp;bug_status=UNCONFIRMED&amp;bug_status=NEW&amp;bug_status=ASSIGNED&amp;bug_status=REOPENED&amp;email1=&amp;emailtype1=substring&amp;emailassigned_to1=1&amp;email2=&amp;emailtype2=substring&amp;emailreporter2=1&amp;changedin=&amp;chfieldfrom=&amp;chfieldto=Now&amp;chfieldvalue=&amp;short_desc=&amp;short_desc_type=substring&amp;long_desc=&amp;long_desc_type=substring&amp;bug_file_loc=&amp;bug_file_loc_type=substring&amp;status_whiteboard=&amp;status_whiteboard_type=substring&amp;keywords=&amp;keywords_type=anywords&amp;op_sys_details=&amp;op_sys_details_type=substring&amp;version_details=&amp;version_details_type=substring&amp;cmdtype=doit&amp;order=Reuse+same+sort+as+last+time&amp;form_name=query">
documentation bugs</a>?</p>
        <p>Interesting Links:<br>
	The following links are for further sites that can help with the
	documentation and review process.<br><p>
	<a href='http://www.docbook.org'> DocBook: The Definitive Guide.</a><br>
	<a href='http://www.sagehill.net/docbookxsl/'>DocBook XSL: The Complete Guide</a>.<br>
	<a href='http://developer.gnome.org/projects/gup/hig/1.0/'> GNOME Human Interface
Guidelines</a></p>
        <p>For both reviewers and documentation writers:<br>
	Please read the following guides. The new docs are based on the 
	GNOME2 XML docbook system.
	Everyone wishing to help please
	follow these guides where possible when reviewing and/or writing docs.</p>
        <p><a href='http://developer.gnome.org/projects/gdp/styleguide.html'>
The GNOME Documentation Style Guide</a><br>
<a href='http://developer.gnome.org/projects/gdp/handbook.html'>
The GNOME Handbook of Writing Software Documentation</a></p>
        <p>We suggest also subscribing to <a href='mailto:gnucash-devel@lists.gnucash.org'>gnucash-devel</a>.</p>
        <p>Reviewers;</p>
        <p>Please check out the documentation module from the GnuCash CVS -
	gnucash-docs. For those not familiar with cvs, the GnuCash website has a
	<a href='/en/hacking.phtml'>description.</a> The only change
	to get the docs is to change the checkout gnucash to checkout
	gnucash-docs. You can also start from the current docs tarball.</p>
        <p>The best way of retaining comments about docs in an easy to find
	way for everyone would be to use <a href='http://bugzilla.gnome.org/'>bugzilla.gnome.org</a> to file the bugs
	under documentation. This can also be done using bug-buddy.</p>
        <p>Writers;</p>
        <p>Also checkout the docs cvs as above. The usual procedure for
	contributors to GnuCash is to initially submit patches to the
	<a href='mailto:gnucash-patches@lists.gnucash.org'>gnucash-patches</a> 
	mailing list. We will handle getting the patches added into CVS 
	until you are given an account. You can also add the 
	patch to a bug report in bugzilla if you wish.</p>
        <p>Please let other writers know which
	section you wish to tackle. Please forward this to 
	<a href='mailto:gnucash-devel@lists.gnucash.org'>gnucash-devel</a> so
	that people can say 'hey I'm doing that already' or 
	'go ahead and do it'.</p>
        <p>You may also want to retain a local copy of the old documentation to
	refer to when writing. This still has a lot of useful information in it
	which hasn't been transferred to the new docs</p>
    </div>
</div>

</div>

<?php include($toppath."/externals/en/footer.phtml"); ?>

