<?php $title = "Donations"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-main.phtml"); ?>

</td>
<td valign="top" width="98%">

<!-- ========================================================== -->
<h1>Donating to the GnuCash Project</h1>

<font size=-1>

You can support the continued development of GnuCash, or simply
show your appreciation for what we've already done, by making a 
financial gift to the GnuCash Project.  The GnuCash Project
is an unincorporated entity, a loose association of the authors
and developers who are involved with maintaining, extending 
and promoting the GnuCash software, documentation and website.
<p>
Show your appreciation by donating to the GnuCash Project today!
Currently, we can only accept PayPal donations made through the 
<a href="http://sourceforge.net/donate/index.php?group_id=192">SourceForge 
donation system</a>.  
If you wish to make a donation in another form, please contact the 
<a href="https://lists.gnucash.org/mailman/listinfo/gnucash-devel">gnucash-devel</a>
mailing list.  Please note that the donation system is anonymous;
The PayPal registration info is not sent to us, and so we typically
don't know who made a donation, and thus can't mail out a thank-you note.
Feel free to announce your donation publicly on the mailing list,
or in private.  We thank you now, in advance. 
Registered SourceForge Users who are logged in when they make a donation
will see their names emblazoned in electrons on the 
<a href="https://sourceforge.net/project/project_donations.php?group_id=192">GnuCash 
donation website</a>.  Amounts are not shown.
<p>
In the spirit of openness an public responsibility, we present a summary 
of current finances below.  Announcements will be made when funds are 
disbursed; we will keep this web page updated periodically.

<p>


<table border="0" cellpadding=1 cellspacing="0" width="100%">
  <tr>
  <td valign="middle" align="center" bgcolor="#666699">
   <table border="0" cellpadding=5 cellspacing=1 bgcolor=#cacaf7 width="100%">
   <tr>
     <td bgcolor=#666699 width=15%><font color="#ffffff"><b>Date</b></td>
     <td bgcolor=#666699 width=55%><font color="#ffffff"><b>Description</b></td>
     <td bgcolor=#666699 width=15%><font color="#ffffff"><b>Amount</b></td>
     <td bgcolor=#666699 width=15%><font color="#ffffff"><b>Current Balance</b></td>
   </tr>
   <!-------------------------------------------------------------->
   <tr bgcolor="#ececff">
     <td valign="top">22 June 2004</td>
     <td valign="top">Donations Received, March 2004 to 22 June 2004</td>
     <td valign="top">$525.95</td>
     <td valign="top">$525.95</td>
   </tr>
   <!-------------------------------------------------------------->
   <tr bgcolor="#ffffff">
     <td valign="top">22 June 2004</td>
     <td valign="top">Current Balance</td>
     <td valign="top"></td>
     <td valign="top">$525.95</td>
   </tr>
   <!-------------------------------------------------------------->
   </table>
</tr>
</table>

      </font>
<!-- ========================================================== -->
  </td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/footer.phtml"); ?>
