<?php $title = "Donations"; ?>
<?php if (!ini_get('register_globals')) {
 include("../emulate_globals_on.php");
}
include($toppath."/externals/en/header.phtml");
include($toppath."/en/menu/menu-main.phtml");
?>

<div id="content">

<h1>Donating to the GnuCash Project</h1>

<p>You can support the continued development of GnuCash, or simply
show your appreciation for what we've already done, by making a
financial gift to the GnuCash Project.  The GnuCash Project
is an unincorporated entity, a loose association of the authors
and developers who are involved with maintaining, extending
and promoting the GnuCash software, documentation and website.</p>

<p>Show your appreciation by donating to the GnuCash Project today!
Currently, we can only accept PayPal donations made through the
<a href="http://sourceforge.net/donate/index.php?group_id=192">SourceForge
donation system</a>.
If you wish to make a donation in another form, please contact the
<a href="https://lists.gnucash.org/mailman/listinfo/gnucash-devel">gnucash-devel</a>
mailing list.  Please note that the donation system is anonymous;
The PayPal registration info is not sent to us, and so we typically
don't know who made a donation, and thus can't mail out a thank-you note.
Feel free to announce your donation publicly on the mailing list,
or in private.  We thank you now, in advance.
Registered SourceForge Users who are logged in when they make a donation
will see their names emblazoned in electrons on the
<a href="https://sourceforge.net/project/project_donations.php?group_id=192">GnuCash
donation website</a>.  Amounts are not shown.</p>

<p>In the spirit of openness an public responsibility, we present a summary
of current finances below.  Announcements will be made when funds are
disbursed; we will keep this web page updated periodically.</p>

<div class="tblborder">
   <table style="border:none;background-color:#cacaf7;"
    cellpadding=5 cellspacing=1 width="100%">
<colgroup><col width="15%">
<col width="55%">
<col width="15%"></colgroup>
   <tr>
     <td style="background-color:#666699">
    <b style="color:white">Date</b></td>
     <td style="background-color:#666699">
    <b style="color:white">Description</b></td>
     <td style="background-color:#666699">
    <b style="color:white">Amount</b></td>
     <td style="background-color:#666699">
    <b style="color:white">Current Balance</b></td>
   </tr>
   <tr style="background-color:#ececff">
     <td valign="top">22 June 2004</td>
     <td valign="top">Donations Received, March 2004 to 22 June 2004</td>
     <td valign="top">$525.95</td>
     <td valign="top">$525.95</td>
   </tr>
   <tr style="background-color:white">
     <td valign="top">22 June 2004</td>
     <td valign="top">Current Balance</td>
     <td valign="top"></td>
     <td valign="top">$525.95</td>
   </tr>
   </table>
</div>

</div>
<?php include($toppath."/externals/en/footer.phtml"); ?>
