<?php $title = "Donations"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-main.phtml"); ?>

</td>
<td valign="top" width="98%">

<!-- ========================================================== -->
<h1>Donating to the GnuCash Project</h1>

<font size=-1>

You can support the continued development of GnuCash, or simply
show your appreciation for what we've already done, by making a 
financial gift to the GnuCash Project.  The GnuCash Project
is an unincorporated entity, a loose association of the authors
and developers who are involved with maintaining, extending 
and promoting the GnuCash software, documentation and website.
An announcement will be made when funds are disbursed; this 
web page will be updated at that time to show a balance sheet
and the funds recipients.
<p>
Show your appreciation by donating to the GnuCash Project today!
Currently, we can only accept PayPal donations made through the 
<a href="http://sourceforge.net/donate/index.php?group_id=192">SourceForge 
donation system</a>.  
If you wish to make a donation in another form, please contact the 
<a href="https://lists.gnucash.org/mailman/listinfo/gnucash-devel">gnucash-devel</a>
mailing list.  Please note that the donation system is anonymous;
The PayPal registration info is not sent to us, and so we typically
don't know who made a donation, and thus can't mail out a thank-you note.
Registered SourceForge Users who are logged in when they make a donation
will see thier names emblazoned in electrons on the 
<a href="https://sourceforge.net/project/project_donations.php?group_id=192">GnuCash 
donation website</a>.  Amounts are not shown.

      </font>
<!-- ========================================================== -->
  </td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/footer.phtml"); ?>
