<?php $title = "Features: Ease of Use"; ?>
<?php if (!ini_get('register_globals')) {
 include("../emulate_globals_on.php");
}
?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-main-general.phtml"); ?>
</td>

<td valign=top>

<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr>
  <td><img src="/images/features/features_title.png"></td>
  <td align=right><a href="javascript:window.close();"><img border=0 src="/images/close_window.png"></a></td>
</tr>
</table>

<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr><td bgcolor=#000000><img src="/images/spacer.png" height=1></td></tr>
</table>

<br>

<table cellpadding=4 cellspacing=0 border=0 width=100%>
<tr>
<td valign=top>
  <img src="/images/features/features_3_text.png"><br><br>

  with keyboard accelerators, check number auto-increment, transaction auto-completion and transaction cut-n-paste make
  entering transactions quick and smooth. 

</td>
<td valign=middle>
  <img src="/images/features/features_3_small.png">
</td>
</tr>
</table>

<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr><td bgcolor=#000000><img src="/images/spacer.png" height=1></td></tr>
</table>

<br>

<table border=0 cellspacing=0 cellpadding=0 width=100% align=center>
<tr>
  <td align=center>
	  <a href=/en/features_2.phtml><img border=0 src="/images/features/features_previous.png"></a>
		 |
	  <a href=/en/features_4.phtml><img border=0 src="/images/features/features_next.png"></a>
	</td>
</tr>
</table>

</td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/footer.phtml"); ?>
