<?php $title = "Features:Ease of Use"; ?>
<?php if (!ini_get('register_globals')) {
 include("../emulate_globals_on.php");
}
?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/externals/en/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-main-general.phtml"); ?>
</div>
<div id="content">

<div>
<img src="/images/features/features_title.png" alt="feature title">
</div>
<div class="featureblock">&nbsp;</div>

<div>
<div class="featureimage">
  <img src="/images/features/features_2_small.png">
</div>
<p class="featurepanel">
  <img src="/images/features/features_2_text.png"><br>
  A master account can have a hierarchy of detail accounts underneath it.
  This allows similar accounts types ( e.g. Cash, Bank, Stock ) to be
  grouped into one master account ( e.g. Assets ).
</p>
</div>
<div class="featureblock">&nbsp;</div>

<div class="featureplay">
 <a href=/en/features_1.phtml><img alt="back to 1"
src="/images/features/features_previous.png"></a>
 |
  <a href=/en/features_3.phtml><img alt="next slide"
 src="/images/features/features_next.png"></a>
</div>

</div>
<?php include($GLOBALS['DOCUMENT_ROOT']."/externals/en/footer.phtml"); ?>
