<?php $title = "Features"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-main-general.phtml"); ?>
</td>

<script language=javascript>
<!--
  
  function newWin(url) {
    newLoc=window.open("","","height=480,width=640,scrollbars=yes")
    newLoc.location=url
  }

// -->
</script>

<td valign=top>

<h1>Features</h1>

<!-- 
<font size=-1>
If you've been looking for a way to manage your personal finances 
under GNU/Linux, you've found it!  Designed to be easy to use,
yet powerful and flexible, GnuCash allows you to track
bank accounts, stocks, income and expenses.   As quick and intuitive
to use as a checkbook register, it is based on professional
accounting principles to ensure balanced books and accurate reports.
GnuCash is backed by an active development community and is blossoming
into a full-fledged accounting system.  Developed under the GPL, 
you have no need to worry about obsolescence, vendor lock-in,
and high-priced support: GnuCash will be there for you.
<BR>
<BR>
This web site is devoted to promoting the Gnucash.org software
development project.  We are committed to developing top-notch 
financial tools for GNU/Linux and Unix users.  This includes the 
development of programming API's and components that can be used 
to create both server and personal applications for home and business use.
By focusing on ease-of-use, modular design, architected interfaces
and well-documented code, we hope that GnuCash and its associated 
financial libraries become the choice of a GNU generation of
programmers and users.
<BR><BR>
</font>
// -->

<font size=-1>
GnuCash has long had many features that support basic accounting 
needs for individuals and families, starting with an easy-to-use
checkbook-register-style layout, and supporting things like
bank statement reconciliation, stock/fund portfolios and 
numerous reports/graphs.  But GnuCash development doesn't 
stand still, and the newest versions add support for small business
accounting as well.  German residents will also enjoy its on-line 
banking features (Sorry, on-line banking is not supported in the US; 
don't blame us, blame your bank.  Tell them to tell us the URL for 
thier OFX servers, instead of hiding it like state secrets.). 
</font>
<p>
<center>
<font size=-1>
Take a graphical tour of some of the core GnuCash features!
</font>
<BR><BR>
<!-- <a href="javascript:newWin('/en/features_1.phtml')"> -->
<a href="/en/features_1.phtml">
<img border=0 src="/images/features/features_start_the_tour.png"></a>
</center>

<center>
<font size=-1>
<BR><BR>
or dive into the 
</font>
<b><a href="/en/features_5.phtml">Complete Features List</a></b>.
</center>

</td>


<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/footer.phtml"); ?>
