<?php $title = "Features: Ease of Use"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-main-general.phtml"); ?>
</td>

<td valign=top>

<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr>
  <td><img src=/images/features/features_title.png></td>
  <td align=right><a href="javascript:window.close();"><img border=0 src=/images/close_window.png></a></td>
</tr>
</table>

<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr><td bgcolor=#000000><img src=/images/spacer.png height=1></td></tr>
</table>

<br>

<table cellpadding=4 cellspacing=0 border=0 width=100%>
<tr>
<td valign=top>
  <img src=/images/features/features_5_text.png><br><br>


<b>What's New in GnuCash 1.7.5?</b><br>
<br>
Version 1.7.x is the beta for the next 1.8.x stable release series,
and includes many new major features:

<dl>
<dt><b>Scheduled Transactions</b>
<dd>You can now create recurring 
    transactions, including automatic reminders when a 
    transaction is due, the ability to postpone a scheduled transaction
    without cancelling it, and the ability to specify only a limited 
    number of transactions.
    <br><br>
<dt><b>Mortgage &amp; Loan Repayment Druid</b></dt>
<dd>A guided dialogue for setting up loan payments as
    scheduled transactions.
    <br><br>
<dt><b>Small Business Accounting Features</b>
<dd>Simplify managing a small business with Customer and Vendor tracking,
    Invoicing and Bill Payment, and Tax and Billing Terms.
    <br><br>
<dt><b>OFX Import</b>
<dd>GnuCash is the first free software application to support
    the Open Financial Exchange protocol that many banks and 
    financial services are moving to use. The development of
    OFX and HBCI support has also resulted in an improved
    transaction matching system that more accurately picks 
    duplicate transactions.
    <br><br>
<dt><b>HBCI Support</b>
<dd>GnuCash is the first free software application to support
    the German Home Banking Computer Information protocol,
    allowing German users to perform statement download and
    initiate bank transfers and direct debits.
    <br><br>
<dt><b>New User Manual and Help</b>
<dd>A brand new user help has been written which focuses on
    how to do tasks in conjunction with a Tutorial and Concepts
    guide that gives the user background information on using 
    GnuCash.
    <br><br>
<dt><b>New Multi-Currency Transaction Handling</b>
<dd>GnuCash no longer requires separate currency exchange
    accounts to handle multiple currency transfers.
    <br><br>
<dt><b>Redesigned Menus</b>
<dd>The GnuCash menus have been redesigned to conform more
    with the new GNOME Human Interface Guidelines.
    <br><br>
</dl>

And of course, some favorite features earlier versions:

	<br><br>
<UL>
<LI>
A reconcile window with running reconciled and cleared balances 
makes balancing against bank statements easy. 
</LI>
<BR><BR>
<LI>
Stock/Mutual Fund Portfolios: Track stocks individually (one per 
account) or in portfolio of accounts (a group of accounts
that can be displayed together). 
</LI>
<BR><BR>
<LI>
Intuit&reg; Quicken&reg; QIF files can be imported, and are automatically
merged to eliminate duplicate transactions. 
</LI>
<BR><BR>
<LI>
Handles internationalized dates and currencies.  The Gnucash 
menus and popups have been translated to 
Danish, French, German, Italian, Japanese, Norwegian, Portuguese, 
Russian, Spanish, Swedish, Turkish, Ukranian, and British English.  
Documentation is available in English, French, Portuguese and Spanish.
</LI>
<BR><BR>
<LI>
Reports: Display Balance Sheet, Profit & Loss, Portfolio Valuation, 
iand others. Reports can be saved as HTML or postscript, or printed.
(Upcoming beta version includes a new integrated graphing 
infrastructure that will add considerable power & beauty to the 
reports.)
</LI>
<BR><BR>
<LI>
Transaction Finder: a powerful transaction query dialogue can help
you quickly locate a needle in a haystack.
</LI>
<BR><BR>
<LI>
Double Entry: When enabled, every
transaction must debit one account and credit others by an
equal amount. This ensures that
the "books balance": that the difference between income and
outflow exactly equals the sum of
all assets and equity.
</LI>
<BR><BR>
<LI>
Income/Expense Account Types (Categories) allow you to 
categorize your cash flow.  When used properly with 
the double-entry feature and equity accounts, these 
enable you to generate reports, such as Profit & Loss, 
that plain-vanilla systems cannot handle.
</LI>
<BR><BR>
<LI>
General Ledger: Multiple accounts
can be displayed in one register window at the same time. This
can ease the trouble of tracking
down typing/entry errors. It also provides a convenient way of
viewing a portfolio of many
stocks, by showing all transactions in that portfolio. 
</LI>
<BR><BR>
<LI>
Get Stock & Mutual Fund quotes
from various web sites, update portfolio automatically. 
Additional pricing sources are added regularly.
</LI>
<BR><BR>
<LI>
Check Printing:  Checks may be printed in standard formats
on common check stocks.  A customization GUI allows custom
check layouts to be developed.
</LI>
<BR><BR>
<LI>
Multiple Currencies &amp; Currency Trading: Multiple currencies are supported 
and can be bought and sold (traded). Currency movements
between accounts are fully balanced when double-entry is
enabled.  
</LI>
<BR><BR>
<LI>
Multi-User SQL support: Multiple users can now simultaneously
access and update GnuCash data stoed in a Postgres SQL backend.
Postgres must be installed and configured to use this option.
</LI>
<BR><BR>
</UL>


</td>
</tr>
</table>

<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr><td bgcolor=#000000><img src=/images/spacer.png height=1></td></tr>
</table>

<br>

<table border=0 cellspacing=0 cellpadding=0 width=100% align=center>
<tr>
  <td align=center>
	  <a href=/en/features_4.phtml><img border=0 src=/images/features/features_previous.png></a>
		 |
	  <img border=0 src=/images/features/features_next_disabled.png>
	</td>
</tr>
</table>

</td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/footer.phtml"); ?>
