<?php 
$title = "Features: Ease of Use";
include("../emulate_globals_on.php");
include($toppath."/externals/en/header.phtml");
include($toppath."/en/menu/menu-main-general.phtml");
?>
</div>
<div id="content">

<div>
<img src="/images/features/features_title.png" alt="feature title">
</div>
<div class="featureblock">&nbsp;</div>

<div>
<div class="featureimage">
  <img src="/images/features/features_4_small.png">
</div>
<p class="featurepanel">
 <img src="/images/features/features_4_text.png"><br>
  A single transaction can be split into several pieces to
  record taxes, fees, and other journal entries.</p>
</div>

<div class="featureblock">&nbsp;</div>

<div class="featureplay">
  <a href=/en/features_3.phtml><img alt="back to 3"
 src="/images/features/features_previous.png"></a>
 |
  <a href=/en/features_5.phtml><img alt="next slide"
 src="/images/features/features_next.png"></a>
</div>
</div>

<?php include($toppath."/externals/en/footer.phtml"); ?>
