<% #ns_adp_include [ns_info pageroot]/en/components/header.adp "Features:Ease of Use" %>
<% #ns_adp_include [ns_info pageroot]/en/menu/menu-general-main.adp %>

<body bgcolor=#ffffff>

<td valign=top>

<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr>
  <td><img src=/images/features/features_title.png></td>
  <td align=right><a href="javascript:window.close();"><img border=0 src=/images/close_window.png></a></td>
</tr>
</table>

<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr><td bgcolor=#000000><img src=/images/spacer.png height=1></td>
</tr>
</table>

<br>

<table cellpadding=4 cellspacing=0 border=0 width=100%>
<tr>
<td valign=top>
  <img src=/images/features/features_1_text.png><br><br>

  If you can use the register in the back of your checkbook, you can use Gnucash. Type directly
  into the register, tab between fields, and use quick-fill to automatically complete the transaction. 

</td>
<td valign=middle>
  <img src=/images/features/features_1_small.png>
</td>
</tr>
</table>

<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr><td bgcolor=#000000><img src=/images/spacer.png height=1></td></tr>
</table>

<br>

<table border=0 cellspacing=0 cellpadding=0 width=100% align=center>
<tr>
  <td align=center>
	  <img border=0 src=/images/features/features_previous_disabled.png>
		 |
	  <a href=/en/features_2><img border=0 src=/images/features/features_next.png></a>
	</td>
</tr>
</table>

</td>

<% #ns_adp_include [ns_info pageroot]/en/components/footer.adp %>
