<?php $title = "Features"; ?>
<?php if (!ini_get('register_globals')) {
 include("../emulate_globals_on.php");
}
?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-main-general.phtml"); ?>

<div id="content">

<div>
<img src="/images/features/features_title.png" alt="feature title">
</div>
<div class="featureblock">&nbsp;</div>

<div>
<div class="featureimage">
<img alt="one" src="/images/features/features_1_small.png">
</div>
<p class="featurepanel">
<img alt="easy to use interface"
 src="/images/features/features_1_text.png"><br>
If you can use the register in the back of your checkbook,
you can use Gnucash. Type directly into the register,
tab between fields, and use quick-fill to automatically
complete the transaction.</p>
</div>

<div class="featureblock">&nbsp;</div>

<div style="text-align:center">
<img alt="at start"
src="/images/features/features_previous_disabled.png">
 |
<a href="/en/features_2.phtml"><img alt="next slide"
 src="/images/features/features_next.png"></a>
</div>
</div>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/footer.phtml"); ?>
