<?php $title = "Features: Ease of Use"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-general-main.phtml"); ?>

<body bgcolor=#ffffff>

<td valign=top>

<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr>
  <td><img src=/images/features/features_title.png></td>
  <td align=right><a href="javascript:window.close();"><img border=0 src=/images/close_window.png></a></td>
</tr>
</table>

<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr><td bgcolor=#000000><img src=/images/spacer.png height=1></td></tr>
</table>

<br>

<table cellpadding=4 cellspacing=0 border=0 width=100%>
<tr>
<td valign=top>
  <img src=/images/features/features_5_text.png><br><br>


  Download GnuCash and try some of the other cool features:

	<br><br>
<UL>
<LI>
A reconcile window with running reconciled and cleared balances 
makes balancing against bank statements easy. 
</LI>
<BR><BR>
<LI>
Stock/Mutual Fund Portfolios: Track stocks individually (one per 
account) or in portfolio of accounts (a group of accounts
that can be displayed together). 
</LI>
<BR><BR>
<LI>
Intuit&reg; Quicken&reg; QIF files can be imported, and are automatically
merged to eliminate duplicate transactions. 
</LI>
<BR><BR>
<LI>
Handles internationalized dates and currencies.  The Gnucash 
menus and popups have been translated to Brazilian Portuguese,
Danish, French, German, Italian, Japanese, Norwegian, Swedish, Spanish, 
Russian, Ukranian, and British English.  Documentation is available 
in English and French.
</LI>
<BR><BR>
<LI>
Reports: Display Balance Sheet, Profit & Loss, Portfolio Valuation, 
or print them as HTML.  Work is proceeding on an integrated graphing 
environment that will allow graphs to be embedded within reports.
</LI>
<BR><BR>
<LI>
Transaction Finder: a powerful transaction query dialogue can help
you quickly locate a needle in a haystack.
</LI>
<BR><BR>
<LI>
Double Entry: When enabled, every
transaction must debit one account and credit others by an
equal amount. This ensures that
the "books balance": that the difference between income and
outflow exactly equals the sum of
all assets and equity.
</LI>
<BR><BR>
<LI>
Income/Expense Account Types (Categories) allow you to 
categorize your cash flow.  When used properly with 
the double-entry feature and equity accounts, these 
enable you to generate reports, such as Profit & Loss, 
that plain-vanilla systems cannot handle.
</LI>
<BR><BR>
<LI>
General Ledger: Multiple accounts
can be displayed in one register window at the same time. This
can ease the trouble of tracking
down typing/entry errors. It also provides a convenient way of
viewing a portfolio of many
stocks, by showing all transactions in that portfolio. 
</LI>
<BR><BR>
<LI>
Get Stock & Mutual Fund quotes
from various web sites, update portfolio automatically. 
Additional pricing sources are added regularly.
</LI>
<BR><BR>
<LI>
Tip-of-the-day popups make learning about new GnuCash features
easy.  Extensive built-in documentation helps answer questions 
you might have about particular features and accounting practices.
</LI>
<BR><BR>
<LI>
Check Printing:  Checks may be printed in standard formats
on common check stocks.  The latest versions of gnome-print 
must be installed to use this feature.
</LI>
<BR><BR>
<LI>
Preferences: the appearance and behavior of the main window
and the register windows can be thoroughly customized through
n application preferences dialog.
</LI>
<BR><BR>
<LI>
Multiple Currencies & Currency Trading: Multiple currencies are supported 
and can be bought and sold (traded). Currency movements
between accounts are fully balanced when double-entry is
enabled.  A simplified interface to multiple-currency handling
is in development.
</LI>
<BR><BR>
</UL>

</td>
</tr>
</table>

<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr><td bgcolor=#000000><img src=/images/spacer.png height=1></td></tr>
</table>

<br>

<table border=0 cellspacing=0 cellpadding=0 width=100% align=center>
<tr>
  <td align=center>
	  <a href=/en/features_4.phtml><img border=0 src=/images/features/features_previous.png></a>
		 |
	  <img border=0 src=/images/features/features_next_disabled.png>
	</td>
</tr>
</table>

</td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/footer.phtml"); ?>
