<?php $title = "Features: What's New"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-main-general.phtml"); ?>
</td>

<td valign=top>

<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr>
  <td><img src=/images/features/features_title.png></td>
  <td align=right><a href="javascript:window.close();"><img border=0 src=/images/close_window.png></a></td>
</tr>
</table>

<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr><td bgcolor=#000000><img src=/images/spacer.png height=1></td></tr>
</table>

<br>

<table cellpadding=4 cellspacing=0 border=0 width=100%>
<tr>
<td valign=top>
  <img src=/images/features/features_5_text.png><br><br>


<h2>What's New in GnuCash 1.8.0?</h2>
The 1.8.x series of stable releases introduce many new features not found
in the older gnucash-1.6.8:

    <br><br>
<dl>
<dt><b>Scheduled Transactions</b>
<dd>You can now create recurring 
    transactions, including automatic reminders when a 
    transaction is due, the ability to postpone a scheduled transaction
    without cancelling it, and the ability to specify only a limited 
    number of transactions.
    <br><br>
<dt><b>Mortgage &amp; Loan Repayment Druid</b></dt>
<dd>A guided dialogue for setting up loan payments as
    scheduled transactions.
    <br><br>
<dt><b>Small Business Accounting Features</b>
<dd>Simplify managing a small business with Customer and Vendor tracking,
    Invoicing and Bill Payment, and Tax and Billing Terms.
    <br><br>
<dt><b>OFX Import</b>
<dd>GnuCash is the first free software application to support
    the Open Financial Exchange protocol that many banks and 
    financial services are moving to use. 
    <br><br>
<dt><b>HBCI Support</b>
<dd>GnuCash is the first free software application to support
    the German Home Banking Computer Information protocol,
    allowing German users to perform statement download and
    initiate bank transfers and direct debits.
    <br><br>
<dt><b>Improved Import Transaction Matching</b>
<dd>The development of OFX and HBCI support has also resulted 
    in an improved transaction matching system that more 
    accurately recognizes duplicate transactions during file import.
    <br><br>
<dt><b>New User Manual and Help</b>
<dd>A new help subsystem that focuses on how to do tasks is now available,
    in addition to a Tutorial and Concepts guide that gives the 
    user background information on accounting principles and how
    they are reflected in GnuCash.
    <br><br>
<dt><b>New Multi-Currency Transaction Handling</b>
<dd>GnuCash no longer requires separate currency exchange
    accounts to handle multiple currency transfers.  Transactions
    can be made directly between accounts denominated in different 
    currencies.
    <br><br>
<dt><b>Redesigned Menus</b>
<dd>The GnuCash menus have been redesigned to conform more
    with the new GNOME Human Interface Guidelines.
    <br><br>
</dl>

<h2>Old Favorites</h2>
And of course, some favorite features from earlier versions:

	<br><br>
<dl>
<dt><b>Statement Reconciliation</b>
<dd>A reconcile window with running reconciled and cleared balances 
    makes balancing against bank statements easy. 
</dd>
<br><br>
<dt><b>Stock/Mutual Fund Portfolios</b> 
<dd>Track stocks individually (one per account) or in portfolio 
    of accounts (a group of accounts that can be displayed together). 
</dd>
<br><br>
<dt><b>QIF Import</b>
<dd>Intuit<sup>&reg;</sup> Quicken<sup>&reg;</sup>
    QIF files can be imported, and are automatically
    merged to eliminate duplicate transactions. 
</dd>
<br><br>
<dt><b>Localization</b>
<dd>Handles internationalized dates and currencies.  The Gnucash 
    menus and popups have been translated to 21 languages, including
    Chinese, Danish, French, German, Hungarian, Italian, Japanese, 
    Norwegian, Polish, Portuguese, Russian, Spanish, Swedish, 
    Turkish, Ukranian, and British English.  
    Documentation is available in English, French, Portuguese and Spanish.
</dd>
<br><br>
<dt><b>Reports</b>
<dd>Display Balance Sheet, Profit & Loss, Portfolio Valuation, 
    and others. Reports can be saved as HTML or postscript, or printed.
</dd>
<br><br>
<dt><b>Transaction Finder</b>
<dd>A powerful transaction query dialogue can help you quickly locate 
    a needle in a haystack.
</dd>
<br><br>
<dt><b>Double Entry</b>
<dd>When enabled, every transaction must debit one account and 
    credit others by an equal amount. This ensures that
    the "books balance": that the difference between income and
    outflow exactly equals the sum of all assets and equity.
</dd>
<br><br>
<dt><b>Income/Expense Account Types</b>
<dd>Income/Expense Account Types (Categories) allow you to 
    categorize your cash flow.  When used properly with 
    the double-entry feature and equity accounts, these 
    enable you to generate reports, such as Profit & Loss, 
    that plain-vanilla systems cannot handle.
</dd>
<br><br>
<dt><b>General Ledger</b>
<dd>Multiple accounts can be displayed in one register window 
    at the same time. This can ease the trouble of tracking
    down typing/entry errors. It also provides a convenient way of
    viewing a portfolio of many
    stocks, by showing all transactions in that portfolio. 
</dd>
<br><br>
<dt><b>Online Stock &amp; Mutual Fund Quotes</b>
<dd>Get Stock & Mutual Fund quotes
    from various web sites, update portfolio automatically. 
    Additional pricing sources are added regularly.
</dd>
<br><br>
<dt><b>Check Printing</b>
<dd>Checks may be printed in standard formats
    on common check stocks.  A customization GUI allows custom
    check layouts to be developed.
</dd>
<br><br>
<dt><b>Multiple Currencies</b>
<dd>Different accounts can be denominated in different currencies.
    Currency movements between accounts are fully balanced when 
    double-entry is enabled.  
</dd>
<br><br>
<dt><b>Multi-User SQL Support</b>
<dd>Multiple users can now simultaneously
    access and update GnuCash data stoed in a Postgres SQL backend.
    Postgres must be installed and configured to use this option.
</dd>
<br><br>
</dl>


</td>
</tr>
</table>

<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr><td bgcolor=#000000><img src=/images/spacer.png height=1></td></tr>
</table>

<br>

<table border=0 cellspacing=0 cellpadding=0 width=100% align=center>
<tr>
  <td align=center>
	  <a href=/en/features_4.phtml><img border=0 src=/images/features/features_previous.png></a>
		 |
	  <img border=0 src=/images/features/features_next_disabled.png>
	</td>
</tr>
</table>

</td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/footer.phtml"); ?>
