<?php $title = "Hacking"; ?>
<?php if (!ini_get('register_globals')) {
 include("../emulate_globals_on.php");
}
?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/externals/en/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-main-developer.phtml"); ?>

</div>
<div id="content">

<h1>Hacking GnuCash</h1>

<p>There are a number of steps to go through to hack on gnucash. 
You will need to install development (<tt>*-devel-*</tt>) 
versions of the packages 
listed on the <a href="/en/required.phtml">tools page</a>.  The latest
development versions of gnucash may depend on bleeding edge 
versions of some gnome tools (e.g. <tt>gnome-print</tt>).  You may also 
need to get unusual or special versions of g-wrap and guppi.
</p>
<p><b>Getting the most recent sources via SVN:</b></p>
<p>
   The latest source code is maintained in a publically readable 
   SVN source code repository.  Accessing it is simple,
   and if you plan to be an active developer, there is
   no better way of getting the source.  The SVN tree
   is not publically writable; once you have patches, 
   you should submit them to the 
   <a href=/en/lists.phtml>gnucash-patches@gnucash.org</a>
   mailing list.  Documentation changes can be sent to the
   same place.</p>
<p>
<b>Update for SVN!</b>
<!--
If you are new to CVS, you may want to take a moment
and visit the <a href="http://www.cvshome.org/">
Concurrent Versions System Home Page</a>, and in particular,
the <a href="http://www.cvshome.org/docs/">documentation page</a>.
CVS allows multiple users to modify the source code for GnuCash,
each without stepping on the toes (and changes) made by others.
If CVS seems at first overwhelming, don't let it be so:
its quite easy to learn and use.
-->
</p>
<p>
   To access the CVS tree, first, login, as so: 
</p>


<table bgcolor="#000000" cellpadding=10><tr><td>
<font color="#aaaaaa">
cvs -d :pserver:cvs@cvs.gnucash.org:/home/cvs/cvsroot login
</font>
</td>
</tr>
</table>

<p>
The password is &quot;guest&quot; ; after entering the password,
you will be immediately returned to the command prompt.  You
can now use other CVS commands to view the source.

To get a copy of the latest/beta development version 
(which is currently version 1.9.x), do a 
</p>

<table bgcolor="#000000" cellpadding=10><tr><td>
<font color="#aaaaaa">
cvs -d :pserver:cvs@cvs.gnucash.org:/home/cvs/cvsroot checkout gnucash 
</font>
</td>
</tr>
</table>

<br>
<b>Building GnuCash:</b><br>
<br>
A complete set of instructions for building GnuCash from source can be
found in the 
<a href="https://cvs.gnucash.org/cgi-bin/cvsweb.cgi/gnucash/README"><tt>README</tt></a>
file in the top-level directory.  For the 
impatient, the following instructions might help:
<p>
Start with a distributed binary version of GnuCash, in order to get 
dependencies resolved.  GnuCash does not currently support GNOME2.

<ol>
<li>Try to install the gnucash binary from your distribution.  For
    example, <tt>gnucash-1.6.6-7.i386.rpm</tt>
<li>Note the missing dependencies.
<li>Install those dependencies and associated -devel packages (if any).
<li>Go to step 1.
<li>Once you get GnuCash installed, remove it. :-)
<li>Download the source for the latest gnucash development version from
    CVS.  All dependecies except for <tt>g-wrap</tt> are the same in 
    GnuCash 1.6.x and 1.8.x
<li>Remove g-wrap, if necessary.
<li>Download </tt>g-wrap-1.3.4</tt> from 
    <a href="http://www.gnucash.org/pub/g-wrap/">http://www.gnucash.org/pub/g-wrap/</a>
<li>Build g-wrap and gnucash
<li>Install additional </tt>-devel</tt> packages when configure complains
</ol>
</p>
<p>
If any of these steps don't make sense to you, you probably need more
background material.  Start with the 
<a href="https://cvs.gnucash.org/cgi-bin/cvsweb.cgi/gnucash/README"><tt>README</tt></a>
file in the source tree.
Note that the GnuCash source code is 
<a href="https://cvs.gnucash.org/cgi-bin/cvsweb.cgi/"> browsable via CVSweb.</a>
However, you may find browsing with <tt>ctags</tt> in your own file system
to be a bit speedier.
</p>

<br>
<b>Getting Older Versions of GnuCash out of CVS:</b><br>
<p>
Older versions and branches can be accessed with tags. 
The branch containing the latest version of the stable 
gnucash-1.8.x code is marked 
with the tag <tt>gnucash-1-8-branch</tt> . Thus, to check out the
latest in the the gnucash-1.8.x series, do the following:
</p>

<table bgcolor="#000000" cellpadding=10><tr><td>
<font color="#aaaaaa">
cvs -d :pserver:cvs@cvs.gnucash.org:/home/cvs/cvsroot checkout -r gnucash-1-8-branch gnucash
</font>
</td>
</tr>
</table>


<p>
Released versions are tagged with the number of the release. Thus,
the tag <tt>gnucash-1-8-0</tt> will get you a copy of the source
as it was for version 1.8.0.  If you are a developer, you should 
probably be working either in the head branch (<tt>HEAD</tt>) 
on the latest beta/development code, or in the 
<tt>gnucash-1-8-branch</tt>, squashing any remaining bugs in the 
current stable version.
</p>
<p>
Other tags of (mostly historical) interest are:
<dl><dd>
<dl>
<dt><b>xacc-09a</b>
<dd>Robin Clark's original source from October 1997.  For history 
    buffs only: the source has been completely re-written since then.
<dt><b>xacc-10b17</b>
<dd>version 1.0.17 (one of the last stable version of xacc, before 
    the name was changed to gnucash).
<dt><b>xacc-10-patch</b>
<dd>the tip of the branch of the stable version 1.0.x series.
<dt><b>xacc-11b6</b>
<dd>version 1.1.6 (an unstable, development version of gnucash)
<dt><b>xacc-12-patch</b>
<dd>the tip of the 1.2 branch. This is the last branch containing
    motif code.  Later versions were re-written in gtk/gnome.
<dt><b>patch-124</b>
<dd>version 1.2.4, one of the last in the 1.2.x series.
<dt><b>gnucash-1-4-branch</b>
<dd>the tip of the 1.4.x branch, the first gtk/gnome stable branch.
<dt><b>gnucash-1-6-branch</b>
<dd>the tip of the 1.6.x branch, the previous stable branch.
<dt><b>gnucash-1-8-branch</b>
<dd>the tip of the 1.8.x branch, the current stable branch.
<dt><b>gnucash-gnome2-dev</b>
<dd>the tip of the GNOME2 branch(currently very unstable) which will be the first GNOME2 version of GnuCash.
</dl>
</dl>

<p>
In order to speed up the performance of CVS, some of the older tags
(stuff older than mid-year 2000, mostly; and some newer stuff) and
branches have been removed from the mainline CVS tree. To those who
are interested in doing historical mining of the CVS tree as it used
to be, you can supply an older branch tag to the following repository:
<br><br>
<table bgcolor="#000000" cellpadding=10><tr><td>
<font color="#aaaaaa">
cvs -d :pserver:cvs@cvs.gnucash.org:/home/cvs/cvsroot checkout -r &lt;some-tag&gt; gnucash-archive
</font>
</td>
</tr>
</table>
</p>

<p>
<b>Getting the most recent sources via FTP:</b></p>
<p>
If you don't like to bother with CVS you can download recent 
snapshots of the CVS tree from one of the FTP sites below.
Note, however, that if you wish to contribute patches and updates
to GnuCash, it is strongly recommended that you learn and use CVS.
We encourage this because the snapshots can sometimes get a bit 
dated, and you just might be fixing a bug that's already fixed.
</p>
<p>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<a href="http://www.linas.org/pub/gnucash/gnucash/sources/">http://www.linas.org/pub/gnucash/gnucash/sources/</a>
</p> 
<p>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<a href="http://www.gnucash.org/pub/gnucash/sources/">http://www.gnucash.org/pub/gnucash/sources/</a>
</p>


<?php include($GLOBALS['DOCUMENT_ROOT']."/externals/en/footer.phtml"); ?>
