<?php $title = "History"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-other-main.phtml"); ?>
</td>

<td valign=top>
<b>History & Credits</b><br><br>

   Whose blood, sweat and tears is this anyway?

<BR><BR><font size="+2"><b>Lead Developers</b></font>
<HR>


<dl>
  <dt>
  <b>Linas Vepstas</b>
  </dt>
  <dd>
    liked what he saw: the GUI was slick, the code was documented and 
    well structured, and it was all GPL'ed. And so he re-wrote it: 
    adding cell-widgets to XbaeMatrix, so that the combobox and arrows 
    would make an even slicker GUI, rewrote the X-Accountant internals 
    to add double-entry, an account hierarchy, split out a transaction 
    mini-engine, added support for stocks, and spiffed up the help
    menus. This was version 1.0 as of January 1998. For version 1.1 &amp;
    1.2, the engine was expanded and refined, and the register window 
    code completely redesigned and made mostly Motif-(and GUI-)independent.
    Linas is now active with Gnumatic Incorporated, a company formed to 
    enhance and support GnuCash for everyone, from home desktop users 
    to commercial and professional accountants.
  </dd>

<BR>
<BR>

  <dt>
  <b>Rob Browning</b>
  </dt>
  <dd>
    abused everyone for not using Perl, and then after we added Perl support, 
    dumped Perl in favor of Guile/Scheme support. Rob built the build 
    infrastructure, hacked the gtk code, and is whacking the file format.
    Also, the re-write of reports and statement downloading in scheme, 
    the g-wrap guile wrapper, and the user preferences.
  </dd>
</dl>

<BR>

<dl>
  <dt>
  <b>Jeremy Collins</b> 
  </dt>
  <dd>
    publicized the GnoMoney project widely and broadly, and then 
    changed its name to GnuCash.   (Actually, put the selection 
    of the name up to popular vote.  Democracy is <b>not</b>
    a good way to pick names.) 
    Jeremy registered the domain name, and created and maintained 
    the gnucash.org web site for years,
    and got the initial GTK/gnome code working.  
  </dd>

<BR>
<BR>


  <dt>
  <b>Dave Peticolas</b>
  </dt>
  <dd>
    hacks obsessively on GnuCash. But he can stop anytime he wants to. Really. 
    (As he is now the gatekeeper of the GnuCash CVS tree, be nice to him,
    or he may decide to stop hacking in the middle of your patch).
  </dd>


<BR>
<BR>

  <dt>
  <b>Rob Clark</b>
  </dt>
  <dd>
    wrote the original X-Accountant in Motif as a school project, 
    taking it to version 0.9 by October 1997.  Although every single 
    line of his code has been re-written, his name appears as a 
    credit in almost every file.  Such is the magic of copyrights.
  </dd>

<BR>
<BR>

  <dt>
  <b>Bill Gribble</b>
  </dt>
  <dd>
    is not shy, or softly spoken.  So don't be shy if you find a bug in 
    his code: QIF import, query API and transaction search, check-printing,
    commodity and currency support, gtkhtml integration and report printing.
  </dd>
</dl>

<BR>

<font size="+2"><b>Fixers and Patchers</b></font>
<hr>

<dl>
      <dt> <a href="mailto:arensb@cfar.umd.edu"> Andrew
      Arensburger</a></dt>

      <dd>for FreeBSD and other patches</dd>

      <dt> <a href="mailto:matt_armstrong@bigfoot.com"> Matt
      Armstrong</a></dt>

      <dd>for misc fixes</dd>

      <dt> <a href="mailto:fred@moremagic.com"> Fred Baube</a></dt>

      <dd>for attempted Java port/MoneyDance</dd>

      <dt> <a href="mailto:dennisb@cs.chalmers.se"> Dennis
      Björklund</a></dt>

      <dd>Swedish translation</dd>

      <dt> <a href="mailto:bojsen@worldnet.att.net"> Per Bojsen</a></dt>

      <dd>several core dump fixes</dd>

      <dt> <a href="http://www.hex.net/~cbbrowne"> Christopher B.
      Browne</a></dt>

      <dd>for perl stock scripts, first draft of Guile-based QIF 
      import code, lots of changes & maintenance of the English 
      documentation, and more</dd>

      <dt> <a href="mailto:grahamc@zeta.org.au"> Graham
      Chapman</a></dt>

      <dd>for the xacc-rpts addon package</dd>

      <dt> <a href="mailto:georgec@sco.com"> George Chen</a></dt>

      <dd>for MS-Money QIF support</dd>

      <dt> <a href="mailtochina@thewrittenword.com">Albert
      Chin-A-Young</a></dt>

      <dd>configure.in patch</dd>

      <dt> <a href="mailto:jcollins@gnucash.org"> Jeremy
      Collins</a></dt>

      <dd>for GnoMoney and GTK port</dd>

      <dt> <a href="mailto:mcondell@bbn.com"> Matthew Condell</a></dt>

      <dd>FreeBSD patch</dd>

      <dt> <a href="mailto:pcondon@rackspace.com"> Patrick
      Condron</a></dt>

      <dd>for setting up a webserver on a T1 connection on 
          behalf of open source enthusiasts 
          <a href="http://www.rackspace.com">
          rackspace.com</a></dd>

      <dt> <a href="mailto:Ciaran.Deignan@bull.net"> Ciaran
      Deignan</a></dt>

      <dd>for AIX binary version</dd>

      <dt> <a href="mailto:tyson@tyse.net"> Tyson Dowd</a></dt>

      <dd>for config/make patches and debian maintenance</dd>

      <dt> <a href="mailto:ripley@xs4all.nl"> Koen D'Hondt</a></dt>

      <dd>for Solaris patches to XmHTML</dd>

      <dt> <a href="mailto:bob@mostly.com"> Bob Drzyzgula</a></dt>

      <dd>for budgeting design notes</dd>

      <dt> <a href="mailto:pjf@schools.net.au"> Paul Fenwick</a></dt>

      <dd>ASX support</dd>

      <dt> <a href="mailto:hfiguiere@teaser.fr"> Hubert Figuiere</a></dt>

      <dd>patch to gnc-prices</dd>

      <dt> <a href="mailto:ju_finck@mail.netwave.de"> Jan-Uwe
      Finck</a></dt>

      <dd>for German message translation</dd>

      <dt> <a href="mailto:rjf@aracnet.com"> Ron Forrester</a></dt>

      <dd>for gnome patches</dd>

      <dt> <a href="mailto:DFreese@osc.uscg.mil"> Dave
      Freese</a></dt>

      <dd>for leap-year fix</dd>

      <dt> <a href="mailto:grib@billgribble.com"> Bill Gribble</a></dt>

      <dd>QIF import code</dd>

      <dt> <a href="mailto:otto@bug.redhat.com"> Otto
      Hammersmith</a></dt>

      <dd>for RedHat RPM packaging</dd>

      <dt> <a href="mailto:offby1@blarg.net"> Eric Hanchrow</a></dt>

      <dd>updated currency documentation</dd>

      <dt> <a href="mailto:haral@codec.ro"> Alexandru
      Harsanyi</a></dt>

      <dd>for fixing miscellaneous core dumps and lockups.</dd>

      <dt> <a href="mailto:john@dhh.gt.org"> John Hasler</a></dt>

      <dd>engine patch</dd>

      <dt> <a href="mailto:jk@isdn-a33.itea.ntnu.no"> Jon K}re
      Hellan</a></dt>

      <dd>for fixing miscellaneous core dumps and lockups.</dd>

      <dt> <a href="mailto:PrakashK@bigfoot.com"> Prakash
      Kailasa</a></dt>

      <dd>for gnome build fixes</dd>

      <dt> <a href="mailto:tkludy@csd.sgi.com"> Tom Kludy</a></dt>

      <dd>for SGI Irix port</dd>

      <dt> <a href="mailto:sk@xgm.de"> Sven Kuenzler</a></dt>

      <dd>for SuSE README file</dd>

      <dt><a href="mailto:blarsen@ada-works.com"> Bryan Larsen</a></dt>

      <dd>guile budget report</dd>

      <dt> <a href="mailto:mellon@andare.fugue.com"> Ted
      Lemon</a></dt>

      <dd>for NetBSD port</dd>

      <dt> <a href="mailto:y-le-ny@ifrance.com"> Yannick Le
      Ny</a></dt>

      <dd>pour la traduction en Fran&ccedil;ais</dd>

      <dt> <a href="mailto:glikely@nortelnetworks.com"> Grant
      Likely</a></dt>

      <dd>gnome and engine patches</dd>

      <dt> <a href="mailto:martinh@pegasus.cc.ucf.edu"> Heath
      Martin</a></dt>

      <dd>major work on the gnome register</dd>

      <dt> <a href="mailto:mgmartin@abacusnet.net"> Matt
      Martin</a></dt>

      <dd>guile error handling code</dd>

      <dt> <a href="mailto:rgmerk@mira.net"> Robert Graham
      Merkel</a></dt>

      <dd>reporting, gnome, and configuration patches.</dd>

      <dt> <a href="mailto:mooney@dogbert.cc.ndsu.NoDak.edu"> Tim
      Mooney</a></dt>

      <dd>port to alpha-dec-osf4.0f</dd>

      <dt> <a href="mailto:gam3@ann.softgams.com"> G. Allen Morris
      III</a></dt>

      <dd>for QIF core dump fix</dd>

      <dt> <a href="mailto:brent@baton.phys.lsu.edu"> Brent Neal</a></dt>

      <dd>TIAA-CREF support in the Finance::Quote perl module.</dd>

      <dt> <a href="mailto:spacey@inch.com"> Peter Norton</a></dt>

      <dd>for a valiant attempt at a GTK port</dd>

      <dt> <a href="mailto:webmaster@obsidian.uia.net">
      OmNiBuS</a></dt>

      <dd>web site graphics and content</dd>

      <dt> <a href="mailto:mopyr@IPM.Lviv.UA"> Myroslav
      Opyr</a></dt>

      <dd>for misc patches</dd>

      <dt> <a href="mailto:laurent.pelecq@wanadoo.fr"> Laurent
      P{'e}lecq</a></dt>

      <dd>i18n patches with gettext</dd>

      <dt> <a href="mailto:Alain.Peyrat@nmu.alcatel.fr"> Alain
      Peyrat</a></dt>

      <dd>for <tt>configure.in</tt> patches</dd>

      <dt> <a href="mailto:peter@wuzel.m.isar.de"> Peter
      Pointner</a></dt>

      <dd>Motif and configuration patches</dd>

      <dt> <a href="mailto:maufk@csv.warwick.ac.uk"> Gavin
      Porter</a></dt>

      <dd>for euro style dates</dd>

      <dt> <a href="mailto:rr@sco.com"> Ron Record</a></dt>

      <dd>for SCO Unixware and OpenServer binaries</dd>

      <dt> <a href="mailto:schoenberger@signsoft.com"> Dirk
      Schoenberger</a></dt>

      <dd>began the Qt/KDE port</dd>

      <dt> <a href="mailto:jan.schrage@urz.uni-heidelberg.de"> Jan
      Schrage</a></dt>

      <dd>documentation patches</dd>

      <dt> <a href="mailto:cls@seawood.org"> Christopher
      Seawood</a></dt>

      <dd>for XbaeMatrix core dump</dd>

      <dt> <a href="mailto:msimons@fsimons01.erols.com"> Mike
      Simons</a></dt>

      <dd>misc <tt> configure.in</tt> patches</dd>

      <dt> <a href="mailto:rich@brake.demon.co.uk"> Richard
      Skelton</a></dt>

      <dd>for Solaris cleanup</dd>

      <dt> <a href="mailto:spruth@bigfoot.com"> Henning
      Spruth</a></dt>

      <dd>for German text and euro date rework</dd>

      <dt> <a href="mailto:parys@freewwweb.com"> Robby Stephenson</a></dt>

      <dd>register patch</dd>

      <dt> <a href="mailto:tma@iis.fhg.de"> Herbert Thoma</a></dt>

      <dd>gnome register & euro support patches</dd>

      <dt> <a href="mailto:detrout@earthlink.net"> Diane
      Trout</a></dt>

      <dd>scheme qif import patch</dd>

      <dt> <a href="mailto:rkw@dataplex.net"> Richard Wackerbarth</a></dt>

      <dd>patch to gnc-prices</dd>

      <dt> <a href="mailto:rob@valinux.com"> Rob Walker</a></dt>

      <dd>guile and register patches</dd>

      <dt> <a href="mailto:dwmw2@infradead.org"> David Woodhouse</a></dt>

      <dd>Great Britain translations</dd>

      <dt> <a href="mailto:gooch@ic.EECS.Berkeley.EDU"> Ken
      Yamaguchi</a></dt>

      <dd>QIF import fixes; MYM import</dd>
    </dl>


</td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/footer.phtml"); ?>
