<?php $title = "Home"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-main.phtml"); ?>

	</td>
  <td valign=top width=98%>
  
<h1>Welcome to GnuCash.org</h1>
  
<font size=1>
If you've been looking for a way to manage your personal finances under GNU/Linux, you've
found it! Designed to be easy to use, yet powerful and flexible, GnuCash allows you to track bank
accounts, stocks, income and expenses. As quick and intuitive to use as a checkbook register, it
is based on professional accounting principles to ensure balanced books and accurate reports.
GnuCash is backed by an active development community and is blossoming into a full-fledged
accounting system. Developed under the GPL, you have no need to worry about obsolescence:
GnuCash will be there for you. 
<br><br>
This web site is devoted to promoting the Gnucash.org software development project. We are
committed to developing top-notch financial tools for GNU/Linux and Unix users. This includes the
development of programming API's and components that can be used to create both server and
personal applications for home and business use. By focusing on ease-of-use, modular design,
architected interfaces and well-documented code, we hope that GnuCash and its associated
financial libraries become the choice of a GNU generation of programmers and users.
</font>
<br><br>

<h1>News</h1>

<font size=1>

<table border=0 cellpadding=1 cellspacing=0 width="100%">
  <tr>
  <td valign=middle align=center bgcolor=#666699>
   <table border=0 cellpadding=5 cellspacing=1 bgcolor=#cacaf7 width="100%">
   <tr>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
				 <td>
         <img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;
				 </td>
<td><B>Announcement:</B> GnuCash 1.5.3 release! - <font size=-2><b>(2001-02-26&nbsp; &nbsp;20:28:45)</b></font> </td>
       </tr>
       </table>
     </td>
	 </tr>
   <tr bgcolor=#ffffff>
     </td>
     <td valign=top>
<font size=1>
<b>Note: this is an unstable development release and may be buggy!</b>  
Most users should probably stick to version 1.4.10 for day-to-day use.  
(All 1.5.x releases will be unstable/buggy. The next stable version 
will be 1.6.0).  
<BR><BR>
<li>new XML file format
<li>better support for importing qifs from online banks
<li>improved checking register
<li>support for charts & graphs
<li>financial calculator
<li>new user account hierarchy wizard
<li>many UI improvements
<li>beta support for postgresql -- see src/engine/sql/README
<BR><BR>

Available at the usual places! 

<br><br><b><a href="http://www.linas.org/pub/gnucash/">(fast mirror)</a></b>
<br><br><b><a href="ftp://ftp.gnucash.org/pub/gnucash/">ftp.gnucash.org</a></b>
<br><br><b><a href="http://download.sourceforge.net/gnucash/">download.sourceforge.net/gnucash</a></b>
</font>
		 </td>
   </tr>
	 </table>
</tr>
</table>


</font>

  </td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/footer.phtml"); ?>
