
<?php $title = "GnuCash on IRC"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-main-help.phtml"); ?>
</td>

<td valign=top>
<h1>GnuCash on IRC</h1>

Have some fun (or merely get help with using and installing GnuCash) 
by discussing GnuCash development with developers and users alike, 
on IRC.  Join the #gnucash channel at irc.gnome.org.

<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/footer.phtml"); ?>
