<?php 
$title = "Related Financial Software";
include("../emulate_globals_on.php");
include($toppath."/externals/en/header.phtml");
include($toppath."/en/menu/menu-main-other.phtml");
?>

<div id="content">

<h1>Related Financial Software</h1>

<div>
<p><b>Select a section:</b>
</p>
<form method=post>
<div>
<select name=linkpage>
  <option value=general
  <?php if ($linkpage == "general") { echo ("selected"); } ?>
  >General References</option>
  <option value=utilities
  <?php if ($linkpage == "utilities") { echo ("selected"); } ?>
  >Utilities</option>
  <option value=palm
  <?php if ($linkpage == "palm") { echo ("selected"); } ?>
  >Palm Computing</option>
  <option value=stock
  <?php if ($linkpage == "stock") { echo ("selected"); } ?>
  >Stock Trading &amp; Technical Analysis</option>
  <option value=quote
  <?php if ($linkpage == "quote") { echo ("selected"); } ?>
  >Quote Sources, Tools</option>
  <option value=money
  <?php if ($linkpage == "money") { echo ("selected"); } ?>
  >Electronic Currencies</option>
  <option value=erp
  <?php if ($linkpage == "erp") { echo ("selected"); } ?>
  >Business, ERP Projects</option>
  <option value=xml
  <?php if ($linkpage == "xml") { echo ("selected"); } ?>
  >XML and Other Data Formats</option>
  <option value=misc
  <?php if ($linkpage == "misc") { echo ("selected"); } ?>
  >Miscellaneous</option>
  <option value=obsolete
  <?php if ($linkpage == "obsolete") { echo ("selected"); } ?>
  >Historical References</option>
  <option value=review
  <?php if ($linkpage == "review") { echo ("selected"); } ?>
  >Gnucash Review &amp; Rating Sites</option>
</select>
<input type=submit value=Go>
</div>
</form>
</div>

<?php
  if ($linkpage != "") { 
	include($toppath."/en/links/links-".$linkpage.".phtml");
  } else {
	include($toppath."/en/links/links-general.phtml");
  }
?>

</div>
<?php include($toppath."/externals/en/footer.phtml"); ?>
