<?php $title = "Related Financial Software"; ?>
<?php if (!ini_get('register_globals')) {
 include("../emulate_globals_on.php");
}
?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-main-other.phtml"); ?>

<div id="content">

<h1>Related Financial Software</h1>

<table>
<tr><td>
<b>Select a section:</b></td>
<td>
<form method=post>
<select name=linkpage>
  <option value=general
  <?php if ($linkpage == "general") { echo ("selected"); } ?>
  >General References</option>
  <option value=utilities
  <?php if ($linkpage == "utilities") { echo ("selected"); } ?>
  >Utilities</option>
  <option value=palm
  <?php if ($linkpage == "palm") { echo ("selected"); } ?>
  >Palm Computing</option>
  <option value=stock
  <?php if ($linkpage == "stock") { echo ("selected"); } ?>
  >Stock Trading & Technical Analysis</option>
  <option value=quote
  <?php if ($linkpage == "quote") { echo ("selected"); } ?>
  >Quote Sources, Tools</option>
  <option value=money
  <?php if ($linkpage == "money") { echo ("selected"); } ?>
  >Electronic Currencies</option>
  <option value=erp
  <?php if ($linkpage == "erp") { echo ("selected"); } ?>
  >Business, ERP Projects</option>
  <option value=xml
  <?php if ($linkpage == "xml") { echo ("selected"); } ?>
  >XML and Other Data Formats</option>
  <option value=misc
  <?php if ($linkpage == "misc") { echo ("selected"); } ?>
  >Miscellaneous</option>
  <option value=obsolete
  <?php if ($linkpage == "obsolete") { echo ("selected"); } ?>
  >Historical References</option>
  <option value=review
  <?php if ($linkpage == "review") { echo ("selected"); } ?>
  >Gnucash Review & Rating Sites</option>
</select>
<input type=submit value=Go>
</td>
</table>
</form>

<?php
  if ($linkpage != "") { 
	include($GLOBALS['DOCUMENT_ROOT']."/en/links/links-".$linkpage.".phtml");
  } else {
	include($GLOBALS['DOCUMENT_ROOT']."/en/links/links-general.phtml");
  }
?>

</div>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/footer.phtml"); ?>
