<?php $title = "Mailing Lists"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-main-help.phtml"); ?>
</td>

<td valign="top">
<h1>GnuCash Mailing Lists</h1>

There are a number of GnuCash mailing lists serving different 
communities: some for users and some for developers.  Click on
the bold type for instructions on how to subscribe and unsubscribe.

<p>

<table border=0 cellpadding=1 cellspacing=0 width="100%">
  <tr>
  <td valign=middle align=center bgcolor=#666699>
   <table border=0 cellpadding=5 cellspacing=1 bgcolor=#cacaf7 width="100%">
   <tr>
     <td bgcolor=#666699 width=25%><font color=#ffffff><b>Mailing List</b></td>
     <td bgcolor=#666699 width=75%><font color=#ffffff><b>Description</b></td>
   </tr>
   <!-------------------------------------------------------------->
   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
	 <!-- use absolute URL so that site can be mirrored but cgi-bins go to orig site! -->
         <td valign=top><A HREF="http://www.gnucash.org/cgi-bin/mailman/listinfo/gnucash-announce"> gnucash-announce@gnucash.org</A></td>
       </tr>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><A HREF="/pipermail/gnucash-announce"> Archives</A></td>
       </tr>
       </table>
     </td>
     <td valign=top>Announcement mailing list: Posts to this moderated list announce
		     important events and news concerning GnuCash.
				     This is a low-volume mailing list (1 or fewer messages a week).</td>
   </tr>
   <!-------------------------------------------------------------->
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><A HREF="http://www.gnucash.org/cgi-bin/mailman/listinfo/gnucash-user"> gnucash-user@gnucash.org</A></td>
       </tr>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><A HREF="/pipermail/gnucash-user"> Archives</A></td>
       </tr>
       </table>
     </td>
     <td valign=top>
    User's mailing list: Discussions of how to install, set up and use
    GnuCash, and discussions such as basic accounting principles.
    This is occasionally a high-volume mailing list (2 to 30 messages a day).
	   </td>
   </tr>
   <!-------------------------------------------------------------->
   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><A HREF="http://www.gnucash.org/cgi-bin/mailman/listinfo/gnucash-devel"> gnucash-devel@gnucash.org</A></td>
       </tr>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><A HREF="/pipermail/gnucash-devel"> Archives</A></td>
       </tr>
       </table>
     </td>
     <td valign=top>
    Developer's mailing list: Discussions of current and future features
    and functions, and how they should be implemented.  
    This is occasionally a high-volume mailing list (2 to 30 messages a day).
		 </td>
   </tr>
   <!-------------------------------------------------------------->
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><A HREF="http://www.gnucash.org/cgi-bin/mailman/listinfo/gnucash-de"> gnucash-de@gnucash.org</A></td>
       </tr>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><A HREF="/pipermail/gnucash-de"> Archives</A></td>
       </tr>
       </table>
     </td>
     <td valign=top>
     Dies ist die Mailingliste für deutsche GnuCash-Benutzer. 
     Die Sprache auf dieser Liste ist Deutsch.
     
	   </td>
   </tr>
   <!-------------------------------------------------------------->
   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><A HREF="http://www.gnucash.org/cgi-bin/mailman/listinfo/gnucash-fr"> gnucash-fr@gnucash.org</A></td>
       </tr>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><A HREF="/pipermail/gnucash-fr"> Archives</A></td>
       </tr>
       </table>
     </td>
     <td valign=top>
     Vous avez essayé GnuCash. Cela vous plaît vraiment mais vous aimeriez
     obtenir de l'aide dans votre langue pour plus de simplicité. Cette mailing
     liste est faite pour vous. Elle va permettre de rester en contact avec des
     personnes francophones utilisant GnuCash qui pourront vous guider dans son
     utilisation quotidienne aussi bien que pour une utilisation professionnelle.
     Elle permettra aussi aux personnes réfractaire à la langue de shakespeare
     de rester au courant des derniers développements du logiciels.

	   </td>
   </tr>
   <!-------------------------------------------------------------->
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><A HREF="http://www.gnucash.org/cgi-bin/mailman/listinfo/gnucash-it"> gnucash-it@gnucash.org</A></td>
       </tr>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><A HREF="/pipermail/gnucash-it"> Archives</A></td>
       </tr>
       </table>
     </td>
     <td valign=top>
     gnucash-it ? la lista di distribuzione per il progetto GnuCash in lingua
     italiana. Quando la propria lingua madre ? l'italiano e l'inglese
     rappresenta un ostacolo, quando si ha intenzione di contribuire alla
     localizzazione (l10n) ed internazionalizzazione (i18n) italiana del
     progetto, quando si vuole incontrare qualche italiano per parlare di
     GnuCash, questa lista di distribuzione ? il luogo adatto per inviare i
     propri messaggi.
     <p>
     gnucash-it ? nata per offrire ai traduttori di GnuCash un valido mezzo
     di comunicazione.  Successivamente spera di diventare il punto
     d'incontro per tutti coloro i quali vogliano contribuire al progetto sia
     in qualit? traduttori, revisori e programmatori per la realt? italiana,
     sia di esperti in grado di aiutare chi si trova alle prime armi.

	   </td>
   </tr>
   <!-------------------------------------------------------------->
   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><A HREF="http://www.gnucash.org/cgi-bin/mailman/listinfo/gnucash-patches"> gnucash-patches@gnucash.org</A></td>
       </tr>
       </table>
     </td>
     <td valign=top>
    Developer's mailing list: Submission and discussion of patches, 
    and notifications of CVS tree updates.  
    Patches should be in <tt>makepatch</tt> format.
    Patches may be against source code, documentation, or foreign
    language translations.
    This is occasionally a high-volume mailing list (2 to 30 messages a day).
    
	   </td>
   </tr>
   <!-------------------------------------------------------------->
   </table>
</tr>
</table>

</td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/footer.phtml"); ?>
