<?php 
$title = "Mailing Lists"; 
include("../emulate_globals_on.php");
include($toppath."/externals/en/header.phtml");
include($toppath."/externals/en/menu-main-help.phtml");
?>

<div id="content">

<h1>GnuCash Mailing Lists</h1>

<p>There are a number of GnuCash mailing lists serving different
communities: some for users and some for developers.  Click on
the bold type for instructions on how to subscribe and unsubscribe.
</p>

<div class="tblborder">
   <table border="0" cellpadding=5 cellspacing=1
    style="background-color:#cacaf7" width="100%">
<colgroup><col width="45%"><col width="55%"></colgroup>
   <tr>
    <td style="background-color:#666699">
    <b style="color:white">Mailing List</b></td>
    <td style="background-color:#666699">
    <b style="color:white">Description</b></td>
   </tr>

   <tr class="divider">
    <td valign="top">
     <!-- use absolute URL so that site can be mirrored but cgi-bins
        go to orig site! -->
    <img src="/images/icons/document.txt.gif" width="16" height="16"
    alt="document icon">
    <A HREF="https://lists.gnucash.org/mailman/listinfo/gnucash-announce">
    gnucash-announce@gnucash.org</A>
    <br>
    <img src="/images/icons/document.txt.gif"
    width="16" height="16" alt="document icon">
    <A HREF="https://lists.gnucash.org/pipermail/gnucash-announce">
    Archives</A>
    </td>
    <td valign="top">Announcement mailing list: Posts to this
    moderated list to announce important events and news concerning
    GnuCash. This is a low-volume mailing list (1 or fewer messages a
    week).</td>
   </tr>

   <tr style="background-color:white">
    <td valign="top">
    <img src="/images/icons/document.txt.gif" width="16" height="16"
    alt="document icon">
    <A HREF="https://lists.gnucash.org/mailman/listinfo/gnucash-user">
    gnucash-user@gnucash.org</A>
    <br>
    <img src="/images/icons/document.txt.gif" width="16" height="16"
    alt="document icon">
    <A HREF="https://lists.gnucash.org/pipermail/gnucash-user">
    Archives</A></td>
    <td valign="top">
    User's mailing list: Discussions of how to install, set up and use
    GnuCash, and discussions such as basic accounting principles.
    This is occasionally a high-volume mailing list (2 to 30 messages a
    day).
    </td>
   </tr>

   <tr class="divider">
     <td valign="top">
    <img src="/images/icons/document.txt.gif" width="16" height="16"
    alt="document icon">
    <A HREF="https://lists.gnucash.org/mailman/listinfo/gnucash-devel">
    gnucash-devel@gnucash.org</A>
    <br>
    <img src="/images/icons/document.txt.gif" width="16" height="16"
    alt="document icon">
    <A HREF="https://lists.gnucash.org/pipermail/gnucash-devel">
    Archives</A>
    </td>
    <td valign="top">
    Developer's mailing list: Discussions of current and future
    features and functions, and how they should be implemented.
    This is occasionally a high-volume mailing list (2 to 30
    messages a day).
	</td>
   </tr>

   <tr style="background-color:white">
    <td valign="top">
    <img src="/images/icons/document.txt.gif" width="16" height="16"
    alt="document icon">
    <A HREF="https://lists.gnucash.org/mailman/listinfo/gnucash-de">
    gnucash-de@gnucash.org</A>
    <br>
    <img src="/images/icons/document.txt.gif" width="16" height="16"
    alt="document icon">
    <A HREF="https://lists.gnucash.org/pipermail/gnucash-de">
    Archives</A>
    </td>
    <td valign="top">
    Dies ist die Mailingliste für deutsche GnuCash-Benutzer.
    Die Sprache auf dieser Liste ist Deutsch.
    </td>
   </tr>

   <tr class="divider">
     <td valign="top">
     <img src="/images/icons/document.txt.gif" width="16" height="16"
     alt="document icon">
     <A HREF="https://lists.gnucash.org/mailman/listinfo/gnucash-es">
     gnucash-es@gnucash.org</A>
     <br><img src="/images/icons/document.txt.gif" width="16" height="16"
     alt="document icon">
     <A HREF="https://lists.gnucash.org/pipermail/gnucash-es">
     Archives</A>
     </td>
     <td valign="top">
     gnucash-es es la lista de distribución del proyecto GnuCash en
     español. Está lista está pensada para usuarios finales y
     colaboradores en la traducción y localización de GnuCash.
     </td>
   </tr>

   <tr style="background-color:white">
    <td valign="top">
    <img src="/images/icons/document.txt.gif" width="16" height="16"
    alt="document icon">
    <A HREF="https://lists.gnucash.org/mailman/listinfo/gnucash-fr">
    gnucash-fr@gnucash.org</A>
    <br>
    <img src="/images/icons/document.txt.gif" width="16" height="16"
    alt="document icon">
    <A HREF="https://lists.gnucash.org/pipermail/gnucash-fr">
    Archives</A>
    </td>
    <td valign="top">
    Vous avez essayé GnuCash. Cela vous plaît vraiment mais vous
    aimeriez obtenir de l'aide dans votre langue pour plus de simplicité.
    Cette mailing liste est faite pour vous. Elle va permettre de rester
    en contact avec des personnes francophones utilisant GnuCash qui
    pourront vous guider dans son utilisation quotidienne aussi bien que
    pour une utilisation professionnelle. Elle permettra aussi aux
    personnes réfractaire à la langue de shakespeare de rester au courant
    des derniers développements du logiciels.
    </td>
   </tr>

   <tr class="divider">
    <td valign="top">
    <img src="/images/icons/document.txt.gif" width="16" height="16"
    alt="document icon">
    <A HREF="https://lists.gnucash.org/mailman/listinfo/gnucash-it">
    gnucash-it@gnucash.org</A>
    <br>
    <img src="/images/icons/document.txt.gif" width="16" height="16"
    alt="document icon">
    <A HREF="https://lists.gnucash.org/pipermail/gnucash-it">
    Archives</A>
    </td>
    <td valign="top">
    <p>gnucash-it è la lista di distribuzione per il progetto GnuCash in
    lingua italiana. Quando la propria lingua madre è l'italiano e
    l'inglese rappresenta un ostacolo, quando si ha intenzione di
    contribuire alla localizzazione (l10n) ed internazionalizzazione
    (i18n) italiana del progetto, quando si vuole incontrare qualche
    italiano per parlare di GnuCash, questa lista di distribuzione è il
    luogo adatto per inviare i propri messaggi.</p>
    <p>gnucash-it è nata per offrire ai traduttori di GnuCash un valido
    mezzo di comunicazione.  Successivamente spera di diventare il punto
    d'incontro per tutti coloro i quali vogliano contribuire al progetto
    sia in qualità traduttori, revisori e programmatori per la realtà
    italiana, sia di esperti in grado di aiutare chi si trova alle prime
    armi.</p>
    </td>
   </tr>

   <tr style="background-color:white">
     <td valign="top">
    <img src="/images/icons/document.txt.gif" width="16" height="16"
    alt="document icon">
    <A HREF="https://lists.gnucash.org/mailman/listinfo/gnucash-patches">
    gnucash-patches@gnucash.org</A>
    <br>
    <img src="/images/icons/document.txt.gif" width="16" height="16"
    alt="document icon">
    <A HREF="https://lists.gnucash.org/pipermail/gnucash-patches">
    Archives</A>
    </td>
    <td valign="top">
    Developer's mailing list: Submission and discussion of patches,
    and notifications of CVS tree updates.
    Patches should be in <tt>makepatch</tt> format.
    Patches may be against source code, documentation, or foreign
    language translations.
    This is occasionally a high-volume mailing list (2 to 30 messages
    a day).
    </td>
   </tr>

   <tr class="divider">
    <td valign="top">
    <img src="/images/icons/document.txt.gif" width="16" height="16"
    alt="document icon">
    <A HREF="https://lists.gnucash.org/mailman/listinfo/gnucash-changes">
    gnucash-changes@gnucash.org</A>
    <br>
    <img src="/images/icons/document.txt.gif" width="16" height="16"
    alt="document icon">
    <A HREF="https://lists.gnucash.org/pipermail/gnucash-changes">
    Archives</A>
    </td>
    <td valign="top">
    Developer's mailing list: A list where commit logs are posted
    together with diffs of changed files in CVS.
    This is occasionally a high-volume mailing list (2 to 30
    messages a day).
    </td>
   </tr>

   </table>
</div>

</div>
<?php include($toppath."/externals/en/footer.phtml"); ?>
