<?php 
$title = "Accounting Software for Linux";
include("../emulate_globals_on.php");
include($toppath."/externals/en/header.phtml");
include($toppath."/en/menu/menu-main.phtml");
?>
<div id="content">

<h1>Older Announcements</h1>

<p>
This is an archive of announcements that once appeared on the 
GnuCash home page.
</p>

<?php
    # indicate where to get translated news from ... 
    $native_newspath  =  "../news/old/";
    $alt_newspath  =  "../news/old/";
    include($toppath."/php-scripts/news-script.php");
    ?>  
</div>

<?php include($toppath."/externals/en/footer.phtml"); ?>

