
<?php $title = "Accounting Software for Linux"; ?>
<?php if (!ini_get('register_globals')) {
 include("../emulate_globals_on.php");
}
?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-main.phtml"); ?>
</div>
<div id="content">

<h1>Older Announcements</h1>

<p>
This is an archive of announcements that once appeared on the 
GnuCash home page.
</p>

<?php
    # indicate where to get translated news from ... 
    $native_newspath  =  "../news/old/";
    $alt_newspath  =  "../news/old/";
    include($GLOBALS['DOCUMENT_ROOT']."/php-scripts/news-script.php");
    ?>  

<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/footer.phtml"); ?>

