<?php $title = "Promote GnuCash"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-other-main.phtml"); ?>
</td>

<td valign=top>
<b>Promote GnuCash</b><br><br>

Want to demonstrate your support for GnuCash?  Exhibit one of these 
banners on your site.
<p>

<a href="/images/banners/control_your_finan.jpg">
<img src="/images/banners/control_your_finan.jpg"
     alt="[Control your Finances with the Power of Open Source - GnuCash]">
<br clear>
125 x 125 pixels</a>
<p>

<a href="/images/banners/gnucash_dollar_button.jpg">
<img src="/images/banners/gnucash_dollar_button.jpg"
     alt="[Gnucash Personal Finance Software]">
<br clear>
125 x 125 pixels</a>
<p>

<a href="/images/banners/GnuCash_Long.jpg">
<img src="/images/banners/GnuCash_Long.jpg"
     alt="[Gnucash Personal Finance Software]">
<br clear>
470 x 62 pixels</a>
<p>

<a href="/images/banners/gnu_bill.gif">
<img src="/images/banners/gnu_bill.gif"
     alt="[US. Dollar Bill w/Stallman's Gnu]">
<br clear>
350 x 147 pixels</a>
<p>

<a href="/images/banners/gnucash.jpg">
<img src="/images/banners/gnucash.jpg"
     alt="[white typewriter letters on black background]">
<br clear>
256 x 53 pixels</a>
<p>

<a href="/images/banners/gnucash_brown.jpg">
<img src="/images/banners/gnucash_brown.jpg"
     alt="[black typewriter letters w/ drop shadow on brown background]">
<br clear>
256 x 53 pixels</a>
<p>

<a href="/images/banners/gnucash_light.jpg">
<img src="/images/banners/gnucash_light.jpg"
     alt="[black typewriter letters on light brown background]">
<br clear>
256 x 53 pixels</a>
<p>

<a href="/images/banners/gnucash_white.jpg">
<img src="/images/banners/gnucash_white.jpg"
     alt="[black typewriter letters on white background]">
<br clear>
256 x 53 pixels</a>
<p>

<a href="/images/banners/gnucash_techno.gif">
<img src="/images/banners/gnucash_techno.gif"
     alt="[modern techno/scifi font on clear background]">
<br clear>
400 x 100 pixels</a>
<p>

<a href="/images/banners/logo_beatnik.gif">
<img src="/images/banners/logo_beatnik.gif"
     alt="[black throbbing beatnik font w/ dropshadow on brown background]">
<br clear>
287 x 88 pixels</a>
<p>

<a href="/images/banners/logo_elegant.jpg">
<img src="/images/banners/logo_elegant.jpg"
     alt="[black elegante font on brown background]">
<br clear>
287 x 88 pixels</a>
<p>


</td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/footer.phtml"); ?>

