<?php $title = "Promote GnuCash"; ?>
<?php if (!ini_get('register_globals')) {
 include("../emulate_globals_on.php");
}
?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/externals/en/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-main-other.phtml"); ?>
<div id="content">

<p><b>Promote GnuCash</b></p>

<p>Want to demonstrate your support for GnuCash?  Exhibit one of these 
banners on your site.
</p>

<p><a href="/images/banners/control_your_finan.jpg">
<img src="/images/banners/control_your_finan.jpg"
     alt="[Control your Finances with the Power of Open Source - GnuCash]">
<br>
125 x 125 pixels</a>
</p>

<p><a href="/images/banners/gnucash_dollar_button.jpg">
<img src="/images/banners/gnucash_dollar_button.jpg"
     alt="[Gnucash Personal Finance Software]">
<br>
125 x 125 pixels</a>
</p>

<p><a href="/images/banners/GnuCash_Long.jpg">
<img src="/images/banners/GnuCash_Long.jpg"
     alt="[Gnucash Personal Finance Software]">
<br>
470 x 62 pixels</a>
</p>

<p><a href="/images/banners/gnu_bill.gif">
<img src="/images/banners/gnu_bill.gif"
     alt="[US. Dollar Bill w/Stallman's Gnu]">
<br>
350 x 147 pixels</a>
</p>

<p><a href="/images/banners/gnucash-green.png">
<img src="/images/banners/gnucash-green.png"
     alt="[Name in Bouncing Green]">
<br>
394 x 123 pixels</a>
</p>

<p><a href="/images/banners/gnucash-flying-win.png">
<img src="/images/banners/gnucash-flying-win.png"
     alt="[Flying Screenshots of GnuCash Screens]">
<br>
304 x 179 pixels</a>
</p>

<p><a href="/images/banners/gnucash.jpg">
<img src="/images/banners/gnucash.jpg"
     alt="[white typewriter letters on black background]">
<br>
256 x 53 pixels</a>
</p>

<p><a href="/images/banners/gnucash_brown.jpg">
<img src="/images/banners/gnucash_brown.jpg"
     alt="[black typewriter letters w/ drop shadow on brown background]">
<br>
256 x 53 pixels</a>
</p>

<p><a href="/images/banners/gnucash_light.jpg">
<img src="/images/banners/gnucash_light.jpg"
     alt="[black typewriter letters on light brown background]">
<br>
256 x 53 pixels</a>
</p>

<p><a href="/images/banners/gnucash_white.jpg">
<img src="/images/banners/gnucash_white.jpg"
     alt="[black typewriter letters on white background]">
<br>
256 x 53 pixels</a>
</p>

<p><a href="/images/banners/gnucash_techno.gif">
<img src="/images/banners/gnucash_techno.gif"
     alt="[modern techno/scifi font on clear background]">
<br>
400 x 100 pixels</a>
</p>

<p><a href="/images/banners/logo_beatnik.gif">
<img src="/images/banners/logo_beatnik.gif"
     alt="[black throbbing beatnik font w/ dropshadow on brown background]">
<br>
287 x 88 pixels</a>
</p>

<p><a href="/images/banners/logo_elegant.jpg">
<img src="/images/banners/logo_elegant.jpg"
     alt="[black elegante font on brown background]">
<br>
287 x 88 pixels</a>
</p>

</div>
<?php include($GLOBALS['DOCUMENT_ROOT']."/externals/en/footer.phtml"); ?>

