<?php $title = "Promote GnuCash"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-other-main.phtml"); ?>

<td valign=top>
<b>Promote GnuCash</b><br><br>
<font size=1>

Want to demonstrate your support for GnuCash?  Exhibit one of these 
banners on your site.
<p>

<a href="/images/banners/control_your_finan.jpg">
<img src="/images/banners/control_your_finan.jpg"
     alt="[Control your Finances with the Power of Open Source - GnuCash]">
<br clear>
125 x 125 pixels</a>
<p>

<a href="/images/banners/gnucash_dollar_button.jpg">
<img src="/images/banners/gnucash_dollar_button.jpg"
     alt="[Gnucash Personal Finance Software]">
<br clear>
125 x 125 pixels</a>
<p>

<a href="/images/banners/GnuCash_Long.jpg">
<img src="/images/banners/GnuCash_Long.jpg"
     alt="[Gnucash Personal Finance Software]">
<br clear>
470 x 62 pixels</a>
<p>

<a href="/images/banners/gnu_bill.gif">
<img src="/images/banners/gnu_bill.gif"
     alt="[US. Dollar Bill w/Stallman's Gnu]">
<br clear>
350 x 147 pixels</a>
<p>


</td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/footer.phtml"); ?>

