<?php $title = "Software Requirements"; ?>
<?php
include("../emulate_globals_on.php");
include($toppath."/externals/en/header.phtml");
include($toppath."/en/menu/menu-main-general.phtml");
?>

<div id="content">

<h1>Software Dependencies</h1>

<p>GnuCash depends on a number of important contributing technologies
in order to implement its major functions.  If you want to compile
and work on GnuCash, you will need to install a recent version of
these libraries.
</p><p>
Without a good package manager (<i>e.g.</i> Debian <tt>apt-get</tt>),
it can be quite tedious to find, download and install all of the
required packages (<i>nightmare</i> is a word that has been used).
Therefore, if you are not a programmer, and just want to <b>use</b>
GnuCash, you should stick to the version supplied by your favorite
Linux distribution (<i>e.g.</i> by installing from the vendor's CDROM),
and install using that distribution's standard installation methods.
If you decide that you cannot live with the version that came with your
distro, and you don't have <tt>apt-get</tt> or a similar tool, then
be prepared for a rather long and involved install/upgrade proceedure.
Note that even with <tt>apt-get</tt>, some packages may still need
to be installed manually.
</p>
<p>
The majority of the GnuCash 1.6.x dependencies are satisfied by installing
standard <a href="http://www.gnome.org/">Gnome 1.4</a> core libraries.
The only dependencies beyond a standard Gnome 1.4 installation are
<a href="#guppi">Guppi</a>, <a
href="#guile">Guile</a>, <a href="#slib">slib</a> and <a
href="#gwrap">G-Wrap</a>.
<br><br>

<div class="tblborder">
   <table border=0 cellpadding=5 cellspacing=1
    style="background-color:#cacaf7" width="100%">
<colgroup><col width="20%">
<col width="40%">
<col width="40%"></colgroup>
   <tr>
     <td style="background-color:#666699">
    <b style="color:white">Name</b></td>
     <td style="background-color:#666699">
    <b style="color:white">Description</b></td>
     <td style="background-color:#666699">
    <b style="color:white">Link</b></td>
   </tr>
   <tr>
     <td colspan=3>
<B>GUI Toolkits:</B><BR>
     </td>
         </tr>

   <tr class="divider">
     <td>
    <img src="/images/icons/document.txt.gif" width=16 height=16
    alt="document icon">&nbsp;Gtk+
     </td>
     <td>The Gimp Toolkit</td>
     <td><a href="http://www.gtk.org/">http://www.gtk.org/</a></td>
   </tr>

   <tr>
     <td>
     <img src="/images/icons/document.txt.gif" width=16 height=16
     alt="document icon" >&nbsp;Gnome
     </td>
     <td>The application infrastructure</td>
     <td><a href="http://www.gnome.org">http://www.gnome.org</a></td>
   </tr>

   <tr class="divider">
     <td>
     <img src="/images/icons/document.txt.gif" width=16 height=16
     alt="document icon" >&nbsp;Glade
     </td>
     <td>GTK+ User Interface Builder - This is how many
    of the gnucash GUI's are designed.</td>
     <td><a href="http://glade.gnome.org">http://glade.gnome.org</a></td>
   </tr>

   <tr>
     <td colspan=3>
     <B>Scripting Interface:</B>
     </td>
   </tr>

   <tr class="divider">
    <td>
    <img src="/images/icons/document.txt.gif" width=16 height=16
    alt="document icon" id="guile">&nbsp;Guile
    </td>
    <td>A Scheme interpreter with C programming
    interfaces - This is how gnucash provides 'extension' and rapid
    implementation capabilities.</td>
    <td><a href="http://www.gnu.org/software/guile/guile.html">
    http://www.gnu.org/software/guile/guile.html</a><br> -   You'll need at
    least 1.3, and 1.6 is strongly recommended.</td>
    </tr>

   <tr>
     <td>
      <img src="/images/icons/document.txt.gif" width=16 height=16
      alt="document icon" id="gwrap">&nbsp;G-wrap
     </td>
     <td>A tool for autogenerating scheme bindings for
    C lanugage functions, structures &amp; enums.</td>
     <td><a href="http://www.gnucash.org/pub/g-wrap/">
    http://http.gnucash.org/pub/g-wrap/</a><br> - You'll want the latest
    in the 1.3 series (1.3.4 or newer)</td>
   </tr>

   <tr class="divider">
     <td>
      <img src="/images/icons/document.txt.gif" width=16 height=16
      alt="document icon" id="slib">&nbsp;slib
     </td>
     <td>Scheme library - Miscellaneous scheme functions
        used by GnuCash.</td>
     <td>
    <a href="http://www-swiss.ai.mit.edu/~jaffer/SLIB.html">
    http://www-swiss.ai.mit.edu/~jaffer/SLIB.html</a></td>
   </tr>

   <tr>
     <td colspan=3>
       <B>Web Infrastructure:</B>
     </td>
   </tr>

   <tr class="divider">
     <td>
      <img src="/images/icons/document.txt.gif" width=16 height=16
      alt="document icon" >&nbsp;GtkHTML
     </td>
     <td>The gtk html layout engine - used by gnucash to
    display help documentation, reports and graphs.</td>
     <td>
    <a href="http://www.advogato.org/proj/GtkHTML/">
    http://www.advogato.org/proj/GtkHTML/</a></td>
   </tr>

   <tr>
     <td>
       <img src="/images/icons/document.txt.gif" width=16 height=16
       alt="document icon" >&nbsp;libghttp
     </td>
     <td>The HTTP library - used by gnucash to chat to
    the http protocol to access web servers.</td>
     <td>
    <a href="http://www.gnome.org/">http://www.gnome.org/</a></td>
   </tr>

   <tr class="divider">
     <td>
      <img src="/images/icons/document.txt.gif" width=16 height=16
      alt="document icon" >&nbsp;Gnome XML
     </td>
     <td valign=top>The XML parsing library - used by gnucash to read
    its file format.</td>
     <td valign=top>
    <a href="http://xmlsoft.org/">http://xmlsoft.org/</a></td>
   </tr>

   <tr>
      <td colspan=3>
       <B>Other:</B>
     </td>
   </tr>

   <tr class="divider">
     <td>
      <img src="/images/icons/document.txt.gif" width=16 height=16
      alt="document icon" >&nbsp;Finance::Quote
     </td>
     <td>A perl module to get stock price quotes and
    currency exchange rates from off the net - This is how gnucash
    accesses price data on the net. You can use the
    'update-finance-quote' script included with the distribution to
    obtain a recent version (CPAN is required).</td>
     <td>
    <a href="http://finance-quote.sourceforge.net/">
    http://finance-quote.sourceforge.net/</a></td>
   </tr>

   <tr>
     <td>
      <img src="/images/icons/document.txt.gif" width=16 height=16
      alt="document icon" >&nbsp;Finance::QuoteHist
     </td>
     <td>A perl module to fetch historical stock prices.</td>
     <td>
    <a href="http://sourceforge.net/projects/quotehist/">
    http://sourceforge.net/projects/quotehist/</a></td>
   </tr>

   <tr class="divider">
     <td>
      <img src="/images/icons/document.txt.gif" width=16 height=16
      alt="document icon" >&nbsp;LibOFX
     </td>
     <td>Library for parsing OFX (Open Financial Exchange)
    data. Used by many American banks.</td>
     <td>
    <a href="http://libofx.sourceforge.net/">
    http://libofx.sourceforge.net/</a>
     </td>
   </tr>

   <tr>
     <td>
      <img src="/images/icons/document.txt.gif" width=16 height=16
      alt="document icon" >&nbsp;OpenHBCI
     </td>
     <td>Library for connecting to German banks that
    support HBCI.</td>
     <td>
    <a href="http://openhbci.sourceforge.net/">
    http://openhbci.sourceforge.net/</a><br>
     Optional; required only if you want to connect to HBCI banks.</td>
   </tr>

   <tr class="divider">
     <td>
      <img src="/images/icons/document.txt.gif" width=16 height=16
      alt="document icon" id="guppi">&nbsp;Guppi
     </td>
     <td>A graphical plotting and analysis tool - used to generate 
	and display gnucash charts and plots.</td>
     <td>
    <a href="http://www.gnome.org/guppi/">http://www.gnome.org/guppi/</a>
    <br> - Any recent version will work, but 0.35.5 or later is 
	required for full functionality.</td>
   </tr>

   <tr>
     <td>
      <img src="/images/icons/document.txt.gif" width=16 height=16
      alt="document icon" >&nbsp;Gnome Print
     </td>
     <td>gnome printing architecture - used by gnucash
    for check printing &amp; general printing.</td>
     <td>
    <a href="http://ftp.gnome.org/pub/GNOME/sources/gnome-print/">
    http://ftp.gnome.org/pub/GNOME/ sources/gnome-print/</a></td>
   </tr>
   </table>
</div>

</div>
<?php include($toppath."/externals/en/footer.phtml"); ?>
