<?php
   echo ("<?xml version=\"1.0\" ?>\n");
?>

 <rss version="2.0" encoding="iso-8859-1">
  <channel>
  <!-- <channel rdf:about="http://www.xml.com/xml/news.rss"> -->
  <title>GnuCash News</title>
  <description>News and Announces concerning the GnuCash Project</description>

<?php
    //  change  this  to  the  directory  of  your  news  files 
    //  they  should  be  plain  ASCII  text  files  with  extension  ".txt" 

    # Perhaps we should be using this, but it won't work until we have
    # the DocumentRoot set up.
    # $newspath = $GLOBALS['DOCUMENT_ROOT']."/news/

    # So we'll just do this for now...
    $newspath  =  "news/"; 

    //  Declare  array  to  hold  filenames 
    $newsfile  =  array(); 
    
    //  Create  handle  to  search  directory  $newspath  for  files 
    $hd  =  dir($newspath); 
    
    //  Get  all  files  and  store  them  in  array 
    while(  $filename  =  $hd->read()  )  { 
        $s=strtolower($filename); 
        if  (strstr($s, ".txt"))  { 
            //  Determine  last  modification  date 
            $lastchanged=filemtime($newspath.$filename); 
            $newsfile[$filename]  =  $lastchanged; 
        }    
    } 
    
    //  Sort  files  in  descending  order 
    arsort($newsfile); 
    //  Output  files  to  browser 
    for(reset($newsfile);  $key  =  key($newsfile);  next($newsfile))  
    { 
        $fa  =  file($newspath.$key); 
        $n=count($fa); 
	if ($n > 5) { $n = 5; }

        // echo("<item rdf:about=\"http://xml.com/pub/2000/08/09/xslt/xslt.html\">"\n);
        echo("<item>\n");
        echo("<title>");
	print $fa[0];

	print  " - (". date( "Y-m-d", $newsfile[$key]) ;
	print  date( "H:i:s",$newsfile[$key]). ")"; 

        echo("</title>\n");
        echo("<description>");

        for  ($i=2;  $i<$n;  $i=$i+1)  { 
	    print $fa[$i];
        } 
        echo("</description>\n");
        echo("<link>");
        echo("http://www.gnucash.org/#");
	print $key;
        echo("</link>\n");
	// print "<pubDate>". date( "Y-m-d", $newsfile[$key]). date( "H:i:s",$newsfile[$key]). " CST</pubDate>\n"
	// echo("<language>en-us</language>\n");
	// echo("<copyright>Copyright 2001-2003 The GnuCash Project</copyright>\n");
        echo("</item>\n");
    }    
    
    $hd->close();  
    ?>  
 </channel>
</rss>
