
</tr>
</table>

<table border=0 cellpadding=3 cellspacing=0 width="100%" bgcolor="#666699">
<tr>
  <td colspan=3 bgcolor="#666699" align=center>
  <font size=-1 color="#ffffff"><b>Copyright © 2001,2002,2003 Projet GnuCash</b></font>
  </td>
</tr>
<tr>
  <td width='10%'>&nbsp;</td>
  <td width='80%' colspan=1 bgcolor="#666699" align="center">
     <font size=-1 color="#ffffff">Problemes Serveur &amp; e-mail contacter : 
	 <a href="mailto:linas@linas.org"><b>linas@linas.org</b></a></font>
	 <br>
	 <font size=-1 color="#ffffff">Problemes de Traduction contacter : 
	 <a href="mailto:xavier.toulzac@ifrance.com"><b>xavier.toulzac@ifrance.com</b></a></font>
	 </td>
  <td width='10%' align=right valign=top><font size=-1 color="#ffffff">
     <a href='http://validator.w3.org/check/referer'>Validation</a></font></td>
</tr>
</table>

</body>
</html>
