  <table border=0 cellpadding=0 cellspacing=6>
  <tr>
  <td><img src="/images/spacer.gif" height=1 width=2></td>
  <td>
    <font size=-1>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/nl/index.phtml">Home / News </a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/nl/features.phtml">Features</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/nl/screenshots.phtml">Screenshots</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/nl/contribute.phtml">Hoe te Helpen?</a><br>

<!--
    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/nl/quiz.phtml">Enquete</a><br>
-->
 
    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/nl/required.phtml">Software Dependencies</a><br>
 
  </td>
  </tr>
  </table>
