  <table border=0 cellpadding=0 cellspacing=6>
  <tr>
  <td><img src="/images/spacer.gif" height=1 width=2></td>
  <td>
    <font size=-1>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/nl/irc.phtml">IRC (Chat)</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/nl/lists.phtml">Mailing Lijsten</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/nl/bugs.phtml">Rapportage Foutmeldingen</a><br>
    
  </td>
  </tr>
  </table>


