  <table border=0 cellpadding=0 cellspacing=6>
  <tr>
  <td><img src="/images/spacer.gif" height=1 width=2></td>
  <td>
    <font size=-1>

<!--
    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="http://www.linas.org/pub/gnucash/">@ linas.org</a><br>
    -->

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="http://www.gnucash.org/pub/">USA (@ gnucash.org)</a><br>
 
    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="http://sourceforge.net/project/showfiles.php?group_id=192">SourceForge</a><br>
 
    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="ftp://planetmirror.com/pub/gnucash/">Australie</a><br>
 
  </td>
  </tr>
  </table>
