<!-- MENU:START -->

<table border=0 cellpadding=4 cellspacing=0 width=100%>
<tr><td bgcolor=#cacaf7>
  <img border=0 src="../www/images/webding.png"> <b>General Information</b>
  <?php include("menu-general.phtml"); ?>
  </td></tr>
<tr><td>
  <img border=0 src="../www/images/webding.png"> <b>Documentation</b>
  <?php include("menu-documentation.phtml"); ?>
  </td></tr>
<tr><td>
  <img border=0 src="../www/images/webding.png"> <b>Help</b>
  <?php include("menu-help.phtml"); ?>
  </td></tr>
<tr><td>
  <img border=0 src="../www/images/webding.png"> <b>Downloads</b>
  <?php include("menu-downloads.phtml"); ?>
  </td> </tr>
<tr><td>
  <img border=0 src="../www/images/webding.png"> <b>Developer Information</b>
  <?php include("menu-developer.phtml"); ?>
  </td></tr>
<tr><td>
  <img border=0 src="../www/images/webding.png"> <b>Other Information</b>
  <?php include("menu-other.phtml"); ?>
  </td></tr>
<tr><td>
  <img border=0 src="../www/images/webding.png"> <b>Search</b>
  <?php include("menu-search.phtml"); ?>
  </td></tr>
</table>

<!-- MENU:END -->
