  <table border=0 cellpadding=0 cellspacing=6>
  <tr>
  <td><img src="/images/spacer.gif" height=1 width=2></td>
  <td>
    <font size=-1>
      <form action="/en/search.phtml" method="get">
      <input type=text name=words size=15>
      <br><font size="-2">Sorteer methode:</font>
      <select name="sort">
      <option value="sort">Standaard
      <option value="time">Tijd
      <option value="revtime">Tijd (omgekeerd)
      </select>
      </form>

  </td>
  </tr>
  </table>
