  <table border=0 cellpadding=0 cellspacing=6>
  <tr>
  <td><img src="/images/spacer.gif" height=1 width=2></td>
  <td>
    <font size=-1>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/en/architecture.phtml">Systeem Architectuur</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/en/roadmap.phtml">Toekomst</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="http://linas.org/linux/gnucash/projects.html">Doel van Project</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/lxr/">Bekijk Broncode</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/en/hacking.phtml">CVS Toegang</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="http://www2.iro.umontreal.ca/~pinard/po/registry.cgi?domain=gnucash">Vertalingen</a><br>

  </td>
  </tr>
  </table>
