  <table border=0 cellpadding=0 cellspacing=6>
  <tr>
  <td><img src="/images/spacer.gif" height=1 width=2></td>
  <td>
    <font size=-1>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/nl/links.phtml">Gerelateerde Financiele Software</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/nl/articles.phtml">GnuCash in het Nieuws</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/nl/promote.phtml">GnuCash Banners!</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/nl/history.phtml">Historie &amp; Credits</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/nl/quiz-results.phtml">resultaten Enquete</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/nl/sizing.phtml">Sizing</a><br>

  </td>
  </tr>
  </table>
