</div>
<div style="clear:both;float:none;">&nbsp;</div>
<div id="tail">
<p style="float:right;padding-right:1em;"><a href='http://validator.w3.org/check/referer'>Validate</a> </p>
<p style="text-align:center;"><b>Copyright &copy; 2001-2006 The GnuCash Project</b></p>
<p style="text-align:center;">Server &amp; email outage reports to
<a href="mailto:linas@linas.org"><b>linas@linas.org</b></a>
</p>
</div>
</body>
</html>
