
</tr>
</table>

<table border=0 cellpadding=3 cellspacing=0 width="100%" bgcolor="#666699">
<tr>
  <td colspan=3 bgcolor="#666699" align=center>
  <font size=-1 color="#ffffff"><b>Copyright © 2001,2002,2003,2004 The GnuCash Project</b></font>
  </td>
</tr>
<tr>
  <td width='10%'>&nbsp;</td>
  <td width='80%' colspan=1 bgcolor="#666699" align="center">
     <font size=-1 color="#ffffff">Server &amp; email outage reports to: 
	 <a href="mailto:linas@linas.org"><b>linas@linas.org</b></a></font></td>
  <td width='10%' align=right valign=top><font size=-1 color="#ffffff">
     <a href='http://validator.w3.org/check/referer'>Validate</a></font></td>
</tr>
</table>

</body>
</html>
