<html>
<head>
<link rel="stylesheet" href="/en/gnucash.css" type="text/css">
<title>GnuCash - <?php echo $title; ?></title>
</head>

<body bgcolor=#ffffff topmargin="0" leftmargin="0" marginwidth="0" marginheight="0"> 

<table border=0 cellpadding=3 cellspacing=0 width="100%">
<tr>
<td valign=bottom colspan=2 bgcolor=#666699><img src=/images/gnucash_logo1.png></td>
<td align=right valign=bottom bgcolor=#666699 width=45%><font size=-1 color=#ffffff>
Language: 
<b>English</b> 
 (<a class=nav href=http://gnucash.planetmirror.com/>AU mirror</a>)
| <a class=nav href=/fr/>Français</a>
| <a class=nav href=http://www.hthoma.de/projekte/gnucash/index.html>Deutsch</a>
 (<a class=nav href=/de/>mirror</a>)
| <a class=nav href=/pt_PT/>Português</a>
&nbsp;</font></td>
</tr>
</table>

<table border=0 cellpadding=3 cellspacing=0 width="90%">
<tr>
<td valign=top width=1% bgcolor=#ffffff>
<img src=/images/spacer.gif width=200 height=1><br>
