
</tr>
</table>

<table border=0 cellpadding=3 cellspacing=0 width="100%">
<tr>
    <td colspan=3 bgcolor=#666699 align=center><font size=-1 color=#ffffff><b>Copyright (c) 2001..2006 The GnuCash Project</b></font></td>
<tr>
</tr>
    <td colspan=3 bgcolor=#666699 align=center><font size=-1 color=#ffffff>Server &amp; email problemen naar: <a href="mailto:linas@linas.org"><b>linas@linas.org</b></a></font></td>
</tr>
</table>

</body>
</html>
