
<b>Als u een fan bent, kunt u op de volgende wijzen helpen:</b><br><br>
<font size=-1>
Er zijn vele beginnende gebruikers van  GnuCash
    die af en toe hulp nodig hebben met het gebruik van GnuCash.  Lees de  
    <a href="/nl/lists.phtml">gnucash-user</a> mailing list,
    en probeer vragen te beantwoorden, of in ieder geval de discussie te leiden.
    Wanneer u officiele training hebt gehad in boekhouden, of  
    behoorlijke financiele ervaring heeft, en u wilt de programmeurs helpen
    bepaalde modules correct te implementeren, dan kunt u meedoen aan de 
    tamelijk technische discussies die plaatshebben  
    in <a href="/nl/lists.phtml">gnucash-devel</a>.
    Dappere beta-testers kunnen we altijd gebruiken voor de laatste
    versie.  Dat is vanwege het feit dat de laatste versie vaak  
    gebroken is, en we mensen nodig hebben die ons kunnen vertellen waar de fouten zitten.
    Bent u een kunstenaar: wel, een nieuw logo, een beter ikoon,
    meer plaatjes kunnen nooit kwaad.
    Wilt u gratis software projecten aanprijzen, schrijf ons:
    wij houden van promoters.
</font>
