
<b>Ben tu een vertaler, dan kunt u als volgt helpen:</b><br><br>
<font size=-1>
Alle menu's en dialoguen in GnuCash zijn volledig 
    geinternationaliseerd/gelocaliseerd middels de GNU gettext tools.
    De kans is groot dat u uw machine al correct geconfigureerd heeft 
    voor uw lokale instellingen, en daarom is het aannemelijk dat
    u GnuCash al in uw eigen taal gebruikt,
    met het juiste datumformaat en valuta. 
    Zo niet, dan is er of een fout aanwezig, of uw computer
    is niet juist geconfigureerd, of uw taal is een andere dan  
    Deens, Engels, Frans, Duits, Italiaans, Japans, 
    Russisch of Zweeds.  
    <p>
    Dit betekent niet dat de vertaling niet perfect is: Als
    de verkeerde woorden of zinnen gebruikt worden, 
    moet u contact opnemen met diegene die de vertaling onderhoudt.
    (zie het README bestand).  Wanneer de verkeerde muntsoort 
    afgebeeld wordt, of er zijn andere landinstellingsproblemen, 
    dan kunt u contact opnemen met de 
    <a href="/en/lists.phtml">gnucash-devel</a> mailing lijst.
    Het is belangrijk te weten dat de invoer methodes voor Aziatische talen (Japans, Chinees, 
    etc.) en de 'van-rechts-naar-links' talen niet compleet zijn:
    we zijn op zoek naar programmeurs die de kennis hebben om dit probleem op te lossen.
	 Tevens ben ik op zoek naar een 'Asian-howto'
    geschreven in het Engels, zodat ik (en in feite alle Engelssprekende programmeurs)
    onze eigen machines kunnen installeren voor een demo. 
    Neem contact op met <a href="mailto:linas@linas.org">linas at linas.org</a>
    als u mij kunt helpen met het opzetten van mijn machine voor de 
    Japanse of Chinese taal.
    </p>
    <p>
    Het maken van nieuwe vertalingen is relatief eenvoudig: 
    bekijk de <a href="/en/hacking.phtml">broncode</a>,
    lees het bestand <tt>README.translator.txt</tt>, en kijk dan
    naar het vertalingsbestand in de <tt>po</tt> folder.
    </p>
    <p>
    We zoeken ook niet-Engelse vertalingen van de website.
    Heeft u een van deze vertalingen, schrijf dan naar 
    <a href="mailto:webmaster@gnucash.org">webmaster at gnucash.org</a>.
    Niet-Engelse vertalingen van de documentatie zijn ook nodig.
    Het moeilijke is, natuurlijk, dat de documentatie tamelijk 
    ruw is en momenteel herschreven wordt.  Als u een goede schrijver 
    bent, neem dan contact met ons op.
</font>
