
<b>Als u een programmeur bent, kunt u op de volgende wijzen helpen:</b><br><br>
<font size=-1>
Ga naar de <a href="/en/lists.phtml">gnucash-devel@gnucash.org</a>
    mailing lijst.  Set up CVS op uw computer, controlleer de
 <a href="/en/hacking.phtml">source code</a>.
    Lees de build readme's in de doc subfolders
    en begin te hacken.  Afhankelijk van uw temperament 
    , wilt u misschien uw hacks ook bespreken
    in de mailing lijst: dit voorkomt devolutie en andere onaangename zaken 
    zoals het uitvinden dat niet iedereen  
    denkt dat uw patch de beste is.  Om een betere indruk te krijgen
    van wat er gaande is, ga naar de 
    <a href="/en/architecture.phtml">architectural overview</a>.
    Om een indruk te krijgen wat er te koop is en wie er wat doet,
    ga naar de 
    <a href="http://www.linas.org/linux/gnucash/projects.html">
    projectlijst</a>.  Deze is lang, maar helpt u te orienteren en een 
    idee te krijgen van van de status van de diverse componenten.
    Last, but not least, kan het erg zinnig en leuk zijn om de bestaande documentatie  
    in de subfolder <tt>src/doc</tt> in
    the brontree te lezen.
</font>
