
<b>Bent u een webmaster, dan kunt u als volgt helpen:</b><br><br>
<font size=-1>
We zoekeniemand die ons kan helpen met het opzetten en onderhouden van al dat 
    fantastische ontwikkelingsgereedschap dat een 'echt' project nodig heeft, zoals
    lxr en bonsai, en misschien een bug-tracking tool,
    of andere bits &amp; pieces.  We hebben zelfs iemand nodig om de  
    mail archiven veilig te stellen en werkend te houden, en er voor te zorgen dat
    recente mail geindexeerd wordt en te doorzoek is.
</font>
