<?php
include("lang.php");
$title = T_("GnuCash 2.6 release tour");
include("emulate_globals_on.php");
include("$top_dir/externals/header.phtml");
include("$top_dir/externals/menu.phtml");
?>

<div id="content">
<h1><?php echo T_($title);?></h1>

<div>
<p>
<?php echo T_("This tour will introduce you to new major features of <span class=\"gnucash\">GnuCash</span> 2.6.");?>
</p>
</div>


<h2 class="featuretitle"><?php echo T_("Jqplot Reports");?></h2>
<p class="justify">
<?php echo T_("<span class=\"gnucash\">GnuCash</span> now uses javascript jqplot to render reports. This gives a more professional look to all graphical reports (piechart, barchart, scatterplot).");?>
</p>
<table class="figure" align="center">
   <tr>
     <td><img src="<?=$top_dir?>/images/2.6-release/2.6-jqplot-reports.png" alt="[jqplot barchart]" /></p>
     </td>
   <tr>
     <th><?php echo T_("A barchart rendered in GnuCash with jqplot.");?>
     </th>
   </tr>
</table>

<h2 class="featuretitle"><?php echo T_("New predefined reports management system");?></h2>
<p class="justify">
<?php echo T_("The old <span class=\"gnucash\">GnuCash</span> custom report management system has been revised. You can save a report using the dedicated options in the File menu and rerun it later by selecting it from the menu Reports->Preconfigured Reports.");?>
</p>
<table class="figure" align="center">
   <tr>
     <td><img src="<?=$top_dir?>/images/2.6-release/2.6-Pre-reports.png" alt="[Preconfigred reports window]" /></p>
     </td>
   <tr>
     <th><?php echo T_("The Preconfigured Reports window. You can select and run a preconfigured report, edit it's name and delete it.");?>
     </th>
   </tr>
</table>

<h2 class="featuretitle"><?php echo T_("Export any report directly to PDF");?></h2>
<p class="justify">
<?php echo T_("It is now possible to export any report directly in a PDF file without going thru the Print window.");?>
</p>

<h2 class="featuretitle"><?php echo T_("Attach file or location to any transaction");?></h2>
<p class="justify">
<?php echo T_("It is now possible to link an external file or a location (URL) to a transaction. This long-requested feature is available through both the Transaction menu and rhe transaction's context menu. The files are displayed in the default viewer for that file type.");?>
</p>

<table class="figure" align="center">
   <tr>
     <td><img src="<?=$top_dir?>/images/2.6-release/2.6-file-location.png" alt="[Attach file/ location to transaction]" /></p>
     </td>
   <tr>
     <th><?php echo T_("You can now attach a file or a location to any transaction.");?>
     </th>
   </tr>
</table>

<h2 class="featuretitle"><?php echo T_("Account colors");?></h2>
<p class="justify">
<?php echo T_("It is now possible to associate to any account a unique color from the edit account window. This color can then be displayed as account name and account register tab background easing the lookup of a specific account.");?>
</p>

<table class="figure" align="center">
   <tr>
     <td><img src="<?=$top_dir?>/images/2.6-release/2.6-acc-colors.png" alt="[Account colors]" /></p>
     </td>
   <tr>
     <th><?php echo T_("The colors ease the lookup of specific accounts in the account tree and in tabs.");?>
     </th>
   </tr>
</table>

<h2 class="featuretitle"><?php echo T_("Timout on \"Save changes on closing\"");?></h2>
<p class="justify">
<?php echo T_("In the General tab of the <span class=\"gnucash\">GnuCash</span> Preferences is now possible to set a timeout for the \"Save changes on closing\" window. If enabled, the \"Save changes on closing\" question will only wait a limited number of seconds for an answer. If the user didn't answer within that time, the changes will be saved automatically and the question window closed.");?>
</p>

<h2 class="featuretitle"><?php echo T_("Save \"Filter By\" settings");?></h2>
<p class="justify">
<?php echo T_("It is now possible to save the \"Filter By...\" settings for an account register.");?>
</p>

<table class="figure" align="center">
   <tr>
     <td><img src="<?=$top_dir?>/images/2.6-release/2.6-save-filter.png" alt="[Filter by save]" /></p>
     </td>
   <tr>
     <th><?php echo T_("Save the \"Filter By...\" settings by enabling the \"Save Filter\" checkbox.");?>
     </th>
   </tr>
</table>

<h2 class="featuretitle"><?php echo T_("Improved business module");?></h2>
<p class="justify">
<?php echo T_("The business module has been revamped and we introduced some new features:");?>
<ul>
<li><?php echo T_("Credit Notes");?></li>
<li><?php echo T_("Customer and Vendor Overview Pages");?></li>
<li><?php echo T_("Customer Overview Reports");?></li>
<li><?php echo T_("Existing Transactions may be reassigned as invoice payments");?></li>
<li><?php echo T_("Support for duplicate invoices");?></li>
<li><?php echo T_("Improved invoice and bill handling: Post, print, or duplicate multiple items directly from a search results list");?></li>
<li><?php echo T_("Better invoice printing setup: Choose a default invoice report as a preference");?></li>
<li><?php echo T_("Reorder invoice entries in the invoice window");?></li>
</ul>
</p>
<table class="figure" align="center">
   <tr>
     <td><img src="<?=$top_dir?>/images/2.6-release/2.6-credit-customer-report.png" alt="[Customer report]" /></p>
     </td>
   <tr>
     <th><?php echo T_("Customer report with an invoice and a credit note.");?>
     </th>
   </tr>
</table>

<h2 class="featuretitle"><?php echo T_("New preference system");?></h2>
<p class="justify">
<?php echo T_("The preferences system has been rewritten to use GSettings from GIO (GLib) instead of GConf. This is a simpler and more robust backend which writes to the OS's native prefs — defaults on OS X and the Registry on MSWindows — and allows us to remove several troublesome dependencies including GConf, ORBit, and DBus.");?></p>
<div class="dialog note">
<p><?php echo T_("Note that window position, column sizes, and sort orders will not be migrated from GConf. Those settings will revert to the default the first time you use Gnucash 2.5.6 or later, but they will be saved once you've reset them. ");?></p>
</div>

<h2 class="featuretitle"><?php echo T_("Relicensing");?></h2>
<p class="justify">
<?php echo T_("By agreement of all authors we have relicensed <span class=\"gnucash\">GnuCash</span> to the Gnu Public License Version 2 or later from just Version 2.");?></p>

<h2 class="featuretitle"><?php echo T_("Download");?></h2>
<p class="justify">
<?php echo T_("You can download the new 2.6 version of <span class=\"gnucash\">GnuCash</span> from the <a href=\"http://gnucash.org\">GnuCash website main page</a>.");?></p>

<h2 class="featuretitle"><?php echo T_("Help");?></h2>
<p class="justify">
<?php echo T_("<span class=\"gnucash\">GnuCash</span> 2.6 comes with updated Help and Guide. If you can't find the answer to your questions in those documents, try with the <a href=\"http://wiki.gnucash.org/wiki/GnuCash\">GnuCash wiki</a>. If both options are unsatisfactory, you can send your questions to the <a href=\"http://wiki.gnucash.org/wiki/Mailing_Lists\">GnuCash mailing lists</a>: the <span class=\"gnucash\">GnuCash</span> community is very friendly and experienced and someone will surely assist you.");?></p>

<h2 class="featuretitle"><?php echo T_("Want to Help?");?></h2>
<p class="justify">
<?php echo T_("<span class=\"gnucash\">GnuCash</span> is a program maintained by volunteers. If you want to be part of the effort, you can contribute in many ways:");?>
<ul>
<li><?php echo T_("By developing the source code");?></li>
<li><?php echo T_("By testing the program and reporting bugs");?></li>
<li><?php echo T_("By translating the program to your language");?></li>
<li><?php echo T_("By creating documentation for the program");?></li>
<li><?php echo T_("By partecipating in the <a href=\"http://wiki.gnucash.org/wiki/Mailing_Lists\">GnuCash mailing lists</a>");?></li>
<li><?php echo T_("<a href=\"http://sourceforge.net/donate/index.php?group_id=192\">By making a donation</a>");?></li>
<li><?php echo T_("By spreding the word");?></li>
<li><?php echo T_("By liking our project page on <a href=\"https://www.facebook.com/Gnucash\">facebook</a> and <a href=\"http://plus.google.com/u/0/+gnucash\">Google+</a>");?></li>
</ul>
</p>
</div>
<?php include("externals/footer.phtml"); ?>
