<?php
include("lang.php");
$title = T_("GnuCash 2.6 release tour");
include("emulate_globals_on.php");
include("$top_dir/externals/header.phtml");
include("$top_dir/externals/menu.phtml");
?>

<div id="content">
<h1><?php echo T_($title);?></h1>

<div>
<p>
<?php echo T_("<span class=\"gnucash\">GnuCash</span> This tour will introduce you to new major features of <span class=\"gnucash\">GnuCash</span> 2.6.");?>
</p>
</div>


<h2 class="featuretitle"><?php echo T_("Jqplot Reports");?></h2>

<p class="justify">
<?php echo T_("<span class=\"gnucash\">GnuCash</span> now uses javascript jqplot to render reports. This gives more flexibility and a more professional look to all graphical reports (piechart, barchart, scatterplot).");?>
</p>

<table class="figure" align="center">
   <tr>
     <td><img src="<?=$top_dir?>/images/2.6-release/2.6-jqplot-reports.png" alt="[Basic account relationship]" /></p>
     </td>
   <tr>
     <th>A barchart rendered in GnuCash with jqplot.
     </th>
   </tr>
</table>

<h2 class="featuretitle"><?php echo T_("New predefined reports management system");?></h2>

<p class="justify">
<?php echo T_("The old <span class=\"gnucash\">GnuCash</span> custom report management system has been revised. You can save a report using the dedicated options in the File menu and rerun it later by selecting it from the menu Reports->Preconfigured Reports.");?>
</p>

<table class="figure" align="center">
   <tr>
     <td><img src="<?=$top_dir?>/images/2.6-release/2.6-Pre-reports.png" alt="[Basic account relationship]" /></p>
     </td>
   <tr>
     <th>The Preconfigured Reports window. You can select and run a preconfigured report, edit it's name and delete it.
     </th>
   </tr>
</table>

<h2 class="featuretitle"><?php echo T_("Export any report directly to PDF");?></h2>

<p class="justify">
<?php echo T_("It is now possible to export any report directly in a PDF file without going thru the Print window.");?>
</p>


<!--
<h2 class="featuretitle"><?php echo T_("Checkbook-Style Register");?></h2>
<p class="justify">
<?php echo T_("The <span class=\"gnucash\">GnuCash</span> checkbook-style register provides a custom, convenient and familiar interface to entering financial transactions.");?></p>
<p class="justify">
<?php echo T_("The register supports common checking and credit-card transactions, as well as income, stock and currency transactions. The following features are also provided:");?>
</p>
<ul>
<li><?php echo T_("The ability to enter <b>split transactions</b>");?></li>
<li><?php echo T_("The ability to mark a transaction as <b>cleared</b> or <b>reconciled</b>");?></li>
<li><?php echo T_("<b>Autofill</b> of entered transactions");?></li>
<li><?php echo T_("The ability to display <b>multiple accounts</b> in a single register window");?></li>
<li><?php echo T_("A <b>summary bar</b> that displays all of the relevant account's balance information");?></li>
<li><?php echo T_("Many options to <b>customize</b> the appearance and the display style");?></li>
</ul>

<table class="figure" align="center">
   <tr>
     <td><img src="<?=$top_dir?>/images/features/feature_register.png" alt="[Register]" /></p></p>
     </td>
   <tr>
     <th>The transactions register.
     </th>
   </tr>
</table>
-->


</div>
<?php include("externals/footer.phtml"); ?>
