<?php
include("lang.php");
$title = T_("GnuCash 2.6 release tour");
include("emulate_globals_on.php");
include("$top_dir/externals/header.phtml");
include("$top_dir/externals/menu.phtml");
?>

<div id="content">
<h1><?php echo T_($title);?></h1>

<div>
<p>
<?php echo T_("<span class=\"gnucash\">GnuCash</span> This tour will introduce you to new major features of <span class=\"gnucash\">GnuCash</span> 2.6.");?>
</p>
</div>


<h2 class="featuretitle"><?php echo T_("Double Entry");?></h2>


<table class="figure" align="center">
   <tr>
     <td><p align="center"><img src="<?=$top_dir?>/images/features/basics_AccountRelationships.png" alt="[Basic account relationship]" /></p>
     </td>
   <tr>
     <th>The double Entry system.
     </th>
   </tr>
</table>

<p class="justify">
<?php echo T_("Every transaction must debit one account and credit others by an equal amount. This ensures the books balance: the difference between income and expenses exactly equals the sum of assets and liabilities.");?>
</p>


<h2 class="featuretitle"><?php echo T_("Checkbook-Style Register");?></h2>
<p align="center"><img src="<?=$top_dir?>/images/features/feature_register.png" alt="[Register]" /></p>
<p class="justify">
<?php echo T_("The <span class=\"gnucash\">GnuCash</span> checkbook-style register provides a custom, convenient and familiar interface to entering financial transactions.");?></p>
<p class="justify">
<?php echo T_("The register supports common checking and credit-card transactions, as well as income, stock and currency transactions. The following features are also provided:");?>
</p>
<ul>
<li><?php echo T_("The ability to enter <b>split transactions</b>");?></li>
<li><?php echo T_("The ability to mark a transaction as <b>cleared</b> or <b>reconciled</b>");?></li>
<li><?php echo T_("<b>Autofill</b> of entered transactions");?></li>
<li><?php echo T_("The ability to display <b>multiple accounts</b> in a single register window");?></li>
<li><?php echo T_("A <b>summary bar</b> that displays all of the relevant account's balance information");?></li>
<li><?php echo T_("Many options to <b>customize</b> the appearance and the display style");?></li>
</ul>

</div>
<?php include("externals/footer.phtml"); ?>
