<?php 
include("lang.php");
$title = T_("Documentation");
$online = T_("Browse documentation online");
$pdf = T_("Download documentation as PDF");
$epub = T_("Download documentation as epub");
$mobi = T_("Download documentation as mobipocket");                                                   
include("emulate_globals_on.php");
include("externals/header.phtml");
include("externals/menu.phtml");
?>

<div id="content">

<h1><?php echo T_("GnuCash Documentation");?></h1>

<p class="justify"><?php echo T_("There are two major <span class=\"gnucash\">GnuCash</span> documentation packages to help users: the <b>Help Manual</b> and the <b>Tutorials and Concepts Guide</b>.");?></p>

<p class="justify"><?php echo T_("The <b>Help Manual</b> is designed to be a quick reference of how to accomplish specific tasks and how to use the features in <span class=\"gnucash\">GnuCash</span>. The <b>Concepts Guide</b> is designed to be an in depth guide to the concepts behind using <span class=\"gnucash\">GnuCash</span> with a tutorial to show how to put those concepts into practice.");?></p>

<p class="justify"><?php echo T_("Additionally, you can talk to someone via IRC at <i>irc.gnome.org</i> channel <b>#gnucash</b> about your question. Another resource is the <a href=\"http://wiki.gnucash.org/wiki/\">English</a> or <a href=\"http://linuxwiki.de/GnuCash\">Deutsch</a> <span class=\"gnucash\">GnuCash</span> wikis.");?></p>

<p class="justify"><?php echo T_("You can also send an email to the <a href=\"mailto:gnucash-user@lists.gnucash.org\">gnucash-user</a> mailing list if you cannot find a satisfactory answer to your question within either the <b>Help Manual</b> or the <b>Tutorial and Concepts Guide</b>. We <b>want</b> feedback from you, it is also through your comments that we know how to improve the documentation.");?></p>

<div class="dialog note">
<p class="justify"><?php echo T_("<span class=\"gnucash\">GnuCash</span>'s documentation has been created by its community. See the <a href=\"develdocs.phtml\">Writing Documentation page</a> if you are interested in contributing to this effort.");?></p>
</div>

<div class="featurecontainer">
<div class="featureborder">
<h2 class="featuretitle">GnuCash v2.4 <?=T_("(current stable release)");?></h2>
</div>
<h3><?= T_("Current <em>stable</em> user documentation and developer documentation");?></h3>
<div id="stabledoc">
<div style="float:left;">
<h2 class="download-title"><?php echo T_("Download");?> (<em><?php echo T_("Stable");?></em>)</h2>
  <ul>
  <li><b><?php echo T_("Help Manual");?></b>
    <table class="doctable">
    <tbody>
      <tr class="doctr">
      <td><?php echo T_("English");?> :</td><td>
        <a href="<?=$top_dir;?>/docs/v2.4/C/gnucash-help/help.html"><img class="docicon" alt="online" title="<?php echo T_($online);?>" src="<?=$top_dir;?>/images/icons/online_logo.png" /></a> | <a href="<?=$top_dir;?>/docs/v2.4/C/gnucash-help.pdf"><img class="docicon" alt="pdf" title="<?php echo T_($pdf);?>" src="<?=$top_dir;?>/images/icons/pdf_logo.png" /></a><!-- | <a href="<?=$top_dir;?>/docs/v2.4/C/gnucash-help.epub"><img class="docicon" alt="epub" title="<?php echo T_($epub);?>" src="<?=$top_dir;?>/images/icons/epub_logo.png" /></a> | <a href="<?=$top_dir;?>/docs/v2.4/C/gnucash-help.mobi"><img class="docicon" alt="mobi" title="<?php echo T_($mobi);?>" src="<?=$top_dir;?>/images/icons/mobipocket_logo.png" /></a>-->
      </td></tr>
      <tr class="doctr">
      <td><?php echo T_("German");?> :</td><td>
        <a href="<?=$top_dir;?>/docs/v2.4/de_DE/gnucash-help/help.html"><img class="docicon" alt="online" title="<?php echo T_($online);?>" src="<?=$top_dir;?>/images/icons/online_logo.png" /></a> | <a href="<?=$top_dir;?>/docs/v2.4/de_DE/gnucash-help.pdf"><img class="docicon" alt="pdf" title="<?php echo T_($pdf);?>" src="<?=$top_dir;?>/images/icons/pdf_logo.png" /></a><!-- | <a href="<?=$top_dir;?>/docs/v2.4/de_DE/gnucash-help.epubf"><img class="docicon" alt="epub" title="<?php echo T_($epub);?>" src="<?=$top_dir;?>/images/icons/epub_logo.png" /></a> | <a href="<?=$top_dir;?>/docs/v2.4/de_DE/gnucash-help.mobi"><img class="docicon" alt="mobi" title="<?php echo T_($mobi);?>" src="<?=$top_dir;?>/images/icons/mobipocket_logo.png" /></a>-->
      </td></tr>
      <tr class="doctr">
      <td><?php echo T_("Italian");?> :</td><td>
        <a href="<?=$top_dir;?>/docs/v2.4/it_IT/gnucash-help/help.html"><img class="docicon" alt="online" title="<?php echo T_($online);?>" src="<?=$top_dir;?>/images/icons/online_logo.png" /></a> | <a href="<?=$top_dir;?>/docs/v2.4/it_IT/gnucash-help.pdf"><img class="docicon" alt="pdf" title="<?php echo T_($pdf);?>" src="<?=$top_dir;?>/images/icons/pdf_logo.png" /></a><!-- | <a href="<?=$top_dir;?>/docs/v2.4/it_IT/gnucash-help.epub"><img class="docicon" alt="epub" title="<?php echo T_($epub);?>" src="<?=$top_dir;?>/images/icons/epub_logo.png" /></a> | <a href="<?=$top_dir;?>/docs/v2.4/it_IT/gnucash-help.mobi"><img class="docicon" alt="mobi" title="<?php echo T_($mobi);?>" src="<?=$top_dir;?>/images/icons/mobipocket_logo.png" /></a>-->
      </td></tr>
    </tbody>
    </table>
  </li>
  <li><b><?= T_("Concepts Guide") ?></b>
    <table class="doctable">
    <tbody>
      <tr class="doctr">
      <td><?php echo T_("English");?> :</td><td>
        <a href="<?=$top_dir;?>/docs/v2.4/C/gnucash-guide/"><img class="docicon" alt="online" title="<?php echo T_($online);?>" src="<?=$top_dir;?>/images/icons/online_logo.png" /></a> | <a href="<?=$top_dir;?>/docs/v2.4/C/gnucash-guide.pdf"><img class="docicon" alt="pdf" title="<?php echo T_($pdf);?>" src="<?=$top_dir;?>/images/icons/pdf_logo.png" /></a><!-- | <a href="<?=$top_dir;?>/docs/v2.4/C/gnucash-guide.epub"><img class="docicon" alt="epub" title="<?php echo T_($epub);?>" src="<?=$top_dir;?>/images/icons/epub_logo.png" /></a> | <a href="<?=$top_dir;?>/docs/v2.4/C/gnucash-guide.mobi"><img class="docicon" alt="mobi" title="<?php echo T_($mobi);?>" src="<?=$top_dir;?>/images/icons/mobipocket_logo.png" /></a>-->
      </td></tr>
      <tr class="doctr">
      <td><?php echo T_("German");?> :</td><td>
        <a href="<?=$top_dir;?>/docs/v2.4/de_DE/gnucash-guide/"><img class="docicon" alt="online" title="<?php echo T_($online);?>" src="<?=$top_dir;?>/images/icons/online_logo.png" /></a> | <a href="<?=$top_dir;?>/docs/v2.4/de_DE/gnucash-guide.pdf"><img class="docicon" alt="pdf" title="<?php echo T_($pdf);?>" src="<?=$top_dir;?>/images/icons/pdf_logo.png" /></a><!-- | <a href="<?=$top_dir;?>/docs/v2.4/de_DE/gnucash-guide.epub"><img class="docicon" alt="epub" title="<?php echo T_($epub);?>" src="<?=$top_dir;?>/images/icons/epub_logo.png" /></a> | <a href="<?=$top_dir;?>/docs/v2.4/de_DE/gnucash-guide.mobi"><img class="docicon" alt="mobi" title="<?php echo T_($mobi);?>" src="<?=$top_dir;?>/images/icons/mobipocket_logo.png" /></a>-->
      </td></tr>
      <tr class="doctr">
      <td><?php echo T_("Italian");?> :</td><td>
        <a href="<?=$top_dir;?>/docs/v2.4/it_IT/gnucash-guide/"><img class="docicon" alt="online" title="<?php echo T_($online);?>" src="<?=$top_dir;?>/images/icons/online_logo.png" /></a> | <a href="<?=$top_dir;?>/docs/v2.4/it_IT/gnucash-guide.pdf"><img class="docicon" alt="pdf" title="<?php echo T_($pdf);?>" src="<?=$top_dir;?>/images/icons/pdf_logo.png" /></a><!-- | <a href="<?=$top_dir;?>/docs/v2.4/it_IT/gnucash-guide.epub"><img class="docicon" alt="epub" title="<?php echo T_($epub);?>" src="<?=$top_dir;?>/images/icons/epub_logo.png" /></a> | <a href="<?=$top_dir;?>/docs/v2.4/it_IT/gnucash-guide.mobi"><img class="docicon" alt="mobi" title="<?php echo T_($mobi);?>" src="<?=$top_dir;?>/images/icons/mobipocket_logo.png" /></a>-->
      </td></tr>
      <tr class="doctr">
      <td><?php echo T_("Japanese");?> :</td><td>
        <a href="<?=$top_dir;?>/docs/v2.4/ja_JP/gnucash-guide/"><img class="docicon" alt="online" title="<?php echo T_($online);?>" src="<?=$top_dir;?>/images/icons/online_logo.png" /></a> | <a href="<?=$top_dir;?>/docs/v2.4/ja_JP/gnucash-guide.pdf"><img class="docicon" alt="pdf" title="<?php echo T_($pdf);?>" src="<?=$top_dir;?>/images/icons/pdf_logo.png" /></a><!-- | <a href="<?=$top_dir;?>/docs/v2.4/ja_JP/gnucash-guide.epub"><img class="docicon" alt="epub" title="<?php echo T_($epub);?>" src="<?=$top_dir;?>/images/icons/epub_logo.png" /></a> | <a href="<?=$top_dir;?>/docs/v2.4/ja_JP/gnucash-guide.mobi"><img class="docicon" alt="mobi" title="<?php echo T_($mobi);?>" src="<?=$top_dir;?>/images/icons/mobipocket_logo.png" /></a>-->
      </td></tr>
    </tbody>
    </table>
  </li>
</ul>
</div>

<div class="downloadimage">
<img alt="stabledoc" src="<?=$top_dir;?>/images/stabledoc.png" />
</div>
</div>

<p class="justify"><?php echo T_("This is the latest stable release of the <span class=\"gnucash\">GnuCash</span> documentation. <em>Stable</em> means that this documentation is not necessarily the most up to date but it works without any problem.");?></p>
</div>

<div class="featurecontainer">
<div class="featureborder">
<h2 class="featuretitle"><?= T_("Nightly Documentation Builds");?></h2>
</div>
<h3><?= T_("Current <em>unstable</em> user documentation and developer documentation");?></h3>
<div id="develdoc">
<div style="float:left;">
<h2 class="download-title"><?php echo T_("Download");?> (<em><?php echo T_("Unstable");?></em>)</h2>
<ul>
  <li><b><?php echo T_("Help Manual");?></b>
    <table class="doctable">
    <tbody>
      <tr class="doctr">
      <td><?php echo T_("English");?> :</td><td>
        <a href="http://code.gnucash.org/docs/help/help.html"><img class="docicon" alt="online" title="<?php echo T_($online);?>" src="<?=$top_dir;?>/images/icons/online_logo.png" /></a> | <a href="http://code.gnucash.org/docs/help.pdf"><img class="docicon" alt="pdf" title="<?php echo T_($pdf);?>" src="<?=$top_dir;?>/images/icons/pdf_logo.png" /></a> | <a href="http://code.gnucash.org/docs/help.epub"><img class="docicon" alt="epub" title="<?php echo T_($epub);?>" src="<?=$top_dir;?>/images/icons/epub_logo.png" /></a> <!--| <a href="http://code.gnucash.org/docs/help.mobi"><img class="docicon" alt="mobi" title="<?php echo T_($mobi);?>" src="<?=$top_dir;?>/images/icons/mobipocket_logo.png" /></a>-->
      </td></tr>
      <tr class="doctr">
      <td><?php echo T_("German");?> :</td><td>
        <a href="http://code.gnucash.org/docs/help-de_DE/help.html"><img class="docicon" alt="online" title="<?php echo T_($online);?>" src="<?=$top_dir;?>/images/icons/online_logo.png" /></a> | <a href="http://code.gnucash.org/docs/help-de_DE.pdf"><img class="docicon" alt="pdf" title="<?php echo T_($pdf);?>" src="<?=$top_dir;?>/images/icons/pdf_logo.png" /></a> | <a href="http://code.gnucash.org/docs/help-de_DE.epub"><img class="docicon" alt="epub" title="<?php echo T_($epub);?>" src="<?=$top_dir;?>/images/icons/epub_logo.png" /></a> <!--| <a href="http://code.gnucash.org/docs/help-de_DE.mobi"><img class="docicon" alt="mobi" title="<?php echo T_($mobi);?>" src="<?=$top_dir;?>/images/icons/mobipocket_logo.png" /></a>-->
      </td></tr>
      <tr class="doctr">
      <td><?php echo T_("Italian");?> :</td><td>
        <a href="http://code.gnucash.org/docs/help-it_IT/help.html"><img class="docicon" alt="online" title="<?php echo T_($online);?>" src="<?=$top_dir;?>/images/icons/online_logo.png" /></a> | <a href="http://code.gnucash.org/docs/help-it_IT.pdf"><img class="docicon" alt="pdf" title="<?php echo T_($pdf);?>" src="<?=$top_dir;?>/images/icons/pdf_logo.png" /></a> | <a href="http://code.gnucash.org/docs/help-it_IT.epub"><img class="docicon" alt="epub" title="<?php echo T_($epub);?>" src="<?=$top_dir;?>/images/icons/epub_logo.png" /></a> <!--| <a href="http://code.gnucash.org/docs/help-it_IT.mobi"><img class="docicon" alt="mobi" title="<?php echo T_($mobi);?>" src="<?=$top_dir;?>/images/icons/mobipocket_logo.png" /></a>-->
      </td></tr>
    </tbody>
    </table>
  </li>
  <li><b><?= T_("Concepts Guide") ?></b>
    <table class="doctable">
    <tbody>
      <tr class="doctr">
      <td><?php echo T_("English");?> :</td><td>
        <a href="http://code.gnucash.org/docs/guide/"><img class="docicon" alt="online" title="<?php echo T_($online);?>" src="<?=$top_dir;?>/images/icons/online_logo.png" /></a> | <a href="http://code.gnucash.org/docs/guide.pdf"><img class="docicon" alt="pdf" title="<?php echo T_($pdf);?>" src="<?=$top_dir;?>/images/icons/pdf_logo.png" /></a> | <a href="http://code.gnucash.org/docs/guide.epub"><img class="docicon" alt="epub" title="<?php echo T_($epub);?>" src="<?=$top_dir;?>/images/icons/epub_logo.png" /></a> <!--| <a href="http://code.gnucash.org/docs/guide.mobi"><img class="docicon" alt="mobi" title="<?php echo T_($mobi);?>" src="<?=$top_dir;?>/images/icons/mobipocket_logo.png" /></a>-->
      </td></tr>
      <tr class="doctr">
      <td><?php echo T_("German");?> :</td><td>
        <a href="http://code.gnucash.org/docs/guide-de_DE/"><img class="docicon" alt="online" title="<?php echo T_($online);?>" src="<?=$top_dir;?>/images/icons/online_logo.png" /></a> | <a href="http://code.gnucash.org/docs/guide-de_DE.pdf"><img class="docicon" alt="pdf" title="<?php echo T_($pdf);?>" src="<?=$top_dir;?>/images/icons/pdf_logo.png" /></a> | <a href="http://code.gnucash.org/docs/guide-de_DE.epub"><img class="docicon" alt="epub" title="<?php echo T_($epub);?>" src="<?=$top_dir;?>/images/icons/epub_logo.png" /></a> <!--| <a href="http://code.gnucash.org/docs/guide-de_DE.mobi"><img class="docicon" alt="mobi" title="<?php echo T_($mobi);?>" src="<?=$top_dir;?>/images/icons/mobipocket_logo.png" /></a>-->
      </td></tr>
      <tr class="doctr">
      <td><?php echo T_("Italian");?> :</td><td>
        <a href="http://code.gnucash.org/docs/guide-it_IT/"><img class="docicon" alt="online" title="<?php echo T_($online);?>" src="<?=$top_dir;?>/images/icons/online_logo.png" /></a> | <a href="http://code.gnucash.org/docs/guide-it_IT.pdf"><img class="docicon" alt="pdf" title="<?php echo T_($pdf);?>" src="<?=$top_dir;?>/images/icons/pdf_logo.png" /></a> | <a href="http://code.gnucash.org/docs/guide-it_IT.epub"><img class="docicon" alt="epub" title="<?php echo T_($epub);?>" src="<?=$top_dir;?>/images/icons/epub_logo.png" /></a> <!--| <a href="http://code.gnucash.org/docs/guide-it_IT.mobi"><img class="docicon" alt="mobi" title="<?php echo T_($mobi);?>" src="<?=$top_dir;?>/images/icons/mobipocket_logo.png" /></a>-->
      </td></tr>
      <tr class="doctr">
      <td><?php echo T_("Japanese");?> :</td><td>
        <a href="http://code.gnucash.org/docs/guide-ja_JP/"><img class="docicon" alt="online" title="<?php echo T_($online);?>" src="<?=$top_dir;?>/images/icons/online_logo.png" /></a> | <a href="http://code.gnucash.org/docs/guide-ja_JP.pdf"><img class="docicon" alt="pdf" title="<?php echo T_($pdf);?>" src="<?=$top_dir;?>/images/icons/pdf_logo.png" /></a> | <a href="http://code.gnucash.org/docs/guide-ja_JP.epub"><img class="docicon" alt="epub" title="<?php echo T_($epub);?>" src="<?=$top_dir;?>/images/icons/epub_logo.png" /></a> <!--| <a href="http://code.gnucash.org/docs/guide-ja_JP.mobi"><img class="docicon" alt="mobi" title="<?php echo T_($mobi);?>" src="<?=$top_dir;?>/images/icons/mobipocket_logo.png" /></a>-->
      </td></tr>
    </tbody>
    </table>
  </li>
</ul>
</div>

<div class="downloadimage">
<img alt="develdoc" src="<?=$top_dir;?>/images/develdoc.png" />
</div>

</div>

<p class="justify"><?php echo T_("Every night a server builds the documentation from the current contents of the <span class=\"gnucash\">GnuCash</span> subversion repository. This includes the <b>Developer Documentation</b> from <b>Doxygen</b> and <b>User Documentation</b> for the current <em>unstable</em> version of <span class=\"gnucash\">GnuCash</span>.");?></p>
</div>

<div class="dialog warning">
<p class="justify"><?php echo T_("<b>NOTE:</b> these documents might not be accessible from time to time because developers might be working on improvements. However they are the most up to date reference for <span class=\"gnucash\">GnuCash</span> users.");?></p>
</div>

<div class="featurecontainer">
<div class="featureborder">
<h2 class="featuretitle"><?php echo T_("Older GnuCash Documentation");?></h2>
</div>
<p class="justify"><?php echo T_("This section contains all the older <span class=\"gnucash\">GnuCash</span> documentation. If you are using one of these old versions of <span class=\"gnucash\">GnuCash</span>, it is highly recommended that you upgrade to the latest stable version.");?></p>
<ul>
  <li><b>GnuCash v2.2</b>:
    <ul>
      <li>
        <b><?php echo T_("Help Manual");?></b>:
        <?php echo T_("English");?> (<a href="<?=$top_dir;?>/docs/v2.2/C/gnucash-help/help.html"><img class="docicon" alt="online" title="<?php echo T_($online);?>" src="<?=$top_dir;?>/images/icons/online_logo.png" /></a>) |
        <?php echo T_("German");?> (<a href="<?=$top_dir;?>/docs/v2.2/de_DE/gnucash-help/help.html"><img class="docicon" alt="online" title="<?php echo T_($online);?>" src="<?=$top_dir;?>/images/icons/online_logo.png" /></a>) |
        <?php echo T_("Italian");?> (<a href="<?=$top_dir;?>/docs/v2.2/it_IT/gnucash-help/help.html"><img class="docicon" alt="online" title="<?php echo T_($online);?>" src="<?=$top_dir;?>/images/icons/online_logo.png" /></a>)
      </li>
    </ul>
    <ul>
      <li>
        <b><?= T_("Concepts Guide") ?></b>:
        <?php echo T_("English");?> (<a href="<?=$top_dir;?>/docs/v2.2/C/gnucash-guide/"><img class="docicon" alt="online" title="<?php echo T_($online);?>" src="<?=$top_dir;?>/images/icons/online_logo.png" /></a>)
        <?php echo T_("Italian");?> (<a href="<?=$top_dir;?>/docs/v2.2/it_IT/gnucash-guide/"><img class="docicon" alt="online" title="<?php echo T_($online);?>" src="<?=$top_dir;?>/images/icons/online_logo.png" /></a>)
      </li>
    </ul>
  </li>
  <li><b>GnuCash v2.0</b>:
    <ul>
      <li>
        <b><?php echo T_("Help Manual");?></b>:
        <?php echo T_("English");?> (<a href="<?=$top_dir;?>/docs/v2.0/C/gnucash-help/help.html"><img class="docicon" alt="online" title="<?php echo T_($online);?>" src="<?=$top_dir;?>/images/icons/online_logo.png" /></a>) |
        <?php echo T_("German");?> (<a href="<?=$top_dir;?>/docs/v2.0/de_DE/gnucash-help/help.html"><img class="docicon" alt="online" title="<?php echo T_($online);?>" src="<?=$top_dir;?>/images/icons/online_logo.png" /></a>)
      </li>
    </ul>
    <ul>
      <li>
        <b><?= T_("Concepts Guide") ?></b>:
        <?php echo T_("English");?> (<a href="<?=$top_dir;?>/docs/v2.0/C/gnucash-guide/"><img class="docicon" alt="online" title="<?php echo T_($online);?>" src="<?=$top_dir;?>/images/icons/online_logo.png" /></a>)
      </li>
    </ul>
  </li>
  <li><b>GnuCash v1.8</b>:
    <ul>
      <li>
        <b><?php echo T_("Help Manual");?></b>:
        <?php echo T_("English");?> (<a href="<?=$top_dir;?>/docs/v1.8/C/gnucash-help/help.html"><img class="docicon" alt="online" title="<?php echo T_($online);?>" src="<?=$top_dir;?>/images/icons/online_logo.png" /></a>,
        <a href="<?=$top_dir;?>/docs/v1.8/C/gnucash-help.pdf"><img class="docicon" alt="pdf" title="<?php echo T_($pdf);?>" src="<?=$top_dir;?>/images/icons/pdf_logo.png" /></a>) |
        <?php echo T_("German");?> (<a href="<?=$top_dir;?>/docs/v1.8/de_DE/gnucash-help/help.html"><img class="docicon" alt="online" title="<?php echo T_($online);?>" src="<?=$top_dir;?>/images/icons/online_logo.png" /></a>)
      </li>
    </ul>
    <ul>
      <li>
        <b><?= T_("Concepts Guide") ?></b>:     
        <?php echo T_("German");?> (<a href="<?=$top_dir;?>/docs/v2.8/C/gnucash-guide/"><img class="docicon" alt="online" title="<?php echo T_($online);?>" src="<?=$top_dir;?>/images/icons/online_logo.png" /></a>,
        <a href="<?=$top_dir;?>/docs/v1.8/C/gnucash-guide.pdf"><img class="docicon" alt="pdf" title="<?php echo T_($pdf);?>" src="<?=$top_dir;?>/images/icons/pdf_logo.png" /></a>)
      </li>
    </ul>
  </li>
  <li><b>GnuCash v1.6</b>: 
  <a href="<?=$top_dir;?>/docs/v1.6/C/"><?php echo T_("English");?></a> | 
  <a href="<?=$top_dir;?>/docs/v1.6/de_DE/"><?php echo T_("German");?></a> | 
  <a href="<?=$top_dir;?>/docs/v1.6/es/"><?php echo T_("Spanish");?></a> | 
  <a href="<?=$top_dir;?>/docs/v1.6/pt_PT/"><?php echo T_("Portugese");?></a></li>
</ul>
</div>

<div class="featurecontainer">
<div class="featureborder">
<h2 class="featuretitle"><?php echo T_("Unofficial documentation");?></h2>
</div>
<p class="justify"><?php echo T_("Some people have written HOWTO guides or tutorials.");?></p>
<ul>
  <li><a href="http://www.austintek.com/gnucash/ncsa-gnucash-talk.html"><?php
	echo T_("Joe Mack's Tutorial");?></a></li>
  <li><a href="http://www.object-refinery.com/gnucash/index.html"><?php
	echo T_("Dave Gilbert's User Guide (Pdf)");?></a></li>
</ul>

<div class="dialog note">
<p class="justify"><?php echo T_("<b>NOTE:</b> the information presented in these sources may or may not be updated to the most recent version of <span class=\"gnucash\">GnuCash</span>. If you are interested in doing development work on these documents, you should contact the original authors.");?></p>
</div>

</div>
</div>
<?php include("externals/footer.phtml"); ?>
