<?php 
$homepage = false;
include("emulate_globals_on.php");
include("lang.php");
$title = T_("Download");
include("externals/header.phtml");
include("externals/menu.phtml"); 
?>

<div id="content">

<h1><?php echo T_("Download GnuCash")?></h1>

<h2><?php printf (T_("Stable release (%s)"), $latest_stable)?></h2>
<p><?php echo T_("A stable release is a version of GnuCash that is well tested and considered appropriate for every day use.")?></p>
<p><?php printf (T_("The latest stable release of GnuCash is %s.  Choose the download for your operating system below."), $latest_stable)?></p>

<h3><?php echo T_("Installers")?></h3>
<ul>
<li><?php printf (T_("GnuCash %s for"), $latest_stable)?> <a href="<?php echo $download_path.$latest_stable_win;?>">Microsoft Windows XP/Vista/7</a></li>
<li><?php printf (T_("GnuCash %s for"), $latest_stable)?> Mac OS X <a href="<?php echo $download_path.$latest_stable_mac_intel;?>">Intel</a> | <a href="<?php echo $download_path.$latest_stable_mac_ppc;?>">Power PC</a> | <a href="http://wiki.gnucash.org/wiki/MacOSX/<?php echo $latest_stable;?>/Readme">Readme</a></li>
</ul>

<a name="distribution"></a><h3>Linux</h3>
<p><?php echo T_("Most linux distributions come bundled with a version of GnuCash, though it's not always the most recent version and it may not have been installed by default. Still it is recommended to use the GnuCash version that comes with your distribution.");?></p>
<p><?php echo T_("Below are ways to install GnuCash on some of the more popular distributions:");?></p>

<ul>
  <li><b>Fedora: </b><?php echo T_("Fedora users can install GnuCash through System->Administration->Add/Remove Software (Gnome) or Applications->System->Software Management (KDE).")?></li>
  <li><b>Mandriva: </b><?php echo T_("Mandriva users can install GnuCash through the Software Management in the Mandriva Linux Control Center.")?></li>
  <li><b>Redhat/Centos: </b><?php echo T_("Redhat and CentOS don't have GnuCash in their repositories by default. It can be installed however from the third-party Epel repository. For more details on configuring this additional software repository for your setup, see ");?><a href="http://fedoraproject.org/wiki/EPEL"><?php echo T_("Epel's wiki page");?></a></li>
  <li><b>Ubuntu: </b><?php echo T_("Ubuntu 9.10 users can install GnuCash through the Software Center (in the Applications menu). This will install GnuCash under the Office category in the Applications menu.")?></li>
</ul>

<h3><?php echo T_("Source code")?></h3>
<ul>
  <li><a href="<?php echo $download_path.$latest_stable_source;?>">bzip2 compressed tarball</a> <?php printf (T_("for GnuCash %s"), $latest_stable)?></li>
  <li><a href="http://www.gnucash.org/pub/gnucash/sources/stable/<?php echo $latest_stable_source;?>"><?= T_("USA Mirror");?></a></li>
  <li><a href="http://ftp.at.gnucash.org/pub/gnucash/sources/stable/<?php echo $latest_stable_source;?>"><?= T_("European Mirror");?></a></li>
 </ul>

<h2><?php printf (T_("Unstable/Development release (%s)"), $latest_unstable)?></h2>
<p><?php echo T_("Unstable (development) releases are for testing purposes only. They contain the newest features and improvements, but may also contain serious bugs still. Don't install these releases for everyday use.")?></p>
<p><?php printf (T_("The latest unstable release of GnuCash is %s.  Choose the download for your operating system below."), $latest_unstable)?></p>

<ul>
  <li><?php printf (T_("GnuCash %s for"), $latest_unstable)?> <a href="<?php echo $download_path.$latest_unstable_win;?>">Microsoft Windows XP/Vista/7</a></li>
  <li><?php printf (T_("GnuCash %s for"), $latest_unstable)?> Mac OS X <a href="<?php echo $download_path.$latest_unstable_mac_intel;?>">Intel</a> | <a href="http://wiki.gnucash.org/wiki/MacOSX/<?php echo $latest_unstable;?>/Readme">Readme</a></li>
  <li><a href="<?php echo $download_path.$latest_unstable_source;?>">bzip2 compressed tarball</a> <?php printf (T_("for GnuCash %s"), $latest_unstable)?></li>
</ul>

<h2><?php echo T_("Other")?></h2>

<ul>
 <li><a href="<?php echo $latest_stable_path;?>"><?php printf (T_("View all GnuCash %s downloads (stable)"), $latest_stable)?></a></li>
 <li><a href="<?php echo $latest_unstable_path;?>"><?php printf (T_("View all GnuCash %s downloads (unstable)"), $latest_unstable)?></a></li>
 <li><a href="http://sourceforge.net/projects/gnucash/files/"><?php echo T_("View all GnuCash downloads")?></a></li>
</ul>

</div>
