<?php 
$homepage = false;
include("emulate_globals_on.php");
include("lang.php");
$title = T_("Download");
include("externals/header.phtml");
include("externals/menu.phtml"); 
?>

<div id="content">

<h1><?php echo T_("Download GnuCash")?></h1>

<div class="featureborder">
<h2 class="featuretitle"><?php printf (T_("Stable release (%s)"), $latest_stable)?></h2>
</div>
<p class="justify"><?php echo T_("A stable release is a version of <span class=\"gnucash\">GnuCash</span> that is well tested and considered appropriate for every day use.")?></p>
<p class="justify"><?php printf (T_("The latest stable release of <span class=\"gnucash\">GnuCash</span> is %s. Choose the download for your operating system below."), $latest_stable)?></p>

<h3><?php echo T_("Installers")?></h3>
<ul class="imagelist">
<li class="imagelistitem" style="background-image: url(<?=$top_dir?>/images/icons/windows.png);"><?php printf (T_("GnuCash %s for"), $latest_stable)?> <a href="<?php echo $download_path.$latest_stable_win;?>">Microsoft Windows XP/Vista/7</a></li>
<li class="imagelistitem" style="background-image: url(<?=$top_dir?>/images/icons/macosx.png);"><?php printf (T_("GnuCash %s for"), $latest_stable)?> Mac OS X <a href="<?php echo $download_path.$latest_stable_mac_intel;?>">Intel</a> | <a href="<?php echo $download_path.$latest_stable_mac_ppc;?>">Power PC</a> | <a href="http://wiki.gnucash.org/wiki/MacOSX/<?php echo $latest_stable;?>/Readme">Readme</a></li>
</ul>

<a id="distribution"></a><h3>Linux</h3>
<p class="justify"><?php echo T_("Most linux distributions come bundled with a version of <span class=\"gnucash\">GnuCash</span>, though it's not always the most recent version and it may not have been installed by default. Still it is recommended to use the <span class=\"gnucash\">GnuCash</span> version that comes with your distribution.");?></p>
<p class="justify"><?php echo T_("Below are ways to install <span class=\"gnucash\">GnuCash</span> on some of the more popular distributions:");?></p>

<ul class="imagelist">
  <li class="imagelistitem" style="background-image: url(<?=$top_dir?>/images/icons/fedora.png);"><b>Fedora: </b><?php echo T_("Fedora users can install <span class=\"gnucash\">GnuCash</span> through System->Administration->Add/Remove Software (Gnome) or Applications->System->Software Management (KDE).")?></li>
  <li class="imagelistitem" style="background-image: url(<?=$top_dir?>/images/icons/mandriva.png);"><b>Mandriva: </b><?php echo T_("Mandriva users can install <span class=\"gnucash\">GnuCash</span> through the Software Management in the Mandriva Linux Control Center.")?></li>
  <li class="imagelistitem" style="background-image: url(<?=$top_dir?>/images/icons/redhat.png);"><b>Redhat/Centos: </b><?php echo T_("Redhat and CentOS don't have <span class=\"gnucash\">GnuCash</span> in their repositories by default. It can be installed however from the third-party Epel repository. For more details on configuring this additional software repository for your setup, see");?> <a href="http://fedoraproject.org/wiki/EPEL"><?php echo T_("Epel's wiki page");?></a>.</li>
  <li class="imagelistitem" style="background-image: url(<?=$top_dir?>/images/icons/ubuntu.png);"><b>Ubuntu: </b><?php echo T_("Ubuntu users can install <span class=\"gnucash\">GnuCash</span> through the Software Center. This will install <span class=\"gnucash\">GnuCash</span> under the Office category in the Applications menu.")?></li>
</ul>
<p class="justify"><?php echo T_("If your distro doesn't ship with <span class=\"gnucash\">GnuCash</span> or you wish to install a different version than it ships with, you could try to build <span class=\"gnucash\">GnuCash</span> directly from the source code. The <span class=\"gnucash\">GnuCash</span> wiki has <a href='http://wiki.gnucash.org/wiki/GnuCash#Installation'>guidelines for several distributions</a>.")?></p>

<h3><?php echo T_("Source code")?></h3>
<ul class="imagelist">
  <li class="imagelistitem" style="background-image: url(<?=$top_dir?>/images/icons/package.png);"><a href="<?php echo $download_path.$latest_stable_source;?>">bzip2 compressed tarball</a> <?php printf (T_("for GnuCash %s"), $latest_stable)?></li>
 </ul>
<p><?php echo T_("For build instructions, please check the <span class=\"gnucash\">GnuCash</span> wiki which has <a href='http://wiki.gnucash.org/wiki/GnuCash#Installation'>guidelines for several distributions</a>.")?></p>

<?php if ($latest_unstable)
      include "unstable-download.phtml";
?>
<div class="featureborder">
<h2 class="featuretitle"><?php echo T_("Other")?></h2>
</div>

<ul>
 <li><a href="<?php echo $latest_stable_path;?>"><?php printf (T_("View all GnuCash %s downloads (stable)"), $latest_stable)?></a></li>

<?php if ($latest_unstable) { ?>
 <li><a href="<?php echo $latest_unstable_path;?>"><?php printf (T_("View all GnuCash %s downloads (unstable)"), $latest_unstable)?></a></li>
<?php } ?>

 <li><a href="http://sourceforge.net/projects/gnucash/files/"><?php echo T_("View all GnuCash downloads")?></a></li>
</ul>

</div>
<?php include("externals/footer.phtml"); ?>
