<?php
include("lang.php");
$title = T_("Features");
include("emulate_globals_on.php");
include("$top_dir/externals/header.phtml");
include("$top_dir/externals/menu.phtml");
?>

<div id="content">
<h1><?php echo T_($title);?></h1>

<div>
<p>
<?php echo T_("GnuCash is a powerful accounting software. This page will try to explain in detail which are the numerous features that GnuCash has to offer to it's users.");?>
</p>
<ul>
<li><a title="<?php echo T_("Jump to the the main features section");?>" href="#main-feat"><?php echo T_("Main features");?></a></li>
<li><?php echo T_("Advanced features");?></li>
<li><?php echo T_("Data storing and exchange features");?></li>
<li><?php echo T_("Other goodies");?></li>
</ul>
</div>

<h1 class="featuresection"><img class="gnc-icon" src="<?=$top_dir?>/images/features/gnucash-icon-32x32.png" alt="[GnuCash]"></a><?php echo T_("Main features");?></h1>

<div class="featurecontainer">
<div class="featureborder">
<h2 class="featuretitle"><?php echo T_("Double Entry");?></h2>
</div>
<div class="center">
<img class="featureimage" src="<?=$top_dir?>/images/features/basics_AccountRelationships.png" alt="[Basic account relationship]">
</div>
<p class="justify">
<?php echo T_("Every transaction must debit one account and credit others by an equal amount. This ensures that the books balance: that the difference between income and expenses exactly equals the sum of assets and liabilities.");?>
</p>
<br clear="all" />
</div>

<div class="featurecontainer">
<div class="featureborder">
<h2 class="featuretitle"><?php echo T_("Checkbook-Style Register");?></h2>
</div>
<div class="center">
<img class="featureimage" src="<?=$top_dir?>/images/features/feature_register.png" alt="[Register]"/>
</div>
<p class="justify">
<?php echo T_("The GnuCash checkbook-style register provides a custom, convenient and familiar interface to entering financial transactions.");?>
<p class="justify">
<?php echo T_("The register supports common checking and credit-card transactions, as well as income, stock and currency transactions. The following features are also provided:");?>
</p>
<ul>
<li><?php echo T_("Autofill of entered transactions");?></li>
<li><?php echo T_("Possibility to mark a transaction as cleared");?></li>
<li><?php echo T_("Possibility to enter split transactions");?></li>
<li><?php echo T_("Multiple accounts can be displayed in one register window at the same time");?></li>
<li><?php echo T_("A summarybar that display all the relevant account's balance informations");?></li>
<li><?php echo T_("Many options to costumize the appearence and the display style");?></li>
</ul>
<br clear="all"/>
</div>

<div class="featurecontainer">
<div class="featureborder">
<h2 class="featuretitle"><?php echo T_("Reports, Graphs");?></h2>
</div>
<img class="featureimage" src="<?=$top_dir?>/images/features/feature_graph-report.png" width="300" height="200" style="float: left; border: solid thin grey; margin: 0.5em;" alt="[Graphs]"/>
<p class="justify">
<?php echo T_("GnuCash has an integrated module to display graphs of your financial data in the form of:");?>
</p>
<ul>
<li><?php echo T_("Barcharts");?></li>
<li><?php echo T_("Piecharts");?></li>
<li><?php echo T_("Scatter plots");?></li>
</ul>

<?php echo T_("GnuCash comes also complete with a full suite of standard and customizeable reports, such as:");?>
<ul>
<li><?php echo T_("Balance Sheet");?></li>
<li><?php echo T_("Profit &amp; Loss");?></li>
<li><?php echo T_("Portfolio Valuation");?></li>
<li><?php echo T_("and many others.");?></li>
</ul>
<p class="justify">
<?php echo T_("Graphs and reports can be highly and easily customized in appearence and contents, in order to fullfill every user's need.");?>
</p>
<br clear="all"/>
</div>

<div class="featurecontainer">
<div class="featureborder">
<h2 class="featuretitle"><?php echo T_("Statement Reconciliation");?></h2>
</div>
<div class="center">
<img class="featureimage" src="<?=$top_dir?>/images/features/feature_reconcile.png" alt="[Reconcile]"/>
</div>
<p class="justify"><?php echo T_("The reconciliation of an account is an operation that allow the user to check the entered transactions belongings to a GnuCash account against a bank statement. This operation is very useful to spot untracked operations.");?></p>
<p class="justify"><?php echo T_("In GnuCash, a reconcile window with running reconciled and cleared balances makes balancing against bank statements an easy task.");?></p>
<br clear="all" />
</div>

<h2><?php echo T_("Income/Expense Account Types");?></h2>
<p><?php echo T_("Income/Expense Account Types (Categories) allow you to categorize your cash flow.  When used properly with the double-entry feature and equity accounts, these enable you to generate reports, such as Profit &amp; Loss, that plain-vanilla systems cannot handle.");?>
</p>
<br clear="all" />

<h2><?php echo T_("Multiple Currencies");?></h2>
<p><?php echo T_("Different accounts can be denominated in different currencies. Currency movements between accounts are fully balanced when double-entry is enabled.");?>
</p>
<br clear="all" />

<h2><?php echo T_("Stock/Mutual Fund Portfolios");?></h2>
<p><?php echo T_("Track stocks individually (one per account) or in portfolio of accounts (a group of accounts that can be displayed together).");?></p>
<br clear="all" />

<h2><?php echo T_("Small Business Accounting Features");?></h2>
<p>
<?php echo T_("Simplify managing a small business with Customer and Vendor tracking, Invoicing and Bill Payment, and Tax and Billing Terms.");?></p>
<br clear="all" />

<h2><?php echo T_("QIF Import");?></h2>
<p><?php echo T_("Intuit<sup>&reg;</sup> Quicken<sup>&reg;</sup> QIF files can be imported, and are automatically merged to eliminate duplicate transactions.");?></p>
<br clear="all" />

<h2><?php echo T_("OFX Import");?></h2>
<p><?php echo T_("GnuCash is the first free software application to support the Open Financial Exchange protocol that many banks and financial services are starting to use.");?></p>
<br clear="all" />

<h2><?php echo T_("HBCI Support");?></h2>
<p><?php echo T_("GnuCash is the first free software application to support the German Home Banking Computer Information protocol, allowing German users to perform statement download and initiate bank transfers and direct debits.");?></p>
<br clear="all" />

<h2><?php echo T_("Improved Import Transaction Matching");?></h2>
<p><?php echo T_("The development of OFX and HBCI support has also resulted in an improved transaction matching system that more accurately recognizes duplicate transactions during file import.");?></p>
<br clear="all" />

<h2><?php echo T_("Localization");?></h2>
<p><?php echo T_("Handles internationalized dates and currencies.  The Gnucash menus and popups have been translated to 21 languages, including Chinese, Danish, French, German, Hungarian, Italian, Japanese, Norwegian, Polish, Portuguese, Russian, Spanish, Swedish, Turkish, Ukrainian, and British English. Documentation is available in English, French, Portuguese and Spanish.");?></p>
<br clear="all" />

<h2><?php echo T_("Transaction Finder");?></h2>
<p>
<img src="<?=$top_dir?>/images/features/feature_search.png" width="300" height="200" alt="[Transaction Finder]" style="float: right; margin: 0.5em; border: solid thin grey;"/>
<?php echo T_("A powerful transaction query dialogue can help you quickly locate a needle in a haystack.");?></p>
<br clear="all" />

<h2><?php echo T_("General Ledger");?></h2>
<p><?php echo T_("Multiple accounts can be displayed in one register window at the same time. This can ease the trouble of tracking down typing/entry errors. It also provides a convenient way of viewing a portfolio of many stocks, by showing all transactions in that portfolio.");?></p>
<br clear="all" />

<h2><?php echo T_("Online Stock &amp; Mutual Fund Quotes");?></h2>
<p><?php echo T_("Get Stock &amp; Mutual Fund quotes from various web sites, update portfolio automatically. Additional pricing sources are added regularly.");?></p>
<br clear="all" />

<h2><?php echo T_("Check Printing");?></h2>
<p><?php echo T_("Checks may be printed in standard formats on common check stocks. A customization GUI allows custom check layouts to be developed.");?></p>
<br clear="all" />

<dl>
<h2><?php echo T_("Scheduled Transactions");?></h2>
<p><?php echo T_("You can now create recurring transactions, including automatic reminders when a transaction is due, the ability to postpone a scheduled transaction without canceling it, and the ability to specify only a limited number of transactions.");?></p>
<br clear="all" />

<h2><?php echo T_("Mortgage &amp; Loan Repayment Druid");?></h2>
<p><?php echo T_("A guided dialogue for setting up loan payments as scheduled transactions.");?>
</p>
<br clear="all" />

<!-- fixme: "complete user manual"? -->
<h2><?php echo T_("New User Manual and Help");?></h2>
<p><?php echo T_("A new help subsystem that focuses on how to do tasks is now available, in addition to a Tutorial and Concepts guide that gives the user background information on accounting principles and how they are reflected in GnuCash.");?></p>
<br clear="all" />

</div>
<?php include("externals/footer.phtml"); ?>
