<?php
$homepage = true;
include ("lang.php");
$page = basename($_SERVER['SCRIPT_NAME']);
// ^ alternate: __FILE__;
include ("externals/header.phtml");
include ("externals/menu.phtml");
?>
<div id="content">
  <h1><?=T_("Welcome to GnuCash.org")?></h1>
  <div style="width: 100%; float: left">
    <div class="download">
      <div style="float: left;">
        <h2 id="dwnld-box"><?php printf (T_("Download GnuCash %s"), $latest_stable)?></h2>
        <ul>
          <li><img alt="linux" src="<?=$top_dir?>/images/icons/linux.png" />
            Linux <a href="<?=$latest_stable_path.$latest_stable_source?>"><?=T_("Source code")?></a>
            | <a href="<?=$home?>/download.phtml#distribution"><?=T_("Via distribution")?></a></li>
          <li><img alt="windows" src="<?=$top_dir?>/images/icons/windows.png" /> <?=\LABEL_WIN?>
            <a
            href="<?=$latest_stable_path.$latest_stable_win?>"><?=\SUPPORTED_WIN?></a></li>
          <li><img alt="macosx" src="<?=$top_dir?>/images/icons/macosx.png" /> <?=\LABEL_MAC?>
            <a
            href="<?=$latest_stable_path.$latest_stable_mac_intel?>"><?=\SUPPORTED_MAC?></a></li>
          <li><a href="<?=$home?>/download.phtml" style="font-size: 80%;"><?=T_("More downloads (Source code, Development …)")?></a></li>
        </ul>
      </div>
      <div class="downloadimage">
        <img alt="download" src="<?=$top_dir?>/images/gnc-download.png" />
      </div>
      <div style="float: left;">
        <p><?php printf(T_( "Version %s is the last version for %s and %s and earlier." ),
           "<a href=\"download.phtml#previous\">".$last_win7_version."</a>", "Windows 7", "MacOS 10.12" )?>
        </p>
        <p><?php printf(T_("Version %s is the last version for Windows XP/Vista and MacOS X 10.8 and earlier, and so the last version that will run on PowerPC Macs."),
            "<a href=\"download.phtml#historical\">".$last_xp_vista_version."</a>" )?>
        </p>
      </div>
    </div><?php // Download ?>

    <p class="justify"><?=$GLOBALS ["default_description"]?></p>

<?php // FIXME: I18N markup: ?>
    <p class="justify"><?=T_("Designed to be easy to use, yet powerful and flexible, <span class=\"gnucash\">GnuCash</span> allows you to track bank accounts, stocks, income and expenses. As quick and intuitive to use as a checkbook register, it is based on professional accounting principles to ensure balanced books and accurate reports."); ?></p>
    <p class="justify" ><?php /* Translators: %s is the link to https://wiki.gnucash.org/wiki/Contributing_to_GnuCash */
    printf(T_("GnuCash is developed, maintained, documented, and translated entirely by volunteers. Want to help out? We have %s."),
             /* Translators: This is the label of the Contributing… wiki link */
      '<a href="https://wiki.gnucash.org/wiki/Contributing_to_GnuCash">'.T_("some suggestions")."</a>");
    /* Translators: %s is the link to weblate */
    printf(" ".T_("Please help translate GnuCash into your language at %s."), '<a href="https://hosted.weblate.org/engage/gnucash/">Weblate</a>')?>
  </div>

  <div style="float: right"> <!--Need help section -->
    <div class="dialog note">
      <h1><?=T_("Need Help?")?></h1>
      <p class="justify">
<?php // FIXME: I18N printf, markup: ?>
        <?=T_("Looking for someone to contact about <span class=\"gnucash\">GnuCash</span>? Try the")?>
          <a href="https://wiki.gnucash.org/wiki/Mailing_Lists"><?=T_("Mailing Lists")?></a>
          <?=T_(", which are public, email-based discussion groups where you can ask and answer <span class=\"gnucash\">GnuCash</span> questions to other users.")?>
      </p>
    </div>
  </div> <!-- Need Help section -->

  <div style="width: 100%">
    <h2 style="margin-bottom: 1px; margin-top: 0px"><?=T_("Feature Highlights"); ?></h2>
  </div>

  <div id="mainfeature">
    <ul>
      <li><?=T_("Double-Entry Accounting")?></li>
      <li><?=T_("Stock/Bond/Mutual Fund Accounts")?></li>
      <li><?=T_("Small-Business Accounting")?></li>
      <li><?=T_("Reports, Graphs")?></li>
      <li><?=T_("QIF/OFX/HBCI Import, Transaction Matching")?></li>
      <li><?=T_("Scheduled Transactions")?></li>
      <li><?=T_("Financial Calculations"); ?></li>
    </ul>
    <a href="<?=$home?>/features.phtml"><?=T_("<b>Discover more …</b>")?></a>
  </div>
  <!-- mainfeature -->
  <div id="newfeatures">
    <h1><?php printf(T_("GnuCash %s Released"), "4.0"); ?></h1>
    <p><?php printf(T_("We've released GnuCash %s with many bugfixes and improvements including some %s!"), "4.0",
                    sprintf("<a href=\"%s\">%s</a>", $home . "/new_features-4.0.phtml", T_("great new features")))?>
    </p>
  </div> <!-- newfeatures -->

<?php /*!-- Android app info 
  <div class="download" style="margin-top:2em">
    <h3 style="margin-bottom:1px; margin-top:0px">GnuCash for Android</h3>
    <div style="width:172px; height:100%; float:right; margin-left:15px; margin-right:15px">
      <a href="https://play.google.com/store/apps/details?id=org.gnucash.android" target="_blank">
        <img alt="Get it on Google Play" src="https://developer.android.com/images/brand/en_generic_rgb_wo_60.png" />
      </a>
      <p style="text-align:center"><a href="https://github.com/codinguser/gnucash-android/blob/master/README.md" target="_blank"><?=T_("Info and development")?></a></p>
    </div>
    <p><?=T_("The GnuCash team recommends the GnuCash for Android app. This app allows you to keep track of your financial transactions on the go for later import into the desktop version of GnuCash.")?></p>
    <p><i><b><?=T_("Note that GnuCash for Android is not a port of the GnuCash program to Android.")?></b></i></p>
  </div> < end Android app info */ ?>
</div> <!-- content -->

<?php include("externals/footer.phtml"); ?>
