<?php 
$homepage = true;
include("emulate_globals_on.php");
include("lang.php");
$title = T_("Free Accounting Software");
include("externals/header.phtml");
include("externals/menu.phtml"); 
?>

<div id="content">

<h1><?php echo T_("Welcome to GnuCash.org")?></h1>

<div id="download">
<h2><?php printf (T_("Download GnuCash %s"), $latest_stable)?></h2>

<ul>
<li><img src="<?=$top_dir?>/images/icons/linux.png" /> Linux <a href="<?php echo $download_path.$latest_stable_source;?>"><?php echo T_("Source");?></a> | <a href="<?=$home?>/download.phtml#distribution"><?php echo T_("Via distribution");?></a></li>
<li><img src="<?=$top_dir?>/images/icons/windows.png" /> Microsoft Windows <a href="<?php echo $download_path.$latest_stable_win;?>">XP/Vista/7</a></li>
<li><img src="<?=$top_dir?>/images/icons/macosx.png" /> Mac OS X <a href="<?php echo $download_path.$latest_stable_mac_intel;?>">Intel</a> | <a href="<?php echo $download_path.$latest_stable_mac_ppc;?>">Power PC</a> | <a href="http://wiki.gnucash.org/wiki/MacOSX/<?php echo $latest_stable;?>/Readme">Readme</a></li>
<li><a href="<?=$home?>/download.phtml" style="font-size: 80%;"><?=T_("More downloads (Source, Development,...)")?></a></li>
</ul>
</div>

<p class="justify"><?php echo T_("GnuCash is personal and small-business financial-accounting software, freely licensed under the <a href=\"http://www.gnu.org/\">GNU</a> GPL and available for GNU/Linux, BSD, Solaris, Mac OS X and Microsoft Windows.");?></p>

<p class="justify"><?php echo T_("Designed to be easy to use, yet powerful and flexible, GnuCash allows you to track bank accounts, stocks, income and expenses.  As quick and intuitive to use as a checkbook register, it is based on professional accounting principles to ensure balanced books and accurate reports. "); ?></p>

<div style="float:right; width:100%">
<h2 style="margin-bottom:1px; margin-top:0px"><?php echo T_("Feature Highlights"); ?></h2>
</div>

<div style="float:right; width:98%;  background-color: #f3f3f3; color: black; border: 2px;  border-color: black; border-style: ridge; padding: 1%">

<div style="width:50%;float:left;">
<ul style="font-style:italic;">
<li><?php echo T_("Double-Entry Accounting");?></li>
<li><?php echo T_("Stock/Bond/Mutual Fund Accounts");?></li>
<li><?php echo T_("Small-Business Accounting");?></li>
<li><?php echo T_("Reports, Graphs");?></li>
</ul>
<a href="<?=$home?>/features.phtml"><?php echo T_("<b>Discover more...</b>");?></a>
</div>

<div style="width:50%;float:left;"> 
<ul style="font-style:italic;">
<li><?php echo T_("QIF/OFX/HBCI Import, Transaction Matching");?></li>
<li><?php echo T_("Scheduled Transactions");?></li>
<li><?php echo T_("Financial Calculations "); ?></li>
</ul>
</div>

</div>

<div style="float:right; width:100%">
<h1><?php echo T_("News"); ?></h1>

<?php
  echo("<!-- top_dir = $top_dir , home = $home -->\n");
  # News will continue to be translated separately because 
  # of the .txt format. 
  # for english, the lang and en news path are identical
  $en_newspath  =  $top_dir."/news";
  $lang_newspath  =  $top_dir."/news/".$lang_dir;
  $oldnews = false;
  include("$top_dir/news/news-script.php");
  emit_news($en_newspath, $lang_newspath, $oldnews);
?>
<div class="newsborder">
<div class="newsheader"><img alt="news panel" src="<?=$top_dir;?>/images/icons/document.txt.gif">&nbsp;
<a href="oldnews.phtml"><?php echo T_("Older Announcements ...");?></a>

</div><div class="newsinner">
<?php echo T_("Click");?> <a href="oldnews.phtml"><?php echo T_("here");?></a> <?php echo T_("for older announcements ...");?>
</div></div>
</div>
</div>
<?php include("externals/footer.phtml"); ?>
