<?php 
include("emulate_globals_on.php");
include("lang.php");
$title = T_("Free Accounting Software");
include("externals/header.phtml");
include("externals/menu.phtml");
?>

<div style="position:fixed; right:0px; top:14%"><img src="<?=$top_dir?>/externals/gnucash-vert.png"></img></div>

<div id="content">

<h1><?php echo T_("Older Announcements");?></h1>

<p>
<?php echo T_("This is an archive of announcements that once appeared on the GnuCash home page.");?>
</p>

<?php
  echo("<!-- top_dir = $top_dir , home = $home -->\n");
  # News will continue to be translated separately because 
  # of the .txt format. 
  # for english, the lang and en news path are identical
  $en_newspath  =  $top_dir."/news";
  $lang_newspath  =  $top_dir."/news/".$lang_dir;
  $oldnews = true;
  include("$top_dir/news/news-script.php");
  emit_news($en_newspath, $lang_newspath, $oldnews);
?>
</div>
<?php include("externals/footer.phtml"); ?>

