<?php
  // This script will fetch the Mac OS X readme file from sourceforge.net
  // parameters:
  // branch: 'stable' or 'unstable'
  // version: Gnucash version for which to get the Readme file (eg '2.3.7')

  include("externals/global_params.php");

  $branch = $_GET['branch'];
  if (($branch!="stable") && ($branch!="unstable")) {
    $branch="stable";
  }

  $readme_path="http://downloads.sourceforge.net/project/gnucash/gnucash%20(".$branch.")/";

  $readme_file="Gnucash%20OSX%20Readme.html";
  if ($branch === "unstable") {
    $readme_file="Gnucash%20Unstable%20OSX%20Readme.html";
  }

  $version=$_GET['version'];
  if (! preg_match('/^[0-9]+\.[0-9]+\.[0-9]+$/',$version)) {
    $version=$latest_stable;
  }

  $location=$readme_path.$version."/".$readme_file;
//  echo $location;
  header("Location: ".$location);
  exit;
?>