<div class="featureborder">
<h2 class="featuretitle"><?php printf (T_("Unstable/Development release (%s)"), $latest_unstable)?></h2>
</div>
<p class="justify"><?php echo T_("Unstable (development) releases are for testing purposes only. They contain the newest features and improvements, but may also contain serious bugs still. Don't install these releases for everyday use.")?></p>
<p class="justify"><?php printf (T_("The latest unstable release of <span class=\"gnucash\">GnuCash</span> is %s.  Choose the download for your operating system below."), $latest_unstable)?></p>

<ul>
  <li><?php printf (T_("GnuCash %s for"), $latest_unstable)?> <a href="<?php echo $download_path.$latest_unstable_win;?>">Microsoft Windows XP/Vista/7</a></li>
  <li><?php printf (T_("GnuCash %s for"), $latest_unstable)?> Mac OS X <a href="<?php echo $download_path.$latest_unstable_mac_intel;?>">Intel</a> | <a href="<?php echo $download_path.$latest_unstable_mac_ppc;?>">PPC</a> | <a href="http://wiki.gnucash.org/wiki/MacOSX/<?php echo $latest_unstable;?>/Readme">Readme</a></li>
  <li><a href="<?php echo $download_path.$latest_unstable_source;?>">bzip2 compressed tarball</a> <?php printf (T_("for GnuCash %s"), $latest_unstable)?></li>
</ul>

