<?php                                                    
include("emulate_globals_on.php");
include("lang.php");
$title = T_("View document");
include("externals/header.phtml");
include("externals/menu.phtml");

# Some base parameters used later on
$basepath       = "http://www.gnucash.org/docs";
$helpdoc        = "gnucash-help/help.html";
$tcdoc          = "gnucash-guide/index.html";
$current_stable = "2.6";

# Determine which documentation to show based on 3 parameters:
# - language
# - help or guide (doc)
# - doc version (rev)

# Show current stable helpdoc, in overall set language by default
$showdoc     = $tcdoc;
$req_doc_ok  = true;
$showrev     = $current_stable;
$req_rev_ok  = true;

# Requested language is set in $locale by included lang.php
if ($locale == "en_US") {
  $showlang  = "C";
} else {
  $showlang  = $locale;
}
$req_lang_ok = true;

# Parse requested document
if (isset ($_GET["doc"])) {
  switch ($_GET["doc"]) {
    case "help":
        $showdoc = $helpdoc;
        break;
    case "guide":
        $showdoc = $tcdoc;
        break;
    default:  /* unknown document requested, will present help by default */
        $req_doc_ok = false;
        break;
  }
}

# Parse requested version
if (isset ($_GET["rev"])) {
  switch ($_GET["rev"]) {
    case "1.8":
        $showrev = "1.8";
        break;
    case "2.0":
        $showrev = "2.0";
        break;
    case "2.2":
        $showrev = "2.2";
        break;
    case "2.4":
        $showrev = "2.4";
        break;
    case "2.6":
        $showrev = "2.6";
        break;
    case "current":
        $showrev = $current_stable;
        break;
    case "trunk":
        $showrev = "trunk";
        break;
    case "nightly":
        $showrev = "trunk";
        break;
    default:  /* unknown version requested, will current stable by default */
        $req_rev_ok = false;
        break;
  }
}

# Now check if the requested combination of doc, revision and language actually exists
# If not, try the default C locale instead.

# First evaluate the nightly builds, they are located on a different server
# To avoid network traffic, the available languages are hard-coded here and should be
# updated if list of languages in which the documentation is available changes
if ($showrev == "trunk") {
  $basepath = "http://code.gnucash.org/docs";
  $trunk_langs = array ( $helpdoc => array( "C", "de", "de_DE", "it", "it_IT"),
                         $tcdoc   => array( "C", "de" "de_DE", "it", "it_IT", "ja", "ja_JP"));
  if (!in_array ($showlang, $trunk_langs[$showdoc])) {
    $showlang    = "C";
    $req_lang_ok = false;
  }
  
  $showurl=$basepath."/".$showlang."/".$showdoc;
} else {
  # For the stable versions, we can simply check file availability because we're
  # on the same server
  $checkpath="docs/v".$showrev."/".$showlang."/".$showdoc;
  if (!file_exists ($checkpath)) {
    $showlang    = "C";
    $req_lang_ok = false;
  }
  
  $showurl=$basepath."/v".$showrev."/".$showlang."/".$showdoc;
}

?>

<div id="content">

<?php if (! $req_doc_ok ) { ?>
<p style="color: red;"><?= T_("The document requested is not available. The tutorial and concepts guide will be displayed instead.")?></p>
<?php } ?>
<?php if (! $req_rev_ok ) {
  $reqrev=$_GET["rev"]; ?>
<p style="color: red;"><?php printf (T_("The document requested is not available for version %s. Version %s will be displayed instead."),
                                     $reqrev, $showrev); ?></p>
<?php } ?>
<?php if (! $req_lang_ok ) { ?>
<p style="color: red;"><?= T_("The document requested is not available in the requested language. The English version will be displayed instead.")?></p>
<?php } ?>

<iframe src="<?php echo $showurl; ?>" style="border-width: 0px; width: 100%; min-width: 700px; height: 80em;">
<?php printf (T_("It seems your browser doesn't support iframes. To view the requested page in a separate window, please <a href=\"%s\" target=\"_new\">click here</a>."), $showurl); ?>
</iframe>

</div>
<?php include("externals/footer.phtml"); ?>
