<?php $title = "GnuCash nas Notícias"; ?>
<?php if (!ini_get('register_globals')) {
 include("../emulate_globals_on.php");
}
?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/menu/menu-other-main.phtml"); ?>
</td>

<td valign=top>
<b>GnuCash nas Notícias!</b>
<br><br>

<dl>
      <dt>
      <b>Gerer ses comptes personnels</b>
      (arquivo: <a href="/press-archive/maximum-linux-2000-12/p1.jpg">página 1</a>,
      <a href="/press-archive/maximum-linux-2000-12/p2.jpg">página 2</a>,
      <a href="/press-archive/maximum-linux-2000-12/p3.jpg">página 3</a>,
      <a href="/press-archive/maximum-linux-2000-12/p4.jpg">página 4</a>)
      
      (MaximumLinux Francesa, Dezembro 2000)
      </dt>
      <dd>
      L'ordinateur prend une place de plus en plus importante 
      dans les foyers, notamment en ce qui concrne la gestion 
      des finances personnelles. Petit tour d'horizon des 
      differents logiciels pour vous aider a faire le bon choix.
      <br><br>
      [nota dos editors: o gnucash-1.4.8 recebe cinco estrelas desta revista Francesa!]
      <br><br>
      </dd>
      
      <dt>
      <b><a href="http://www.linuxgram.com/newsitem.phtml?sid=109&aid=10365">
      Armas do Gnome</a></b>
      (<a href="/press-archive/linuxgram-2000-12/newsitem.html">cópia de arquivo</a>)
      (Linuxgram, Dezembro 2000)
      </dt>
      <dd>
      Armas do Gnome: Não É Paranoia se Eles Estiverem Mesmo Aí Para O Apanhar!
      Nautilus (Eazel) = Gestor de Ficheiros MS Explorer 
      <br><br>
      </dd>
      
      <dt>
      <b><a href="http://www.linuxorbit.com/features/newbie10.php3">
      O Novato experimenta o GnuCash</a></b>
      (<a href="/press-archive/linuxorbit-2000-12/features-newbie10.php3.html">cópia de arquivo</a>)
      (Linux Orbit, Dezembro 2000)
      </dt>
      <dd>
      Eu tinha andado à procura de algo que pudesse interessar a 
      um neófito do Linux tal como eu e com um pouco de suporte do 
      guru da Linux Orbit, decidi-me a experimentar o GnuCash e 
      dar-lhe a prespectiva do novato. Apesar de eu sempre ter 
      utilizado folhas de cálculo para acompanhar as minhas finanças, 
      pensei, e porque não.
      <br><br>
      </dd>
      
      <dt>
      <b><a href="http://www.linuxnews.com/stories.php?story=526">
      O que o GnuCash tem de novo</a></b>
      (<a href="/press-archive/linuxnews-2000-10/stories.html">cópia de arquivo</a>)
      (LinuxNews, Outubro 2000)
      </dt>
      <dd>GnuCash, o sistema financeiro e de contabilidade em código aberto, está 
      a preparar-se para se tornar no principal pacote de contabilidade em Linux--e 
      está rapidamente a encontrar a forma de o conseguir. 
      Rob Browning, um dos programadores do GnuCash, explicou que ultimamente o 
      projecto se tem vindo a expandir. "De momento somos agora quatro programadores 
      a tempo inteiro, e estamos a preparar-nos para admitir mais uns poucos," disse ele,
      atribuindo o crescimento da equipa--e do projecto--ao suporte financeiro 
      dado pela Gnumatic Incorporated, anunciado a 14 de Agosto de 2000. 
      <br><br>
      </dd>

      <dt>
      <b>
      <a href="http://slashdot.org/articles/00/06/19/1721237.shtml">
      Gnucash v1.4.0 Disponibilizado</a></b>
      (<a href="/press-archive/slashdot-2000-06/slashdot.org.articles.00.06.19.1721237.html">cópia de arquivo</a>)
      (Slashdot, Junho 2000)
      </dt>
      <dd>
      Ur@eus escreveu: "A equipa do Gnucash acabou de lançar a versão 1.4.0 do 
      seu maravilhoso gestor de finanças pessoais ao estilo do Quicken. Esta é 
      a primeira versão estável desde a conversão de Motif para GNOME. Poderá 
      encontrar o Gnucash 1.4.0 no Gnucash.org" Isto cobre uma grande falha nas 
      aplicações para Linux: Tenho utilizado o gnucash desde à um ano até agora, 
      e ele tem dado grandes saltos em termos de funcionalidades e estabilidade. 
      Não é o quicken, mas para a maioria de nós é semelhante o suficiente. Se 
      estiver a ter problemas com o endereço principal, tente esta réplica. 
      <br><br>
      </dd>

      <dt>
      <b><a href="http://linux.davecentral.com/bol_20000612.html">
      Vencedor do Melhor do Linux</a></b>
      (<a href="/press-archive/davecentral-2000-06/bol_20000612.html">cópia de arquivo</a>)
      (Dave Central, Junho 2000)
      </dt>
      <dd>
      Gestão financeira informática: já não é apenas 
      para o Quicken. No constante esforço de passar 
      a minha rotina de verificação do livro de cheques 
      dos meus recibos desorganizados para uma boa 
      automatização em Linux, aceitei a ajuda do GnuCash.
      Se esta aplicação conseguir colocar as minhas ruinosas
      finanças em ordem, imagine o que pode fazer por um 
      indivíduo organizado como você.
      <br><br>
      </dd>
      
      <dt>
      <b><a href="http://www.lwn.net/2000/0504/devel.phtml">
      Outra análise ao gnucash</a></b>
      (<a href="/press-archive/lwn.net-2000-0504/devel.html">cópia de arquivo</a>)
      (LWN.net, Maio 2000)
      </dt>
      <dd>
      Dezembro passado executamos uma análise ao gnucash que concluiu 
      que a aplicação - um pacote livre de finanças pessoais e de pequenas 
      empresas - não estava ainda pronto para o estrelato.  Inspirado pelo 
      facto de ter conhecido os programadores na Linux Business Expo, a LWN 
      efectuou outra análise ao gnucash. Conclusão: desenvolveu-se muito.  
      O seu editor tem o prazer de anunciar uma completa transição para 
      o gnucash, vendo-se assim livre da última aplicação Windows que tinha 
      no seu sistema. Altura de reclamar aquela partição. 
      <br><br>
      </dd>
      
      <dt>
      <b><a href="http://www.linuxworld.com/linuxworld/lw-2000-04/f_lw-04-vcontrol_4.html">
      Não existe contabilidade para Linux</a></b>
      (<a href="/press-archive/linuxworld-2000-04/f_lw-04-vcontrol_4.html">cópia de arquivo</a>)
      (LinuxWorld, Abril 2000)
      </dt>
      <dd>
      O Linux está a tornar-se multi-funcional? Não se basear as suas conclusões 
      nos resultados da pesquisa que acabei de fazer no Freshmeat quando introduzi 
      "contabilidade" como termo a pesquisar. Obtive comida para marrões: 
      contabilização de pacotes, contabilização de tráfego em multi-routing, 
      monitorização RDIS, medidores de tráfego em rede, e, no topo da lista, 
      uma modificação ao daemon de contabilização de rede. 
      <br><br>
      </dd>
 
      <dt>
      <b><a href="http://www.linuxmall.com/news/?1,2">
      O Projecto GNUCash: Focando-se na Gestão Financeira em Linux</a></b>
      (<a href="/press-archive/linuxmall/linuxmall.com,news,1,2,index.html">cópia de arquivo</a>) 
      (LinuxMall, Março 2000)
      </dt>
      <dd>
      À cinco anos, Linas Vepstas trabalhava "para uma .com. Nóes estavamos 
      lá, estavamos na onda, sabiamos o que tinhamos a fazer para ter sucesso, 
      estavamos a construir este sitio web com NT... na altura, NT era o futuro 
      rei. Era de loucos apostar contra a Microsoft." Então ele descobriu o 
      Linux--e lançou o Projecto GNUCash, com o objectivo de desenvolver aplicações 
      financeiras e de contabilidade estáveis, fáceis de utilizar e flexíveis, 
      para GNU/Linux. 
      <br><br>
      </dd>

      <dt>
      <b><a href="http://slashdot.org/articles/00/02/28/0945240.shtml">
      Lançado o Gnucash 1.3.0 Beta</a></b> 
      (<a href="/press-archive/slashdot-2000-02/slashdot.org.articles.00.02.28.0945240.html">cópia de arquivo</a>)
      (Slashdot, Fevereiro 2000)
      </dt>
      <dd>
      O Jeremy Collins escreveu-nos para nos dizer que o Gnucash 1.3.0 Beta 
      foi lançado. Nós mantemos os anúncios de lançamento de aplicações num 
      mínimo e deixamos outros sítios mais apropriados realiza-los, mas este 
      é bastante significativo. O Gnucash é hoje em dia a melhor aplicação 
      quickenesca para Linux, tal como todos sabem: são essas estranhas aplicações 
      que nos mantêm a utilizar outros SOs. Nós já vamos tendo vários processadores 
      de texto, folhas de cálculo e de manipulação de imagem, mas ver desenvolvimentos 
      a surgir na área dos pacotes financeiros (também jogos e vídeo) é importante. 
      De qualquer forma, sugiro que verifiquem esta aplicação: eu tenho-a utilizado 
      desde quando se chamava xacc e é muito boa. Obtenha-a em ftp.gnucash.org e 
      relate erros (bugs) caso os encontre. 
      <br><br>
      </dd>
      
      <dt>
      <b><a href="http://lwn.net/1999/features/GnuCash/">
      Uma avaliação do GnuCash 1.2.5</a></b>
      (<a href="/press-archive/lwn.net-1999-features/lwn.net,1999,features,GnuCash,index.html">cópia de arquivo</a>)
      (LWN.net, Dezembro 1999)
      </dt>
      <dd>
      Aqui está uma desagradável confissão de um autor da LWN: na 
      verdade eu ainda utilizo o Windows.  Eu arranco-o para correr 
      apenas uma aplicação - uma aplicação de finanças pessoais antiga, 
      proprietária. É a única coisa que algumas vez achei útil no Windows. 
      Ocasionalmente eu procuro por aí uma substituição livre para que 
      possa recuperar aquela última e pequena partição do meu disco. 
      Este artigo é o resultado da minha mais recente procura - condicionada, 
      adicionalmente, pela aterradora sensação de que a minha aplicação 
      actual provavelmente não está preparada para a passagem para o ano 2000...
      <br><br>
      </dd>

      <dt>
      <b><a href="http://www.32bitsonline.com/article.php3?file=issues/199902/lj-19990208&page=1">Aplicações de Finanças Pessoais</a></b>
      (<a href="/press-archive/32bitsonline-1999-02/lj-19990208.html">cópia de arquivo</a>)
      (32BitsOnline.com Fevereiro 1999)
      </dt>
      <dd>
      A disponibilidade de aplicações especializadas é uma das fraquezas do Linux
      quando comparado com sistemas operativos rivais. No reino das finanças pessoais, 
      nenhum dos mais conhecidos pacotes de aplicações se encontra disponível em Linux.
      Felizmente, a Intuit irá um dia portar para a plataforma Linux as suas populares 
      linhas de produtos Quicken e QuickBooks. Até lá, que estão algumas aplicações de 
      finanças pessoais para o colocar a verificar o seu livro de cheques em Linux.
      <br><br>
      </dd>
      </dl>


</td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/footer.phtml"); ?>
