<?php $title = "Contribuir"; ?>
<?php if (!ini_get('register_globals')) {
 include("../emulate_globals_on.php");
}
?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/menu/menu-developer-main.phtml"); ?>
</td>

<td valign=top>
<h1>Como Contribuir</h1>

<p>
GnuCash é um projecto de desenvolvimento de uma Aplicação Livre 
e a dinâmica de contribuição é muito semelhante à de qualquer outro.
O que você pode contribuir depende muito dos seus conhecimentos, 
o tempo que tem disponível, e aquilo que gosta de fazer.
GnuCash está à procura de testadores beta, programadores, escritores, 
moderadores de discussões, tradutores e pessoas geralmente simpáticas.   

<br><br>
<table>
<tr><td>
<b>Seleccione o seu talento para ver onde se encaixa:</b></td>
<td>
<form method=post>
<select name=contribute>
  <option value=programmer
   <?php if ($contribute == "programmer") { echo ("selected"); } ?>
  >Eu sou programador</option>
  <option value=translator
   <?php if ($contribute == "translator") { echo ("selected"); } ?>
  >Eu sou um tradutor</option>
  <option value=fan
   <?php if ($contribute == "fan") { echo ("selected"); } ?>
  >Eu sou um fã</option>
  <option value=webmaster
   <?php if ($contribute == "webmaster") { echo ("selected"); } ?>
  >Eu sou um webmaster</option>
  <option value=writer
   <?php if ($contribute == "writer") { echo ("selected"); } ?>
  >Eu sou um escritor/reporter</option>
</select>
<input type=submit value=Go>
</td>
</table>
</form>

<?php
  if ($contribute != "") { 
		include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/contribute/contribute-".$contribute.".phtml");
  }
?>


</td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/footer.phtml"); ?>
