<?php $title = "Características: Facilidade de Utilização"; ?>
<?php if (!ini_get('register_globals')) {
 include("../emulate_globals_on.php");
}
?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/menu/menu-general-main.phtml"); ?>
</td>

<td valign=top>

<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr>
  <td><img src=/images/features/features_title.png></td>
  <td align=right><a href="javascript:window.close();"><img border=0 src=/images/close_window.png></a></td>
</tr>
</table>

<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr><td bgcolor=#000000><img src=/images/spacer.png height=1></td></tr>
</table>

<br>

<table cellpadding=4 cellspacing=0 border=0 width=100%>
<tr>
<td valign=top>
  <img src=/images/features/features_5_text.png><br><br>


  Descarregue o GnuCash e tente algumas das outras óptimas funcionalidades:

	<br><br>
<UL>
<LI>
Uma janela de reconciliação com saldos reconciliados e limpos 
torna mais simples comparar com o extracto bancário. 
</LI>
<BR><BR>
<LI>
Portfólios de Acções/Títulos: Acompanhe as acções individualmente (uma por 
conta) ou em portfólios de contas (um grupo de contas que pode ser 
visualizada em conjunto). 
</LI>
<BR><BR>
<LI>
Ficheiros QIF do Intuit&reg; Quicken&reg; podem ser importados, e são automaticamente 
agregados para eliminar transacções duplicadas. 
</LI>
<BR><BR>
<LI>
Gere datas e moedas internacionalizadas.  Os menus e janelas do Gnucash 
foram traduzidos para Alemão, Dinamarquês, Espanhol, Francês, Italiano, 
Japonês, Norueguês, Português do Brasil, Português de Portugal, Sueco, 
Russo, Ucraniano, e Inglês Britânico.  A documentação está disponível em 
Inglês, Francês, Português de Portugal e Espanhol.
</LI>
<BR><BR>
<LI>
Relatórios: Apresenta Folha de Balanço, Lucros & Prejuizos, Valorização do Portfólio, 
e outros. Os relatórios podem ser gravados como HTML ou postscript, ou impressos.
(A próxima versão beta inclui uma nova infraestrutura integrada de gráficos 
que irá adicionar considerável poder & beleza aos relatórios.)
</LI>
<BR><BR>
<LI>
Procura de Transacções: uma poderosa janela de procura de transacções pode 
ajuda-lo a rapidamente localizar uma agulha num palheiro.
</LI>
<BR><BR>
<LI>
Dupla Entrada: Quando activada, todas as transacções têm de 
debitar uma conta e creditar outras por um igual montante. 
Isto assegura que as "contas saldam": que a diferença entre 
receitas e despesas é exactamente igual à soma de todos os 
activos e passivos.
</LI>
<BR><BR>
<LI>
Contas de Tipo (Categorias) Receita/Despesa permitem-lhe 
categorizar os seus fluxos de dinheiro.  Quando devidamente 
utilizadas com a característica de dupla-entrada e contas de 
passivo, estas permitem-lhe gerar relatórios, tais como Lucros 
& Prejuizos, que sistemas mais simples não conseguem produzir.
</LI>
<BR><BR>
<LI>
Plano de Contas: Multiplas contas podem ser visualizadas 
simultaneamente numa janela de registo. Isto pode aliviar o 
trabalho de procurar erros de escrita ou registo. Também 
disponibiliza um método conveniente de visualizar um portfólio 
de várias acções, ao mostrar todas as transacções nesse portfólio. 
</LI>
<BR><BR>
<LI>
Obtenha cotações de Acções & Outros Títulos a partir de vários 
sítios web, actualizando automaticamente o seu portfólio. 
Outras fontes de cotações são adicionadas regularmente.
</LI>
<BR><BR>
<LI>
Janelas de Dica do Dia torna fácil a aprendizagem de novas funcionalidades 
do GnuCash.  A extensa documentação incluida ajuda a responder a questões 
que possa ter sobre funcionalidades específicas e procedimentos contabilísticos.
</LI>
<BR><BR>
<LI>
Impressão de Cheques:  Cheques podem ser impressos em formatos standard nos 
impressos de cheque apropriados.  Um interface gráfico de personalização 
permite desenvolver desenhos (disposições) personalizados de cheques.
</LI>
<BR><BR>
<LI>
Preferências: a visualização e comportamento da janela principal e das janelas 
de registo podem ser amplamente personalizadas através de uma janela de 
preferências da aplicação.
</LI>
<BR><BR>
<LI>
Múltiplas Moedas & Câmbios: São suportadas múltiplas moedas e estas 
podem ser compradas ou vendidas (transaccionadas). Movimentos de 
moedas entre contas são completamente saldados quando a dupla-entrada 
está activada.  Um interface simplificado para a gestão de múltiplas 
moedas encontra-se em desenvolvimento.
</LI>
<BR><BR>
<LI>
Documentação Online: agora incui uma pequena funcionalidade de pesquisa.
</LI>
<BR><BR>
</UL>

</td>
</tr>
</table>

<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr><td bgcolor=#000000><img src=/images/spacer.png height=1></td></tr>
</table>

<br>

<table border=0 cellspacing=0 cellpadding=0 width=100% align=center>
<tr>
  <td align=center>
	  <a href=/pt_PT/features_4.phtml><img border=0 src=/images/features/features_previous.png></a>
		 |
	  <img border=0 src=/images/features/features_next_disabled.png>
	</td>
</tr>
</table>

</td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/footer.phtml"); ?>
