<?php $title = "Características:Facilidade de Utilização"; ?>
<?php if (!ini_get('register_globals')) {
 include("../emulate_globals_on.php");
}
?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/menu/menu-general-main.phtml"); ?>
</td>

<td valign=top>

<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr>
  <td><img src=/images/features/features_title.png></td>
  <td align=right><a href="javascript:window.close();"><img border=0 src=/images/close_window.png></a></td>
</tr>
</table>

<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr><td bgcolor=#000000><img src=/images/spacer.png height=1></td></tr>
</table>

<br>

<table cellpadding=4 cellspacing=0 border=0 width=100%>
<tr>
<td valign=top>
  <img src=/images/features/features_2_text.png><br><br>

  Uma conta pai pode ter uma hierarquia de contas de detalhe sob sí. Isto permite que tipos de contas
  semelhantes ( por ex. Dinheiro, Banco, Acções ) sejam agrupadas numa grande conta ( por ex. Bens ). 

</td>
<td valign=middle>
  <img src=/images/features/features_2_small.png>
</td>
</tr>
</table>

<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr><td bgcolor=#000000><img src=/images/spacer.png height=1></td></tr>
</table>

<br>

<table border=0 cellspacing=0 cellpadding=0 width=100% align=center>
<tr>
  <td align=center>
	  <a href=/pt_PT/features_1.phtml><img border=0 src=/images/features/features_previous.png></a>
		 |
	  <a href=/pt_PT/features_3.phtml><img border=0 src=/images/features/features_next.png></a>
	</td>
</tr>
</table>

</td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/footer.phtml"); ?>
