<?php $title = "Funcionalidades"; ?>
<?php if (!ini_get('register_globals')) {
 include("../emulate_globals_on.php");
}
?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/menu/menu-general-main.phtml"); ?>
</td>

<script language=javascript>
<!--
  
  function newWin(url) {
    newLoc=window.open("","","height=480,width=640,scrollbars=yes")
    newLoc.location=url
  }

// -->
</script>

<td valign=top>

<h1>Features</h1>

<font size=-1>
Se você tem estado à procura de uma forma de gerir as suas finanças 
pessoais em GNU/Linux, você encontrou-a!  Concebido para ser de fácil 
utilização, mas poderoso e flexível, GnuCash permite-lhe acompanhar 
contas bancárias, acções, receitas e despesas.   Tão rápido e intuitivo 
de utilizar como o registo de um livro de cheques, é baseado em princípios 
contabilísticos profissionais para assegurar contas saldadas e relatórios 
precisos. GnuCash é suportado por uma comunidade de programadores activa e 
está-se a tornar num completo sistema contabilístico.  Desenvolvido sob a 
GPL, leva a que você não tenha de se preocupar com a obsolescência: o GnuCash 
estará sempre lá para si.
<BR>
<BR>
Este sítio web tem como objectivo promover o projecto Gnucash.org de 
desenvolvimento da aplicação.
Nós estamos empenhados em desenvolver ferramentas financeiras de topo 
para GNU/Linux e utilizadores Unix.  Isto inclui o desenvolvimento de 
APIs de programação e componentes que possam ser utilizados para criar 
tanto aplicações de servidor como pessoais para utilização doméstica 
e empresarial. Ao nos focarmos na facilidade de utilização, desenho modular, 
arquitectura de interfaces e código bem documentado, esperamos que o GnuCash 
e as bibliotecas financeiras a ele associadas se tornem na escolha de uma 
geração de programadores e utilizadores GNU.
<BR>
<BR>
</font>

<center>
<!-- <a href="javascript:newWin('/pt_PT/features_1.phtml')"> -->
<a href="/pt_PT/features_1.phtml">
<img border=0 src=/images/features/features_start_the_tour.png></a>
</center>

</font>

</td>


<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/footer.phtml"); ?>
