<?php $title = "História"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/menu/menu-other-main.phtml"); ?>
</td>

<td valign=top>
<b>História & Créditos</b><br><br>

   Afinal de contas, de quem é este sangue, suor e lágrimas?

<BR><BR><font size="+2"><b>Programadores Principais</b></font>
<HR>


<dl>
  <dt>
  <b>Linas Vepstas</b>
  </dt>
  <dd>
    gostou do que viu: o aspecto visual era bonito, o código estava 
    documentado e bem estruturado, e era todo GPL. E assim ele 
    re-escreveu-o: adicionou widgets de célula ao XbaeMatrix, para 
    que caixas de lista e setas ficassem mais bonitas, re-escreveu 
    o processador do X-Accountant para adicionar 
    a dupla-entrada, uma hierarquia de contas, um motor para transacções 
    com parcelas, adicionou suporte para acções, e melhorou os menus de 
    ajuda. Essa foi a versão 1.0 em Janeiro de 1998. Para as versões 
    1.1 &amp; 1.2, o motor interno foi aumentado e refinado, e a janela 
    de registo completamente redesenhada e tornada quase que 
    independente do Motif (e aspecto gráfico). 
    Linas está agora envolvido na Gnumatic Incorporated, uma empresa formada 
    para melhorar e suportar o GnuCash para todos, desde os utilizadores 
    caseiros até às empresas e contabilistas profissionais.  
  </dd>

<BR>
<BR>

  <dt>
  <b>Rob Browning</b>
  </dt>
  <dd>
    abusou de toda a gente por não utilizarem Perl, e depois de 
    termos adicionado suporte para Perl, desistiu do Perl a favor do 
    suporte Guile/Scheme.  Rob construiu a infraestrutura de compilação, 
    modificou o código gtk, e está a alterar o formato do ficheiro.
    Ainda re-escreveu os relatórios e o descarregar de extractos em scheme,
    o wrapper g-wrap para guile, e as preferências de utilizador.
  </dd>
</dl>

<BR>

<dl>
  <dt>
  <b>Jeremy Collins</b> 
  </dt>
  <dd>
    criou e divulgou largamente o projecto GnoMoney, 
      e depois mudou o seu nome para GnuCash. 
      (Na verdade, colocou o nome a votação.  A democracia não é uma boa 
      forma de escolher nomes.) Jeremy registou o nome de domínio, criou 
      e manteve o sitio de internet gnucash.org durante vários anos, além
      de que conseguiu fazer funcionar o código GTK/gnome inicial.  
  </dd>

<BR>
<BR>


  <dt>
  <b>Dave Peticolas</b>
  </dt>
  <dd>
    programa obsecivamente no GnuCash. Mas ele consegue parar assim que 
    queira. A sério.
    (Ele é agora o guardião da árvore de código CVS do GnuCash, pelo que 
    sejam simpáticos ou ele pode desistir de programar a meio do vosso patch).
  </dd>


<BR>
<BR>

  <dt>
  <b>Rob Clark</b>
  </dt>
  <dd>
    programou o original X-Accountant em
    Motif como projecto escolar, levando-o até à versão 0.9 em Outubro
    de 1997.  Apesar de cada linha do seu código ter já sido re-escrita, 
    o seu nome surge como crédito em quase todos os ficheiros.
    Tal é a magia dos direitos de autor.
  </dd>

<BR>
<BR>

  <dt>
  <b>Bill Gribble</b>
  </dt>
  <dd>
    não é tímido, ou de falinhas mansas.  Assim não sejam tímidos se encontrarem
    um erro no seu código: Importação QIF, API de pesquisa e procura de transacções, 
    impressão de cheques, suporte para bens e moedas, integração gtkhtml e impressão 
    de relatórios.
  </dd>
</dl>

<BR>

<font size="+2"><b>Pessoas que Corrigiram Erros</b></font>
<hr>

<dl>
      <dt> <a href="mailto:arensb@cfar.umd.edu"> Andrew
      Arensburger</a></dt>

      <dd>pelas modificações para FreeBSD e outras</dd>

      <dt> <a href="mailto:matt_armstrong@bigfoot.com"> Matt
      Armstrong</a></dt>

      <dd>pelas várias correcções</dd>

      <dt> <a href="mailto:fred@moremagic.com"> Fred Baube</a></dt>

      <dd>por tentar portar para Java (MoneyDance)</dd>

      <dt> <a href="mailto:dennisb@cs.chalmers.se"> Dennis
      Björklund</a></dt>

      <dd>Tradução para Sueco</dd>

      <dt> <a href="mailto:bojsen@worldnet.att.net"> Per Bojsen</a></dt>

      <dd>várias correcções de core dump</dd>

      <dt> <a href="http://www.hex.net/~cbbrowne"> Christopher B.
      Browne</a></dt>

      <dd>pelos scripts em perl para acções, primeiro rascunho do 
      código de importação QIF baseado em Guile, várias modificaçõesl 
      & manutenção da documentação em Inglês, e mais</dd>

      <dt> <a href="mailto:grahamc@zeta.org.au"> Graham
      Chapman</a></dt>

      <dd>pelo pacote de acrescento xacc-rpts</dd>

      <dt> <a href="mailto:georgec@sco.com"> George Chen</a></dt>

      <dd>pelo suporte para QIF do MS-Money</dd>

      <dt> <a href="mailtochina@thewrittenword.com">Albert
      Chin-A-Young</a></dt>

      <dd>modificação do configure.in</dd>

      <dt> <a href="mailto:jcollins@gnucash.org"> Jeremy
      Collins</a></dt>

      <dd>pelo GnoMoney e porte para GTK</dd>

      <dt> <a href="mailto:mcondell@bbn.com"> Matthew Condell</a></dt>

      <dd>modificação FreeBSD</dd>

      <dt> <a href="mailto:pcondon@rackspace.com"> Patrick
      Condron</a></dt>

      <dd>por configurar um servidor web numa ligação T1 
          em nome dos entusiastas do código aberto 
          <a href="http://www.rackspace.com">
          rackspace.com</a></dd>

      <dt> <a href="mailto:Ciaran.Deignan@bull.net"> Ciaran
      Deignan</a></dt>

      <dd>pela versão em binário para AIX</dd>

      <dt> <a href="mailto:tyson@tyse.net"> Tyson Dowd</a></dt>

      <dd>pelas modificação ao config/make e manutenção da versão para debian</dd>

      <dt> <a href="mailto:ripley@xs4all.nl"> Koen D'Hondt</a></dt>

      <dd>pelas modificações ao XmHTML para Solaris</dd>

      <dt> <a href="mailto:bob@mostly.com"> Bob Drzyzgula</a></dt>

      <dd>pelas notas de implementação da orçamentação</dd>

      <dt> <a href="mailto:pjf@schools.net.au"> Paul Fenwick</a></dt>

      <dd>suporte ASX</dd>

      <dt> <a href="mailto:hfiguiere@teaser.fr"> Hubert Figuiere</a></dt>

      <dd>modificação ao gnc-prices</dd>

      <dt> <a href="mailto:ju_finck@mail.netwave.de"> Jan-Uwe
      Finck</a></dt>

      <dd>pela tradução das mensagens para Alemão</dd>

      <dt> <a href="mailto:rjf@aracnet.com"> Ron Forrester</a></dt>

      <dd>pelas modificações ao gnome</dd>

      <dt> <a href="mailto:DFreese@osc.uscg.mil"> Dave
      Freese</a></dt>

      <dd>pela correcção para anos bissextos</dd>

      <dt> <a href="mailto:grib@billgribble.com"> Bill Gribble</a></dt>

      <dd>código de importação QIF</dd>

      <dt> <a href="mailto:otto@bug.redhat.com"> Otto
      Hammersmith</a></dt>

      <dd>pelo empacotamento em RPM RedHat</dd>

      <dt> <a href="mailto:offby1@blarg.net"> Eric Hanchrow</a></dt>

      <dd>actualização à documentação de moedas</dd>

      <dt> <a href="mailto:haral@codec.ro"> Alexandru
      Harsanyi</a></dt>

      <dd>por corrigir vários core dumps e lockups.</dd>

      <dt> <a href="mailto:john@dhh.gt.org"> John Hasler</a></dt>

      <dd>modificação ao motor</dd>

      <dt> <a href="mailto:jk@isdn-a33.itea.ntnu.no"> Jon K}re
      Hellan</a></dt>

      <dd>por corrigir vários core dumps e lockups.</dd>

      <dt> <a href="mailto:PrakashK@bigfoot.com"> Prakash
      Kailasa</a></dt>

      <dd>pelas correcções à compilação gnome</dd>

      <dt> <a href="mailto:tkludy@csd.sgi.com"> Tom Kludy</a></dt>

      <dd>pelo porte para SGI Irix</dd>

      <dt> <a href="mailto:sk@xgm.de"> Sven Kuenzler</a></dt>

      <dd>pelo ficheiro LEIA-ME (README) para SuSE</dd>

      <dt><a href="mailto:blarsen@ada-works.com"> Bryan Larsen</a></dt>

      <dd>relatório de orçamentação em guile</dd>

      <dt> <a href="mailto:mellon@andare.fugue.com"> Ted
      Lemon</a></dt>

      <dd>pelo porte para NetBSD</dd>

      <dt> <a href="mailto:y-le-ny@ifrance.com"> Yannick Le
      Ny</a></dt>

      <dd>pela tradução para Francês</dd>

      <dt> <a href="mailto:glikely@nortelnetworks.com"> Grant
      Likely</a></dt>

      <dd>modificações gnome e ao motor</dd>

      <dt> <a href="mailto:martinh@pegasus.cc.ucf.edu"> Heath
      Martin</a></dt>

      <dd>maior parte do trabalho no registo em gnome</dd>

      <dt> <a href="mailto:mgmartin@abacusnet.net"> Matt
      Martin</a></dt>

      <dd>código de gestão de erros em guile</dd>

      <dt> <a href="mailto:rgmerk@mira.net"> Robert Graham
      Merkel</a></dt>

      <dd>modificações de relatórios, gnome, e de configuração.</dd>

      <dt> <a href="mailto:mooney@dogbert.cc.ndsu.NoDak.edu"> Tim
      Mooney</a></dt>

      <dd>porte para alpha-dec-osf4.0f</dd>

      <dt> <a href="mailto:gam3@ann.softgams.com"> G. Allen Morris
      III</a></dt>

      <dd>correcção do core dump do QIF</dd>

      <dt> <a href="mailto:brent@baton.phys.lsu.edu"> Brent Neal</a></dt>

      <dd>suporte TIAA-CREF no módulo perl Finance::Quote.</dd>

      <dt> <a href="mailto:spacey@inch.com"> Peter Norton</a></dt>

      <dd>pela valorosa tentativa de um porte GTK</dd>

      <dt> <a href="mailto:webmaster@obsidian.uia.net">
      OmNiBuS</a></dt>

      <dd>conteudo e gráficos do sítio web</dd>

      <dt> <a href="mailto:mopyr@IPM.Lviv.UA"> Myroslav
      Opyr</a></dt>

      <dd>por modificações várias</dd>

      <dt> <a href="mailto:laurent.pelecq@wanadoo.fr"> Laurent
      P{'e}lecq</a></dt>

      <dd>modificações de internacionalização com o gettext</dd>

      <dt> <a href="mailto:Alain.Peyrat@nmu.alcatel.fr"> Alain
      Peyrat</a></dt>

      <dd>pelas modificações ao <tt>configure.in</tt></dd>

      <dt> <a href="mailto:peter@wuzel.m.isar.de"> Peter
      Pointner</a></dt>

      <dd>modificações Motif e de configuração</dd>

      <dt> <a href="mailto:maufk@csv.warwick.ac.uk"> Gavin
      Porter</a></dt>

      <dd>pelas datas de estilo europeu</dd>

      <dt> <a href="mailto:rr@sco.com"> Ron Record</a></dt>

      <dd>pelos binários para SCO Unixware e OpenServer</dd>

      <dt> <a href="mailto:schoenberger@signsoft.com"> Dirk
      Schoenberger</a></dt>

      <dd>iniciou o porte Qt/KDE</dd>

      <dt> <a href="mailto:jan.schrage@urz.uni-heidelberg.de"> Jan
      Schrage</a></dt>

      <dd>modificações à documentação</dd>

      <dt> <a href="mailto:cls@seawood.org"> Christopher
      Seawood</a></dt>

      <dd>pela resolução do core dump no XbaeMatrix</dd>

      <dt> <a href="mailto:msimons@fsimons01.erols.com"> Mike
      Simons</a></dt>

      <dd>várias modificações ao <tt>configure.in</tt></dd>

      <dt> <a href="mailto:rich@brake.demon.co.uk"> Richard
      Skelton</a></dt>

      <dd>pela limpeza para Solaris</dd>

      <dt> <a href="mailto:spruth@bigfoot.com"> Henning
      Spruth</a></dt>

      <dd>pelo texto em Alemão e re-escrita das datas europeias</dd>

      <dt> <a href="mailto:parys@freewwweb.com"> Robby Stephenson</a></dt>

      <dd>modificação ao registo</dd>

      <dt> <a href="mailto:tma@iis.fhg.de"> Herbert Thoma</a></dt>

      <dd>registo gnome & e modificações de suporte ao euro</dd>

      <dt> <a href="mailto:detrout@earthlink.net"> Diane
      Trout</a></dt>

      <dd>modificação à importação QIF em scheme</dd>

      <dt> <a href="mailto:rkw@dataplex.net"> Richard Wackerbarth</a></dt>

      <dd>modificação ao gnc-prices</dd>

      <dt> <a href="mailto:rob@valinux.com"> Rob Walker</a></dt>

      <dd>modificações guile e ao registo</dd>

      <dt> <a href="mailto:dwmw2@infradead.org"> David Woodhouse</a></dt>

      <dd>traduções para Inglês Britânico</dd>

      <dt> <a href="mailto:gooch@ic.EECS.Berkeley.EDU"> Ken
      Yamaguchi</a></dt>

      <dd>correcções à importação QIF; importação MYM</dd>
    </dl>


</td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/footer.phtml"); ?>
