<?php $title = "Principal"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/menu/menu-main.phtml"); ?>

	</td>
  <td valign=top width=98%>
  
<h1>Bem Vindo ao GnuCash.org</h1>
  
<font size=-1>
Se tem andado à procura de uma forma de gerir as suas finanças pessoais em GNU/Linux, você encontrou-a! 
Concebido para ser fácil de utilizar, mas poderoso e flexível, o GnuCash permite-lhe acompanhar contas 
bancárias, acções, receitas e despesas. Tão rápido e intuitivo de utilizar como o registo de um livro 
de cheques, baseia-se em princípios profissionais de contabilidade para assegurar contas saldadas e 
relatórios precisos. O GnuCash é suportado por uma comunidade de programadores activa e está a evoluir 
para um completo sistema contabilístico. Desenvolvido sob a GPL, faz com que você não tenha de se preocupar 
com a obsolescência: o GnuCash stará lá sempre para si. 
<br><br>
O objectivo deste sítio web é promover o projecto Gnucash.org de desenvolvimento aplicacional. Estamos 
emprenhados em desenvolver ferramentas financeiras de topo para utilizadores do GNU/Linux e Unix. Isto 
inclui o desenvolvimento de APIs de programação e componentes que possam ser utilizados para criar tanto 
servidores como aplicações pessoais para utilização profissional e doméstica. Ao nos focarmos na facilidade 
de utilização, desenho modular, arquitectura de interfaces e código bem documentado, esperamos que o GnuCash 
e as bibliotecas financeiras associadas se tornem na escolha de uma geração de utilizadores e programadores GNU.
<br><br>
</font>

<h1>Notícias</h1>

       

<?php include ($GLOBALS['DOCUMENT_ROOT']."/php-scripts/news-script.php"); ?>

<font size=-2>
<a href="/surf/guppi-pie-demo.html">teste</a>
<a href="/surf/short.gml">teste2</a>
<a href="/surf/demo.gml">teste3</a>
</font>
                  

  </td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/footer.phtml"); ?>
