<?php $title = "Principal"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/menu/menu-main.phtml"); ?>

	</td>
  <td valign=top width=98%>
  
<h1>Bem Vindo ao GnuCash.org</h1>
  
<font size=-1>
Se tem andado à procura de uma forma de gerir as suas finanças pessoais em GNU/Linux, você encontrou-a! 
Concebido para ser fácil de utilizar, mas poderoso e flexível, o GnuCash permite-lhe acompanhar contas 
bancárias, acções, receitas e despesas. Tão rápido e intuitivo de utilizar como o registo de um livro 
de cheques, baseia-se em princípios profissionais de contabilidade para assegurar contas saldadas e 
relatórios precisos. O GnuCash é suportado por uma comunidade de programadores activa e está a evoluir 
para um completo sistema contabilístico. Desenvolvido sob a GPL, faz com que você não tenha de se preocupar 
com a obsolescência: o GnuCash stará lá sempre para si. 
<br><br>
O objectivo deste sítio web é promover o projecto Gnucash.org de desenvolvimento aplicacional. Estamos 
emprenhados em desenvolver ferramentas financeiras de topo para utilizadores do GNU/Linux e Unix. Isto 
inclui o desenvolvimento de APIs de programação e componentes que possam ser utilizados para criar tanto 
servidores como aplicações pessoais para utilização profissional e doméstica. Ao nos focarmos na facilidade 
de utilização, desenho modular, arquitectura de interfaces e código bem documentado, esperamos que o GnuCash 
e as bibliotecas financeiras associadas se tornem na escolha de uma geração de utilizadores e programadores GNU.
<br><br>
</font>

<h1>Notícias</h1>

       

<?php
    //  change  this  to  the  directory  of  your  news  files 
    //  they  should  be  plain  ASCII  text  files  with  extension  ".txt" 

    # Perhaps we should be using this, but it won't work until we have
    # the DocumentRoot set up.
    # $newspath = $GLOBALS['DOCUMENT_ROOT']."/news/

    # So we'll just do this for now...
    $newspath  =  "news/"; 

    //  Declare  array  to  hold  filenames 
    $newsfile  =  array(); 
    
    //  Create  handle  to  search  directory  $newspath  for  files 
    $hd  =  dir($newspath); 
    
    //  Get  all  files  and  store  them  in  array 
    while(  $filename  =  $hd->read()  )  { 
        $s=strtolower($filename); 
        if  (strstr($s, ".txt"))  { 
            //  Determine  last  modification  date 
            $lastchanged=filemtime($newspath.$filename); 
            $newsfile[$filename]  =  $lastchanged; 
        }    
    } 
    
    //  Sort  files  in  descending  order 
    arsort($newsfile); 
    //  Output  files  to  browser 
    for(reset($newsfile);  $key  =  key($newsfile);  next($newsfile))  
    { 
        $fa  =  file($newspath.$key); 
        $n=count($fa); 

        echo("<table border=0 cellpadding=1 cellspacing=0 width=\"100%\">");
        echo("<tr><td valign=middle align=center bgcolor=#666699>");
        echo("<table border=0 cellpadding=5 cellspacing=1 bgcolor=#cacaf7 width=\"100%\">");
        echo("<tr><td valign=top>");
        echo("<table border=0 cellpadding=0 cellspacing=0>");
        echo("<tr><td> <img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>");
       
        echo("<td>");
	print $fa[0];
	print  " - <font size=-1><b>(".date( "Y-m-d",$newsfile[$key]);
	print  "&nbsp; &nbsp;".date( "H:i:s",$newsfile[$key]). ")</b></font></td>\n"; 
        echo("</tr> </table> </td> </tr>");
        echo("<tr bgcolor=#ffffff> <td valign=top> <font size=-1>");

        for  ($i=1;  $i<$n;  $i=$i+1)  { 
	    print $fa[$i];
        } 
        echo("</font> </td> </tr> </table> </tr> </table><br><br>");

    }    
    
    $hd->close();  
    ?>  

<font size=-2>
<a href="/surf/guppi-pie-demo.html">teste</a>
<a href="/surf/short.gml">teste2</a>
<a href="/surf/demo.gml">teste3</a>
</font>
                  

  </td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/footer.phtml"); ?>
