<?php $title = "Aplicações Financeiras Relacionadas"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/menu/menu-other-main.phtml"); ?>
</td>


<td valign=top>
<h1>Aplicações Financeiras Relacionadas</h1>

<table>
<tr><td>
<b>Seleccione uma secção:</b></td>
<td>
<form method=post>
<select name=linkpage>
  <option value=general
  <?php if ($linkpage == "general") { echo ("selected"); } ?>
  >Referências Genéricas</option>
  <option value=utilities
  <?php if ($linkpage == "utilities") { echo ("selected"); } ?>
  >Utilitários</option>
  <option value=palm
  <?php if ($linkpage == "palm") { echo ("selected"); } ?>
  >Computação Palm</option>
  <option value=stock
  <?php if ($linkpage == "stock") { echo ("selected"); } ?>
  >Corretagem de Acções & Análise Técnica</option>
  <option value=quote
  <?php if ($linkpage == "quote") { echo ("selected"); } ?>
  >Fontes de Cotações, Ferramentas</option>
  <option value=erp
  <?php if ($linkpage == "erp") { echo ("selected"); } ?>
  >Empresas, Projectos ERP</option>
  <option value=xml
  <?php if ($linkpage == "xml") { echo ("selected"); } ?>
  >XML e Outros Formatos de Dados</option>
  <option value=misc
  <?php if ($linkpage == "misc") { echo ("selected"); } ?>
  >Vários</option>
  <option value=obsolete
  <?php if ($linkpage == "obsolete") { echo ("selected"); } ?>
  >Referências Históricas</option>
  <option value=review
  <?php if ($linkpage == "review") { echo ("selected"); } ?>
  >Sitios que Reviram & Avaliaram o GnuCash</option>
</select>
<input type=submit value=Go>
</td>
</table>
</form>

<?php
  if ($linkpage != "") { 
	include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/links/links-".$linkpage.".phtml");
  } else {
	include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/links/links-general.phtml");
  }
?>


</td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/footer.phtml"); ?>
