<?php $title = "Listas de E-Mail"; ?>
<?php if (!ini_get('register_globals')) {
 include("../emulate_globals_on.php");
}
?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/menu/menu-developer-main.phtml"); ?>
</td>

<td valign=top>
<h1>Listas de E-Mail do GnuCash</h1>

Existem algumas listas de e-mail do GnuCash servindo comunidades 
distintas: alguma spara utilizadores outra para programadores.  Prima 
sobre o texto a negrito para instruções sobre como a subscrever ou desistir.

<p>

<table border=0 cellpadding=1 cellspacing=0 width="100%">
  <tr>
  <td valign=middle align=center bgcolor=#666699>
   <table border=0 cellpadding=5 cellspacing=1 bgcolor=#cacaf7 width="100%">
   <tr>
     <td bgcolor=#666699 width=25%><font color=#ffffff><b>Lista de E-Mail</b></td>
     <td bgcolor=#666699 width=75%><font color=#ffffff><b>Descrição</b></td>
   </tr>
   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><A HREF="https://lists.gnucash.org/mailman/listinfo/gnucash-announce"> gnucash-announce@gnucash.org</A></td>
       </tr>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><A HREF="/pipermail/gnucash-announce"> Archives</A></td>
       </tr>
       </table>
     </td>
     <td valign=top>Lista de e-mail de anúncios: Mensagens nesta lista moderada anunciam 
		     eventos importantes e notícias relacionadas com o GnuCash.
		     Esta é uma lista de pouco tráfego (1 ou menos mensagens por semana).</td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><A HREF="https://lists.gnucash.org/mailman/listinfo/gnucash-user"> gnucash-user@gnucash.org</A></td>
       </tr>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><A HREF="/pipermail/gnucash-user"> Archives</A></td>
       </tr>
       </table>
     </td>
     <td valign=top>
    Lista de E-Mail dos Utilizadores: Discussões sobre como instalar, configurar e 
    utilizar o GnuCash, e debates sobre assuntos tais como princípios contabilísticos 
    básicos. Esta é ocasionalmente uma lista com muito tráfego (2 a 30 mensagens por dia).
	   </td>
   </tr>
   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><A HREF="https://lists.gnucash.org/mailman/listinfo/gnucash-devel"> gnucash-devel@gnucash.org</A></td>
       </tr>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><A HREF="/pipermail/gnucash-devel"> Archives</A></td>
       </tr>
       </table>
     </td>
     <td valign=top>
    Lista de E-Mail dos programadores: Discussões sobre as actuais e futuras 
    características e funcionalidades, e como deverão ser implementadas.  
    Esta é ocasionalmente uma lista com muito tráfego (2 a 30 mensagens por dia).
		 </td>
   </tr>

   <!-------------------------------------------------------------->
   <tr bgcolor="#ffffff">
     <td valign="top">
       <table border="0" cellpadding="0" cellspacing="0">
       <tr>
         <td valign="top"><img src="/images/icons/document.txt.gif" width="16" height="16" border="0">&nbsp;</td>
         <td valign="top"><A HREF="https://lists.gnucash.org/mailman/listinfo/gnucash-de"> gnucash-de@gnucash.org</A></td>
       </tr>
       <tr>
         <td valign="top"><img src="/images/icons/document.txt.gif" width="16" height="16" border="0">&nbsp;</td>
         <td valign="top"><A HREF="/pipermail/gnucash-de"> Archives</A></td>
       </tr>
       </table>
     </td>
     <td valign="top">
     Dies ist die Mailingliste für deutsche GnuCash-Benutzer. 
     Die Sprache auf dieser Liste ist Deutsch.
     
	   </td>
   </tr>
   <!-------------------------------------------------------------->
   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><A HREF="https://lists.gnucash.org/mailman/listinfo/gnucash-es"> gnucash-es@gnucash.org</A></td>
       </tr>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><A HREF="/pipermail/gnucash-es"> Archives</A></td>
       </tr>
       </table>
     </td>
     <td valign=top>
     gnucash-es es la lista de distribución del proyecto GnuCash en español.
     Está lista está pensada para usuarios finales y colaboradores en la
     traducción y localización de GnuCash.
     
	   </td>
   </tr>
   <!-------------------------------------------------------------->
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><A HREF="https://lists.gnucash.org/mailman/listinfo/gnucash-fr"> gnucash-fr@gnucash.org</A></td>
       </tr>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><A HREF="/pipermail/gnucash-fr"> Archives</A></td>
       </tr>
       </table>
     </td>
     <td valign=top>
     Vous avez essayé GnuCash. Cela vous plaît vraiment mais vous aimeriez
     obtenir de l'aide dans votre langue pour plus de simplicité. Cette mailing
     liste est faite pour vous. Elle va permettre de rester en contact avec des
     personnes francophones utilisant GnuCash qui pourront vous guider dans son
     utilisation quotidienne aussi bien que pour une utilisation professionnelle.
     Elle permettra aussi aux personnes réfractaire à la langue de shakespeare
     de rester au courant des derniers développements du logiciels.

	   </td>
   </tr>
   <!-------------------------------------------------------------->
   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><A HREF="https://lists.gnucash.org/mailman/listinfo/gnucash-it"> gnucash-it@gnucash.org</A></td>
       </tr>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><A HREF="/pipermail/gnucash-it"> Archives</A></td>
       </tr>
       </table>
     </td>
     <td valign=top>
     gnucash-it è la lista di distribuzione per il progetto GnuCash in lingua
     italiana. Quando la propria lingua madre è l'italiano e l'inglese
     rappresenta un ostacolo, quando si ha intenzione di contribuire alla
     localizzazione (l10n) ed internazionalizzazione (i18n) italiana del
     progetto, quando si vuole incontrare qualche italiano per parlare di
     GnuCash, questa lista di distribuzione è il luogo adatto per inviare i
     propri messaggi.
     <p>
     gnucash-it è nata per offrire ai traduttori di GnuCash un valido mezzo
     di comunicazione.  Successivamente spera di diventare il punto
     d'incontro per tutti coloro i quali vogliano contribuire al progetto sia
     in qualità traduttori, revisori e programmatori per la realtà italiana,
     sia di esperti in grado di aiutare chi si trova alle prime armi.
	   </td>
   </tr>
   <!-------------------------------------------------------------->
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><A HREF="https://lists.gnucash.org/mailman/listinfo/gnucash-patches"> gnucash-patches@gnucash.org</A></td>
       </tr>
       </table>
     </td>
     <td valign=top>
    Lista de E-Mail dos programadores: Entrega e discussão de alterações ao 
    código, e notificações sobre actualizações à árvore de CVS.  
    Alterações deverão estar no formato <tt>makepatch</tt>.
    As alterações podem ser sobre código fonte, documentação, ou traduções 
    para idiomas estrangeiros.
    Esta é ocasionalmente uma lista com muito tráfego (2 a 30 mensagens por dia).
    
	   </td>
   </tr>
   </table>
</tr>
</table>

</td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/footer.phtml"); ?>
