<?php $title = "Listas de E-Mail"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/menu/menu-developer-main.phtml"); ?>
</td>

<td valign=top>
<h1>Listas de E-Mail do GnuCash</h1>

Existem algumas listas de e-mail do GnuCash servindo comunidades 
distintas: alguma spara utilizadores outra para programadores.  Prima 
sobre o texto a negrito para instruções sobre como a subscrever ou desistir.

<p>

<table border=0 cellpadding=1 cellspacing=0 width="100%">
  <tr>
  <td valign=middle align=center bgcolor=#666699>
   <table border=0 cellpadding=5 cellspacing=1 bgcolor=#cacaf7 width="100%">
   <tr>
     <td bgcolor=#666699 width=25%><font color=#ffffff><b>Lista de E-Mail</b></td>
     <td bgcolor=#666699 width=75%><font color=#ffffff><b>Descrição</b></td>
   </tr>
   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><A HREF="http://www.gnumatic.com/cgi-bin/mailman/listinfo/gnucash-announce"> gnucash-announce@gnucash.org</A></td>
       </tr>
       </table>
     </td>
     <td valign=top>Lista de e-mail de anúncios: Mensagens nesta lista moderada anunciam 
		     eventos importantes e notícias relacionadas com o GnuCash.
				     Esta é uma lista de pouco tráfego (1 ou menos mensagens por semana).</td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><A HREF="http://www.gnumatic.com/cgi-bin/mailman/listinfo/gnucash-user"> gnucash-user@gnucash.org</A></td>
       </tr>
       </table>
     </td>
     <td valign=top>
    Lista de E-Mail dos Utilizadores: Discussões sobre como instalar, configurar e 
    utilizar o GnuCash, e debates sobre assuntos tais como princípios contabilísticos 
    básicos. Esta é ocasionalmente uma lista com muito tráfego (2 a 30 mensagens por dia).
	   </td>
   </tr>
   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><A HREF="http://www.gnumatic.com/cgi-bin/mailman/listinfo/gnucash-devel"> gnucash-devel@gnucash.org</A></td>
       </tr>
       </table>
     </td>
     <td valign=top>
    Lista de E-Mail dos programadores: Discussões sobre as actuais e futuras 
    características e funcionalidades, e como deverão ser implementadas.  
    Esta é ocasionalmente uma lista com muito tráfego (2 a 30 mensagens por dia).
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><A HREF="http://www.gnumatic.com/cgi-bin/mailman/listinfo/gnucash-patches"> gnucash-patches@gnucash.org</A></td>
       </tr>
       </table>
     </td>
     <td valign=top>
    Lista de E-Mail dos programadores: Entrega e discussão de alterações ao 
    código, e notificações sobre actualizações à árvore de CVS.  
    Alterações deverão estar no formato <tt>makepatch</tt>.
    As alterações podem ser sobre código fonte, documentação, ou traduções 
    para idiomas estrangeiros.
    Esta é ocasionalmente uma lista com muito tráfego (2 a 30 mensagens por dia).
    
	   </td>
   </tr>
   </table>
</tr>
</table>

</td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/footer.phtml"); ?>
