
<?php $title = "Accounting Software for Linux"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/menu/menu-main.phtml"); ?>

	</td>
  <td valign=top width=98%>
  

<h1>Older Announcements</h1>

<font size=-1>
This is an archive of announcements that once appeared on the 
GnuCash home page.
<br><br>
</font>

<?php
    # indicate where to get translated news from ... 
    $native_newspath  =  "news/old/";
    $alt_newspath  =  "../news/old/";
    include($GLOBALS['DOCUMENT_ROOT']."/php-scripts/news-script.php");
    ?>  

  </td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/footer.phtml"); ?>

