<?php $title = "Promover o GnuCash"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/menu/menu-other-main.phtml"); ?>
</td>

<td valign=top>
<b>Promover o GnuCash</b><br><br>

Deseja demonstrar o seu apoio ao GnuCash?  Exponha uma destas imagens 
na sua página.
<p>

<a href="/images/banners/control_your_finan.jpg">
<img src="/images/banners/control_your_finan.jpg"
     alt="[Controle as suas Finanças com a força do Código Aberto - GnuCash]">
<br clear>
125 x 125 pixels</a>
<p>

<a href="/images/banners/gnucash_dollar_button.jpg">
<img src="/images/banners/gnucash_dollar_button.jpg"
     alt="[Aplicação de Finanças Pessoais Gnucash]">
<br clear>
125 x 125 pixels</a>
<p>

<a href="/images/banners/GnuCash_Long.jpg">
<img src="/images/banners/GnuCash_Long.jpg"
     alt="[Aplicação de Finanças Pessoais Gnucash]">
<br clear>
470 x 62 pixels</a>
<p>

<a href="/images/banners/gnu_bill.gif">
<img src="/images/banners/gnu_bill.gif"
     alt="[Nota de Dólar E.U.A. c/ o Gnu do Stallman]">
<br clear>
350 x 147 pixels</a>
<p>

<a href="/images/banners/gnucash.jpg">
<img src="/images/banners/gnucash.jpg"
     alt="[letras brancas de máquina de escrever sobre fundo preto]">
<br clear>
256 x 53 pixels</a>
<p>

<a href="/images/banners/gnucash_brown.jpg">
<img src="/images/banners/gnucash_brown.jpg"
     alt="[letras pretas de máquina de escrever c/ silhueta sobre fundo castanho]">
<br clear>
256 x 53 pixels</a>
<p>

<a href="/images/banners/gnucash_light.jpg">
<img src="/images/banners/gnucash_light.jpg"
     alt="[letras pretas de máquina de escrever sobre fundo castanho claro]">
<br clear>
256 x 53 pixels</a>
<p>

<a href="/images/banners/gnucash_white.jpg">
<img src="/images/banners/gnucash_white.jpg"
     alt="[letras pretas de máquina de escrever sobre fundo branco]">
<br clear>
256 x 53 pixels</a>
<p>

<a href="/images/banners/gnucash_techno.gif">
<img src="/images/banners/gnucash_techno.gif"
     alt="[tipo de letra moderno tecno/scifi sobre fundo liso]">
<br clear>
400 x 100 pixels</a>
<p>

<a href="/images/banners/logo_beatnik.gif">
<img src="/images/banners/logo_beatnik.gif"
     alt="[tipo de letra beatnik c/ silhuetas sobre fundo castanho]">
<br clear>
287 x 88 pixels</a>
<p>

<a href="/images/banners/logo_elegant.jpg">
<img src="/images/banners/logo_elegant.jpg"
     alt="[tipo de letra elegante em preto sobre fundo castanho]">
<br clear>
287 x 88 pixels</a>
<p>


</td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/footer.phtml"); ?>

