<?php $title = "Requisitos Aplicacionais"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/menu/menu-general-main.phtml"); ?>
</td>

<td valign=top>

<h1>Requisitos Aplicacionais</h1>

Estas são as tecnologias mais importantes que contribuem para o GnuCash 
e de que este depende para implementar as suas principais funcionalidades.  
Terá de instalar uma versão recente destas para compilar e trabalhar com o gnucash.
<br><br>


<table border=0 cellpadding=1 cellspacing=0 width="100%">
  <tr>
  <td valign=middle align=center bgcolor=#666699>
   <table border=0 cellpadding=5 cellspacing=1 bgcolor=#cacaf7 width="100%">
   <tr>
     <td bgcolor=#666699 width=25%><font color=#ffffff><b>Nome</b></td>
     <td bgcolor=#666699 width=50%><font color=#ffffff><b>Descrição</b></td>
     <td bgcolor=#666699 width=25%><font color=#ffffff><b>Endereço</b></td>
   </tr>
   <tr>
           <td colspan=3>
<B>Conjuntos de Ferramentas de Interface:</B><BR>
     </td>
         </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>Gtk+</td>
       </tr>
       </table>
     </td>
     <td valign=top>O Conjunto de Ferramentas Gimp</td>
     <td valign=top><a href="http://www.gtk.org/">http://www.gtk.org/</a></td>
   </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>Gnome</td>
       </tr>
       </table>
     </td>
     <td valign=top>A infraestrutura da aplicação</td>
     <td valign=top><a href="http://www.gnome.org">http://www.gnome.org</a></td>
   </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>Glade</td>
       </tr>
       </table>
     </td>
     <td valign=top>Construtor de Interfaces Gráficos GTK+ - É desta forma que muitas janelas do gnucash são criadas.</td>
     <td valign=top><a href="http://glade.pn.org">http://glade.pn.org</a></td>
   </tr>

   <tr>
           <td colspan=3>
       <B>Interface de Scripting:</B><BR>
     </td>
         </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>Guile</td>
       </tr>
       </table>
     </td>
     <td valign=top>Um interpretador Scheme com interfaces de programação C - É desta forma que o gnucash disponibiliza 'extensões' e capacidades de desenvolvimento rápido</td>
     <td valign=top><a href="http://www.gnu.org/software/guile/guile.html">http://www.gnu.org/software/guile/guile.html</a></td>
   </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>G-wrap</td>
       </tr>
       </table>
     </td>
     <td valign=top>Uma ferramenta para gerar automaticamente conecções scheme para funções, estruturas & enums. em linguagem C</td>
     <td valign=top><a href="#">Sem Endereço</a></td>
   </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>Scheme</td>
       </tr>
       </table>
     </td>
     <td valign=top>A Linguagem Scheme</td>
     <td valign=top><a href="http://www.scheme.org/">http://www.scheme.org/</a></td>
   </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>slib</td>
       </tr>
       </table>
     </td>
     <td valign=top>Biblioteca Scheme - Várias funções scheme utilizadas pelo GnuCash.</td>
     <td valign=top><a href="http://www-swiss.ai.mit.edu/~jaffer/SLIB.html">http://www-swiss.ai.mit.edu/~jaffer/SLIB.html</a></td>
   </tr>

   <tr>
           <td colspan=3>
       <B>Infraestrutura Web:</B><BR>
     </td>
         </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>GtkHTML</td>
       </tr>
       </table>
     </td>
     <td valign=top>O motor de visualização html do gtk - utilizada pelo gnucash para mostrar documentação de ajuda, relatórios e gráficos.</td>
     <td valign=top><a href="http://www.advogato.org/proj/GtkHTML/">http://www.advogato.org/proj/GtkHTML/</a></td>
   </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>libghttp</td>
       </tr>
       </table>
     </td>
     <td valign=top>A biblioteca HTTP library - utilizada pelo gnucash para falar no protocolo http para aceder a servidores web.</td>
     <td valign=top><a href="http://www.gnome.org/">http://www.gnome.org/</a></td>
   </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>Gnome XML</td>
       </tr>
       </table>
     </td>
     <td valign=top>A biblioteca de parseamento XML - utilizada pelo gnucash para ler o seu formato de ficheiro.</td>
     <td valign=top><a href="http://xmlsoft.org/">http://xmlsoft.org/</a></td>
   </tr>

   <tr>
           <td colspan=3>
       <B>Outras:</B><BR>
     </td>
         </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>Finance::Quote</td>
       </tr>
       </table>
     </td>
     <td valign=top>Um módulo em perl para obter na internet cotações de acções e taxas câmbios de moedas - É assim que o gnucash acede a dados de cotações na net.</td>
     <td valign=top><a href="http://finance-quote.sourceforge.net/">http://finance-quote.sourceforge.net/</a></td>
   </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>Finance::QuoteHist</td>
       </tr>
       </table>
     </td>
     <td valign=top>Um módulo em perl para obter históricos de valores de cotações.</td>
     <td valign=top><a href="http://sourceforge.net/project/?group_id=2403">http://sourceforge.net/project/?group_id=2403</a></td>
   </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>Guppi</td>
       </tr>
       </table>
     </td>
     <td valign=top>Uma ferramenta de desenho gráfico e de análise - utilizada para gerar e mostrar os gráficos e histogramas no gnucash.</td>
     <td valign=top><a href="http://www.gnome.org/guppi/">http://www.gnome.org/guppi/</a></td>
   </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>Gnome Print</td>
       </tr>
       </table>
     </td>
     <td valign=top>Arquitectura de impressão gnome - utilizada pelo gnucash para a impressão de cheques & impressão geral.</td>
     <td valign=top><a href="http://www.sourceforge.net/projects/gnome-print/">http://www.sourceforge.net/projects/gnome-print/</a></td>
   </tr>

   </table>
</tr>
</table>



</td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/footer.phtml"); ?>
