
<div class="newsborder">
<div class="newsheader"><img alt="news panel" 
src="images/icons/document.txt.gif">&nbsp;
<?php echo _("<b>Announcement:</b> GnuCash 1.9.0 Release");?>
<b> (
2006-02-09   05:19:32
)</b>
</div><div class="newsinner">
<br><?php echo _("The GnuCash development team proudly announces GnuCash 1.9.0 aka \"We're gonna make it!\", the first of several unstable 1.9.x releases of the GnuCash Open Source Accounting Software which will eventually lead to the stable version 2.0.0. This release is the very first of the gtk2-based GnuCash series, and is intended for developers and adventurous testers who want to help tracking down all those bugs that are still in there.");?>
<br>
<br>

<b><big><?php echo _("What's New in GnuCash 1.9.0?");?></big></b><br>
<?php
echo " o " . _("Welcome to GnuCash 1.9.0 aka \"We're gonna make it!\" the first of several unstable releases of the GnuCash Open Source Accounting Software which will eventually lead to the stable version 2.0.0. This release is the very first of the gtk2-based GnuCash series and is intended for developers and adventurous testers who want to help tracking down bugs.") . "<br>";
echo " o " . _("WARNING WARNING WARNING - Make sure you make backups of any files used in testing versions of GnuCash in the 1.9.x series. Although the developers go to great lengths to ensure that no data will be lost we cannot guarentee that your data will not be affected if for some reason GnuCash crashes in testing these releases.") . "<br>";
echo " o " . _("PLEASE TEST TEST AND TEST SOME MORE any and all features important to you. Then post any bugs you find to bugzilla http://bugzilla.gnome.org/enter_bug.cgi?product=GnuCash") . "<br>";
echo " o " . _("If you have the urge to help beyond testing please get involved in the discussions on the GnuCash mailing lists which you will find at http://www.gnucash.org. We especially need people to help with updating the documentation as all texts refer currently to the 1.8.x series. Please see http://wiki.gnucash.org/wiki/Development on how to get involved.") . "<br>";
echo " o " . _("PS I'm not going to list the many features changed or updated in this release because obviously there is so much that has changed.") . "<br>";?>

<h2><?php echo _("Caveats");?></h2>
<p><?php echo _("Caveats for testers:");?></p>
<ul><li><?php echo _("Any 1.9.x version might <i>crash unexpectedly at any point</i> during runtime. If you test some serious work in a 1.9.x release, make sure you hit \"Save\" after ever non-trivial workstep.");?>
</li><li><?php echo _("Keep in mind that features which are not used in everyday work might crash unexpectedly at all times. This includes but is not limited to: graphical reports, scheduled transaction editor, price editor, financial calculator, OFX/QIF/HBCI import.");?>
</li><li><?php echo _("Especially all the <i>new features</i> might crash instantly on testing. This applies in particular to any of the budget-related features. We may always decide to disable such new features for the initial 2.0.0 release, and re-enable them in a later release.");?>
</li><li><?php echo _("The <i>documentation is completely outdated</i>. All help texts usually only refer to the 1.8.x series; please expect all descriptions in the help texts to be totally wrong when applied to the upcoming 1.9.x series. Everyone is invited to help improve the documentation; see <a href=\"http://wiki.gnucash.org/wiki/Development\" title=\"http://wiki.gnucash.org/wiki/Development\">http://wiki.gnucash.org/wiki/Development</a> on how to get
involved.");?>
</li></ul>
<h2><?php echo _("How can you help?");?></h2>
<ul><li><?php echo _("Testing: Test it and help us discover all bugs that might show up in there. Please enter each and every bug into bugzilla at ");?>
<a href="http://bugzilla.gnome.org/enter_bug.cgi?product=GnuCash" title="http://bugzilla.gnome.org/enter bug.cgi?product=GnuCash">http://bugzilla.gnome.org/enter_bug.cgi?product=GnuCash</a>
</li><li><?php echo _("Translating: The new release comes with plenty of new translation strings. If you consider contributing a translation, we invite you to test this release already, but please keep in mind that we are not yet in our string freeze phase. Please check <a
href=\"http://wiki.gnucash.org/wiki/Translation_Status\" title=\"http://wiki.gnucash.org/wiki/Translation Status\">http://wiki.gnucash.org/wiki/Translation_Status</a> for updates on this, as we recommend to wait for the string freeze phase for the serious translation work.");?>
</li></ul>


<br><br>
<?php echo _("Available at the usual places!");?>

<br><br>
<b><a href="http://www.gnucash.org/pub/gnucash/">http://www.gnucash.org</a></b>
</div>
</div>
