<! BEGIN HEADER>

<HTML>
<HEAD>
<?php

if($TITLE)
    print "<TITLE>$TITLE</TITLE>";
else
    print "<TITLE>GnuCash!</TITLE>";

?>
<STYLE TYPE="text/css">
<!-- 
        A:link {text-decoration:none}
        A:visited{text-decoration:none}
        A:active{text-decoration:none}

//-->
</STYLE>
<meta name="description" content="GnuCash personal financial software for Linux is easy to use and provides powerful features."
<meta name="keywords" content="Financial, Money, Accounting, Finance, Software, Quicken, MSMoney, Peachtree, Linux, GPL">
</HEAD>

<BODY BGCOLOR="#8b7765" TEXT="#000000" LINK="#666a1b" VLINK="#b76767">

<! END HEADER>

<CENTER>
<IMG SRC="images/newlogo.gif">
</CENTER>

<BR>

<CENTER>
<TABLE WIDTH=800>
  <TR>
    <TD WIDTH=200 VALIGN=TOP>

      <?php include("include/links.inc"); ?>
       
    </TD>
    <TD WIDTH=550 VALIGN=TOP>

