<! BEGIN LINKS >

      <?php include("include/table_top.inc") ?>
       general information
      <?php include("include/table_middle.inc") ?>
      
        &nbsp;- <A HREF="/">About GnuCash</A><BR>
        &nbsp;- <A HREF="http://www.multimania.com/yleny/gnucash/" ALT="En Francais">Gnucash en Français</A><BR>
        &nbsp;- <A HREF="gnome_screenshots.php3" ALT="Screen Shots">Screenshots</A><BR>
        &nbsp;- <A HREF="features.php3" ALT="Features">Features</A><BR>
        &nbsp;- <A HREF="http://www.linas.org/pub/">Download</A><BR>
        &nbsp;- <A HREF="http://www.gnucash.org/pub/">Download (slow, use above)</A><BR>
        &nbsp;- <A HREF="http://download.sourceforge.net/gnucash/">Download (mirror)</A><BR>
        <P>
      <?php include("include/table_bottom.inc") ?>

      <?php include("include/table_top.inc") ?>
      developer information
      <?php include("include/table_middle.inc") ?>
         &nbsp;- <A HREF="architecture.php3">System Architecture</A><BR>
         &nbsp;- <A HREF="http://linas.org/linux/xacc/projects.html">Project Goals</A><BR>
         <!-- &nbsp;- <A HREF="/cgi-bin/bugtrack">Gnucash Bug Tracker</A><BR> -->
         &nbsp;- <A HREF="developers.php3">Developers</A><BR>
         &nbsp;- <A HREF="maillist.php3">Mailing List&nbsp;-&nbsp;Help</A><BR>
         &nbsp;- <A HREF="archives.php3">Mailing List&nbsp;-&nbsp;Archives</A><BR>
         &nbsp;- <A HREF="source_code.php3">Getting Source Code</A>
         <P>
      <?php include("include/table_bottom.inc") ?>

      <?php include("include/table_top.inc") ?>
       other information
      <?php include("include/table_middle.inc") ?>
         &nbsp;- <A HREF="links.php3">Links</A> <BR>
         &nbsp;- <A HREF="articles.php3" ALT="Articles">Gnucash in the news!</A><BR>
         &nbsp;- <A HREF="/docs">Documentation</A> <BR>
         <P>
      <?php include("include/table_bottom.inc") ?>

      <?php include("include/table_top.inc") ?>
       search gnucash.org 
      <?php include("include/table_middle.inc") ?>
       <center>
       <form action="/search.php3" method="get">
       <input type=text name=words size=15>
       <br><font size="-2">Sort method:</font>
       <select name="sort">
       <option value="sort">Standard
       <option value="time">Time
       <option value="revtime">Time (reversed)
       </select>
       </form>
      <?php include("include/table_bottom.inc") ?>

<! END LINKS > 
