<! BEGIN LINKS >

      <?php include("include/table_top.inc") ?>
       general information
      <?php include("include/table_middle.inc") ?>
      
        &nbsp;- <A HREF="/">GnuCash Home Page</A><BR>
        &nbsp;- <A HREF="features.php3">Features</A><BR>
        &nbsp;- <A HREF="gnome_screenshots.php3">Screenshots</A><BR>
        &nbsp;- <A HREF="http://www.multimania.com/yleny/gnucash/">GnuCash en Français</A><BR>
        &nbsp;- <A HREF="http://www.hthoma.de/projekte/gnucash/index.html">GnuCash auf deutsch</A><BR>
        &nbsp;- <A HREF="http://www.linas.org/pub/gnucash/">Download</A><BR>
        &nbsp;- <A HREF="http://www.gnucash.org/pub/">Download (mirror)</A><BR>
	<!--
        &nbsp;- <A HREF="http://download.sourceforge.net/gnucash/">Download (incomplete mirror)</A><BR>
	-->
        <P>
      <?php include("include/table_bottom.inc") ?>

      <?php include("include/table_top.inc") ?>
      developer information
      <?php include("include/table_middle.inc") ?>
         &nbsp;- <A HREF="architecture.php3">System Architecture</A><BR>
         &nbsp;- <A HREF="tools.php3">Required Toolkits</A><BR>
         &nbsp;- <A HREF="http://linas.org/linux/gnucash/projects.html">Project Goals</A><BR>
         &nbsp;- <A HREF="contribute.php3">How to Contribute</A><BR>
         <!-- &nbsp;- <A HREF="/cgi-bin/bugtrack">Gnucash Bug Tracker</A><BR> -->
         &nbsp;- <A HREF="maillist.php3">Mailing List&nbsp;-&nbsp;Help</A><BR>
         &nbsp;- <A HREF="archives.php3">Mailing List&nbsp;-&nbsp;Archives</A><BR>
         <!-- &nbsp;- <A HREF="ChangeLog-1.4">ChangeLog for version 1.4</A><BR>
         &nbsp;- <A HREF="ChangeLog-1.5">ChangeLog for version 1.5</A><BR>
	 -->
         &nbsp;- <A HREF="http://bugs.gnome.org/db/pa/lgnucash.html">Gnome Trouble Tickets</A><BR>
         &nbsp;- <A HREF="/lxr/">LXR source code broswer</A><BR>
         &nbsp;- <A HREF="source_code.php3">Hacking GnuCash</A>
         <P>
      <?php include("include/table_bottom.inc") ?>

      <?php include("include/table_top.inc") ?>
       other information
      <?php include("include/table_middle.inc") ?>
         &nbsp;- <A HREF="links.php3">Related Financial Software</A> <BR>
         &nbsp;- <A HREF="articles.php3" ALT="Articles">Gnucash in the news!</A><BR>
         &nbsp;- <A HREF="/docs/C/index.html">Documentation - English</A> <BR>
         &nbsp;- <A HREF="/docs/fr/xacc-main.html">Documentation - Français</A> <BR>
         &nbsp;- <A HREF="/banners.php3">Banner Ads</A> <BR>
         &nbsp;- <A HREF="developers.php3">History and Credits</A><BR>
         &nbsp;- <A HREF="http://www.gnumatic.com/">Gnumatic - Corporate Support</A> <BR>
         <P>
      <?php include("include/table_bottom.inc") ?>

      <?php include("include/table_top.inc") ?>
       search gnucash.org 
      <?php include("include/table_middle.inc") ?>
       <center>
       <form action="/search.php3" method="get">
       <input type=text name=words size=15>
       <br><font size="-2">Sort method:</font>
       <select name="sort">
       <option value="sort">Standard
       <option value="time">Time
       <option value="revtime">Time (reversed)
       </select>
       </form>
      <?php include("include/table_bottom.inc") ?>

<! END LINKS > 
