<?php $title = "Accounting Software for Linux"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-main.phtml"); ?>

	</td>
  <td valign=top width=98%>
  
<h1>GnuCash T-Shirts!</h1>
  
<font size=-1>
We have some left-over t-shirts from prior trade shows; approximately
a dozen in a mix of M, L and XL sizes.  We'd like to sell them: they're
$15.00 each with shipping & handling included for USA addresses. If you 
are overseas, write us, we'll have to figure out the shipping costs.
<br><br>
The back of the t-shirt shows this logo:
<br>
<img src="t-shirt-back-small.gif">
<br><br>
The front of the shirt has a left breast plate in black-n-white:
<br>
<img src="t-shirt-front-small.gif">
<br><br>
If you are interested, please drop an e-mail to 
<a href="mailto:sales@gnumatic.com">sales@gnumatic.com</a>
to reserve a shirt.  Be sure to indicate the size.  Then make
out a check to "Gnumatic Incorporated" for $15.00, and mail it to:
<br><br>
<br>Gnumatic Incoporated
<br>632B N. Lamar Blvd
<br>Austin TX 78703
<br><br>
If you want us to accept a credit card, let us know.  We are not set 
up for these.  We could have listed these on ebay, but didn't.
<br><br>
If you have bright ideas for how to use gnucash to automate this 
process, let us know.  If you can recommend a web-based 'shopping cart'
for this, let us know.  In the meanwhile, we're working on it.




<br><br>
</font>


  </td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/footer.phtml"); ?>
