<?php $title = "GnuCash T-Shirt Offer"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-main.phtml"); ?>

	</td>
  <td valign=top width=98%>
  
<h1>GnuCash T-Shirts!</h1>
  
<font size=-1>
We have some left-over t-shirts from prior trade shows; approximately
a dozen in a mix of M, L and XL sizes.  We'd like to sell them: they're
$15.00 each with shipping & handling included for USA addresses. If you 
are overseas, write us, we'll have to figure out the shipping costs.
<br><br>
The back of the t-shirt shows this logo:
<br>
<img src="t-shirt-back-small.gif">
<br><br>
The front of the shirt has a left breast plate in black-n-white:
<br>
<img src="t-shirt-front-small.gif">
<br><br>
If you are interested, please drop an e-mail to 
<a href="mailto:sales@gnumatic.com">sales@gnumatic.com</a>
to reserve a shirt.  Be sure to indicate the size.  Then make
out a check to "Gnumatic Incorporated" for $15.00, and mail it to:
<br><br>
<br>Gnumatic Incoporated
<br>632B N. Lamar Blvd
<br>Austin TX 78703
<br><br>
If you want us to accept a credit card, let us know.  We are not set 
up for these.  We could have listed these on ebay, but didn't.
<br><br>
If you have bright ideas for how to use gnucash to automate this 
process, let us know.  If you can recommend a web-based 'shopping cart'
for this, let us know.  In the meanwhile, we're working on it.
<br><br>

Alternate payment techniques:
<h3>Pay with Pay-Pal</h3>
<img src="paypal_logo.gif" align=right>
Just pay use <a href="http://www.paypal.com">paypal</a> to 
pay sales@gnumatic.com

<h3>Pay With e-gold</h3>

<img src="e-gold-logo.gif" align=right>
<form action="https://www.e-gold.com/sci_asp/payments.asp" method="POST" target=_top>
  <input type="hidden" name="PAYEE_ACCOUNT" value="281678">
   <input type="hidden" name="PAYEE_NAME" value="Gnumatic Incorporated">
Pay 
<input type=text value="15.00" name="PAYMENT_AMOUNT" size=5>
<input type=hidden name="PAYMENT_UNITS" value=1>
   USD worth of e-gold per t-shirt
<input type=hidden name="PAYMENT_METAL_ID" value=1>
<input type="hidden" name="STATUS_URL" value="mailto:sales@gnumatic.com">
<input type="hidden" name="NOPAYMENT_URL" 
   value="http://www.gnucash.org/en/t-shirt/thanks.phtml">
<input type="hidden" name="NOPAYMENT_URL_METHOD" value="LINK">
<input type="hidden" name="PAYMENT_URL" 
   value="http://www.gnucash.org/en/t-shirt/thanks.phtml">
<input type="hidden" name="PAYMENT_URL_METHOD" value="LINK">
<input type="hidden" name="BAGGAGE_FIELDS" value="CUSTOMERID">
<input type="hidden" name="CUSTOMERID" value="0">
<input type="hidden" name="SUGGESTED_MEMO" value='GnuCash T-Shirt Offer (e-gold)'>
<input type="submit" name="PAYMENT_METHOD" value="Pay Now">
</form> 
(Even if you have no intention of paying with e-gold, you can click 
the button above to see what happens.  Nothing happens until you 
open an account with e-gold, and even then, you'll have to specify 
your account number and passphrase to pay.)



<br><br>
</font>


  </td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/footer.phtml"); ?>
