<%

global gui
set gui(list) [list gtk gnome glade]
set gui(columns) [list name description link]

$gui['gtk:name'] = "Gtk+"
set gui(gtk:name) "Gtk+"
set gui(gtk:description) "The Gimp Toolkit"
set gui(gtk:link) "http://www.gtk.org/"

set gui(gnome:name) "Gnome"
set gui(gnome:description) "The application infrastructure"
set gui(gnome:link) "http://www.gnome.org"

set gui(glade:name) "Glade"
set gui(glade:description) "GTK+ User Interface Builder - This is how many of the gnucash GUI's are designed."
set gui(glade:link) "http://glade.pn.org"

%>


<%

global script
set script(list) [list guile gwrap scheme slib]
set script(columns) [list name description link]

set script(guile:name) "Guile"
set script(guile:description) "A Scheme interpreter with C programming interfaces - This is how gnucash provides 'extension' and rapid implementation capabilities"
set script(guile:link) "http://www.gnu.org/software/guile/guile.html"

set script(gwrap:name) "G-wrap"
set script(gwrap:description) "A tool for autogenerating scheme bindings for C lanugage functions, structures & enums."
set script(gwrap:link) "NO URL"

set script(scheme:name) "Scheme"
set script(scheme:description) "The Scheme Language"
set script(scheme:link) "http://www.scheme.org/"

set script(slib:name) "slib"
set script(slib:description) "Scheme library - Miscellaneous scheme functions used by GnuCash."
set script(slib:link) "http://www-swiss.ai.mit.edu/~jaffer/SLIB.html"

%>

<%

global web
set web(list) [list gtkhtml libghttp libxml]
set web(columns) [list name description link]

set web(gtkhtml:name) "GtkHTML"
set web(gtkhtml:description) "The gtk html layout engine - used by gnucash to display help documentation, reports and graphs."
set web(gtkhtml:link) "http://www.advogato.org/proj/GtkHTML/"

set web(libghttp:name) "libghttp"
set web(libghttp:description) "The HTTP library - used by gnucash to chat the http protocol to access web servers."
set web(libghttp:link) "http://www.gnome.org/"

set web(libxml:name) "Gnome XML"
set web(libxml:description) "The XML parsing library - used by gnucash to read its file format."
set web(libxml:link) "http://xmlsoft.org/"

%>

<%

global other
set other(list) [list financequote financequotehist guppi gnomeprint] 
set other(columns) [list name description link]

set other(financequote:name) "Finance::Quote"
set other(financequote:description) "A perl module to get stock price quotes and currency exchange rates from off the net - This is how gnucash accesses price data on the net."
set other(financequote:link) "http://finance-quote.sourceforge.net/"

set other(financequotehist:name) "Finance::QuoteHist"
set other(financequotehist:description) "A perl module to fetch historical stock prices."
set other(financequotehist:link) "http://sourceforge.net/project/?group_id=2403"

set other(guppi:name) "Guppi"
set other(guppi:description) "A graphical plotting and analysis tool - used to generate and display gnucash charts and plots."
set other(guppi:link) "http://www.gnome.org/guppi/"

set other(gnomeprint:name) "Gnome Print"
set other(gnomeprint:description) "gnome printing architecture - used by gnucash for check printing & general printing."
set other(gnomeprint:link) "http://www.sourceforge.net/projects/gnome-print/"

%>
