<%

global gui
set gui(list) [list gtk gnome glade]
set gui(columns) [list name description link]

$gui['gtk:name'] = "Gtk+"
set gui(gtk:name) "Gtk+"
set gui(gtk:description) "As Ferramentas Gimp"
set gui(gtk:link) "http://www.gtk.org/"

set gui(gnome:name) "Gnome"
set gui(gnome:description) "A infraestrutura da aplicação"
set gui(gnome:link) "http://www.gnome.org"

set gui(glade:name) "Glade"
set gui(glade:description) "Construtor de Interfaces de Utiizador em GTK+ - É assim que muitos dos interfaces do gnucash são criados."
set gui(glade:link) "http://glade.pn.org"

%>


<%

global script
set script(list) [list guile gwrap scheme slib]
set script(columns) [list name description link]

set script(guile:name) "Guile"
set script(guile:description) "Um interpretador Scheme com interfaces de programação C - É assim que o gnucash oferece capacidades de 'extensão' e desenvolvimento rápido"
set script(guile:link) "http://www.gnu.org/software/guile/guile.html"

set script(gwrap:name) "G-wrap"
set script(gwrap:description) "Uma ferramenta para gerar automaticamente ligações scheme para funções da linguagem C, estruturas & enums."
set script(gwrap:link) "SEM ENDEREÇO"

set script(scheme:name) "Scheme"
set script(scheme:description) "A Linguagem Scheme"
set script(scheme:link) "http://www.scheme.org/"

set script(slib:name) "slib"
set script(slib:description) "Biblioteca Scheme - Funções scheme variadas utilizadas pelo GnuCash."
set script(slib:link) "http://www-swiss.ai.mit.edu/~jaffer/SLIB.html"

%>

<%

global web
set web(list) [list gtkhtml libghttp libxml]
set web(columns) [list name description link]

set web(gtkhtml:name) "GtkHTML"
set web(gtkhtml:description) "O motor gtk de geração html - utilizado pelo gnucash para mostrar documentação de ajuda, relatórios e gráficos."
set web(gtkhtml:link) "http://www.advogato.org/proj/GtkHTML/"

set web(libghttp:name) "libghttp"
set web(libghttp:description) "A biblioteca HTTP - utilizada pelo gnucash para implementar o protocolo http para aceder a servidores web."
set web(libghttp:link) "http://www.gnome.org/"

set web(libxml:name) "Gnome XML"
set web(libxml:description) "A biblioteca de parseamento XML - utilizada pelo gnucash para ler o seu formato de ficheiro."
set web(libxml:link) "http://xmlsoft.org/"

%>

<%

global other
set other(list) [list financequote financequotehist guppi gnomeprint] 
set other(columns) [list name description link]

set other(financequote:name) "Finance::Quote"
set other(financequote:description) "Um módulo em perl para obter na internet cotações de acções e taxas de câmbio - É assim que o gnucash acede a dados sobre preços na net."
set other(financequote:link) "http://finance-quote.sourceforge.net/"

set other(financequotehist:name) "Finance::QuoteHist"
set other(financequotehist:description) "Um módulo em perl para obter preços históricos de acções."
set other(financequotehist:link) "http://sourceforge.net/project/?group_id=2403"

set other(guppi:name) "Guppi"
set other(guppi:description) "Uma ferramente de análise e plotagem - utilizada para apresentar os gráficos e tabelas do gnucash."
set other(guppi:link) "http://www.gnome.org/guppi/"

set other(gnomeprint:name) "Gnome Print"
set other(gnomeprint:description) "Arquitectura de impressão no gnome - utilizada pelo gnucash para impressão de cheques & tudo o resto."
set other(gnomeprint:link) "http://www.sourceforge.net/projects/gnome-print/"

%>
