
<b>Se você for um fã, aqui está como pode ajudar:</b><br><br>
<font size=-1>
Existem muitos utilizadores do GnuCash novatos e intermédios
    que ocasionalmente necessitam de ajuda na utilização do GnuCash.  Acompanhe a 
    lista de e-mail <a href="/en/lists.phtml">gnucash-user</a>,
    e ajude a responder a questões, ou pelo menos oriente as discussões
    aí tidas.  Se tiver formação teórica em contabilidade, ou 
    experiência considerável em finanças, e deseja ajudar os 
    programadores a implementar correctamente as funcionalidades, então
    deverá juntar-se às discussões técnicas que ocorrem na 
    <a href="/en/lists.phtml">gnucash-devel</a>. Corajosos testadores 
    de versões beta são sempre necessários para mais recente 
    versão.  Isto deve-se a que a última versão está frequentemente com 
    problemas, e necessitamos de alguém que nos diga onde estão os erros.
    Se for um artista: bem, um novo logotipo, um icon melhor,
    mais gráficos: estas coisas de certeza que não fazem mal.
    Se gosta de promover e divulgar projectos de aplicações livres, escreva-nos:
    nós gostamos de promotores.
</font>
