
<b>Se você for um tradutor, aqui está como poderá ajudar:</b><br><br>
<font size=-1>
Todos os menus e janelas no GnuCash estão completamente  
    internacionalizáveis/localizáveis utilizando a ferramenta GNU gettext.
    As probabilidades são boas de você ja ter configurado a sua
    máquina correctamente para o seu idioma (locale), e assim, as 
    probabilidades são razoáveis de você já ter visto o GnuCash no 
    seu idioma nativo, com as datas e moedas devidamente 
    localizadas.  Caso contrário, ou existe um erro, a sua máquina está mal 
    configurada, ou o seu idioma nativo não é 
    Dinamarquês, Inglês, Francês, Alemão, Italiano, Japonês, 
    Russo ou Sueco.  
    <p>
    Isto não significa que a tradução é perfeita: se a frase ou palavra  
    incorrecta estiver a ser utilizada nos menus ou janelas, 
    você deverá contactar o responsável pelo seu idioma 
    (veja no ficheiro README os responsáveis).  Se a moeda apresentada 
    for incorrecta, ou existirem outros problemas de localização, 
    você deverá contactar a lista de e-mail 
    <a href="/en/lists.phtml">gnucash-devel</a>.
    Note que os métodos de entrada de dados para Asiático (Japonês, Chinês, 
    etc.) e idiomas da direita para a esquerda estão parcialmente não funcionais:
    estamos à procura de programadores que tenham os conhecimentos necessários 
    para corrigir os problemas nos métodos de introdução nos widgets gnome de 
    entrada que utilizamos.  Também: eu pessoalmente gostaria de um 'Como Fazer-Asiático'
    escrito em Inglês para que eu (na verdade, nós, os  
    programadores que falam inglês) pudesse configurar as nossas máquinas aqui 
    para uma demonstração.  Escreva para <a href="mailto:linas@linas.org">linas at linas.org</a>
    caso consiga ajudar-me a configurar a minha máquina para Japonês ou Chinês.
    </p>
    <p>
    Preparar novas traduções é relativamente simples: 
    Obtenha o <a href="/en/hacking.phtml">código fonte</a>,
    leia o ficheiro <tt>README.translator.txt</tt>, e depois procure 
    o ficheiro de traduções no directório <tt>po</tt>.
    </p>
    <p>
    Também necessitamos de tradutores para idiomas que não o Inglês para a 
    página de internet. Se for uma destas pessoas, escreva ao 
    <a href="mailto:webmaster@gnucash.org">webmaster at gnucash.org</a>.
    Também são necessárias traduções da documentação para outros idiomas que não o Inglês.
    O parte problemática é, claro, que a documentação está bastante pouco
    trabalhada, e está de momento a ser re-escrita.  Se for um bom 
    escritor, contacte-nos.
</font>
