
<b>Se você for um webmaster, aqui está como pode ajudar:</b><br><br>
<font size=-1>
Nos gostariamos de alguém que nos ajudasse a configurar e manter todas 
    aquelas óptimas ferramentas de desenvolvimento que um projecto 'a sério' deve ter,
    tais como lxr e bonsai, e talvez uma ferramenta de acompanhamento de erros (bugs),
    ou outros pequenos detalhes.  Nós até precisamos de alguém que se certifique 
    que os arquivos de e-mails das listas estão a correr bem, e que as mensagens 
    recentes estão a ser indexadas &amp; e são procuráveis.
</font>
