
<b>Se você for um escritor, aqui está como poderá ajudar:</b><br><br>
<font size=-1>
A documentação precisa de ser refeita. Algumas pessoas podem achar 
    que a contabilidade é maçuda, mas isso não significa que a 
    documentação as deverá pôr a dormir.  E ter as últimas novidades 
    em notícias financeiras, criando algo no género do 
    advogato para tópicos financeiros, poderá não ser uma má ideia.
</font>
