
<b>Se você for um programador, aqui está como pode ajudar:</b><br><br>
<font size=-1>
Inscreva-se na lista de e-mail <a href="/en/lists.phtml">gnucash-devel</a>.
    Configure o CVS na sua máquina, e obtenha o  
    <a href="/en/hacking.phtml">código fonte</a>.
    Leia os ficheiros readme de compilação no subdirectório doc 
    e comece a programar.  Por outro lado, dependendo do seu 
    temperamento, você provavelmente desejará discutir as suas modificações
    na lista de e-mail: isto evitará devoluções e outras coisas 
    desagradáveis ao descobrir que nem toda a gente acha que a sua 
    modificação é maravilhosa.  Para obter uma ideia mais clara do 
    que se passa, estude a 
    <a href="/en/architecture.phtml">análise de arquitectura</a>.
    Para obter uma ideia do que está pensado, e quem está a fazer o quê,
    verifique a  
    <a href="http://www.linas.org/linux/gnucash/projects.html">
    lista de projectos</a>.  É longa, mas deverá orientar e 
    dar uma ideia do estado actual de vários componentes.
    Por último, mas dificilmente o menos importante, deverá analisar a documentação 
    existente no subdirectório <tt>src/doc</tt> na 
    árvore de código.
</font>
