<?php $title = _("Donations");
include("../emulate_globals_on.php");
include("externals/header.phtml");
include("externals/menu-main-documentation.phtml");
?>

<div id="content">

<h1><?php echo _("Donating to the GnuCash Project");?></h1>

<p><?php echo _("You can support the continued development of GnuCash, or simply show your appreciation for what we've already done, by making a financial gift to the GnuCash Project.  The GnuCash Project is an unincorporated entity, a loose association of the authors and developers who are involved with maintaining, extending and promoting the GnuCash software, documentation and website."); ?></p>

<p><?php echo _("Show your appreciation by donating to the GnuCash Project today! Currently, we can only accept PayPal donations made through the ");?>
<a href="http://sourceforge.net/donate/index.php?group_id=192"><?php
echo _("SourceForge donation system");?></a>.
<?php echo _("If you wish to make a donation in another form, please contact the "); ?>
<a href="https://lists.gnucash.org/mailman/listinfo/gnucash-devel">gnucash-devel</a>
<?php echo _("mailing list.  Please note that the donation system is anonymous; The PayPal registration info is not sent to us, and so we typically don't know who made a donation, and thus can't mail out a thank-you note. Feel free to announce your donation publicly on the mailing list, or in private.  We thank you now, in advance. Registered SourceForge Users who are logged in when they make a donation will see their names emblazoned in electrons on the ");
?>

<a href="https://sourceforge.net/project/project_donations.php?group_id=192"><?php
echo _("GnuCash donation website"); ?></a>. <?php echo _("Amounts are not shown.");?>
</p>

<p><?php echo _("In the spirit of openness an public responsibility, we present a summary of current finances below.  Announcements will be made when funds are disbursed; we will keep this web page updated periodically."); ?></p>

<div class="tblborder">
   <table cellpadding=5 cellspacing=1 width="100%">
   <colgroup><col width="15%"><col width="55%"><col width="15%"></colgroup>
   <tr>
    <td class="tblheader"><b><?php echo _("Date");?></b></td>
    <td class="tblheader"><b><?php echo _("Description");?></b></td>
    <td class="tblheader"><b><?php echo _("Amount");?></b></td>
    <td class="tblheader"><b><?php echo _("Current Balance");?></b></td>
   </tr>
   <tr>
     <td valign="top"><?php echo _("22-June-2004");?></td>
     <td valign="top"><?php echo _("Donations Received, March 2004 to 22 June 2004");?></td>
     <td valign="top">$525.95</td>
     <td valign="top">$525.95</td>
   </tr>
   <tr class="divider">
     <td valign="top"><?php echo _("22-June-2004");?></td>
     <td valign="top"><?php echo _("Current Balance");?></td>
     <td valign="top"></td>
     <td valign="top">$525.95</td>
   </tr>
   </table>
</div>

</div>
<?php include("externals/footer.phtml"); ?>
