<?php 
$title = "Features: Ease of Use";
include("../emulate_globals_on.php");
include($toppath."/externals/en/header.phtml");
include($toppath."/en/menu/menu-main-general.phtml");
?>
</div>
<div id="content">

<div>
<img src="/images/features/features_title.png" alt="feature title">
</div>
<div class="featureblock">&nbsp;</div>

<div>
<div class="featureimage">
  <img src="/images/features/features_3_small.png">
</div>
<p class="featurepanel">
  <img src="/images/features/features_3_text.png"><br>
  With keyboard accelerators, check number auto-increment,
  transaction auto-completion and transaction cut-n-paste make
  entering transactions quick and smooth.</p>
</div>
<div class="featureblock">&nbsp;</div>

<div class="featureplay">
  <a href=features_2.phtml><img alt="back to 2" src="/images/features/features_previous.png"></a>
 |
 <a href=features_4.phtml><img alt="next slide"
 src="/images/features/features_next.png"></a>
</div>

</div>
<?php include($toppath."/externals/en/footer.phtml"); ?>
