<?php 
$title = "Features: Ease of Use";
include("../emulate_globals_on.php");
include("externals/header.phtml");
include("externals/menu-main-general.phtml");
?>

<div id="content">

<div>
<img src="/images/features/features_title.png" alt="feature title">
</div>
<div class="featureblock">&nbsp;</div>

<div>
<div class="featureimage">
  <img src="/images/features/features_4_small.png" alt="four">
</div>
<p class="featurepanel">
 <img src="/images/features/features_4_text.png" alt="splits"><br>
<?php echo _("A single transaction can be split into several pieces to record taxes, fees, and other journal entries.");?></p>
</div>

<div class="featureblock">&nbsp;</div>

<div class="featureplay">
  <a href=features_3.phtml><img alt="<?php echo _("back to slide 3");?>"
 src="/images/features/features_previous.png"></a>
 |
  <a href=features_5.phtml><img alt="<?php echo _("next slide");?>"
 src="/images/features/features_next.png"></a>
</div>
</div>

<?php include("externals/footer.phtml"); ?>
