<?php $title = "Features"; ?>
<?php 
include("../emulate_globals_on.php");
include($toppath."/externals/en/header.phtml");
include($toppath."/en/menu/menu-main-general.phtml");
?>

<div id="content">
<h1><?php echo _("Features");?></h1>

<p><?php echo _("GnuCash has long had many features that support basic accounting needs for individuals and families, starting with an easy-to-use checkbook-register-style layout, and supporting things like bank statement reconciliation, stock/fund portfolios and numerous reports/graphs.  But GnuCash development doesn't stand still, and the newest versions add support for small business accounting as well.  German residents will also enjoy its on-line banking features (Sorry, on-line banking is not supported in the US; don't blame us, blame your bank.  Tell them to tell us the URL for their OFX servers, instead of hiding it like state secrets.).");?>
</p>
<p style="text-align:center">
<?php echo _("Take a graphical tour of some of the core GnuCash features!");?></p>
<p style="text-align:center"><a href="features_1.phtml">
<img alt="start" src="/images/features/features_start_the_tour.png"></a>
</p>

<p style="text-align:center">or dive into the<br>
<b><a href="features_5.phtml"><?php echo _("Complete Features List");?></a></b>.
</p>

</div>
<?php include($GLOBALS['DOCUMENT_ROOT']."/externals/en/footer.phtml"); ?>
