<?php 
$title = "Features: What's New";
include("../emulate_globals_on.php");
include("externals/header.phtml");
include("externals/menu-main-general.phtml");
?>
<div id="content">

<div>
  <img src="/images/features/features_title.png" alt="feature title">
</div>
<div class="featureblock">&nbsp;</div>

<div>
  <img src="/images/features/features_5_text.png">
</div>


<h2><?php echo _("What's New in GnuCash 1.8.0?");?></h2>
<p><?php echo _("The 1.8.x series of stable releases introduce many new features not found in the older gnucash-1.6.8.");?></p>
<?php # mark the updated features for translating when editing
?>
<dl>
<dt><b><?php echo _("Scheduled Transactions");?></b>
<dd><?php echo _("You can now create recurring transactions, including automatic reminders when a transaction is due, the ability to postpone a scheduled transaction without canceling it, and the ability to specify only a limited number of transactions.");?>
    <br><br>
<dt><b><?php echo _("Mortgage &amp; Loan Repayment Druid");?></b></dt>
<dd><?php echo _("A guided dialogue for setting up loan payments as scheduled transactions.");
?>
    <br><br>
<dt><b><?php echo _("Small Business Accounting Features");?></b>
<dd><?php echo _("Simplify managing a small business with Customer and Vendor tracking,    Invoicing and Bill Payment, and Tax and Billing Terms.");?>
    <br><br>
<dt><b><?php echo _("OFX Import");?></b>
<dd><?php echo _("GnuCash is the first free software application to support the Open Financial Exchange protocol that many banks and financial services are starting to use.");?>
    <br><br>
<dt><b><?php echo _("HBCI Support");?></b>
<dd><?php echo _("GnuCash is the first free software application to support the German Home Banking Computer Information protocol, allowing German users to perform statement download and initiate bank transfers and direct debits.");?>
    <br><br>
<dt><b><?php echo _("Improved Import Transaction Matching");?></b>
<dd><?php echo _("The development of OFX and HBCI support has also resulted in an improved transaction matching system that more accurately recognizes duplicate transactions during file import.");?>
    <br><br>
<dt><b><?php echo _("New User Manual and Help");?></b>
<dd><?php echo _("A new help subsystem that focuses on how to do tasks is now available, in addition to a Tutorial and Concepts guide that gives the user background information on accounting principles and how they are reflected in GnuCash.");?>
    <br><br>
<dt><b><?php echo _("New Multi-Currency Transaction Handling");?></b>
<dd><?php echo _("GnuCash no longer requires separate currency exchange accounts to handle multiple currency transfers.  Transactions can be made directly between accounts denominated in different currencies.");?>
    <br><br>
<dt><b><?php echo _("Redesigned Menus");?></b>
<dd><?php echo _("The GnuCash menus have been redesigned to conform more with the new GNOME Human Interface Guidelines.");?>
    <br><br>
</dl>

<h2><?php echo _("Old Favorites");?></h2>
<?php echo _("And of course, some favorite features from earlier versions:");?>

	<br><br>
<dl>
<dt><b><?php echo _("Statement Reconciliation");?></b>
<dd><?php echo _("A reconcile window with running reconciled and cleared balances makes balancing against bank statements easy.");?>
</dd>
<br><br>
<dt><b><?php echo _("Stock/Mutual Fund Portfolios");?></b>
<dd><?php echo _("Track stocks individually (one per account) or in portfolio of accounts (a group of accounts that can be displayed together).");?>
</dd>
<br><br>
<dt><b><?php echo _("QIF Import");?></b>
<dd><?php echo _("Intuit<sup>&reg;</sup> Quicken<sup>&reg;</sup> QIF files can be imported, and are automatically merged to eliminate duplicate transactions.");?>
</dd>
<br><br>
<dt><b><?php echo _("Localization");?></b>
<dd><?php echo _("Handles internationalized dates and currencies.  The Gnucash menus and popups have been translated to 21 languages, including Chinese, Danish, French, German, Hungarian, Italian, Japanese, Norwegian, Polish, Portuguese, Russian, Spanish, Swedish, Turkish, Ukrainian, and British English. Documentation is available in English, French, Portuguese and Spanish.");?>
</dd>
<br><br>
<dt><b><?php echo _("Reports");?></b>
<dd><?php echo _("Display Balance Sheet, Profit &amp; Loss, Portfolio Valuation, and others. Reports can be saved as HTML or postscript, or printed.");?>
</dd>
<br><br>
<dt><b><?php echo _("Transaction Finder");?></b>
<dd><?php echo _("A powerful transaction query dialogue can help you quickly locate a needle in a haystack.");?>
</dd>
<br><br>
<dt><b><?php echo _("Double Entry");?></b>
<dd><?php echo _("When enabled, every transaction must debit one account and credit others by an equal amount. This ensures that the \"books balance\": that the difference between income and outflow exactly equals the sum of all assets and equity.");?>
</dd>
<br><br>
<dt><b><?php echo _("Income/Expense Account Types");?></b>
<dd><?php echo _("Income/Expense Account Types (Categories) allow you to categorize your cash flow.  When used properly with the double-entry feature and equity accounts, these enable you to generate reports, such as Profit &amp; Loss, that plain-vanilla systems cannot handle.");?>
</dd>
<br><br>
<dt><b><?php echo _("General Ledger");?></b>
<dd><?php echo _("Multiple accounts can be displayed in one register window at the same time. This can ease the trouble of tracking down typing/entry errors. It also provides a convenient way of viewing a portfolio of many stocks, by showing all transactions in that portfolio.");?>
</dd>
<br><br>
<dt><b><?php echo _("Online Stock &amp; Mutual Fund Quotes");?></b>
<dd><?php echo _("Get Stock &amp; Mutual Fund quotes from various web sites, update portfolio automatically. Additional pricing sources are added regularly.");?>
</dd>
<br><br>
<dt><b><?php echo _("Check Printing");?></b>
<dd><?php echo _("Checks may be printed in standard formats on common check stocks. A customization GUI allows custom check layouts to be developed.");?>
</dd>
<br><br>
<dt><b><?php echo _("Multiple Currencies");?></b>
<dd><?php echo _("Different accounts can be denominated in different currencies. Currency movements between accounts are fully balanced when double-entry is enabled.");?>
</dd>
<br><br>
<dt><b><?php echo _("Multi-User SQL Support");?></b>
<dd><?php echo _("Multiple users can now simultaneously access and update GnuCash data stored in a Postgres SQL backend. Postgres must be installed and configured to use this option.");?>
</dd>
<br><br>
</dl>
</div>

<br>

<div class="featureplay">
  <a href=features_4.phtml><img alt="<?php echo _("back to slide 4");?>" 
src="images/features/features_previous.png"></a>
		 |
  <img alt="<?php echo _("end of slides");?>" 
src="images/features/features_next_disabled.png">
</div>
</div>

<?php include("externals/footer.phtml"); ?>
