<?php 
$title = "Features:Ease of Use";
include("../emulate_globals_on.php");
include("externals/header.phtml");
include("externals/menu-main-general.phtml");
?>

<div id="content">

<div>
<img src="images/features/features_title.png" alt="feature title">
</div>
<div class="featureblock">&nbsp;</div>

<div>
<div class="featureimage">
  <img src="images/features/features_2_small.png" alt="two">
</div>
<p class="featurepanel">
  <img src="images/features/features_2_text.png" alt="hierarchy"><br>
<?php echo _("A master account can have a hierarchy of detail accounts underneath it. This allows similar accounts types ( e.g. Cash, Bank, Stock ) to be grouped into one master account ( e.g. Assets ).");?>
</p>
</div>
<div class="featureblock">&nbsp;</div>

<div class="featureplay">
 <a href=features_1.phtml><img alt="<?php echo _("back to first slide");?>"
src="/images/features/features_previous.png"></a>
 |
  <a href=features_3.phtml><img alt="<?php echo _("next slide");?>"
 src="/images/features/features_next.png"></a>
</div>

</div>
<?php include("externals/footer.phtml"); ?>
