<?php 
$title = "GnuCash on IRC";
include("../emulate_globals_on.php");
include($toppath."/externals/en/header.phtml");
include($toppath."/externals/en/menu-main-help.phtml");
?>

<div id="content">

<h1>GnuCash on IRC</h1>

Have some fun (or merely get help with using and installing GnuCash) 
by discussing GnuCash development with developers and users alike, 
on IRC.  Join the #gnucash channel at irc.gnome.org.
</div>

<?php include($toppath."/externals/en/footer.phtml"); ?>
