<?php 
$title = "Related Financial Software";
include("../emulate_globals_on.php");
include($toppath."/externals/en/header.phtml");
include($toppath."/en/menu/menu-main-other.phtml");
?>

<div id="content">

<h1>Related Financial Software</h1>

<div>
<p><b>Select a section:</b>
</p>
<form method="get" action="<?php echo $_SERVER["PHP_SELF"];?>">
<div>
<select name="linkpage">
  <option value="general"
  <?php if ($_GET["linkpage"] == "general") { echo ("selected"); } ?>
  >General References</option>
  <option value="utilities"
  <?php if ($_GET["linkpage"] == "utilities") { echo ("selected"); } ?>
  >Utilities</option>
  <option value="palm"
  <?php if ($_GET["linkpage"] == "palm") { echo ("selected"); } ?>
  >Palm Computing</option>
  <option value="stock"
  <?php if ($_GET["linkpage"] == "stock") { echo ("selected"); } ?>
  >Stock Trading &amp; Technical Analysis</option>
  <option value="quote"
  <?php if ($_GET["linkpage"] == "quote") { echo ("selected"); } ?>
  >Quote Sources, Tools</option>
  <option value="money"
  <?php if ($_GET["linkpage"] == "money") { echo ("selected"); } ?>
  >Electronic Currencies</option>
  <option value="erp"
  <?php if ($_GET["linkpage"] == "erp") { echo ("selected"); } ?>
  >Business, ERP Projects</option>
  <option value="xml"
  <?php if ($_GET["linkpage"] == "xml") { echo ("selected"); } ?>
  >XML and Other Data Formats</option>
  <option value="misc"
  <?php if ($_GET["linkpage"] == "misc") { echo ("selected"); } ?>
  >Miscellaneous</option>
  <option value="obsolete"
  <?php if ($_GET["linkpage"] == "obsolete") { echo ("selected"); } ?>
  >Historical References</option>
  <option value="review"
  <?php if ($_GET["linkpage"] == "review") { echo ("selected"); } ?>
  >Gnucash Review &amp; Rating Sites</option>
</select>
<input type="submit" value="Go">
</div>
</form>
</div>

<?php
  if ($linkpage != "") { 
	include($toppath."/www/links/links-".$linkpage.".phtml");
  } else {
	include($toppath."/www/links/links-general.phtml");
  }
?>

</div>
<?php include($toppath."/externals/en/footer.phtml"); ?>
