<?php 
$title = "Survey"; 
include("../emulate_globals_on.php");
include($toppath."/externals/en/header.phtml");
include($toppath."/en/menu/menu-main-general.phtml");
?>

</div>
<div id="content">

<h1>GnuCash User Survey</h1>

<p><b>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</b>
</p>
<p><b>
The GnuCash Features Survey is now closed.  You can view the results 
<a href="/en/quiz-results.phtml">here</a>
</b></p>

<p>
<b>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</b>
</p><p>
<b>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</b>
</p><p>
<b>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</b>
</p><p>

GnuCash is at a cross-roads in its development.  Most of the features one might
expect in a basic accounting program have been implemented, and the few that
haven't been will be soon.   After that, there are
<a href="/en/roadmap.phtml">
many paths that GnuCash can take</a>.
But where to?  This survey will help shape that decision.  Of course, GnuCash
is a project driven by volunteers, and any programmer with an 'itch to scratch'
can implement any feature they wish for GnuCash.   But maybe the results of this
survey will help focus the debate and the energies a bit.   This is your chance
to make your wishes known.
</p><p>
Warning: this is a long survey. It has 45 questions, and its broken into 
six sections:
</p><ul>
<li>General
<li>Commercializing GnuCash
<li>Using GnuCash
<li>Future Features
<li>Online Banking
<li>Personal Profile
</ul>

<p>Feel free to skip questions that you
don't understand, or those that you don't really have an opinion on.
Skip entire pages if they bore you.
But please: one vote per person, and no ballot-stuffing.
</p>

<?php $sid=2;
       include("/home/httpd/tools/phpESP-1.2beta3/public/handler.php");?> 

<?php include($toppath."/externals/en/footer.phtml"); ?>
