<?php $title = "Screenshots"; ?>
<?php
include("../emulate_globals_on.php");
include($toppath."/externals/en/header.phtml");
include($toppath."/en/menu/menu-main-general.phtml");
?>
<div id="content">

<h1>Screenshots</h1>

<div class="tblborder">
   <table cellpadding=5 cellspacing=1 width="100%">
   <colgroup><col width="25%"><col width="45%"><col width="30%"></colgroup>
   <tr>
     <td class="tblheader"><b>Screenshot</b></td>
     <td class="tblheader"><b>Description</b></td>
     <td class="tblheader"><b>Thumbnail</b></td>
   </tr>
<?php

	$screenshotpath = "images/gnome-1.6/";
	$imagesrc =  $screenshotpath;
	$imagepath = $screenshotpath;

	$d = dir($imagepath);
	while($entry=$d->read()) {
	  if(ereg("-thumb", $entry)) { continue; }
	  if(!ereg("gif$", $entry)) { continue; }

	$file_clean = explode(".", $entry);
	$entry = $file_clean[0]."-thumb";
	  
	$description = implode("", file($imagepath.$entry.".gif.description")); 
	$name = implode("", file($imagepath.$entry.".gif.name"));
?>
   <tr>
     <td style="text-align:left">
	<img src="images/icons/search_icon.gif" 
	width=16 height=16 alt="screenshot icon">&nbsp;<a 
	href="<?php echo $imagesrc.$file_clean[0].".gif"; ?>"><?php 
	echo $name; ?></a>
     </td>
     <td><?php echo $description; ?></td>
     <td><a href="<?php echo $imagesrc.$file_clean[0].".gif"; ?>"><img 
	alt="<?php echo $file_clean[0]; ?>"
	src="<?php echo $imagesrc.$file_clean[0]."-thumb.gif"; ?>"></a>
    </td>
   </tr>
<?php 
  }
  $d->close();
?>

   </table>
</div>

</div>
<?php include($toppath."/externals/en/footer.phtml"); ?>
