<!-- MENU:START -->

<table border=0 cellpadding=4 cellspacing=0 width=100%>
<tr>
  <td><img border=0 src=/images/webding.png> <a href="/pt_PT/">Principal</a></td>
</tr>
<tr>
  <td bgcolor=#cacaf7>
  <img border=0 src=/images/webding.png> <b>Informação Genérica</b>

<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/menu/menu-general.phtml"); ?>

  </td>
</tr>
<tr>
  <td>
  <img border=0 src=/images/webding.png> <b>Ficheiros</b>

<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/menu/menu-downloads.phtml"); ?>

  </td>
</tr>
<tr>
  <td>
  <img border=0 src=/images/webding.png> <b>Informação Programadores</b>

<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/menu/menu-developer.phtml"); ?>

  </td>
</tr>
<tr>
  <td>
  <img border=0 src=/images/webding.png> <b>Outra Informação</b>

<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/menu/menu-other.phtml"); ?>

  </td>
</tr>
<tr>
  <td>
  <img border=0 src=/images/webding.png> <b>Documentação</b>

<?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/menu/menu-documentation.phtml"); ?>

  </td>
</tr>
</table>

<!-- MENU:END -->
