  <table border=0 cellpadding=0 cellspacing=6>
  <tr>
  <td><img src="/images/spacer.gif" height=1 width=2></td>
  <td>
    <font size=-1>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/pt_PT/architecture.phtml">Arquitectura do Sistema</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="http://linas.org/linux/gnucash/projects.html">Objectivos do Projecto</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/pt_PT/contribute.phtml">Contribuir</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/pt_PT/lists.phtml">Listas de E-Mail</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="http://bugs.gnome.org/db/pa/lgnucash.html">Notas de Erro Gnome</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/lxr/">Navegar no código fonte</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/pt_PT/hacking.phtml">Modificar o GnuCash</a><br>

  </td>
  </tr>
  </table>
