  <table border=0 cellpadding=0 cellspacing=6>
  <tr>
  <td><img src="/images/spacer.gif" height=1 width=2></td>
  <td>
    <font size=-1>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/pt_PT/links.phtml">Aplicações financeiras relacionadas</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/pt_PT/articles.phtml">GnuCash nas notícias</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/pt_PT/promote.phtml">Promover o GnuCash</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/pt_PT/history.phtml">História</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="http://www.gnumatic.com/">Apoio Empresarial</a><br>

  </td>
  </tr>
  </table>
