  <table border=0 cellpadding=0 cellspacing=6>
  <tr>
  <td><img src="/images/spacer.gif" height=1 width=2></td>
  <td>
    <font size=-1>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/pt_PT/features.phtml">Funcionalidades</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/pt_PT/screenshots.phtml">Imagens de Ecrã</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/gnome-1.5-screenshots.php3">Imagens de Ecrã Beta</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/pt_PT/roadmap.phtml">O Caminho em Frente</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/pt_PT/required.phtml">Requisitos Aplicacionais</a><br>
 
<!--
    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="http://www.multimania.com/yleny/gnucash/">GnuCash en Français</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="http://www.hthoma.de/projekte/gnucash/index.html">GnuCash auf deutsch</a><br>
-->
 
  </td>
  </tr>
  </table>
