
    <h2>Revue de Gnucash &amp; Sites de Notation </h2>
    Sites qui notent, étudient, classent publient gnucash.

    <ul>
    <li><a href="http://freshmeat.net/projects/gnucash/?highlight=gnucash">Freshmeat</a>
        
    <li>ZD Net <a href="http://www.appwatch.com/Linux/App/571/data.html">
        AppWatch</a> vous enverra une notification par e-mail lorsqu'une nouvelle version
        de gnucash sortira.Donne aussi un indice de popularité.
    <li><a href="http://www.icewalk.com/softlib/app/app_00056.html">IceWalkers</a>      
        listes beaucoup de projets open-source .
    <li><a href="http://linux.davecentral.com/6044_officeacct.html">Dave 
        Central</a>.  
    <li><a href="http://www.linuxberg.com/x11html/preview/9340.html">Tucows</a>
    <li><a href="http://www.softseek.com/Linux/Home_Family_and_Leisure/Home_Finance/Review_42842_index.html">Softseek</a>
    </ul>
