
<?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-header.phtml"); ?>

   <tr><td colspan=2>
<B>Utilisation des Palm</B><BR>
   </td> </tr>
   
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-start.phtml"); ?>
         	<A HREF="http://sourceforge.net/projects/pm2qif/">pm2qif est un convertisseur de 
         	fichier de PocketMoney vers QIF</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-middle.phtml"); ?>
		  un ensemble de scripts perl pour convertir vos fichiers de données PocketMoney vers 
		  les fichiers QIF.  PocketMoney est un shareware de compatibilité populaire sur palm.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-start.phtml"); ?>
		 <A HREF="http://sourceforge.net/projects/freecoins/">FreeCoins</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-middle.phtml"); ?>
		 Un logiciel de comptabilité GPL pour PalmOS
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-end.phtml"); ?>
   </table>
</tr>
</table>
