
<?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-header.phtml"); ?>

   <tr>
     <td colspan=2>
<B>Quote Sources, Tools</B><BR>
     </td>
   </tr>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-start.phtml"); ?>
		 <a href="http://finance-quote.sourceforge.net/">Finance::Quote</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-middle.phtml"); ?>
		 Un module Perl pour recuperer les cours des actions et les taux de devises  
		 a partir d'une variété de sources internet.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-start.phtml"); ?>
		 <a href="http://getquote.giammy.com/">GetQuote</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-middle.phtml"); ?>
		 Un outils en ligne de commande pour recuperer les cours des actions. developpé en C.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-start.phtml"); ?>
		 <a href="http://www.marketwatch.com/tools/quotes/basic.asp?siteid=mktw">CBS
		 MarketWatch</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-middle.phtml"); ?>
		 Flux de données gratuit.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-start.phtml"); ?>
		 <a href="http://www.datek.com/">Datek</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-middle.phtml"); ?>
		 Flux de données gratuit.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-start.phtml"); ?>
		 <a href="http://quicken.excite.com/investments/quotes/">Excite - Quicken</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-middle.phtml"); ?>
		 Flux de données gratuit.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-start.phtml"); ?>
		 <a href="http://www.financialweb.com/mktIndex.asp">FinancialWeb</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-middle.phtml"); ?>
		 Flux de données gratuit.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-start.phtml"); ?>
		 <a href="http://freerealtime.com">FreeRealTime</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-middle.phtml"); ?>
		 Flux de données gratuit.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-start.phtml"); ?>
		 <a href="http://money.go.com">GoMoney - ABC News</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-middle.phtml"); ?>
		 Flux de données gratuit.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-start.phtml"); ?>
		 <a href="http://www.money.net">MoneyNet</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-middle.phtml"); ?>
		 Flux de données gratuit.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-end.phtml"); ?>
   </table>
</tr>
</table>
