
<?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-header.phtml"); ?>

   <tr>
     <td colspan=2>
<B>General References</B><BR>
     </td>
     </tr>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-start.phtml"); ?>
		 <a href="http://www.gldialtone.com/links.htm">Les liens stupefiant de GL Dialtone</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-middle.phtml"); ?>
		 Fournit une vaste liste de lien vers de grands registres webs, des logiciels de comptabilité, 
		 des services professionnels asp, de la facturation électronique et d'autres choses dans ce 
		 genre.<a href="http://www.gldialtone.com/"> La comptabilité générale Dialtone</a>
		  elle-même fournit beaucoup d'information et un forum de discussion pour 
		  rassembler les réflexions sur la comptabilité. 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-start.phtml"); ?>
		 <a href="http://www.transaction.net/money/">Comment Fonctionne l'argent</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-middle.phtml"); ?>
	    L'argent n'est pas nécessairement  une monnaie nationale : cela peut être des points miles 
	    de compagnie aérienne, des heures échangées et bien d'autres choses. 
	    Cette page passe en revue différentes idées d'argent et liste les caractéristiques 
	    de des différents types de monnaie.   
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-start.phtml"); ?>
		 <a href="http://www.e-gold.com/e-gold.asp?cid=281678">E-Gold</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-middle.phtml"); ?>
	    L'E-Gold est une monnaie électronique. À la différence d'une monnaie nationale, 
	    elle est émise par une entreprise privé et soutenue par des réserves d'or. 
	    À la différence d'une carte de crédit, c'est un peu plus anonyme, 
	    mais pas tout à fait aussi anonyme que de l'argent comptant. 
	    Sa popularité augmente lentement.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-start.phtml"); ?>
		 <a href="http://www.iasc.org.uk/frame/cen2.htm">Standards Internationaux de 
		 Comptabilité</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-middle.phtml"); ?>
		 Le Comité de Standards International de Comptabilité. 
		 Abrupt, mais une bonne source des documents techniques et légaux qui définissent des 
		 règles de comptabilité.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-start.phtml"); ?>
		 <a href="http://cbbrowne.com/info/finances.html">Les applications de C.Browne, 
		 Linux, et autres sujets</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-middle.phtml"); ?>
		Christophe Browne passe en revue un certain nombre d'applications financières pour Linux. 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-start.phtml"); ?>
		 <a href="http://www.linuxlinks.com/Software/Financial/"> Les logiciels financiers 
		 de LinuxLinks</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-middle.phtml"); ?>
		 Une vaste liste de programmes libres (gratuits) et commerciaux. 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-end.phtml"); ?>
  </table>
</tr>
</table>
