
<?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-header.phtml"); ?>

<tr> <td colspan=2>
<B>Divers</B><BR>
</td> </tr>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-start.phtml"); ?>
		 <a href="http://www.unixrealm.com/downloads/">Unixrealm</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-middle.phtml"); ?>
		 Des package pre-compilé de Gnome et GnuCash pour Solaris.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-start.phtml"); ?>
		 <a href="http://www.ibm.com/java/sanfrancisco">IBM San Francisco</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-middle.phtml"); ?>
		 Classes Java professionnelles et Financières.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-start.phtml"); ?>
		 <a href="http://www.integrion.com/">Integrion</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-middle.phtml"); ?>
		 Un conglomérat de 16 banques + IBM dont le but est de construire une 
		 infrastructure de banque en ligne. le déploiement est en cours 
		 dans certaines grandes banques.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-start.phtml"); ?>
		 <a href="http://www.sun.com/980224/javapos/">Java Point of Sale</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-middle.phtml"); ?>
		 &nbsp;
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-start.phtml"); ?>
		 <a href="http://www.pango.org/">Pango</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-middle.phtml"); ?>
		 Un afficheur de texte Internationalisé pour gtk.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-start.phtml"); ?>
		 <a href="ftp://ftp.gnu.org/pub/gnu/plotutils/">Gnu Plotutils</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-middle.phtml"); ?>
		 Un package permettant les graphiques/dessins.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-start.phtml"); ?>
         	<a href="http://www.im.lcs.mit.edu/~magnus/ml/">GTK grid widget</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-middle.phtml"); ?>
		 Probablement mieux que Clint, gtktable (ndt: portable pour gtk ?)
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-start.phtml"); ?>
		 <a href="http://www.didx.com/xml-builder.html">XML Builder</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-middle.phtml"); ?>
		 Permet de décrire des écrans d'interfaces utilisateurs en utilisant XML. 
		 Jetez aussi un oeil sur le xpfe de mozilla.org.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-start.phtml"); ?>
		 <a href="http://www.engelschall.com/sw/eperl">Embedded Perl</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-middle.phtml"); ?>
		 Permet d'améliorer Perl a l'intérieur de pages html pour créer des contenus dynamiques.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-start.phtml"); ?>
		 <a href="http://www.ispras.ru/~knizhnik/gigabase.html">GigaBASE</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-middle.phtml"); ?>
		 Une base de données SQL améliorée.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-end.phtml"); ?>
   </table>
</tr>
</table>
