
<?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-header.phtml"); ?>

   <tr> <td colspan=2>
<B>Utilitaires</B><BR>
     </td> </tr>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-start.phtml"); ?>
		<A HREF="http://gnucashtoqif.sourceforge.net/">gnucashtoqif</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-middle.phtml"); ?>
		 Un outil Java pour convertir les fichiers XML GnuCashau format QIF.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-start.phtml"); ?>
		<A HREF="http://nicolas.marchildon.net/gnu_qif/">gnu_qif</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-middle.phtml"); ?>
		 n outil Java pour convertir d'autre format financiers vers le QIF.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-start.phtml"); ?>
		<A HREF="http://www-cad.eecs.berkeley.edu/~gooch/mymdump.html">MYMdump</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-middle.phtml"); ?>
		 Convertisseur de fichier MYM vers QIF MYM est l'acronyme de  Managing Your Money.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-start.phtml"); ?>
		 <a href="http://www.snaught.com/gbonds/">GBonds</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-middle.phtml"); ?>
		 Outil du bureau Gnome  pour suivre les Bond U.S..
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/links-end.phtml"); ?>
   </table>
</tr>
</table>
