<?php $title = "GnuCash in het Nieuws"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-main-other.phtml"); ?>
</td>

<td valign=top>
<b>GnuCash in het Nieuws!</b>
<br><br>
Een verzameling persberichten van over de gehele wereld.
<br><br>

<dl>
      <dt>
      <b><a href="http://www.golem.de/0302/23786.html">GnuCash-Finanzverwaltung für Linux unterstützt HBCI</a></b> (<a href="/press-archive/golem.de-2003-02/23786.html">archival copy</a>) (golem.de, 3 Feb 2003) 
      </dt>
      <dd>
      Das GnuCash-Entwicklerteam hat jetzt die Version 1.8 von GnuCash veröffentlicht, einer Open-Source-Finanzverwaltung für Linux/Unix, die sich an Privatanwender und Kleinbetriebe richtet. In der neuen stabilen Version wird erstmals das Online-Banking über HBCI unterstützt. 
      <br><br>
      </dd>
      <dt><b><a href="http://www.linux-community.de/Neues/story?storyid=6378">GnuCash 1.8.0 jetzt mit HBCI-Unterstützung </a></b> 
      (<a href="/press-archive/linux-community.de-2003-02/story.storyid-6378.html">archival copy</a>) (Linux Community, 3 Feb 2003)
      </dt>
      <dd>
      Das GnuCash Entwicklerteam meldet die Veröffentlichung von GnuCash 1.8.0, der OpenSource-Finanzverwaltung für Linux/Unix. 

      "Wozu braucht man jetzt noch Windows? Online-Banking mit HBCI und die private Kontoverwaltung ist nun vollständig auf Linux möglich," meint Christian Stimming vom Entwicklerteam. 
      <br><br>
      </dd>
      <dt>
      <b>
      <a href="http://heise.de/newsticker/data/anw-09.12.02-006/">HBCI-Bibliothek für Linux/Unix</a> </b>(<a href="/press-archive/heise.de-2002-12/index.html">archival copy</a>) (heise online, 9 Dec 2002)
      </dt>
      <dd>
      Das OpenHBCI-Entwicklerteam stellt die nach eigenen Angaben erste freie OpenSource-Implementierung des Homebanking-Standards HBCI (Home Banking Computer Interface) für Linux/Unix
      <br><br>
      </dd>
      <dt>
      <b>
      <a href="http://www.pro-linux.de/news/2002/4975.html">GnuCash mit HBCI-Unterstützung erschiene</a></b>

      (<a href="/press-archive/pro-linux-2002-12/4975.html">archival copy</a>)
      (Pro-Linux, 2 Dec 2002)
      </dt>
      <dd>
      Das »GnuCash«-Entwickler-Team kündigte heute die Verfügbarkeit von GnuCash 1.7.4 mit HBCI-Unterstützung (Home Banking Computer Information) an.
      <br><br>
      </dd>
      <dt>
      <b>
      <a href="http://www.linuxworld.com/go.cgi?id=740992">Balancing your books? GnuCash is the answer</a></b>

      (<a href="/press-archive/linuxworld-2002-09/0916.gnucash.html">archival copy</a>)
      (Linux World, 16 Sept 2002)
      </dt>
      <dd>Joe Barr walks us through his experience with GnuCash personal-accounting software. His conclusion? GnuCash is good enough to trust with his miniature donkey farm?s bookkeeping. (1,200 words) 
      <br><br>
      </dd>
      <dt>
      <b>
      <a href="http://www.linuxjournal.com/article.php?sid=5669&mode=thread&order=0">
      Keep Track of Your Money</a></b>
      (<a href="/press-archive/linuxjournal-2002-06/article.php?sid=6559">archival copy</a>)
      (Linux Journal, 8 June 2002)
      </dt>
      <dd>Recently, I took the big step: I became a freelancer. It's great, 
      but even after a short while, I began to realize that there were some 
      changes in my behavior concerning finances and spending money. So I 
      thought decided to start keeping track of my personal accounts, 
      especially with having more time to go shopping. I never thought 
      I would do this, but now I do, and I'm feeling more secure knowing 
      exactly how I spend my income.      
      <br><br>
      </dd>
										    
      <dt>
      <b><a href="http://www.lwn.net/2001/0621/">
      GnuCash and library dependencies, again</a></b>
      (<a href="/press-archive/lwn.net-2001-0621/index.html">archival copy</a>)
      (LWN.net, June 21 2001)
      </dt>
      <dd> 
      Last week's item about the GnuCash 1.6 release and its many 
      library dependencies drew more than the usual amount of mail, 
      including this response from the GnuCash project itself. We 
      seem to have hit a bit of a nerve there. So this week we'll 
      follow up with two more articles; this one looks at the 
      library dependency issue again, and the following one is a
      quick review of the 1.6 release itself. 
      <br><br>
      </dd>
      
      <dt>
      <b><a href="http://www.lwn.net/2001/0614/">
      gnucash 1.6 and the dependency nightmare</a></b>
      (<a href="/press-archive/lwn.net-2001-0614/index.html">archival copy</a>)
      (LWN.net, June 14 2001)
      </dt>
      <dd> The release of gnucash 1.6 was announced on June 11. 
      gnucash is an important application - it is the only free 
      package which provides comprehensive personal and business 
      finance functionality. Your editor has been using it for 
      over a year, and has been anxiously waiting for it to catch
      up to what the commercial finance packages can do. 
      <br><br>
      </dd>
      
      <dt>
      <b>Gerer ses comptes personnels</b>
      (archive: <a href="/press-archive/maximum-linux-2000-12/p1.jpg">page 1</a>,
      <a href="/press-archive/maximum-linux-2000-12/p2.jpg">page 2</a>,
      <a href="/press-archive/maximum-linux-2000-12/p3.jpg">page 3</a>,
      <a href="/press-archive/maximum-linux-2000-12/p4.jpg">page 4</a>)
      
      (MaximumLinux France, December 2000)
      </dt>
      <dd>
      L'ordinateur prend une place de plus en plus importante 
      dans les foyers, notamment en ce qui concrne la gestion 
      des finances personnelles. Petit tour d'horizon des 
      differents logiciels pour vous aider a faire le bon choix.
      <br><br>
      [editors note: gnucash-1.4.8 gets five stars from this French magazine!]
      <br><br>
      </dd>
      
      <dt>
      <b><a href="http://www.linuxgram.com/newsitem.phtml?sid=109&aid=10365">
      Guns along the Gnome</a></b>
      (<a href="/press-archive/linuxgram-2000-12/newsitem.html">archival copy</a>)
      (Linuxgram, December 2000)
      </dt>
      <dd>
      Guns along the Gnome: It Ain't Paranoia If They're Really Out To Get You
      Nautilus (Eazel) = MS Explorer File Manager 
      <br><br>
      </dd>
      
      <dt>
      <b><a href="http://www.linuxorbit.com/features/newbie10.php3">
      The Newbie test drives GnuCash</a></b>
      (<a href="/press-archive/linuxorbit-2000-12/features-newbie10.php3.html">archival copy</a>)
      (Linux Orbit, December 2000)
      </dt>
      <dd>
      I'd been looking around for something that might interest a 
      Linux neophyte like myself and with a little coaching from 
      the head honcho at Linux Orbit, I decided to try out GnuCash 
      and give you the newbie perspective. Although I've always 
      used spreadsheets to keep track of finances, I figured, what 
      the heck.
      <br><br>
      </dd>
      
      <dt>
      <b><a href="http://www.linuxnews.com/stories.php?story=526">
      What's New with GnuCash</a></b>
      (<a href="/press-archive/linuxnews-2000-10/stories.html">archival copy</a>)
      (LinuxNews, October 2000)
      </dt>
      <dd>GnuCash, the open source accounting and finance system, is 
      gearing up to become the premier accounting package on Linux--and 
      is rapidly finding the means to do it. 
      Rob Browning, one of GnuCash's developers, explained that the 
      project has been expanding of late. "Right now we have four 
      full-time developers, and we're about to hire a few more," he said,
      attributing the growth of the staff--and the project--to financial 
      backing from Gnumatic Incorporated, announced August 14, 2000. 
      <br><br>
      </dd>

      <dt>
      <b>
      <a href="http://slashdot.org/articles/00/06/19/1721237.shtml">
      Gnucash v1.4.0 Released</a></b>
      (<a href="/press-archive/slashdot-2000-06/slashdot.org.articles.00.06.19.1721237.html">archival copy</a>)
      (Slashdot, June 2000)
      </dt>
      <dd>
      Ur@eus writes: "The Gnucash team has released the
      1.4.0 version of their wonderful Quicken-like personal
      finance manager. This is the first stable release since the move from
      Motif to GNOME. You find Gnucash 1.4.0 at Gnucash.org" This plugs
      a major gaping hole in Linux software: I've been using gnucash for a
      year now, and it's made great leaps in terms of features and stability. It
      isn't quicken, but its close enough for most of us. If you're having
      problems with the main link, try this mirror. 
      <br><br>
      </dd>

      <dt>
      <b><a href="http://linux.davecentral.com/bol_20000612.html">
      Best of Linux Winner</a></b>
      (<a href="/press-archive/davecentral-2000-06/bol_20000612.html">archival copy</a>)
      (Dave Central, June 2000)
      </dt>
      <dd>
      Computer finance management: it isn't just
      for Quicken anymore. In my continuing effort
      to move my checkbook balancing routine from
      disorganized receipts to clean Linux
      automation, I've enlisted the help of GnuCash.
      If this program can put my scattered financial
      house in order, imagine what it can do for an
      organized individual like you.
      <br><br>
      </dd>
      
      <dt>
      <b><a href="http://www.lwn.net/2000/0504/devel.phtml">
      Another look at gnucash</a></b>
      (<a href="/press-archive/lwn.net-2000-0504/devel.html">archival copy</a>)
      (LWN.net, May 2000)
      </dt>
      <dd>
      Last December we ran a review of gnucash that concluded 
      that the program - a free personal and small business finance 
      package - was not quite ready for prime time.  Inspired by 
      meeting the developers at the Linux Business Expo, LWN took 
      another look at gnucash. Conclusion: it has come a long way.  
      Your editor is pleased to announce a complete transition to 
      gnucash, thus getting rid of the last Windows application on 
      his system. Time to reclaim that partition. 
      <br><br>
      </dd>
      
      <dt>
      <b><a href="http://www.linuxworld.com/linuxworld/lw-2000-04/f_lw-04-vcontrol_4.html">
      There's no accounting for Linux</a></b>
      (<a href="/press-archive/linuxworld-2000-04/f_lw-04-vcontrol_4.html">archival copy</a>)
      (LinuxWorld, April 2000)
      </dt>
      <dd>
      Is Linux getting mainstream? Not if you base your conclusion 
      on the search results I just got at Freshmeat when I entered 
      "accounting" as my search term. I got geek soup: packet accounting, 
      multirouting traffic accounting, ISDN monitoring, network traffic 
      accounting meter, and, at the top of the list, a patch for the net 
      accounting daemon. 
      <br><br>
      </dd>
 
      <dt>
      <b><a href="http://www.linuxmall.com/news/?1,2">
      The GNUCash Project: Focusing on Money Management for Linux</a></b>
      (<a href="/press-archive/linuxmall/linuxmall.com,news,1,2,index.html">archival copy</a>) 
      (LinuxMall, March 2000)
      </dt>
      <dd>
      Five years ago, Linas Vepstas was working "with a .com. We were with 
      it, we were hip, we knew which side of our bread was buttered, we 
      were building this web site with NT... back then, NT was the once 
      and future king. It was crazy to bet against Microsoft." Then he
      discovered Linux--and launched the GNUCash Project, aimed at 
      developing stable, easy-to-use, flexible financial accounting 
      software for GNU/Linux. 
      <br><br>
      </dd>

      <dt>
      <b><a href="http://slashdot.org/articles/00/02/28/0945240.shtml">
      Gnucash 1.3.0 Beta Released</a></b> 
      (<a href="/press-archive/slashdot-2000-02/slashdot.org.articles.00.02.28.0945240.html">archival copy</a>)
      (Slashdot, February 2000)
      </dt>
      <dd>
      Jeremy Collins wrote in to tell us that Gnucash 1.3.0 Beta
      is out. We keep the software release announcements to a
      minimum and let more appropriate sites handle them,
      but this is pretty significant. Gnucash is the best quickenesque program
      under Linux today, and as we all know: it's those pesky end user apps
      that we lag behind other OSs. We've already got several word
      processors, spreadheets and image manipulation coming along nicely,
      but seeing development happen in the financial package area (also
      games and video) is important. Anyway, I'd suggest checking this one
      out: I've been using it since xacc and it's good if you're anal. Check out
      the ftp.gnucash.org and report bugs if you see 'em. 
      <br><br>
      </dd>
      
      <dt>
      <b><a href="http://lwn.net/1999/features/GnuCash/">
      A look at GnuCash 1.2.5</a></b>
      (<a href="/press-archive/lwn.net-1999-features/lwn.net,1999,features,GnuCash,index.html">archival copy</a>)
      (LWN.net, December 1999)
      </dt>
      <dd>
      Here is an unpleasant confession for an LWN author to make: 
      I actually still use Windows.  I boot it to run exactly one 
      program - an old, proprietary personal finance application. 
      It's the only thing I have ever found useful on Windows. 
      Occasionally I look around for a free replacement so that 
      I can recover that one last, small partition on my disk. 
      This article is the result of my latest attempt - driven, 
      additionally, by the sinking feeling that my current 
      application probably won't handle the next century very well...
      <br><br>
      </dd>

      <dt>
      <b><a href="http://www2.linuxjournal.com/articles/currents/008.html">
      Dispelling the Great "There Aren't Any Applications" Myth</a></b>
      (<a href="/press-archive/linuxjournal-1999-09/www2.linuxjournal.com,articles,currents,008.html">archival copy</a>)
      (Linux Journal, September 1999)
      </dt>
      <dd>
      Windows users say, "I'd love to run Linux, but the applications 
      just aren't there." Prove them wrong!  I'm sure you've heard the 
      following from your Windows-using friends: "According to what 
      I've been reading, Linux software is all server stuff and there 
      just aren't enough easy-to-use applications for desktop use." 
      So they keep using Windows. 
      <br><br>
      </dd>

      <dt>
      <b><a href="http://www.32bitsonline.com/article.php3?file=issues/199902/lj-19990208&page=1">Personal Finance Software</a></b>
      (<a href="/press-archive/32bitsonline-1999-02/lj-19990208.html">archival copy</a>)
      (32BitsOnline.com February 1999)
      </dt>
      <dd>
      Availability of specialized applications is one of the weaknesses of Linux
      compared to its operating system counterparts. In the realm of personal
      finance, none of the well-known software packages are available for Linux.
      Hopefully, Intuit will port their popular Quicken and QuickBooks line of
      products to the Linux platform someday. Until then, here are a few personal
      finance applications to get you balancing your checkbooks in the Linux
      environment.
      <br><br>
      </dd>
      </dl>


</td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/footer.phtml"); ?>
