<?php $title = "GnuCash Bug Rapportage"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-main-help.phtml"); ?>
</td>

<td valign=top>

<h1>GnuCash Bugs via GNOME Bugzilla</h1>

<p>
Het GnuCash bug rapportage systeem is nu ondergebracht bij GNOME bugzilla.
Dit geeft het GnuCash project de mogelijkheid bug reports te ontvangen die gegenereerd zijn door  
Bug Buddy en tevens kan gebruik gemaakt worden van de voordelen van het  GNOME bug 
team en haar overall administratie van GNOME bugs.
</p>
<p>
Wilt u het GNOME bug system gebruiken om een GnuCash bug door te geven,
gaat u dan naar <a href="http://bugzilla.gnome.org">bugzilla.gnome.org</a> 
en gebruik de formulieren voor uw verslagt.<br>
</p>

<p>
<ul>
<li><a href="http://bugzilla.gnome.org/buglist.cgi?product=GnuCash">Klik hier</a> 
voor een volledige lijst met GnuCash Bugs (waaronder oude reeds opgeloste bugs)</li>
<li><a href="http://bugzilla.gnome.org/buglist.cgi?product=GnuCash&bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=NEEDINFO&bug_status=REOPENED&chfieldto=Now&cmdtype=doit&namedcmd=nautilus-backgrounds&order=Reuse+same+sort+as+last+time&form_name=query">Klik Hier</a>
   om de openstaande bugs te bekijken.</li>
</ul>

</p>

<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/footer.phtml"); ?>
