<?php $title = "Draag bij!"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/nl/menu/menu-main-general.phtml"); ?>
</td>

<td valign=top>
<h1>Hoe kunt u bijdragen?</h1>

<p>
GnuCash is een Free Software project en de  
dynamiek van bijdragen lijkt erg op die van andere.
Wat u bijdraagt hangt af van uw kennis, 
de beschikbare tijd, en van wat u leuk vindt om te doen.
GnuCash zoekt beta-testers, programmeurs, schrijvers, 
mensen die vragen kunnen beantwoorden, vertalers en gewoon aardige mensen.   

<br><br>
<table>
<tr><td>
<b>Selecteer uw talent om te zien waar u in past:</b></td>
<td>
<form method=post>
<select name=contribute>
  <option value=programmer
   <?php if ($contribute == "programmer") { echo ("selected"); } ?>
  >Ik ben een programmeur</option>
  <option value=translator
   <?php if ($contribute == "translator") { echo ("selected"); } ?>
  >Ik ben een vertaler</option>
  <option value=fan
   <?php if ($contribute == "fan") { echo ("selected"); } ?>
  >Ik ben een  fan</option>
  <option value=webmaster
   <?php if ($contribute == "webmaster") { echo ("selected"); } ?>
  >Ik ben een webmaster</option>
  <option value=writer
   <?php if ($contribute == "writer") { echo ("selected"); } ?>
  >Ik ben een schrijver/verslaggever</option>
</select>
<input type=submit value=Go>
</td>
</table>
</form>

<?php
  if ($contribute != "") { 
		include($GLOBALS['DOCUMENT_ROOT']."/nl/contribute/contribute-".$contribute.".phtml");
  }
?>


</td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/footer.phtml"); ?>
