

U kunt de ontwikkeling van GnuCash ondersteunen of uw sympathie betuigen for wat al gedaan is  
middels een financiele gift aan de GnuCash community.

De 

cbbrowne's fsex
christmas cards

paypal

http://www.c2it.com


You can make your appreciation know by supporting the gnucash project financially through donations

GnuCash is Free Software developed

Christian Stimminbg  Street address http://info.cstim.de

Conrad Canterford (conrad@mail.watersprite.com.au)
GPO Box 355
Canberra, ACT 2601
Australia.
Foreign (non-Australian) currency is acceptable, though Australian
currency is much preferred. Note that I loose a significant portion of
foreign currency to the bank in conversion fees.


