<?php $title = "Features: What's New"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/nl/menu/menu-main-general.phtml"); ?>
</td>

<td valign=top>

<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr>
  <td><img src=/images/features/features_title.png></td>
  <td align=right><a href="javascript:window.close();"><img border=0 src=/images/close_window.png></a></td>
</tr>
</table>

<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr><td bgcolor=#000000><img src=/images/spacer.png height=1></td></tr>
</table>

<br>

<table cellpadding=4 cellspacing=0 border=0 width=100%>
<tr>
<td valign=top>
  <img src=/images/features/features_5_text.png><br><br>


<h2>Wat Is Nieuw in GnuCash 1.8.0?</h2>
De stabiele 1.8.x serie introduceert vele nieuwe onderwerpen die niet aanwezig waren in de oudere  gnucash-1.6.8 versie:

    <br><br>
<dl>
<dt><b>Periodieke Transacties</b>
<dd>U kunt nu periodieke transacties invoeren, met een automatische herinnering op het moment dat de termijn verstreken is, met de mogelijkheid een transactie uit te stellen zonder de periodieke transactie te annuleren, en met de mogelijkheid om een beperkt aantal transacties op te geven.
    <br><br>
<dt><b>Hypotheek &amp; Lening Aflossings Druide</b></dt>
<dd>Een geleide dialoog om aflossingen op te zetten als periodieke transactie.
    <br><br>
<dt><b>Boekhouden voor midden- en kleinbedrijf</b>
<dd>Vereenvoudig het managen van eenklein bedrijf met behulp van de Klant- en Leverancier tracking@, Rekeningenoverzichten, en Belasting en Nota Terijnen.
    <br><br>
<dt><b>OFX Import</b>
<dd>GnuCash is de eerste gratis software applicatie die het Open Financial Exchange protocol ondersteund waarvan steeds meer en meer banken gebruik maken. 
    <br><br>
<dt><b>HBCI ondersteuning</b>
<dd>GnuCash is de eerste gratis software application die het Duitse Home Banking Computer Information protocol ondersteund. Dit stelt Duitse gebruikers in staat lijsten binnen te halen en overboekingen te doen.
    <br><br>
<dt><b>Verbeterde Import Transactie Matching</b>
<dd>De ontwikkeling van OFX en HBCI support heeft ook geresulteerd in 
een verbeterd transactie matching systeem dat betrouwbaarder is in het herkennen van duplicaten in  geimporteerde bestanden.
    <br><br>


<dt><b>Nieuwe Gebruikershandleiding en Help</b>
<dd>Een nieuw help-subsystem dat zich richt op hoe welke taken uit te voeren is nu beschikbaar. 
    Daarnaast is er een handleiding die de gebruiker achtergrondinformatie geeft over boekhoudprincipes en hoe die in GnuCash werken.
    <br><br>
<dt><b>Nieuwe Verwerking van Valuta Transacties</b>
<dd>In GnuCash is het niet langer noodzakelijk apparte rekeningen aan te maken voor iedere individuele muntsoort. Transacties kunnen direct gemaakt worden tussen rekeningen in diverse valuta.
    <br><br>
<dt><b>Nieuwe Vormgeving Menus</b>
<dd>De GnuCash menus zijn opnieuw vormgegeven om beter te voldoen aan de GNOME Human Interface Richtlijnen.
    <br><br>
</dl>

<h2>Oude Favorieten</h2>
En natuurlijk zijn er een aantal favorieten uit eerdere versies beschikbaar:
	<br><br>
<dl>
<dt><b>Statement Reconciliation</b>
<dd>A reconcile window with running reconciled and cleared balances 
    makes balancing against bank statements easy. 
</dd>
<br><br>
<dt><b>Stock/Mutual Fund Portfolios</b> 
<dd>Track stocks individually (one per account) or in portfolio 
    of accounts (a group of accounts that can be displayed together). 
</dd>
<br><br>
<dt><b>QIF Import</b>
<dd>Intuit<sup>&reg;</sup> Quicken<sup>&reg;</sup>
    QIF bestanden kunnen geimporteerd worden en worden automatisch zodanig samengevoegd dat duplicaten verwijderd worden. 
</dd>
<br><br>
<dt><b>Internationale Eigenschappen</b>
<dd>GnuCash kan internationale valuta en data gebruiken. Bovendien zijn de menus vertaald naar 21 talen, waaronder
    Chinees, Deens, Frans, Duits, Hongaars, Italiaans, Japans, Nederlands, Noors, Pools, Portugees, Russisch, Spaans, Zweeds, Turks, en Engels.  
    Documentatie is beschikbaar in Engels, Frans, Portugees, en Spaans.
</dd>
<br><br>
<dt><b>Raportages</b>
<dd>Druk Balans Overzichten, Winst- en Verliesrekeningen, en dergelijke af. De rapporten kunnen opgeslagen als HTML of postscript, of worden geprint.
</dd>
<br><br>
<dt><b>Transactie Zoeker</b>
<dd>Een krachtigen transactie zoeker dialoog kan behulpzaam zijn bij het snel vinden van de naald in de hooiberg.
</dd>
<br><br>
<dt><b>Dubbele Invoer</b>
<dd>Wanneer ingeschakeld, moet iedere afboeking van een rekening gepaard gaan met een gelijkwaardige bijschrijving op een andere rekening. Dit zorgt er voor dat de boeken in balans zijn en blijven.
</dd>
<br><br>
<dt><b>Inkomsten/Uitgaven Rekening Types</b>
<dd>Inkomsten/Uitgaven Rekening Types (Categorien) maken het mogelijk de geldstroom te  
    categoriseren. Wanneer juist toegepast in combinatie 
    met de dubbele invoer controle, kunnen eenvoudig rapporten gegenereerd worden,
    zoals Winst & Verlies rapporten.
</dd>
<br><br>
<dt><b>Algemeen Register</b>
<dd>Meerdere rekeningen kunnen tegelijkertijd afgebeeld worden in een enkel registervenster. 
    Dit vergemakkelijkt het opsporen van invoerfouten.
</dd>
<br><br>
<dt><b>Online Aandelen &amp; Fondsen</b>
<dd>Koersen van Aandelen & Fondsen kunnen binnengehaald worden van websites en automatisch bijgewerkt worden.
</dd>
<br><br>
<dt><b>Afdrukken van Cheques</b>
<dd>Cheques kunnen afgedrukt worden in standaard formaten of gangbare cheques.
    Middels een GUI kunt u uw eigen formaat aanmaken.
</dd>
<br><br>
<dt><b>Valuta</b>
<dd>Verschillende rekeningen kunnen werken met verschillende valuta.
    Valuta verschuivingen tussen rekeningen worden volledig in balans gebracht wanneer de Dubble Invoer optie ingeschakeld is.  
</dd>
<br><br>
<dt><b>Multi-User SQL Ondersteuning</b>
<dd>Meerder gebruikers hebben nu tegelijkertijd
    toegang tot GnuCash data die opgeslagen ligt in een Postgres SQL backend.
    Postgres moet geinstalleerd zijn voor deze optie.
</dd>
<br><br>
</dl>


</td>
</tr>
</table>

<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr><td bgcolor=#000000><img src=/images/spacer.png height=1></td></tr>
</table>

<br>

<table border=0 cellspacing=0 cellpadding=0 width=100% align=center>
<tr>
  <td align=center>
	  <a href=/nl/features_4.phtml><img border=0 src=/images/features/features_previous.png></a>
		 |
	  <img border=0 src=/images/features/features_next_disabled.png>
	</td>
</tr>
</table>

</td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/footer.phtml"); ?>
