<?php $title = "History"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-main-other.phtml"); ?>
</td>

<td valign=top>
<b>Historie & Krediet</b><br><br>

   Wiens bloed zweet en tranen zitten er eigenlijk in?

<BR><BR><font size="+2"><b>Hoofdontwikkelaars</b></font>
<HR>
(In Chronologische Volgorde)
<br><br>


<dl>
  <dt>
  <b>Robin Clark</b>
  </dt>
  <dd>
    schreef het originele programma X-Accountant in Motif als een school project, 
    bracht het naar versie 0.9 in October 1997.  Hoewel elke regel code herschreven is, komt zijn naam in vrijwel elk bestand voor. Dat is de magie van  copyrights.
  </dd>

<BR>
<BR>

  <dt>
  <b>Linas Vepstas</b>
  </dt>
  <dd>
    vond aardig wat hij zag: de GUI was prima, de code was gedocumenteerden goed gestructureerd, en alles was onder GPL. En daarom herschreef hij het: 
    voegde cell-widgets toe aan XbaeMatrix, zodat de combobox en pijlen de GUI nog chiquer werden, herschreef de X-Accountant internals 
    om dubbele invoer mogelijk te maken, een rekekning hierarchie, splitste de transaction mini-engine, voegde ondersteuning toe voor aandelen, en verfraaide de help menus. Dit was versie  1.0 van January 1998. Voor version 1.1 &amp;
    1.2 werd de engineuitgebreid en verfijnd, en de registervenster 
    code werd volledig herontworpen en bijna volledig onafhankelijk gemaakt van  Motif (en GUI).
    Linas is nu actief binnen Gnumatic Incorporated, een bedrijf dat onstaan is ter versterking en ondersteuning van GnuCash voor iedereen, van thuisgebruiker tot commerciele en professionele accountants.
  </dd>

<BR>
<BR>

  <dt>
  <b>Jeremy Collins</b> 
  </dt>
  <dd>
    publiceerde het GnoMoney project en veranderde later de naam naar  GnuCash.   (Eigelijk was dat het resultaat van een stemming). Democratie is <b>niet</b>
    de manier om een naam te kiezen.) 
    Jeremy registreede de domainnaam en creerde en onderhield jarenlang de gnucash.org web site. uiteindelijk kreeg hij de initiele GTK/gnome code aan de praat.  
    Het nieuwste design is ook van Jeremy's hand.
  </dd>

<BR>
<BR>

  <dt>
  <b>Rob Browning</b> (<a href="/images/people/browning.srl.jpg">photo</a>)
  </dt>
  <dd>
    beledigde iedereen die geen Perl gebruikte, en toen we Perl support toevoegden dumpte hij Perl ten gunste van  Guile/Scheme support. Rob zette de infrastructuur op en onderhield die een tijdje, voegde gebruikersinstellingen toe, 
    en herschreef de rapporten in scheme. Een van Rob's laatste bijdragen is 
    overstap naar XML bestandformaat.
    Momenteel draagt hij bij aan scheme performance.  He is de g-wrap
    guile wrapper maintainer.
    <br><Br>
    Rob Browning komt uit Dallas en is momenteel een vluchteling van zijn
    doctoraal studie op het UT Computer Science department, waar hij gespecialiseerd is in robotics en computer vision. 
  </dd>

<BR>
<BR>

  <dt>
  <b>Yannick Le Ny</b>
  </dt>
  <dd>
    Onze Franse vertaler.
    Hij heeft de menus, berichten, README en documentatie vertaald naar het Frans.
    Hetzelfde deed hij met de franse vertaling voor de GnuCash website, hard werkend om het up to date te houden.
    Maakte patches voor de Yahoo Europe updates.
  </dd>

<BR>
<BR>

  <dt>
  <b>Dave Peticolas</b> (<a href="/images/people/peticolas.jpg">photo</a>)
  </dt>
  <dd>
    hackt gedreven GnuCash. Maar hij kan stoppen wanneer hij wil. Echt waar. 
    (Omdat hij de gatekeeper van de GnuCash CVS tree is, moet je wel aardig tegen hem blijven,
    anders stopt hij misschien wel met hacken midden in jouw patch).
  </dd>

<BR>
<BR>

  <dt>
  <b>Bill Gribble</b>
  </dt>
  <dd>
    is niet beascheiden. Dus blijf niet bescheiden wanneer je een fout vindt in  
    zijn code: QIF import, query API en transactie search, check-printing,
    commodity en valuta support, gtkhtml integratie en rapport printing,
    pgp support, guppi integratie, en de layout van het hoofdscherm.
  </dd>


<BR>
<BR>

  <dt>
  <b>Robert Graham Merkel</b>
  </dt>
  <dd>
    Rapportage, gnome, en config patches
  </dd>

<BR>
<BR>

  <dt>
  <b>James LewisMoss</b>
  </dt>
  <dd>
    XML Refactoring. Automatische test suite.
  </dd>


<BR>
<BR>
<dt><b>Carol Champagne</b></dt>
<dd>Eerste versie van de GnuCash gebruikershandleiding</dd>
<BR>
<BR>

  <dt>
  <b>Christian Stimming</b> (<a href="/images/people/cstim.jpg">photo</a>)
  </dt>
  <dd>
    leverde de belangrijkste bijdragen aan de huidige rapport infrastructuur, 
    creeerde vele belangrijke rapporten.  Hij is momenteel de 
    internationaliseringsguru, als supervisor over de vertalingen van gnucash in 
    21 verschillende talen. He speelde een belangrijke rol in het ontwikkelen van HBCI voor Duitse gebruikers.
  </dd>

<BR>
<BR>
<dt><b>Derek Atkins</b> (<a href="/images/people/warlord8.tif">photo</a>) 
    (<a href="/images/people/warlord.jpg">photo</a>) </dt>
<dd>Krijgsheer die de RPC backend voor beginners maakte, en is heeft de leiding in de ontwikkeling van de small business features.</dd>
<BR>
<BR>
<dt><b>Joshua Sled</b></dt>
<dd>jsled creeerde de totale transactie-planning infrastructuur.</dd>
<BR>
<BR>
<dt><b>Chris Lyttle</b> (<a href="/images/people/wilddev.jpg">photo</a>) </dt>
<dd>wilddev</dd>
<BR>
<BR>
<dt><b>David Hampton</b> (<a href="/images/people/hampton.jpg">photo</a>) </dt>
<dd></dd>
<BR>
<BR>
<dt><b>Benoit Gregoire</b></dt>
<dd>schreef libOFX, waarmee GnuCash het
    OFX (Open Financial Exchange) protocol and bestandformaat kan begrijpen.</dd>
<BR>
<BR>

</dl>

<BR>


<font size="+2"><b>Fixers en Patchers</b></font>
<hr>
(In Alphabetical Order)

<dl>

<dt><b>Andrew Arensburger</b> &lt;<i>arensb@cfar.umd.edu</i>&gt; </dt><dd> voor FreeBSD &amp; andere patches</dd>
<dt><b>Matt Armstrong</b> &lt;<i>matt_armstrong@bigfoot.com</i>&gt; </dt><dd> voor diverse correcties</dd>
<dt><b>Fred Baube</b> &lt;<i>fred@moremagic.com</i>&gt; </dt><dd> voor poging tot Java port/MoneyDance</dd>
<dt><b>Dennis Björklund</b> &lt;<i>dennisb@cs.chalmers.se</i>&gt; </dt><dd> Zweedse vertaling</dd>
<dt><b>Per Bojsen</b> &lt;<i>bojsen@worldnet.att.net</i>&gt; </dt><dd> verschilledne core dump correcties</dd>
<dt><b>Terry Boldt</b> &lt;<i>tboldt@attglobal.net</i>&gt; </dt><dd> financiele calculator en expressie parser</dd>
<dt><b>Simon Britnell</b> &lt;<i>simon.britnell@peace.com</i>&gt; </dt><dd> patch voor RPM spec</dd>
<dt><b>Christopher B. Browne</b> &lt;<i>cbbrowne@hex.net</i>&gt; </dt><dd> voor perl, veel van de schema's en documentatie</dd>
<dt><b>Conrad Canterford</b> &lt;<i>conrad@mail.watersprite.com.au</i>&gt; </dt><dd> register bug correctie</dd>
<dt><b>Bill Carlson</b> &lt;<i>wwc@wwcnet.nu</i>&gt; </dt><dd>verbetering performance</dd>
<dt><b>Graham Chapman</b> &lt;<i>grahamc@zeta.org.au</i>&gt; </dt><dd> voor het xacc-rpts addon pakket</dd>
<dt><b>George Chen</b> &lt;<i>georgec@sco.com</i>&gt; </dt><dd> voor MS-Money QIF's &amp; correcties</dd>
<dt><b>Albert Chin-A-Young</b> &lt;<i>china@thewrittenword.com</i>&gt; </dt><dd> configure.in patch</dd>
<dt><b>Kenneth Christiansen</b> &lt;<i>kenneth@gnome.org</i>&gt; </dt><dd> Deense vertaling</dd>
<dt><b>Jeremey Collins</b> &lt;<i>jcollins@gnucash.org</i>&gt; </dt><dd> voor GnoMoney &amp; GTK port</dd>
<dt><b>Matthew Condell</b> &lt;<i>mcondell@bbn.com</i>&gt; </dt><dd> FreeBSD patch</dd>
<dt><b>Patrick Condron</b> &lt;<i>pcondon@rackspace.com</i>&gt; </dt><dd> voor webserver en T1 verbinding van rackspace.com</dd>
<dt><b>Raphael Dechenaux</b> &lt;<i>raphael.dechenaux@worldonline.fr</i>&gt; </dt><dd> register patch</dd>
<dt><b>Ciaran Deignan</b> &lt;<i>Ciaran.Deignan@bull.net</i>&gt; </dt><dd> voor AIX binaire versie</dd>
<dt><b>Glen Ditchfield</b> &lt;<i>gjditchfield@acm.org</i>&gt; </dt><dd> aangepaste documentatie</dd>
<dt><b>Tyson Dowd</b> &lt;<i>tyson@tyse.net</i>&gt; </dt><dd> voor config/make patches &amp; debian maint</dd>
<dt><b>Koen D'Hondt</b> &lt;<i>ripley@xs4all.nl</i>&gt; </dt><dd> voor Solaris patches naar XmHTML</dd>
<dt><b>Bob Drzyzgula</b> &lt;<i>bob@mostly.com</i>&gt; </dt><dd> voor budgeting design notes</dd>
<dt><b>Paul Fenwick</b> &lt;<i>pjf@schools.net.au</i>&gt; </dt><dd> ASX ondersteuning, Finance::Quote</dd>
<dt><b>Hubert Figuiere</b> &lt;<i>hfiguiere@teaser.fr</i>&gt; </dt><dd> patch naar gnc-prices</dd>
<dt><b>Valek Filippov</b> &lt;<i>frob@df.ru</i>&gt; </dt><dd> Russische vertaling</dd>
<dt><b>Jan-Uwe Finck</b> &lt;<i>jufi@nerdnet.de</i>&gt; </dt><dd> voor Duitse message vertaling</dd>
<dt><b>Kevin Finn</b> &lt;<i>kevinfinn@mediaone.net</i>&gt; </dt><dd> auto-decimale punt patch, opties patch</dd>
<dt><b>Ron Forrester</b> &lt;<i>rjf@aracnet.com</i>&gt; </dt><dd> voor gnome patches</dd>
<dt><b>Dave Freese</b> &lt;<i>DFreese@osc.uscg.mil</i>&gt; </dt><dd> voor schrikkeljaar correctie</dd>
<dt><b>John Goerzen</b> &lt;<i>jgoerzen@complete.org</i>&gt; </dt><dd> file i/o fix voor 64-bit architecturen</dd>
<dt><b>Hans de Graaff</b> &lt;<i>hans@degraaff.org</i>&gt; </dt><dd> xml patches</dd>
<dt><b>Bill Gribble</b> &lt;<i>grib@billgribble.com</i>&gt; </dt><dd> qif importering code</dd>
<dt><b>Mitsuo Hamada</b> &lt;<i>mhamada@redhat.com</i>&gt; </dt><dd> Japanse vertalings</dd>
<dt><b>Otto Hammersmith</b> &lt;<i>otto@bug.redhat.com</i>&gt; </dt><dd> voor RedHat RPM version</dd>
<dt><b>Eric Hanchrow</b> &lt;<i>offby1@blarg.net</i>&gt; </dt><dd> updated currency documentation</dd>
<dt><b>Alexandru Harsanyi</b> &lt;<i>haral@codec.ro</i>&gt; </dt><dd> voor core dumps, lockups, gtk work</dd>
<dt><b>John Hasler</b> &lt;<i>john@dhh.gt.org</i>&gt; </dt><dd> engine patch</dd>
<dt><b>Jon Kåre Hellan</b> &lt;<i>hellan@acm.org</i>&gt; </dt><dd> misc core dump correcties</dd>
<dt><b>Claus Hindsgaul</b> &lt;<i>claus_h@image.dk</i>&gt; </dt><dd> Deense vertaling</dd>
<dt><b>Miquel Jordana Vilamitjana</b> &lt;<i>jjvmjv@mundomail.net</i>&gt; </dt><dd> Spaanse vertaling van handleiding</dd>
<dt><b>Prakash Kailasa</b> &lt;<i>PrakashK@bigfoot.com</i>&gt; </dt><dd> voor gnome build correcties</dd>
<dt><b>Alexey Kakunin</b> &lt;<i>small@arcadia.spb.ru</i>&gt; </dt><dd> quickfill patch voor cyrillisch</dd>
<dt><b>Ben Kelly</b> &lt;<i>ben.kelly@ieee.org</i>&gt; </dt><dd> voor motif menu bug fix, core dump correcties</dd>
<dt><b>Tom Kludy</b> &lt;<i>tkludy@csd.sgi.com</i>&gt; </dt><dd> voor SGI Irix port</dd>
<dt><b>Sven Kuenzler</b> &lt;<i>sk@xgm.de</i>&gt; </dt><dd> voor SuSE README bestand</dd>
<dt><b>Bryan Larsen</b> &lt;<i>blarsen@ada-works.com</i>&gt; </dt><dd> guile budget rapport</dd>
<dt><b>Graham Leggett</b> &lt;<i>minfrin@sharp.fm</i>&gt; </dt><dd> voor plossen van een crash probleem</dd>
<dt><b>Ted Lemon</b> &lt;<i>mellon@andare.fugue.com</i>&gt; </dt><dd> voor NetBSD port</dd>
<dt><b>Grant Likely</b> &lt;<i>glikely@nortelnetworks.com</i>&gt; </dt><dd> gnome en engine patches</dd>
<dt><b>Duarte Loreto</b> &lt;<i>happyguy_pt@hotmail.com</i>&gt; </dt><dd> Portugese vertalingen</dd>
<dt><b>Heath Martin</b> &lt;<i>martinh@pegasus.cc.ucf.edu</i>&gt; </dt><dd> gnome patches, belangrijk register werk</dd>
<dt><b>Matt Martin</b> &lt;<i>mgmartin@abacusnet.net</i>&gt; </dt><dd> guile foutafhandelingscode</dd>
<dt><b>Robert Graham Merkel</b> &lt;<i>rgmerk@mira.net</i>&gt; </dt><dd> reporting, gnome, en config patches</dd>
<dt><b>Juan Manuel García Molina</b> &lt;<i>juanmagm@mail.com</i>&gt; </dt><dd> spanse vertaling</dd>
<dt><b>Christopher Molnar</b> &lt;<i>molnarc@mandrakesoft.com</i>&gt; </dt><dd> maakte systeem patch</dd>
<dt><b>Tim Mooney</b> &lt;<i>mooney@dogbert.cc.ndsu.NoDak.edu</i>&gt; </dt><dd> port naar alpha-dec-osf4.0f</dd>
<dt><b>G. Allen Morris III</b> &lt;<i>gam3@ann.softgams.com</i>&gt; </dt><dd> voor QIF core dump</dd>
<dt><b>James LewisMoss</b> &lt;<i>dres@debian.org</i>&gt; </dt><dd> design doc patches, xml, test suite</dd>
<dt><b>Steven Murdoch</b> &lt;<i>sjmurdoch@linuxfan.com</i>&gt; </dt><dd> gnc-prices fix voor beurs van Londen</dd>
<dt><b>Brent Neal</b> &lt;<i>brent@baton.phys.lsu.edu</i>&gt; </dt><dd> TIAA-CREF ondersteuning.</dd>
<dt><b>Johnny Ernst Nielsen</b> &lt;<i>j.e.nielsen@iname.com</i>&gt; </dt><dd> Deense vertaling</dd>
<dt><b>Stefan Nobis</b> &lt;<i>stefan-ml@snobis.de</i>&gt; </dt><dd> Duitse vertaling patch</dd>
<dt><b>Peter Norton</b> &lt;<i>spacey@inch.com</i>&gt; </dt><dd> voor poging tot een GTK port</dd>
<dt><b>OmNiBuS</b> &lt;<i>webmaster@obsidian.uia.net</i>&gt; </dt><dd> web site graphics &amp; inhoud</dd>
<dt><b>Gordon Oliver</b> &lt;<i>gordo@pincoya.com</i>&gt; </dt><dd> multiple valuta status lijn patch</dd>
<dt><b>Myroslav Opyr</b> &lt;<i>mopyr@IPM.Lviv.UA</i>&gt; </dt><dd> voor misc patches</dd>
<dt><b>Dave Peticolas</b> &lt;<i>dave@krondo.com</i>&gt; </dt><dd> extensive intelligent patches</dd>
<dt><b>Laurent P'elecq</b> &lt;<i>laurent.pelecq@wanadoo.fr</i>&gt; </dt><dd> i18n patches met gettext</dd>
<dt><b>Alain Peyrat</b> &lt;<i>Alain.Peyrat@nmu.alcatel.fr</i>&gt; </dt><dd> voor configure.in patches</dd>
<dt><b>Peter Pointner</b> &lt;<i>peter@wuzel.m.isar.de</i>&gt; </dt><dd> QIF import correcties, Qt patches</dd>
<dt><b>Gavin Porter</b> &lt;<i>maufk@csv.warwick.ac.uk</i>&gt; </dt><dd> voor euro stijl data</dd>
<dt><b>Tomas Pospisek</b> &lt;<i>tpo@spin.ch</i>&gt; </dt><dd> debian patches</dd>
<dt><b>Ron Record</b> &lt;<i>rr@sco.com</i>&gt; </dt><dd> voor SCO Unixware &amp; OpenServer binaries</dd>
<dt><b>Keith Refson</b> &lt;<i>Keith.Refson@earth.ox.ac.uk</i>&gt; </dt><dd> Solaris correcties</dd>
<dt><b>Dirk Schoenberger</b> &lt;<i>schoenberger@signsoft.com</i>&gt; </dt><dd> Qt/KDE werk</dd>
<dt><b>Jan Schrage</b> &lt;<i>jan.schrage@urz.uni-heidelberg.de</i>&gt; </dt><dd> documentatie patches</dd>
<dt><b>Christopher Seawood</b> &lt;<i>cls@seawood.org</i>&gt; </dt><dd> voor XbaeMatrix core dump</dd>
<dt><b>Alessandro Seveso</b> &lt;<i>aleseveso@tiscalinet.it</i>&gt; </dt><dd> Italiaanse vertalingen</dd>
<dt><b>Mike Simons</b> &lt;<i>msimons@fsimons01.erols.com</i>&gt; </dt><dd> misc configure.in patches</dd>
<dt><b>Keld Simonsen</b> &lt;<i>keld@dkuug.dk</i>&gt; </dt><dd> Deense vertaling</dd>
<dt><b>Richard Skelton</b> &lt;<i>rich@brake.demon.co.uk</i>&gt; </dt><dd> voor Solaris cleanup</dd>
<dt><b>Henning Spruth</b> &lt;<i>spruth@bigfoot.com</i>&gt; </dt><dd> voor Duitse text &amp; euro datum rework</dd>
<dt><b>Ben Stanley</b> &lt;<i>bds02@uow.edu.au</i>&gt; </dt><dd> test infrastructure</dd>
<dt><b>Robby Stephenson</b> &lt;<i>robby.stephenson@usa.net</i>&gt; </dt><dd> register &amp; bestandshistorie patches</dd>
<dt><b>Christian Stimming</b> &lt;<i>stimming@uclink.berkeley.edu</i>&gt; </dt><dd> rapport patch</dd>
<dt><b>Bartek Szady</b> &lt;<i>bszx@bszxdomain.edu.eu.org</i>&gt; </dt><dd> engine en build systeem patches</dd>
<dt><b>Herbert Thoma</b> &lt;<i>tma@iis.fhg.de</i>&gt; </dt><dd> gnome register &amp; euro support patches</dd>
<dt><b>Diane Trout</b> &lt;<i>detrout@earthlink.net</i>&gt; </dt><dd> scheme qif import patch</dd>
<dt><b>Richard -Gilligan- Uschold</b> &lt;<i>uschold@cs.ucf.edu</i>&gt; </dt><dd> tax rapport &amp; txf export</dd>
<dt><b>Richard Wackerbarth</b> &lt;<i>rkw@dataplex.net</i>&gt; </dt><dd> patch voor gnc-prices, qif import correcties</dd>
<dt><b>Rob Walker</b> &lt;<i>rob@valinux.com</i>&gt; </dt><dd> guile en register patches</dd>
<dt><b>David Woodhouse</b> &lt;<i>dwmw2@infradead.org</i>&gt; </dt><dd> Engelse (UK) vertalingen</dd>
<dt><b>Ken Yamaguchi</b> &lt;<i>gooch@ic.EECS.Berkeley.EDU</i>&gt; </dt><dd> QIF import correcties; MYM import</dd>
<dt><b>Shimpei Yamashita</b> &lt;<i>shimpei@gol.com</i>&gt; </dt><dd> Japanse vertaling</dd>
</dl>


</td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/footer.phtml"); ?>
