<?php $title = "Open Source Accounting Software"; ?>
<?php if (!ini_get('register_globals')) {
 include("../emulate_globals_on.php");
}
?>
<?php include("components/header.phtml"); ?>
<?php include("menu/menu-main.phtml"); ?>

  </td>
  <td valign=top width=98%>
  
<h1>Welkom op GnuCash.org</h1>

<p>Als u op zoek bent geweest naar een manier om uw persoonlijke financien bij te houden met Gratis Software, ben u op de juiste plek! Eenvoudig in gebruik, maar toch krachtig en flexibel stelt GnuCash u in staat bankrekeningen, aandelen, inkomsten en uitgaven bij te houden. Net zo eenvoudig te gebruiken als een kasboek register, gebasseerd op profesionele boekhoud principes om accuraatheid te garanderen. GnuCash wordt ondersteund door een actieve ontwikkelingsgroep en bloeit op tot een volwaardig boekhoudsysteem. Ontwikkeld onder de GPL hoeft u zich geen zorgen te maken dat het programma verouderd: GnuCash zal er voor u zijn.. </p>


<p>Op deze website is ter bevordering van het Gnucash.org software
ontwikkelingsproject. Wij zijn toegewijd in het ontwikkelen van prima
financiele software voor GNU/Linux en Unix gebruikers. Hierbij zijn
inbegrepen de ontwikkeling van programming API's, libraries en componenten
die gebruikt kunnen worden voor thuisgebruik en voor zakelijk gebruik.  Door
de nadruk te leggen op aspecten als eenvoud in gebruik, modulair ontwerp,
goed-ontworpen interfaces en een goed-gedocumenteerde code, hopen we dat
GnuCash en de bijbehorende financiele libraries de keuze worden voor een GNU
generatie van programmeerders en gebruikers.</p>

<p>Inderdaar, GnuCash werkt nu op Mac OSX, alsook onder GNU/Linux, *BSD, en de 
traditionele Unixes: Solaris, AIX, en andere.</p>

<h1>Nieuws</h1>
      

<?php 
$en_newspath = "../news/en/";
$lang_newspath = "../news/nl/";
include("../news/news-script.php"); ?>

  </td>

<?php include("components/footer.phtml"); ?>
