<?php $title = "Open Source Accounting Software"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/nl/menu/menu-main.phtml"); ?>

	</td>
  <td valign=top width=98%>
  
<h1>Welkom op GnuCash.org</h1>
  
<font size=-1>
Als u op zoek bent geweest naar een manier om uw persoonlijke financien bij te houden met Gratis Software, ben u op de juiste plek! Eenvoudig in gebruik, maar toch krachtig en flexibel stelt GnuCash u in staat bankrekeningen, aandelen, inkomsten en uitgaven bij te houden. Net zo eenvoudig te gebruiken als een kasboek register, gebasseerd op profesionele boekhoud principes om accuraatheid te garanderen. GnuCash wordt ondersteund door een actieve ontwikkelingsgroep en bloeit op tot een volwaardig boekhoudsysteem. Ontwikkeld onder de GPL hoeft u zich geen zorgen te maken dat het programma verouderd: GnuCash zal er voor u zijn.. 
<br><br>
Op deze website is ter bevordering van het Gnucash.org software ontwikkelingsproject. Wij zijn toegewijd in het ontwikkelen van prima financiele software voor GNU/Linux en Unix 
gebruikers. Hierbij zijn inbegrepen de ontwikkeling van programming API's, libraries en componenten die gebruikt kunnen worden voor thuisgebruik en voor zakelijk gebruik.
Door de nadruk te leggen op aspecten als eenvoud in gebruik, modulair ontwerp, goed-ontworpen  interfaces en een goed-gedocumenteerde code, hopen we dat GnuCash en de bijbehorende financiele libraries de keuze worden voor een GNU generatie van programmeerders en gebruikers.
<br><br>
Inderdaar, GnuCash werkt nu op Mac OSX, alsook onder GNU/Linux, *BSD, en de 
traditionele Unixes: Solaris, AIX, en andere.
</font>


<h1>Nieuws</h1>

       

<?php
    //  change  this  to  the  directory  of  your  news  files 
    //  they  should  be  plain  ASCII  text  files  with  extension  ".txt" 

    # Perhaps we should be using this, but it won't work until we have
    # the DocumentRoot set up.
    # $newspath = $GLOBALS['DOCUMENT_ROOT']."/news/

    # So we'll just do this for now...
    $newspath  =  "news/"; 

    //  Declare  array  to  hold  filenames 
    $newsfile  =  array(); 
    
    //  Create  handle  to  search  directory  $newspath  for  files 
    $hd  =  dir($newspath); 
    
    //  Get  all  files  and  store  them  in  array 
    while(  $filename  =  $hd->read()  )  { 
        $s=strtolower($filename); 
        if  (strstr($s, ".txt"))  { 
            //  Determine  last  modification  date 
            $lastchanged=filemtime($newspath.$filename); 
            $newsfile[$filename]  =  $lastchanged; 
        }    
    } 
    
    //  Sort  files  in  descending  order 
    arsort($newsfile); 
    //  Output  files  to  browser 
    for(reset($newsfile);  $key  =  key($newsfile);  next($newsfile))  
    { 
        $fa  =  file($newspath.$key); 
        $n=count($fa); 

        echo("<table border=0 cellpadding=1 cellspacing=0 width=\"100%\">");
        echo("<tr><td valign=middle align=center bgcolor=#666699>");
        echo("<table border=0 cellpadding=5 cellspacing=1 bgcolor=#cacaf7 width=\"100%\">");
        echo("<tr><td valign=top>");
        echo("<table border=0 cellpadding=0 cellspacing=0>");
        echo("<tr><td> <img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>");
       
        echo("<td>");
	print $fa[0];
	print  " - <font size=-1><b>(".date( "Y-m-d",$newsfile[$key]);
	print  "&nbsp; &nbsp;".date( "H:i:s",$newsfile[$key]). ")</b></font></td>\n"; 
        echo("</tr> </table> </td> </tr>");
        echo("<tr bgcolor=#ffffff> <td valign=top> <font size=-1>");

        for  ($i=1;  $i<$n;  $i=$i+1)  { 
	    print $fa[$i];
        } 
        echo("</font> </td> </tr> </table> </tr> </table><br><br>");

    }    
    
    $hd->close();  
    ?>  

<font size=-2>
<a href="/surf/guppi-pie-demo.html">test</a>
<a href="/surf/short.gml">test2</a>
<a href="/surf/demo.gml">test3</a>
</font>
                  

  </td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/footer.phtml"); ?>
