
<?php $title = "GnuCash op IRC"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/nl/menu/menu-main-help.phtml"); ?>
</td>

<td valign=top>
<h1>GnuCash op IRC</h1>

Maak plezier (of zoek hulp bij het installeren of gebruiken van GnuCash) 
en bespreek de ontwikkeling van GnuCash met programmeurs en gebruikers op IRC.
 Kom naar kanaal #gnucash op irc.gnome.org.

<?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/footer.phtml"); ?>
