<?php $title = "Related Financial Software"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-main-other.phtml"); ?>
</td>


<td valign=top>
<h1>Gerelateerde Financiele Programma's</h1>

<table>
<tr><td>
<b>Selecteer eem sectie:</b></td>
<td>
<form method=post>
<select name=linkpage>
  <option value=general
  <?php if ($linkpage == "general") { echo ("selected"); } ?>
  >Algemene Referenties</option>
  <option value=utilities
  <?php if ($linkpage == "utilities") { echo ("selected"); } ?>
  >Utilities</option>
  <option value=palm
  <?php if ($linkpage == "palm") { echo ("selected"); } ?>
  >Palm Computing</option>
  <option value=stock
  <?php if ($linkpage == "stock") { echo ("selected"); } ?>
  >Aandelen handel & Technische Analyse</option>
  <option value=quote
  <?php if ($linkpage == "quote") { echo ("selected"); } ?>
  >Quote Sources, Tools</option>
  <option value=money
  <?php if ($linkpage == "money") { echo ("selected"); } ?>
  >Electronisch Valuta</option>
  <option value=erp
  <?php if ($linkpage == "erp") { echo ("selected"); } ?>
  >Business, ERP Projecten</option>
  <option value=xml
  <?php if ($linkpage == "xml") { echo ("selected"); } ?>
  >XML en Overige Data Formaten</option>
  <option value=misc
  <?php if ($linkpage == "misc") { echo ("selected"); } ?>
  >Diverse</option>
  <option value=obsolete
  <?php if ($linkpage == "obsolete") { echo ("selected"); } ?>
  >Historische Referenties</option>
  <option value=review
  <?php if ($linkpage == "review") { echo ("selected"); } ?>
  >Gnucash Reviews & Beoordelingen</option>
</select>
<input type=submit value=Go>
</td>
</table>
</form>

<?php
  if ($linkpage != "") { 
	include($GLOBALS['DOCUMENT_ROOT']."/en/links/links-".$linkpage.".phtml");
  } else {
	include($GLOBALS['DOCUMENT_ROOT']."/en/links/links-general.phtml");
  }
?>


</td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/footer.phtml"); ?>
