<?php $title = "Mailing Lijsten"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/nl/menu/menu-main-help.phtml"); ?>
</td>

<td valign=top>
<h1>GnuCash Mailing Lijsten</h1>

Er zijn een aantal GnuCash mailing lijsten voor verschillende soorten doelgroepen: 
sommige zijn gericht op gebruikers, andere op ontwikkelaars.  Klik op de vette tekst voor 
instructies hoe in en uit te schrijven.

<p>

<table border=0 cellpadding=1 cellspacing=0 width="100%">
  <tr>
  <td valign=middle align=center bgcolor=#666699>
   <table border=0 cellpadding=5 cellspacing=1 bgcolor=#cacaf7 width="100%">
   <tr>
     <td bgcolor=#666699 width=25%><font color=#ffffff><b>Mailing Lijst</b></td>
     <td bgcolor=#666699 width=75%><font color=#ffffff><b>Beschrijving</b></td>
   </tr>
   <!-------------------------------------------------------------->
   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><A HREF="/cgi-bin/mailman/listinfo/gnucash-announce"> gnucash-announce@gnucash.org</A></td>
       </tr>
       </table>
     </td>
     <td valign=top>Aankondiging mailing lijst: Post naar deze moderated lijst, kondigt belangrijke gebeurtenissen en nieuws aan omtrent GnuCash. Dit is een kleine mailing lijst (1 of minder berichten per week).</td>
   </tr>
   <!-------------------------------------------------------------->
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><A HREF="/cgi-bin/mailman/listinfo/gnucash-user"> gnucash-user@gnucash.org</A></td>
       </tr>
       </table>
     </td>
     <td valign=top>
    Gebruikers mailing lijst: Discussies hoe GnuCash te installeren, af te stellen en te gebruiken, en discussies zoals basale boekhoudprincipes.
    Dit is bij tijd en wijle een mailing lijst met veel berichten (2 tot 30 berichten per dag).
	   </td>
   </tr>
   <!-------------------------------------------------------------->
   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><A HREF="/cgi-bin/mailman/listinfo/gnucash-devel"> gnucash-devel@gnucash.org</A></td>
       </tr>
       </table>
     </td>
     <td valign=top>
    Developer's mailing lijst: Discussies over de huidige en toekomstige features
    en functies, en hoe ze geimplementeerd moeten owrden.  
    Dit is een high-volume mailing lijst (2 tot 30 berichten per dag).
		 </td>
   </tr>
   <!-------------------------------------------------------------->
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><A HREF="/cgi-bin/mailman/listinfo/gnucash-de"> gnucash-de@gnucash.org</A></td>
       </tr>
       </table>
     </td>
     <td valign=top>
     Dies ist die Mailingliste für deutsche GnuCash-Benutzer. 
     Die Sprache auf dieser Liste ist Deutsch.
     
	   </td>
   </tr>
   <!-------------------------------------------------------------->
   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><A HREF="/cgi-bin/mailman/listinfo/gnucash-patches"> gnucash-patches@gnucash.org</A></td>
       </tr>
       </table>
     </td>
     <td valign=top>
    Developer's mailing lijst: Insturen en discussie van patches, 
    en aankondiging van CVS tree updates.  
    Patches moeten in <tt>makepatch</tt> formaat zijn.
    Patches mogen ingaan tegen de broncode, documentatie, of vertalingen.
    Dit is een high-volume mailing lijst (2 tot 30 berichten per dag).
    
	   </td>
   </tr>
   <!-------------------------------------------------------------->
   </table>
</tr>
</table>

</td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/footer.phtml"); ?>
