
<?php $title = "Accounting Software voor Linux"; ?>
<?php if (!ini_get('register_globals')) {
 include("../emulate_globals_on.php");
}
?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/nl/menu/menu-main.phtml"); ?>

	</td>
  <td valign=top width=98%>
  

<h1>Older Announcements</h1>

<font size=-1>
Dit is een archief van de aankondigingen die ooit op de  
GnuCash home page hebben gestaan.
<br><br>
</font>


<?php
    # indicate where to get translated news from ... 
    $native_newspath  =  "news/old/";
    $alt_newspath  =  "../news/old/";
    include($GLOBALS['DOCUMENT_ROOT']."/php-scripts/news-script.php");
    ?>  

  </td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/footer.phtml"); ?>

