<?php $title = "Survey"; ?>
<?php if (!ini_get('register_globals')) {
 include("../emulate_globals_on.php");
}
?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/nl/menu/menu-main-general.phtml"); ?>
</td>

<td valign=top>
<h1>GnuCash Enquete</h1>

<b>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</b>
<p>
<b>
De GnuCash Enquete is gesloten.  De resultaten kunt u 
<a href="/nl/quiz-results.phtml">hier</a> bekijken.
</b>

<p>
<b>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</b>
<p>
<b>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</b>
<p>
<b>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</b>
<p>

GnuCash is op een cruciaal punt gekomen in haar ontwikkeling.  De meeste implementaties die verwacht 
mogen worden van een basaal boekhoudprogramma zijn aanwezig, en de paar die nog niet aanwezig zijn, zullen snel verwerkt worden.   Daarna zijn er 
<a href="/nl/roadmap.phtml">
verschillende kanten waar GnuCash heen kan gaan</a>.
Maar waarheen?  Deze enquete zal helpen in de beslissing hierover.  Uiteraard is GnuCash
een project dat gedragen wordt door vrijwilligers en iedere programmeur kan met een beetje goede wil elke applicatie implementeren die hij wil.   Maar misschien zal deze enquete helpen in het sturen van deze discussie. Dit is uw kans om uw wensen kenbaar te maken.
<p>
Opgelet: dit is een grote enquete. Er zijn 45 vragen, onderverdeeld in 6 secties:
<ul>
<li>Algemeen
<li>Commercialisering van GnuCash
<li>GnuCash gebruiken
<li>Toekomstige implementaties
<li>Online Bankieren
<li>Persoonlij Profiel
</ul>

Sla gerust de vragen over die u niet begrijpt, of waar u geen mening over heeft.
Maar a.u.b.: slechts een formulier per persoon.
<p>

<?php $sid=2;
       include("/home/httpd/tools/phpESP-1.2beta3/public/handler.php");?> 



</td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/footer.phtml"); ?>
