<?php $title = "Software Requirements"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/nl/menu/menu-main-general.phtml"); ?>
</td>

<td valign=top>

<h1>Software Dependencies</h1>

GnuCash depends on a number of important contributing technologies 
in order to implement its major functions.  If you want to compile
and work on GnuCash, you will need to install a recent version of 
these libraries.
<br><br>
Without a good package manager (<i>e.g.</i> Debian <tt>apt-get</tt>),
it can be quite tedious to find, download and install all of the 
required packages (<i>nightmare</i> is a word that has been used).
Therefore, if you are not a programmer, and just want to <b>use</b> 
GnuCash, you should stick to the version supplied by your favorite
Linux distribution (<i>e.g.</i> by installing from the vendor's CDROM),
and install using that distribution's standard installation methods.
If you decide that you cannot live with the version that came with your 
distro, and you don't have <tt>apt-get</tt> or a similar tool, then 
be prepared for a rather long and involved install/upgrade proceedure.
Note that even with <tt>apt-get</tt>, some packages may still need 
to be installed manually.
<br><br>

The majority of the GnuCash 1.6.x dependencies are satisfied by installing 
standard <a href="http://www.gnome.org/">Gnome 1.4</a> core libraries. 
The only dependencies beyond a standard Gnome 1.4 installation are 
<a href="#guppi">Guppi</a>, <a
href="#guile">Guile</a>, <a href="#slib">slib</a> and <a
href="#gwrap">G-Wrap</a>. 
<br><br>

<table border=0 cellpadding=1 cellspacing=0 width="100%">
  <tr>
  <td valign=middle align=center bgcolor=#666699>
   <table border=0 cellpadding=5 cellspacing=1 bgcolor=#cacaf7 width="100%">
   <tr>
     <td bgcolor=#666699 width=25%><font color=#ffffff><b>Name</b></td>
     <td bgcolor=#666699 width=50%><font color=#ffffff><b>Description</b></td>
     <td bgcolor=#666699 width=25%><font color=#ffffff><b>Link</b></td>
   </tr>
   <tr>
           <td colspan=3>
<B>GUI Toolkits:</B><BR>
     </td>
         </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>Gtk+</td>
       </tr>
       </table>
     </td>
     <td valign=top>The Gimp Toolkit</td>
     <td valign=top><a href="http://www.gtk.org/">http://www.gtk.org/</a></td>
   </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>Gnome</td>
       </tr>
       </table>
     </td>
     <td valign=top>The application infrastructure</td>
     <td valign=top><a href="http://www.gnome.org">http://www.gnome.org</a></td>
   </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>Glade</td>
       </tr>
       </table>
     </td>
     <td valign=top>GTK+ User Interface Builder - This is how many of the gnucash GUI's are designed.</td>
     <td valign=top><a href="http://glade.gnome.org">http://glade.gnome.org</a></td>
   </tr>

   <tr>
           <td colspan=3>
       <B>Scripting Interface:</B><BR>
     </td>
         </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><a name="guile">Guile</a></td>
       </tr>
       </table>
     </td>
     <td valign=top>A Scheme interpreter with C programming interfaces - This is how gnucash provides 'extension' and rapid implementation capabilities.</td>
     <td valign=top><a href="http://www.gnu.org/software/guile/guile.html">http://www.gnu.org/software/guile/guile.html</a> -   You'll need at least 1.3, and 1.6 is strongly recommended.</td>
   </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><a name="gwrap">G-wrap</a></td>
       </tr>
       </table>
     </td>
     <td valign=top>A tool for autogenerating scheme bindings for C lanugage functions, structures & enums.</td>
     <td valign=top><a href="http://www.gnucash.org/pub/g-wrap/">http://http.gnucash.org/pub/g-wrap/</a> - You'll want the latest in the 1.3 series (1.3.4 or newer)</td>
   </tr>

<!-- Scheme isn't really a dependency, like ... there's nothing to
download and install for end-users, except guile, which is seperately
mentioned.
		-- jsled, 2001.06.11. -->
   <!-- tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>Scheme</td>
       </tr>
       </table>
     </td>
     <td valign=top>The Scheme Language</td>
     <td valign=top><a href="http://www.scheme.org/">http://www.scheme.org/</a></td>
   </tr -->

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><a name="slib">slib</a></td>
       </tr>
       </table>
     </td>
     <td valign=top>Scheme library - Miscellaneous scheme functions used by GnuCash.</td>
     <td valign=top><a href="http://www-swiss.ai.mit.edu/~jaffer/SLIB.html">http://www-swiss.ai.mit.edu/~jaffer/SLIB.html</a></td>
   </tr>

   <tr>
           <td colspan=3>
       <B>Web Infrastructure:</B><BR>
     </td>
         </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>GtkHTML</td>
       </tr>
       </table>
     </td>
     <td valign=top>The gtk html layout engine - used by gnucash to display help documentation, reports and graphs.</td>
     <td valign=top><a href="http://www.advogato.org/proj/GtkHTML/">http://www.advogato.org/proj/GtkHTML/</a></td>
   </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>libghttp</td>
       </tr>
       </table>
     </td>
     <td valign=top>The HTTP library - used by gnucash to chat the http protocol to access web servers.</td>
     <td valign=top><a href="http://www.gnome.org/">http://www.gnome.org/</a></td>
   </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>Gnome XML</td>
       </tr>
       </table>
     </td>
     <td valign=top>The XML parsing library - used by gnucash to read its file format.</td>
     <td valign=top><a href="http://xmlsoft.org/">http://xmlsoft.org/</a></td>
   </tr>

   <tr>
           <td colspan=3>
       <B>Other:</B><BR>
     </td>
         </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>Finance::Quote</td>
       </tr>
       </table>
     </td>
     <td valign=top>A perl module to get stock price quotes and currency exchange rates from off the net - This is how gnucash accesses price data on the net. You can use the 'update-finance-quote' script included with the distribution to obtain a recent version (CPAN is required).</td>
     <td valign=top><a href="http://finance-quote.sourceforge.net/">http://finance-quote.sourceforge.net/</a></td>
   </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>Finance::QuoteHist</td>
       </tr>
       </table>
     </td>
     <td valign=top>A perl module to fetch historical stock prices.</td>
     <td valign=top><a href="http://sourceforge.net/project/?group_id=2403">http://sourceforge.net/project/?group_id=2403</a></td>
   </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>LibOFX</td>
       </tr>
       </table>
     </td>
     <td valign=top>Library for parsing OFX (Open Financial Exchange) data. Used by many American banks.</td>
     <td valign=top><a href="http://libofx.sourceforge.net/">http://libofx.sourceforge.net/</a> 
     </td>
   </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>OpenHBCI</td>
       </tr>
       </table>
     </td>
     <td valign=top>Library for connecting to German banks that support HBCI.</td>
     <td valign=top><a href="http://openhbci.sourceforge.net/">http://openhbci.sourceforge.net/</a> 
     Optional; required only if you want to connect to HBCI banks.</td>
   </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><a name="guppi">Guppi</a></td>
       </tr>
       </table>
     </td>
     <td valign=top>A graphical plotting and analysis tool - used to generate and display gnucash charts and plots.</td>
     <td valign=top><a href="http://www.gnome.org/guppi/">http://www.gnome.org/guppi/</a> - Any recent version will work, but 0.35.5 or later is required for full functionality.</td>
   </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>Gnome Print</td>
       </tr>
       </table>
     </td>
     <td valign=top>gnome printing architecture - used by gnucash for check printing & general printing.</td>
     <td valign=top><a href="http://www.sourceforge.net/projects/gnome-print/">http://www.sourceforge.net/projects/gnome-print/</a></td>
   </tr>

   </table>
</tr>
</table>



</td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/footer.phtml"); ?>
