<?php $title = "Sizing"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/nl/menu/menu-main-other.phtml"); ?>
</td>

<td valign=top>
<b>Sizing</b><br><br>

<p>
Het is vaak interessant om de broncode te bestuderen achter een software  project in ontwikkeling. Geen raar idee; het gaat per slot van rekening allemaal om calculaties.  GnuCash is gedurende de jaren gegroeid van een klein electronisch kasboek tot een tamelijk grote desktop applicatie met vele mogelijkheden.  
</p>
<P>
GnuCash bestaat op het moment uit meer dan 3 miljoen programmaregels verspreid over meer dan 1000 bestanden. Het is vertaald naar 23 talen met dank aan 139 auteurs.
</P>
<p>
De tabel hieronder wat zien van de historie van het <SPAN CLASS="APPLICATION">GnuCash</SPAN>
development project.  Bedenk dat niet alle bestanden hierin opgenomen zijn: bijvoorbeeld de Make bestanden, configure.in en autogen.sh worden niet meegerekend. 
Ook de bestanden die automatisch gegenereerd worden, worden buiten beschouwing gelaten, zoals ook bestanden die 'geleend' zijn uit andere projecten. Dit geldt ook voor experimental bestanden, perl scripts, en diverse converters,
addons en utilities.  Tenslotte worden ook de <tt>glade<tt> bestanden niet geteld, 
ondanks dat grote gedeeltes van de GUI in <tt>glade</tt> geschreven zijn.
bestanden.
</P>
<P>
KLOC's zijn geen goede maatstaf voor productiviteit van een programmeur,
zoals ook <SPAN CLASS="APPLICATION">wc</SPAN > geen goede manier is om 
KLOC's te tellen. Betere maatstaven zijn de complexiteitsmaastaven die bijvoorbeeld het aantal en de grootte van de if-then-else blocken tellen, of de grootte en het totale aantal blocken, of het aantal mathematische operators per 
statement. Misschien laten we al deze berekeningen op een dag eens los op de huidige code. 
Het onderstaande is wat we nu hebben. We hebben geprobeerd om alleen de handgeschreven code mee te tellen; dat betekent bestanden die direct door mensen zijn ge-edit. Dit is om overschatting van het aantal KLOC's door  automatisch gegenereerde code te voorkomen (daarom worden de glade bestanden niet meegeteld: ze zijn groot en worden automatisch gegenereerd).
</P>
<P>
<DIV CLASS="TABLE">
<P><B >Table 1.  Historische Ontwikkelingsstatistieken</B></P>
<TABLE BORDER="1" CLASS="CALSTABLE">
<THEAD>
<TR
><TH ALIGN="LEFT" VALIGN="TOP" >Versie</TH
><TH ALIGN="LEFT" VALIGN="TOP" >engine</TH
><TH ALIGN="LEFT" VALIGN="TOP" >backend</TH
><TH ALIGN="LEFT" VALIGN="TOP" >register</TH
><TH ALIGN="LEFT" VALIGN="TOP" >grootboek</TH
><TH ALIGN="LEFT" VALIGN="TOP" >motief</TH
><TH ALIGN="LEFT" VALIGN="TOP" >gnome</TH
><TH ALIGN="LEFT" VALIGN="TOP" >misc apps</TH
><TH ALIGN="LEFT" VALIGN="TOP" >import export</TH
><TH ALIGN="LEFT" VALIGN="TOP" >raporten</TH
><TH ALIGN="LEFT" VALIGN="TOP" >schema</TH
><TH ALIGN="LEFT" VALIGN="TOP" >business</TH
><TH ALIGN="LEFT" VALIGN="TOP" >test</TH
><TH ALIGN="LEFT" VALIGN="TOP" >gebruikers docs</TH
><TH ALIGN="LEFT" VALIGN="TOP" >internal txt</TH
><TH ALIGN="LEFT" VALIGN="TOP" >Totaal</TH>
<TH ALIGN="LEFT" VALIGN="TOP" >Talen</TH >
<TH ALIGN="LEFT" VALIGN="TOP" >Auteur Credits</TH >
</TR>
</THEAD><TBODY>

<!-------------------------------------------------->
<tr>
<td>xacc-0.9 Sept 97</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>34 bestanden (7.5+0.9)</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>5 bestanden (0.4)</td>
<td>1 bestand (0.1)</td>
<td>40 bestanden (8.8)</td>
<td>1</td>
<td>1</td>
</tr>
<!-------------------------------------------------->
<tr>
<td>xacc-0.9w Dec 97</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>51 bestanden (13.8+1.5)</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>9 bestanden (0.8)</td>
<td>1 bestand (0.1)</td>
<td>61 bestanden (16.2)</td>
<td>1</td>
<td>2</td>
</tr>
<!-------------------------------------------------->
<tr>
<td>xacc-1.0.17 Feb 98</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>52 bestanden (14.8+1.8)</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>12 bestanden (1.4)</td>
<td>4 bestanden (0.3)</td>
<td>68 bestanden (18.3)</td>
<td>1</td>
<td>7</td>
</tr>
<!-------------------------------------------------->
<tr>
<td>gnucash-1.1.15 Aug 98</td>
<td>24 bestanden (6.2+1.5)</td>
<td>-</td>
<td>31 bestanden (6.1+1.7)</td>
<td>5 bestanden (1.4+0.4)</td>
<td>30 bestanden (7.4+0.7)</td>
<td>17 bestanden (3.4+0.5)</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>3 bestanden (0.3)</td>
<td>-</td>
<td>-</td>
<td>16 bestanden (1.9)</td>
<td>17 bestanden (1.8)</td>
<td>159 bestanden (34.7)</td>
<td>1 (0.17)</td>
<td>25</td>
</tr>
<!-------------------------------------------------->
<tr>
<td>gnucash-1.2.2 Aug 99</td>
<td>41 bestanden (10.2+3.6)</td>
<td>-</td>
<td>28 bestanden (5.5+1.7)</td>
<td>14 bestanden (2.4+0.6)</td>
<td>26 bestanden (8.7+0.5)</td>
<td>-</td> 
<td>-</td>
<td>-</td>
<td>-</td>
<td>14 bestanden (1.4)</td>
<td>-</td>
<td>-</td>
<td>30 bestanden (2.6)</td>
<td>15 bestanden (1.8)</td>
<td>168 bestanden (39.0)</td>
<td>3 (0.54)</td>
<td>41</td>
</tr>
<!-------------------------------------------------->
<tr>
<td>gnucash-1.3.6 April 2000</td>
<td>41 bestanden (12.9+4.0)</td>
<td>-</td>
<td>32 bestanden (6.8+2.1)</td>
<td>19 bestanden (4.0+0.8)</td>
<td>-</td> 
<td>78 bestanden (32.2+3.0)</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>74 bestanden (4.0+0.7+12.3)</td>
<td>-</td>
<td>-</td>
<td>33 bestanden (7.8)</td>
<td>25 bestanden (4.5)</td>
<td>302 bestanden (95.1)</td>
<td>5 (4.3) </td>
<td>61</td>
</tr>
<!-------------------------------------------------->
<tr>
<td>gnucash-1.4.6 Sept 2000</td>
<td>43 bestanden (13.0+3.6)</td>
<td>-</td>
<td>27 bestanden (5.9+2.0)</td>
<td>24 bestanden (5.4+1.8)</td>
<td>-</td>
<td>82 bestanden (33.8+3.0)</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>68 bestanden (4.0+0.7+15.5)</td>
<td>-</td>
<td>-</td>
<td>36 bestanden (9.3)</td>
<td>36 bestanden (4.8)</td>
<td>316 bestanden (101.9)</td>
<td>7 (6.0)</td>
<td>82</td>
</tr>
<!-------------------------------------------------->
<tr>
<td>gnucash-1.4.12 April 2001</td>
<td>43 bestanden (13.1+3.6)</td>
<td>-</td>
<td>27 bestanden (5.9+2.0)</td>
<td>24 bestanden (5.4+1.8)</td>
<td>-</td>
<td>82 bestanden (33.5+3.0)</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>73 bestanden (4.0+0.7+17.7)</td>
<td>-</td>
<td>-</td>
<td>43 bestanden (11.5)</td>
<td>39 bestanden (6.0)</td>
<td>331 bestanden (108.2)</td>
<td>12 (17.8)</td>
<td>97</td>
</tr>
<!-------------------------------------------------->
<tr>
<td>gnucash-1.5.2 Sept 2000</td>
<td>46 bestanden (14.9+3.7)</td>
<td>-</td>
<td>29 bestanden (6.3+2.0)</td>
<td>25 bestanden (5.7+1.8)</td>
<td>-</td>
<td>83 bestanden (35.8+2.9)</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>73 bestanden (4.6+0.8+16.8)</td>
<td>-</td>
<td>-</td>
<td>37 bestanden (10.7)</td>
<td>48 bestanden (8.2)</td>
<td>341 bestanden (114.2)</td>
<td>8 (7.8)</td>
<td>89</td>
</tr>
<!-------------------------------------------------->
<tr>
<td>gnucash-1.6.0 Juni 2001</td>
<td>139 bestanden (42.8+8.3)</td>
<td>-</td>
<td>28 bestanden (5.7+2.0) </td>
<td>23 bestanden (10.1+1.5)</td>
<td>-</td>
<td>132 bestanden (60.0+4.2)</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>102 bestanden (6.2+0.8+27.3)</td>
<td>-</td>
<td>-</td>
<td>64 bestanden (12.1)</td>
<td>69 bestanden (12.9)</td>
<td>455 bestanden (193.9)</td>
<td>11 (18.7)</td>
<td>123</td>
</tr>
<!-------------------------------------------------->
<tr>
<td>gnucash-1.7.2 November 2002</td>
<td>104 bestanden (28.7+7.8+3.3)</td>
<td>89 bestanden (30.0+3.3)</td>
<td>34 bestanden (5.2+2.0) <hr> 29 bestanden (10.5+1.2)</td>
<td>17 bestanden (9.4+0.7)</td>
<td>-</td>
<td>143 bestanden (56.0+4.7+0.9)</td>
<td>75 bestanden (17.0+2.5+5.1)</td>
<td>78 bestanden (11.1+1.5+7.3)</td>
<td>38 bestanden (2.4+0.1+14.2)</td>
<td>17 bestanden (3.4)</td>
<td>94 bestanden (19.9+1.9+4.5)</td>
<td>72 bestanden (7.9+0.1+0.7)</td>
<td>83 bestanden (22.2)</td>
<td>62 bestanden (11.6)</td>
<td>935 bestanden (297.1)</td>
<td>21 (56.1)</td>
<td>130</td>
</tr>
<!-------------------------------------------------->
<tr>
<td>gnucash-1.8.4 Juni 2003</td>
<td>100 bestanden (29.7+8.3+3.4)</td>
<td>89 bestanden (30.1+3.3)</td>
<td>35 bestanden (5.3+2.0) <hr> 31 bestanden (10.7+1.2)</td>
<td>17 bestanden (10.2+0.8)</td>
<td>-</td>
<td>151 bestanden (58.7+5.1+1.1)</td>
<td>71 bestanden (16.9+2.6+5.2)</td>
<td>86 bestanden (13.3+1.8+7.5)</td>
<td>52 bestanden (2.4+0.2+15.1)</td>
<td>17 bestanden (4.1)</td>
<td>98 bestanden (21.5+2.0+5.1)</td>
<td>76 bestanden (8.6+0.2+0.7)</td>
<td>24 bestanden (13.8) <hr> 199 bestanden (80.3)</td>
<td>69 bestanden (14.3)</td>
<td>1115 bestanden (385.5)</td>
<td>23 (62.4)</td>
<td>139</td>
</tr>
</TBODY ></TABLE ></DIV >

 </P ><P >
 Iedere cel geeft het volgende weer:
    
     aantal *c, *.h en *.scm bestanden
     (KLOCS in *.c + KLOCS in *.h + KLOCS in *.scm)
     Als er geen *.scm bestanden zijn in de folder, dan worden alleen de (KLOCS in *.c + KLOCS in *.h)
     weergegeven.  Als er alleen een nummer tussen haakjes staat, is dat het juiste aantal KLOC's voor de betreffende statistiek.

 </P ><P >
 KLOC == kilo-lines-of-code, zoals gerapporteerd door
   <SPAN CLASS="APPLICATION" >wc</SPAN >.  Zoals hierboven vermeld is wc geen verschrikkelijk goede maatstaf, maar het is wat we voor handen hebben.

    <P></P>
<b>Tabel Kolom Legend</b><br><br>
    <P></P>
 <DL>
    <DT><B>engine</B></DT>
    <DD>Inhoud van de src/engine en de include folders.
        De 'engine' is gesplitst van de motief code in versie 1.1.  
        De data opslag backend (bestand-io, sql) is gesplitst in de loop van versie 1.5
	<P></P>
        </DD>
    <DT><B>backend</B></DT>
    <DD>Inhoud van de src/backend folder (versie 1.7 en later)
        of src/engine/bestand, src/engine/sql (versie 1.6 en eerder)
	<P></P>
        </DD>
    <DT><B>register</B></DT>
    <DD>Inhoud van de src/register folder (versie 1.6 en eerder)
        of src/register/register-core (versie 1.7 en later).  Het register
        is gesplitst van een aparte componentvan de motief code in versie 1.1.
        zoals uit de statistieken kan worden afgeleid, is de register code tamelijk stabiel gebleven.
        Vanaf versie 1.7 en later komt er een tweede getal bij: het aantal regels code in src/register/register-gnome (voorheen gezien als onderdeel van gnome)
	<P></P>
        </DD>
    <DT><B>grootboek</B></DT>
    <DD>*.c, *.h bestanden in de src folder (versie 1.6 en eerder)
          of src/register/ledger-core (versie 1.7 en later)

	<P></P>
    </DD>
    <DT><B>motief</B></DT>
    <DD>Inhoud van de src/motif folder (versie 1.2 en eerder). De motief
        versie van de code is niet voortgezet na versie 1.2, nadat het grootste gedeelte van de non-gui code was verplaatst naar of de engine, het register of het grootboek.

	<P></P>
    </DD>
    <DT><B>gnome</B></DT>
    <DD>Inhoud van src/gnome plus src/register/gnome (versie 1.6 en eerder).  Voor
        versie 1.7 en later bestaat deze uit src/gnome, src/gnome-search en src/gnome-util
	<P></P>
    </DD>

    <DT><B>misc app</B></DT>
    <DD>Inhoud van miscellanous applicatie gerelateerde folders (versie 1.7 en later):
        src/app-bestand, src/app-utils, src/calculation, src/core-utils, src/gnc-module,
        src/network-utils, src/tax/us
	<P></P>
    </DD>

    <DT><B>import export</B></DT>
    <DD>Code voor import en export van diverse bestand formaten: inhoud van de src/import-export
        folder.
	<P></P>
     </DD>

    <DT><B>rapporten</B></DT>
    <DD>Code voor het genereren van rapporten en grafieken: inhoud van de src/reports
        folder.
	<P></P>
     </DD>

    <DT><B>schema</B></DT>
    <DD>scheme en guile code in folders src/scm plus src/guile (versie 1.6 en eerder).
        In versie 1.7 en later is veel van deze code verplaatst naar reports, import/export, en naar individuele modules; dus alleen de miscellaneous code blijft over.
	<P></P>
    </DD>

    <DT><B>business</B></DT>
    <DD>Code om small-busines features teimplementeren: inhoud van de src/business
        folder.
	<P></P>
     </DD>

    <DT><B>test</B></DT>
    <DD>Code automatische regressie testen uit te voeren: inhoud van de src/*/test folders.
	<P></P>
     </DD>

    <DT><B>docs</B></DT>
    <DD>English-language-only gebruikersdocumentatie, waaronder on-line help en handleiding
        (html, sgml of xml). Voor versie 1.8.4 en later, geeft het number onder de balk de vertaalde niet engelse documenten (momenteel
	de, es, fr, pt_PT). Beide getallen zijn moeilijk te tellen, onder andere vanwege de meerdere competerende versies.
	<P></P>
    </DD>
    
    <DT><B>interne txt</B></DT>
    <DD>Het aantal design documenten en README bestanden bedoeld voor ontwikkelaars.
        Hieronder *.txt bestanden, *.texinfo bestanden en README.* bestanden
     in alle subfolders.  Voor versie 1.7 en later worden alleen diegene in de  src subfolder meegeteld.
	<P></P>
     </DD>

    <DT><B>Talen</B></DT>
    <DD>Het aantal talen waarin de applicatieberichten zijn vertaald (het aantal  <tt>po/*.po</tt> bestanden). 
      Tussen haakjes staat het aantal berichten in de berichtbestanden 
      (<tt>grep msgstr po/*.po |wc</tt>), in duizendtallen.
	<P></P>
    </DD>
    
    <DT><B>Auteurs</B></DT>
    <DD>Het aantal mensen dat genoemd wordt in het AUTHORS bestand (versie 1.6 en later)
        of het README bestand (eerdere versies).  hieronder zijn de hoofdontwikkelaars,
	patch submitters en vertalers. Het bevat ook de auteurs die opgesomd zijn in het gnucash-docs/AUTHORS bestand
	maar niet in de gnucash/AUTHORS hoofdbestand.
	<P></P>
    </DD>
</DL>


</td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/footer.phtml"); ?>

