
<b>Si vous etes un fan, Voila en quoi vous pouvez aider :</b><br><br>
<font size=-1>
  Il existe de nombreux utilsateurs debutants ou peu experimenté sur GnuCash 
  qui peuvent avoir un besoin d'aide occasionnel sur GnuCash. 

 Inscrivez vous sur la liste de distribution 
    <a href="/en/lists.phtml">gnucash-user</a> (en Anglais) ou  <a href="/en/lists.phtml">gnucash-fr</a>,
et aidez a repondre aux questions posées ou au moins essayer d'animer les discussions. 
Si vous avez une fomation en comptabilité
ou une grande experience en finance, vous pouvez vouloir aider les developpeurs a implmenter 
les nouvelles fonctionalités correctement.dans ce cas vous pouvez rejoindre les discussions 
plus techniques sur la liste  <a href="/en/lists.phtml">gnucash-devel</a> (en anglais).
Nous avons toujours besoin de courageux Beta-testeurs pour les dernieres versions. 
Ceci parceque la derniere version est frequement plantée, et nous avons besoin de 
quelqu'un indiquant ou sont les bugs.
Si vous etes un artiste : He bien , un nouveau logo, une icone plus jolieou plus de graphiques
c'est certain, ces chose ne font pas de mal ...
Si vous preferez promouvoir des projets de logiciels gratuits, ecrivez nous :
nous aimons les promoteurs.
</font>
