
<b>Si vous etes programmeur, voici comment contribuer :</b><br><br>
<font size=-1>
Inscrivez vous sur la liste de distribution de <a href="/en/lists.phtml">gnucash-devel@gnucash.org</a>.  
Installez CVS sur votre machine, et vérifiez le <a href="/en/hacking.phtml">code source</a>. 

Jetez un coup d'oeil aux readme de la version dans le sous répertoire de Documentation et allez y. 
D'autre part, selon votre tempérament, vous voudrez probablement discuter de vos développement 
sur la liste de distribution : ceci évitera les régressions et la mauvaise surprise de constater 
que tout le monde ne pense pas que votre patch est le meilleur. Pour avoir une meilleure idée de 
ce qui est en cours, étudiez <a href="/en/architecture.phtml">la vue d'ensemble de l'architecture </a>. 
Pour avoir une idée de ce qui est dans les placards, et de qui fait quoi, tournez vous vers 
<a href="http://www.linas.org/linux/gnucash/projects.html">la liste des projets</a>. 
C'est long, mais cela devrait vous aider à vous orienter et vous donner une idée du statut 
des divers composants. Une dernière chose, mais pas des moindre, vous devriez aller jeter un 
oeil à la documentation existante dans le sous répertoire <tt>src/doc</tt> dans l'arborescence 
des sources.
</font>
