
<b>Si vous etes redacteur, voici comment vous pouvez nous aider :</b><br><br>
<font size=-1>
La documentation a grand besoin d'une révision. Certains peuvent penser que la comptabilité 
c'est ennuyeux, mais cela ne signifie pas que la documentation devrait vous faire dormir. 
Et avoir les dernières nouvelles financières, en créant quelque chose en lignes avec des sujets 
financiers, n'est peut être pas une mauvaise idée.
</font>
