
<b>Si vous êtes un traducteur, voici comment vous pouvez aider:</b>
<p>
<div class='smalltext' align='justify'>
Tous les menus et dialogues dans GnuCash sont  entièrement  internationalisés / localisés à 
l'aide de l'outil GNU gettext. Il y a de bonnes chances pour que vous ayez déjà configuré votre 
machine correctement pour votre langue locale, et donc, les chances sont raisonnables que vous 
ayez déjà GnuCash dans votre langue maternelle, avec les dates et les devises correctement 
localisées. Si ce n'est pas le cas, ou il y a un bug, ou votre machine est mal configurée, 
ou votre langue maternelle n'est pas encore supportée. Ceci ne signifie pas que la traduction 
est parfaite: 
 <p>
Si de mauvaises expressions ou des mots erronés sont employés dans les menus ou les dialogues, 
vous devriez contacter le responsable de la maintenance pour votre langue (regardez la page 
 <a href='/trans/'>Traduction de GnuCash</a>pour plus d'infos). Si une devise fausse vous est 
 proposée, ou s'il y a d'autres problèmes de localisation, vous devriez entrer en contact avec 
 la liste de distribution <a href="/en/lists.phtml">gnucash-devel</a>. Notez que les saisies 
 pour les langues Asiatique (japonais, chinois, etc...) et des langues lues de droite à gauches 
 sont partiellement abandonnées: nous recherchons les programmeurs qui seront assez bien informés 
 pour fixer dans les problèmes des méthodes de saisie dans les composants gnome que nous 
 utilisons. En outre: J'aimerais personnellement un 'Asiatique-howto ' écrit en anglais de sorte 
 que je (réellement, nous, les développeurs qui parlent anglais) puisse installer une demo 
 localisée pour ces pays. Écrivez à <a href="mailto:linas@linas.org">linas at linas.org</a> 
 si vous pouvez m'aider à installer ma machine en japonais ou chinois. 
</p>
<p>
La préparation de nouvelles traductions est relativement facile: vérifiez la page 
<a href="/trans/">de traduction GnuCash</a> qui contient toutes les informations dont vous 
avez besoin. 
</p>
<p>
Nous avons besoin également des traductions non Anglaises du site Internet. Si vous faites partie 
de ces critères, écrivez <a href="mailto:webmaster@gnucash.org">au webmaster de gnucash.org</a>. Des traductions Non Anglaises de la 
documentation sont également nécessaires. La partie embêtante est, naturellement, que la 
documentation est tout à fait impénétrable, et est actuellement reécrite. Si vous êtes un grand 
rédacteur, contactez-nous. 
</div>

