
<b>Si vous etes webmaster, voila comment nous aider :</b><br><br>
<font size=-1>
Nous voudrions que quelqu'un nous aide à installer et maintenir tous ces outils de développement 
qu'un 'vrai 'projet devrait avoir, comme "lxr" et "bonsai" (ndt: je ne connaît pas ces outils 
faite moi savoir si vous avez une meilleure traduction), et peut-être un outil suivi d'anomalie, 
ou plein d'autres petites choses. Nous avons de même besoin de quelqu'un pour s'assurer que 
les archives de courrier fonctionnent correctement, et que le courrier récent est classé &amp; 
et que la recherche est efficace.
</font>
