
<b>Here is how you can help:</b><br><br>
<font size=1>
All of the menus and dialogues in GnuCash are fully 
    internationalized/localized using the GNU gettext tools.
    Chances are good that you've already configured your 
    machine correctly for your locale, and therefore, chances
    are reasonable that you're already seeing GnuCash in your
    native language, with correctly localized dates and 
    currencies.  If not, either there's a bug, your machine
    is misconfigured, or your native language is not 
    Danish, English, French, German, Italian, Japanese, 
    Russian or Swedish.  
    <p>
    This does not mean that the translation is perfect: if 
    the wrong phrase or word is used in menus or dialogues, 
    you should contact the maintainer for your language
    (see the README file for credits).  If the wrong currency
    is displayed, or there are other localization problems, 
    you should contact the 
    <a href="/en/lists.phtml">gnucash-devel</a> mailing list.
    Note that the input methods for Asian (Japanese, Chinese, 
    etc.) and right-to-left languages are partially broken:
    we are looking for programmers who are knowledgeable enough 
    to fix in input method problems in the gnome input widgets 
    that we use.  Also: I'd personally like an 'Asian-howto'
    written in English so that I (actually, we, the 
    English-speaking developers) could set up our boxes here 
    for a demo.  Write <a href="mailto:linas@linas.org">linas at linas.org</a>
    if you can help me set up my machine for Japanese or Chinese.
    </p>
    <p>
    Preparing new translations is relatively easy: 
    check out the <a href="/en/hacking.phtml">source code</a>,
    review the file <tt>README.translator.txt</tt>, and then
    look at the translation file in the <tt>po</tt> directory.
    </p>
    <p>
    We also need non-English translations of the website.
    If you've got one of these, write
    <a href="mailto:webmaster@gnucash.org">webmaster at gnucash.org</a>.
    Non-English translations of the documentation are also needed.
    The sticky part is, of course, that the documentation is quite
    rough, and is currently being re-written.  If you are a 
    great writer, contact us.
</font>
