
<b>Here is how you can help:</b><br><br>
<font size=1>
There are many novice and intermediate users of GnuCash
    who need occasional help using GnuCash.  Hang out on the 
    <a href="/en/lists.phtml">gnucash-user</a> mailing list,
    and help answer questions, or at least guide the discussion
    there.  If you have formal training in accounting, or 
    considerable experience in finance, and you want to help
    the developers implement the features correctly, then
    you should join the rather technical discussions that 
    occur on <a href="/en/lists.phtml">gnucash-devel</a>.
    Courageous beta-testers are always needed for the latest
    version.  That's because the latest version is frequently 
    broken, and we need someone to tell us where the bugs are.
    If you are an artist: well, a new logo, a better icon,
    more graphics: these things sure don't hurt.
    If you like to promote free software projects, write to us:
    we like promoters.
</font>
