
<b>Here is how you can help:</b><br><br>
<font size=1>
We'd like somebody to help set up and maintain all those
    neat development tools that a 'real' project should have,
    such as lxr and bonsai, and maybe a bug-tracking tool,
    or other bits &amp; pieces.  We even need someone to make 
    sure that the mail archives are running correctly, and that
    recent mail is getting indexed &amp; is searchable.
</font>
