
<b>If you are a translator, here is how you can help:</b>
<p>
<div class='smalltext' align='justify'>
    The GnuCash application menus and dialogs have been
    translated to over two dozen languages, although
    <a href='/trans/'>about half of these are incomplete</a>.  
    To help with the translation of the core application, 
    please review the 
    <a href='/trans/'>GnuCash Language Translation</a>
    webpage, as well as the 
    <a href="http://www2.iro.umontreal.ca/~pinard/po/registry.cgi?domain=gnucash">
    Translation Project</a>.
    <p>
    Note that one paricularly important but often neglected
    part of localization is the default/initial account 
    hierarchy.  The hierarchy not only must be presented in
    the local language, but must frequently adhere to local
    accounting practices and customs if not laws.  If you 
    have formal accounting experience in your country/region,
    please help by reviewing, correcting and adding new account 
    hierarchies.
    </p>
    <p>
    We are in desperate need of translations of the documentation.
    The most recent English versions of 
    <a href="docs.phtml">the documentation</a> are in pretty darn 
    good shape, but we lack translations to almost all major languages.  
    Please write to the <tt><a href="lists.phtml">gnucash-devel</a></tt>
    mailing list if you can help with the documentation.
    </p>
    <p>
    Last but not least, we need translations of the website.  All
    but the English-language websites have fallen into disrepair, 
    and need to be updated.  If you can help, write to me:
    <a href="mailto:linas@linas.org">linas@linas.org</a>.
    </p>
</div>

