
<b>If you are a fan, here is how you can help:</b><br><br>
<font size=-1>
There are many novice and intermediate users of GnuCash
    who need occasional help using GnuCash.  Hang out on the 
    <a href="/en/lists.phtml">gnucash-user</a> mailing list,
    and help answer questions, or at least guide the discussion
    there.  If you can't help with your time, then
    the GnuCash Project is 
    <a href="donations.phtml">accepting cash donations</a>.
    <p>
    If you have the skills, here are other ways you can help:
     

<ul>
<li>Accountants:
    If you have formal training in accounting, or 
    considerable experience in finance, and you want to help
    the developers implement the features correctly, then
    you should join the rather technical discussions that 
    occur on <a href="/en/lists.phtml">gnucash-devel</a>.
    Although we don't encourage trolling for business,
    you might find new clients after hanging out on the 
    mailing lists for a while.

<li>Courageous beta-testers to assist in finding bugs
    and triaging the <a href="bugs.html">Bug List</a>.
    The hardest part about fixing a bug is usually being 
    able to find it and reproduce it; we need this help.

<li>Artists: We sure would like a real, honest-to-goodness
    logo.  Beleive it or not, we don't really have one yet.
    Improved icons, some spruced-up interior decor for the 
    website could help too.
<li>Promoters: Free Software gets better when more people use
    it.  More people use it when more people know about it.
    Help us get GnuCash into the lime-light.
</ul>
</font>
