
<b>If you are a programmer, here is how you can help:</b><br><br>
<font size=1>
Get on the <a href="/en/lists.phtml">gnucash-devel</a>
    mailing list.  Set up CVS on your machine, and check 
    out the <a href="/en/hacking.phtml">source code</a>.
    Take a look at the build readme's in the doc subdirectory
    and get hacking.  On the other hand, depending on your 
    temperament, you'll probably want to discuss your hacks
    on the mailing list: this will avoid devolution and 
    other unpleasentries of finding out that not everyone 
    thinks your patch is the greatest.  To get a better
    idea of what's going on, study the 
    <a href="/en/architecture.phtml">architectural overview</a>.
    To get an idea of what's in store, and who's doing what,
    look over the 
    <a href="http://www.linas.org/linux/gnucash/projects.html">
    projects list</a>.  Its long, but it should help orient
    and give an idea of the status of various components.
    Last, but hardly least, you should go over the existing 
    documentation in the subdirectory <tt>src/doc</tt> in
    the source tree.
</font>
