<?php $title = "Contribuer"; ?>
<?php if (!ini_get('register_globals')) {
 include("../emulate_globals_on.php");
}
?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/fr/menu/menu-main-general.phtml"); ?>
</td>

<td valign=top>
<h1>Comment contribuer</h1>

<p>
<div class='text' align='justify'>

GnuCash est un projet de développement de logiciel gratuit et la dynamique de contribution
est comme pour les autres projets. Ce a quoi vous contribuez dépend beaucoup de
votre compétence, du temps que vous avez de disponible, et de ce que vous prenez plaisir à faire.
GnuCash recherche des bêta-testeurs, des programmeurs, des rédacteurs, des animateurs
(répondant aux questions sur irc, forums ou mailing-list),
des traducteurs et de tout un tas d'autres personnes sympas.

</div>

<p>

<table>
<tr><td>
<b>Choisissez votre compétence pour voir en quoi vous pourriez aider : </b></td>
<td>
<form method="post" action="/fr/contribute.phtml">
<select name=contribute>
  <option value=programmer
   <?php if ($contribute == "programmer") { echo ("selected"); } ?>
  >Je  suis un programmeur</option>
  <option value=translator
   <?php if ($contribute == "translator") { echo ("selected"); } ?>
  >Je suis un traducteur</option>
  <option value=fan
   <?php if ($contribute == "fan") { echo ("selected"); } ?>
  >Je suis un fan</option>
  <option value=webmaster
   <?php if ($contribute == "webmaster") { echo ("selected"); } ?>
  >Je suis webmaster</option>
  <option value=writer
   <?php if ($contribute == "writer") { echo ("selected"); } ?>
  >Je suis redacteur/journaliste</option>
</select>
<input type=submit value=Go>
</form>

</td>
</table>

<hr noshade>
<?php
  if ($contribute != "") { 
		include($GLOBALS['DOCUMENT_ROOT']."/fr/contribute/contribute-".$contribute.".phtml");
  }
?>


</td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/footer.phtml"); ?>
