<?php $title = "Fonctionnalités: Quoi de nouveau"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/fr/menu/menu-main-general.phtml"); ?>
</td>

<td valign=top>

<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr>
  <td><img src=/images/features/features_title.png></td>
  <td align=right><a href="javascript:window.close();"><img border=0 src=/images/close_window.png></a></td>
</tr>
</table>

<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr><td bgcolor=#000000><img src=/images/spacer.png height=1></td></tr>
</table>

<br>

<table cellpadding=4 cellspacing=0 border=0 width=100%>
<tr>
<td valign=top>
  <img src=/images/features/features_5_text.png><br><br>

<h2>Quoi de nouveau pour GnuCash 1.8.0?</h2>
La série de versions stables 1.8.x présentent beaucoup 
de nouvelles fonctionnalités inconnues dans les version antérieures gnucash-1.6.8 :
    <br><br>
<dl>
<dt><b>Transactions Planifiées</b>
<dd>
 Vous pouvez maintenant créer des transactions se récurrente, 
 y compris des rappels automatiques quand une transaction est due, 
 la capacité de remettre une transaction sans annuler la planification, 
 et la capacité d'indiquer un nombre limité de transactions.
 <br><br>

<dt><b>Assistant D'Hypothèque &amp; De Remboursement De Prêt</b></dt>
<dd>
Un assistant vous guide pour mettre en place des remboursements de prêt
en tant que transactions planifiées. 
<br><br>
<dt><b>Fonctionnalité  De Comptabilité De Petite Entreprise</b>
<dd>
Simplifiez le contrôle d'une petite entreprise avec le suivi du client et 
du fournisseur, le paiement et le recouvrement de la facturation, et 
les échéances d'impôts et de factures.
<br><br>
<dt><b>Importation d'OFX </b>
<dd>

GnuCash est la première application libre à soutenir le 
protocole d'échange financier ouvert que beaucoup de banques et services 
financiers commencent à utiliser. 
<br><br>
<dt><b>Support de HBCI</b>
<dd>
GnuCash est la première application libre à soutenir le 
protocole allemand  d'information d'opérations bancaires personnelles 
, permettant aux utilisateurs allemands d'exécuter des virements 
bancaires et d'initier des débits directs. 
<br><br>

<dt><b>Améliorations de la Réconciliation de Transaction Importées</b>
<dd>
Le développement d'OFX et de HBCI a également eu comme conséquence 
l'améliorations du  système de réconciliation des transactions qui identifie 
plus exactement des transactions en doubles pendant l'importation des fichiers de comptes. 
<br><br>
<dt><b>Un Nouveau Manuel et  de l'Aide Utilisateur</b>
<dd>
Un nouveau sous-système d'aide qui se concentre sur comment exécuter 
différentes actions est maintenant disponible, en plus d'un tutorial 
et d'un guide de concepts qui fournit à l'utilisateur les informations 
de base sur les règles de comptabilité et comment elles sont gérées par 
GnuCash. 
    <br><br>
<dt><b>Nouvelle Gestion Des Transaction Multidevise</b>
<dd>

GnuCash n'exige plus des comptes séparés en devises pour manipuler des transferts 
en devise multiples. Des transactions peuvent être faites directement entre 
les comptes libellés  dans différentes devises. 
 <br><br>
<dt><b>Menus Redessiné</b>
<dd>
Les menus de GnuCash ont été remodelés pour se conformer davantage aux 
nouvelles directives de l'interface GNOME. 
 <br><br>
</dl>

<h2>Anciennes Fonctionnalités</h2>
Et naturellement, quelques fonctionnalités des versions précédentes  : 
<br><br>
<dl>
<dt><b>Rapport De Réconciliation</b>
<dd>
Une fenêtre de réconciliation avec la liste des transactions
  encore non réconciliées et celles marquées afin d'équilibrer 
  facilement vos comptes avec vos relevés bancaires. 
</dd>
<br><br>
<dt><b>Portefeuille De Fonds (FCP,sicav)/Actions</b> 
<dd>
Vous pouvez suivre vos actions individuellement (une par compte)
 ou dans un portefeuille de comptes (un groupe de comptes qui peuvent être 
visualisé ensemble). 
</dd>
<br><br>
<dt><b>Importation de fichier QIF</b>
<dd>
Les fichiers Intuit<sup>&reg;</sup> Quicken<sup>&reg;</sup>
    QIF peuvent être importé, et sont automatiquement fusionné 
    pour éliminer des transactions doubles. 
</dd>
<br><br>
<dt><b>Localisation</b>
<dd>
Support des formats de dates et devises internationalisées. 
Les menus et les dialogues de Gnucash ont été traduits en 21 langues, 
y compris le Chinois, le danois, le Français, l'Allemand, le Hongrois, 
l'Italien, le Japonais, le Norvégien, le polonais, le Portugais, le Russe, 
l'Espagnol, le Suédois, le Turc, l'ukrainiens, et l'anglais britannique. 
La documentation est disponible en anglais, français, Portugais et en 
Espagnol. 
</dd>
<br><br>
<dt><b>Rapports</b>
<dd>
Affiche le bilan, les bénéfices et les pertes, l'évaluation du portefeuille, 
et bien d'autres. Les rapports peuvent être sauvés en HTML ou postscript, 
ou être imprimés. 
</dd>
<br><br>
<dt><b>Système de Recherche De Transaction </b>
<dd>
Un puissant dialogue de requêtes sur les transactions 
peut vous aider à localiser rapidement une aiguille dans une meule de foin. 
</dd>
<br><br>
<dt><b>La Double Entrée</b>
<dd>
Une fois permise, chaque transaction doit créditer un compte et débiter 
un autre d'un montant équivalent. Ceci assure à cela l'"équilibre du 
registre" : la différence entre les revenus et les dépenses égale 
exactement la somme de tous les capitaux et capitaux propres. 
</dd>
<br><br>
<dt><b>Types De Compte De Revenus/Dépenses 
</b>
<dd>
Les types (catégories) de compte De Revenus/Dépenses  vous permettent de classer 
vos flux financiers. Lorsque cela est utilisés correctement, la fonctionnalités  
de double entrée et les comptes de capitaux propres,ceux-ci vous permettent de 
produire des rapports, tels que les perte et profits , que les systèmes classique 
ne peuvent pas manipuler. 
</dd>
<br><br>
<dt><b>Registre Général de comptes</b>
<dd>
Des comptes multiples peuvent être affichés en même temps dans une fenêtre de registre. 
Ceci peut soulager les problèmes de dépistage des erreurs de frappes/saisie. 
Il fournit également une manière commode de regarder un portefeuille contenant 
beaucoup d'actions, en montrant toutes les transactions de ce portefeuille. 
</dd>
<br><br>
<dt><b>Cotations d'Actions En ligne &amp; de Fonds commun de placement  
</b>
<dd>
Obtenez des Cotations des fonds commun de placement et des actions
a partir de divers site Internet, et la mise à jour du portefeuille automatique. 
De nouvelles sources de cotations sont ajoutées régulièrement. 
</dd>
<br><br>
<dt><b>Impression de cheques</b>
<dd>
Les chèques peuvent être imprimés dans des formats standard.
Une personnalisation de l'interface utilisateur permet de développer différentes dispositions.
</dd>
<br><br>
<dt><b>Devises Multiple</b>
<dd>
Différents comptes peuvent être dénommés dans différentes devises. Les mouvements de devise 
entre les comptes sont entièrement équilibrés quand on permet la comptabilité en double entrée.  
</dd>
<br><br>
<dt><b>Support de requêtes SQL Multi utilisateurs</b>
<dd>
Les utilisateurs multiples peuvent maintenant simultanément accéder et mettre à jour des données 
de GnuCash stockées dans une base SQL Postgres principale. Postgres doit être installé et configuré 
pour utiliser cette option. 
</dd>
<br><br>
<dt>
</dl>
</td>
</tr>
</table>
<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr><td bgcolor=#000000><img src=/images/spacer.png height=1></td></tr>
</table>
<br>
<table border=0 cellspacing=0 cellpadding=0 width=100% align=center>
<tr>
  <td align=center>
	  <a href=/en/features_4.phtml><img border=0 src=/images/features/features_previous.png></a>
		 |
	  <img border=0 src=/images/features/features_next_disabled.png>
	</td>
</tr>
</table>
</td>


<?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/footer.phtml"); ?>
