<?php $title = "Fonctionnalités"; ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/fr/menu/menu-main-general.phtml"); ?>
</td>

<script language=javascript>
<!--
  
  function newWin(url) {
    newLoc=window.open("","","height=480,width=640,scrollbars=yes")
    newLoc.location=url
  }

// -->
</script>

<td valign=top>

<h1>Fonctionnalités</h1>

<font size=-1>
GnuCash a longtemps eu beaucoup de fonctionnalités pour supporter les besoins de base de la
comptabilité personnelle et familiale, en commençant par une méthode facile à utiliser
de livre-registre de compte, et le support de diverses opérations de réconciliation 
des relevés bancaires, les portefeuilles Actions/Fonds et de nombreux rapports/graphiques.
  <BR>
<BR>
Mais le dévelopement de GnuCash ne s'arrête pas là,
et les versions les plus récentes ajoutent un support sur les comptabilités des petites
entreprises. 

Les résidants allemands apprécieront également la fonctionnalité de gestion des opérations
bancaires en ligne (désolé, la gestion en ligne n'est pas
supportée aux USA; ne nous blâmez pas, blâmez votre banque. Dites-leur de nous dire
les URL de  leurs serveurs  OFX  tiers, au lieu de les cacher comme des secrets d'état).
</font>
<p>
<center>
<font size=-1>
Faites une visite visuelle des fonctionnalités du noyau de GnuCash.
</font>
<BR><BR>
<!-- <a href="javascript:newWin('/en/features_1.phtml')"> -->
<a href="/en/features_1.phtml">
<img border=0 src=/images/features/features_start_the_tour.png></a>
</center>
<center>
<font size=-1>
<BR><BR>
Ou plongez vous dans la
</font>
<b><a href="/fr/features_5.phtml">Liste Complete des Fonctionalités</a></b>.
</center>
</td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/footer.phtml"); ?>
