<?php $title = "Logiciel de Gestion comptable Open Source"; ?>
<?php if (!ini_get('register_globals')) {
 include("../emulate_globals_on.php");
}
?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/fr/menu/menu-main.phtml"); ?>

	</td>
  <td valign="top" width="98%">
  
<h1>Bienvenue Sur GnuCash.org</h1>
  
<font size=-1>

Si vous recherchez un moyen de gérer vos finances personnelles en utilisant un logiciel gratuit
Vous l'avez trouvé ! Etudié pour être simple à utiliser, puissant et flexible, GnuCash vous permet
de suivre vos comptes bancaires, portefeuilles action, revenus et dépenses.
Aussi rapide et intuitif à utiliser qu'un registre de compte papier, il est basé sur des principes
de comptabilité professionnelle pour assurer l'équilibre des comptes et des rapports fiables.
GnuCash est soutenu par une communauté de développement active et s'épanouit dans un véritable plan comptable.
Développé sous la licence GPL, vous n'avez aucune raison  de vous inquiéter de son l'obsolescence :
GnuCash sera là pour vous.

Ce site Web est consacré à favoriser le projet de développement de Gnucash.org.

Nous sommes impliqué dans le développement d'outils financiers et de comptabilité au top
pour les utilisateurs de GNU/Linux et d'Unix.
Ceci inclut le développement de programmes de gestion des api, des bibliothèques et des composants qui peuvent
être employés pour créer des applications client ou serveur pour une utilisation personnelle ou professionnelle.
En se concentrant sur la facilité d'utilisation, la conception modulaire, des interfaces architecturées et
du code bien documenté, nous espérons que GnuCash et ses bibliothèques financières associées
seront le choix d'une génération de programmeurs GNU et d'utilisateurs.

<br><br>
Oui, GnuCash tourne maintenant du MAX OSX aussi bien que sur  GNU/Linux, *BSD, et les
autres Unix Traditionnels : Solaris, AIX, etc ...
<br><br><br>
<b>Cette page est en cours de traduction</b> de l'anglais vers le français.
Il est possible que certains liens vous emmènent sur le site Anglais de GnuCash,
cela signifie que nous n'avons pas terminé la traduction complète du site.
Si vous constatez une erreur ou une omission sur cette page, n'hésitez pas a me
contacter pour pouvoir la corriger au plus vite. Merci de votre indulgence.

<br><br><br>
</font>


<h1>Actualités</h1>

<?php 
$lang_newspath = $toppath . "/news/fr/";
$en_newspath = $toppath . "/news/en/";
include($toppath."/news/news-script.php"); 
?>

<font size=-2>
<a href="/surf/guppi-pie-demo.html">test</a>
<a href="/surf/short.gml">test2</a>
<a href="/surf/demo.gml">test3</a>
</font>
                  

  </td>

<?php include($toppath."/fr/components/footer.phtml"); ?>
