
<?php $title = "GnuCash on IRC"; ?>
<?php if (!ini_get('register_globals')) {
 include("../emulate_globals_on.php");
}
?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/fr/menu/menu-main-help.phtml"); ?>
</td>

<td valign=top>
<h1>GnuCash on IRC</h1>
Juste pour le plaisir ou pour obtenir simplement de l'aide sur GnuCash ( utilisation et installation)
en discutant du développement de GnuCash avec les développeurs et les utilisateurs , sur l'IRC.
rejoignez le canal #gnucash sur irc.gnome.org. 

<?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/footer.phtml"); ?>
