<?php $title = "Logiciels/Package requis"; ?>
<?php if (!ini_get('register_globals')) {
 include("../emulate_globals_on.php");
}
?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/header.phtml"); ?>
<?php include($GLOBALS['DOCUMENT_ROOT']."/fr/menu/menu-main-general.phtml"); ?>
</td>

<td valign=top>

<h1>Logiciels/Package requis</h1>
GnuCash dépend d'un  nombre important de technologies 
afin de mettre en application ses fonctions principales. Si vous voulez 
compiler et travailler avec GnuCash, vous devrez installer une version récente 
de ces bibliothèques. 
<br><br>
Sans bon manager de paquet  (<i>par exemple.</i> Debian <tt>apt-get</tt>), 
il peut être tout à fait pénible de trouver, télécharger et installer tous les 
paquets exigés (<i>cauchemar</i> est un mot qui a été utilisé). 
Par conséquent, si vous n'êtes pas un programmeur, et vous voulez juste <b>utiliser</b> 
GnuCash, vous devriez coller à la version fournie par votre distribution 
préférée de Linux ( <i>par exemple.</i> par l'installation du CDROM de votre 
fournisseur), et vous devriez l'installer en utilisant les méthodes standard de cette 
distribution. Si vous décidez que vous ne pouvez pas vivre avec la  version 
qui est livrée avec votre distribution,  et vous n'avez pas <tt>apt-get</tt> 
ou un outil équivalent, alors préparez vous pour un procédure  
d'installation/mise a jour plutôt longue et compliquée. Notez que même avec 
<tt>apt-get</tt>,  vous aurez peut etre besoin d'installer quelques paquets 
manuellement. 
<br><br>

La majorité des dépendances de GnuCash 1.6.x sont satisfaites par  
l'installation des librairies standard <a href="http://www.gnome.org/">Gnome 1.4</a>. 
Les seules dépendances supplémentaires  à l'installation de  Gnome sont 
<a href="#guppi">Guppi</a>, <a
href="#guile">Guile</a>, <a href="#slib">slib</a> et <a
href="#gwrap">G-Wrap</a>. 

<br><br>
<table border=0 cellpadding=1 cellspacing=0 width="100%">
  <tr>
  <td valign=middle align=center bgcolor=#666699>
   <table border=0 cellpadding=5 cellspacing=1 bgcolor=#cacaf7 width="100%">
   <tr>
     <td bgcolor=#666699 width=25%><font color=#ffffff><b>Nom</b></td>
     <td bgcolor=#666699 width=50%><font color=#ffffff><b>Description</b></td>
     <td bgcolor=#666699 width=25%><font color=#ffffff><b>Lien</b></td>
   </tr>
   <tr>
           <td colspan=3>
<B>Outils de l'interface utilisateur:</B><BR>
     </td>
         </tr>
   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>Gtk+</td>
       </tr>
       </table>
     </td>
     <td valign=top>les outils de "The Gimp"</td>
     <td valign=top><a href="http://www.gtk.org/">http://www.gtk.org/</a></td>
   </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>Gnome</td>
       </tr>
       </table>
     </td>
     <td valign=top>infrastructure de l'application </td>
     <td valign=top><a href="http://www.gnome.org">http://www.gnome.org</a></td>
   </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>Glade</td>
       </tr>
       </table>
     </td>
     <td valign=top>Constructeur d'interface utilisateur en GTK+ - c'est avec lui que la plupart des fenêtres Gnucash sont faites.</td>
     <td valign=top><a href="http://glade.gnome.org">http://glade.gnome.org</a></td>
   </tr>

   <tr>
           <td colspan=3>
       <B>Interface de Scripts :</B><BR>
     </td>
         </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><a name="guile">Guile</a></td>
       </tr>
       </table>
     </td>
     <td valign=top>Un interpréteur de Scheme  avec des interfaces de programmation en  C   - C'est grâce à cela que gnucash peu fournir des "extensions" et une implémentation rapide de nouvelles fonctionnalités.</td>
     <td valign=top><a href="http://www.gnu.org/software/guile/guile.html">http://www.gnu.org/software/guile/guile.html</a> -   Vous aurez besoin au moins de la version 1.3, et la  1.6 est fortement recommandée.</td>
   </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><a name="gwrap">G-wrap</a></td>
       </tr>
       </table>
     </td>
     <td valign=top>Un outil pour générer automatiquement des liaisons entre Scheme et des fonctions en langage C, des structures & enum.</td>
     <td valign=top><a href="http://www.gnucash.org/pub/g-wrap/">http://http.gnucash.org/pub/g-wrap/</a> - Vous préférerez les dernières version dans la série 1.3 (1.3.4 ou supérieur).</td>
   </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><a name="slib">slib</a></td>
       </tr>
       </table>
     </td>
     <td valign=top>librairie Scheme - Diverses fonctions scheme utilisées par GnuCash.</td>
     <td valign=top><a href="http://www-swiss.ai.mit.edu/~jaffer/SLIB.html">http://www-swiss.ai.mit.edu/~jaffer/SLIB.html</a></td>
   </tr>
   <tr>
           <td colspan=3>
       <B>Infrastructure Internet:</B><BR>
     </td>
         </tr>
   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>GtkHTML</td>
       </tr>
       </table>
     </td>
     <td valign=top>Le moteur gtk html  - utilisé par gnucash pour afficher l'aide,la documentation, les rapports et les graphs.</td>
     <td valign=top><a href="http://www.advogato.org/proj/GtkHTML/">http://www.advogato.org/proj/GtkHTML/</a></td>
   </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>libghttp</td>
       </tr>
       </table>
     </td>
     <td valign=top>La librairie HTTP  - utilisée par gnucash pour discuter en utilisant le protocole HTTP pour accéder aux serveurs Webs.</td>
     <td valign=top><a href="http://www.gnome.org/">http://www.gnome.org/</a></td>
   </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>Gnome XML</td>
       </tr>
       </table>
     </td>
     <td valign=top>La librairie de lecture XML - utilisée par gnucash pour lire les fichiers dans ce format.</td>
     <td valign=top><a href="http://xmlsoft.org/">http://xmlsoft.org/</a></td>
   </tr>

   <tr>
           <td colspan=3>
       <B>Other:</B><BR>
     </td>
         </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>Finance::Quote</td>
       </tr>
       </table>
     </td>
     <td valign=top>Un module en perl qui récupère les prix des actions et les taux des devises a partir d'Internet - c'est grâce a cela que gnucash accède aux données de cotations sur le net. Vous pouvez utiliser le script 'update-finance-quote' inclus dans votre distribution pour en obtenir une version récente (Vous aurez besoin de CPAN).</td>
     <td valign=top><a href="http://finance-quote.sourceforge.net/">http://finance-quote.sourceforge.net/</a></td>
   </tr>
   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>Finance::QuoteHist</td>
       </tr>
       </table>
     </td>
     <td valign=top>Un module en perl qui récupère  l'historique de cotations d'une action.</td>
     <td valign=top><a href="http://sourceforge.net/project/?group_id=2403">http://sourceforge.net/project/?group_id=2403</a></td>
   </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>LibOFX</td>
       </tr>
       </table>
     </td>
     <td valign=top>Librairie pour lire les données au format OFX (Open Financial Exchange). Utilisé par beaucoup de banques américaines.</td>
     <td valign=top><a href="http://libofx.sourceforge.net/">http://libofx.sourceforge.net/</a> 
     </td>
   </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>OpenHBCI</td>
       </tr>
       </table>
     </td>
     <td valign=top>Librairie permettant la connexion aux banques allemandes supportant le protocole HBCI.</td>
     <td valign=top><a href="http://openhbci.sourceforge.net/">http://openhbci.sourceforge.net/</a> 
     Facultatif; nécessaire seulement  si vous souhaitez vous connecter au banques utilisant HBCI.</td>
   </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top><a name="guppi">Guppi</a></td>
       </tr>
       </table>
     </td>
     <td valign=top>Un outil pour tracer des graphiques et faire de l'analyse - utilisé pour générer et afficher les dessins et graphiques de gnucash.</td>
     <td valign=top><a href="http://www.gnome.org/guppi/">http://www.gnome.org/guppi/</a> - N'importe quelle version récente fonctionnera, mais la 0.35.5 ou supérieure est nécessaire pour toutes les fonctionnalités.</td>
   </tr>

   <tr bgcolor=#ececff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
         <td valign=top>Gnome Print</td>
       </tr>
       </table>
     </td>
     <td valign=top>Architecture d'impression de gnome - Utilisé par gnucash les impressions.</td>
     <td valign=top><a href="http://www.sourceforge.net/projects/gnome-print/">http://www.sourceforge.net/projects/gnome-print/</a></td>
   </tr>

   </table>
</tr>
</table>



</td>

<?php include($GLOBALS['DOCUMENT_ROOT']."/fr/components/footer.phtml"); ?>
