  <table border=0 cellpadding=0 cellspacing=6>
  <tr>
  <td><img src="/images/spacer.gif" height=1 width=2></td>
  <td>
    <font size=-1>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/en/architecture.phtml">System Architecture</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/en/roadmap.phtml">The Road Ahead</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="http://linas.org/linux/gnucash/projects.html">Project Goals</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/lxr/">Browse Source Code</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/en/hacking.phtml">CVS Access</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="http://www2.iro.umontreal.ca/~pinard/po/registry.cgi?domain=gnucash">Language Translations</a><br>

  </td>
  </tr>
  </table>
