<!-- MENU:START -->
<?php if (!ini_get('register_globals')) {
 include("../emulate_globals_on.php");
}

echo "<div id=\"news\">";
echo "<div id=\"othernews\">";
include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-general.phtml");
echo "</div>\n<div class=\"othernews\">\n";
include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-documentation.phtml");
echo "</div>\n<div class=\"othernews\">\n";
include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-help.phtml");
echo "</div>\n<div class=\"othernews\">\n";
include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-downloads.phtml");
# highlighted menu entry:
echo "</div>\n<div class=\"highlight\">\n";
include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-developer.phtml");
echo "</div>\n<div class=\"othernews\">\n";
include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-other.phtml");
echo "</div>\n<div class=\"othernews\">\n";
include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-search.phtml");
echo "</div>\n";
?>

<!-- MENU:END -->
