  <table border=0 cellpadding=0 cellspacing=6>
  <tr>
  <td><img src="/images/spacer.gif" height=1 width=2></td>
  <td>
    <font size=-1>
      <form action="/search.php3" method="get">
      <input type=text name=words size=15>
      <br><font size="-2">Sort method:</font>
      <select name="sort">
      <option value="sort">Standard
      <option value="time">Time
      <option value="revtime">Time (reversed)
      </select>
      </form>

  </td>
  </tr>
  </table>
