<span class="linktop">
<img class="dot" src="/images/webding.png" alt="marker">
<b>Developer Information</b>
</span>
<ul><li><a href="/en/architecture.phtml">System Architecture</a></li>
<li><a href="/en/roadmap.phtml">The Road Ahead</a></li>
<li><a href="http://linas.org/linux/gnucash/projects.html">Project Goals</a></li>
<li><a href="http://cvs.gnucash.org/docs/HEAD/modules.html">Source Docs</a></li>
<li><a href="https://cvs.gnucash.org/cgi-bin/cvsweb.cgi/">Browse Source Code</a></li>
<li><a href="/en/hacking.phtml">CVS Access</a></li>
<li><a href="http://www.gnucash.org/trans/">Language Translations</a></li>
</ul>

