<!-- MENU:START -->
<?php if (!ini_get('register_globals')) {
 include("../emulate_globals_on.php");
}
$self = $_SERVER["HTTP_HOST"];
if(ereg("lists.gnucash.org",$self)) {
	$home = "http://www.gnucash.org";
}
else {
$home = "";
}

echo "<div id=\"news\">";
echo "<div id=\"othernews\">";
include($GLOBALS['DOCUMENT_ROOT']."/externals/en/menu-general.phtml");
echo "</div>\n<div class=\"othernews\">\n";
include($GLOBALS['DOCUMENT_ROOT']."/externals/en/menu-documentation.phtml");
echo "</div>\n<div class=\"othernews\">\n";
include($GLOBALS['DOCUMENT_ROOT']."/externals/en/menu-help.phtml");
echo "</div>\n<div class=\"othernews\">\n";
include($GLOBALS['DOCUMENT_ROOT']."/externals/en/menu-downloads.phtml");
# highlighted menu entry:
echo "</div>\n<div class=\"highlight\">\n";
include($GLOBALS['DOCUMENT_ROOT']."/externals/en/menu-developer.phtml");
echo "</div>\n<div class=\"othernews\">\n";
include($GLOBALS['DOCUMENT_ROOT']."/externals/en/menu-other.phtml");
echo "</div>\n<div class=\"othernews\">\n";
include($GLOBALS['DOCUMENT_ROOT']."/externals/en/menu-search.phtml");
echo "</div>\n";
echo "</div>\n";
?>

<!-- MENU:END -->
