<span class="linktop">
<img class="dot" src="/images/webding.png" alt="marker">
<b>Other Information</b>
</span>
<ul>
<li><a href="/en/links.phtml">Related Financial Software</a></li>
<li><a href="/en/articles.phtml">GnuCash in the News</a></li>
<li><a href="/en/promote.phtml">GnuCash Banners!</a></li>
<li><a href="/en/history.phtml">History &amp; Credits</a></li>
<li><a href="/en/quiz-results.phtml">Survey Results</a></li>
<li><a href="/en/sizing.phtml">Sizing</a></li>
<li><a href="/en/rss-feed.phtml">
<img src="/images/rss.gif" alt="rss logo"></a></li>
</ul>
