<?php
echo "<span class=\"linktop\">\n";
echo "<img class=\"dot\" src=\"/images/webding.png\" alt=\"marker\">\n";
echo "<b>Developer Information</b>\n";
echo "</span>\n";
echo "<ul><li><a href=\"$home/en/architecture.phtml\">System Architecture</a></li>\n";
echo "<li><a href=\"$home/en/roadmap.phtml\">The Road Ahead</a></li>\n";
echo "<li><a href=\"http://linas.org/linux/gnucash/projects.html\">Project Goals</a></li>\n";
echo "<li><a href=\"http://svn.gnucash.org/docs/HEAD/\">Source Docs</a></li>\n";
echo "<li><a href=\"http://svn.gnucash.org/trac/browser/\">Browse Source Code</a></li>\n";
echo "<li><a href=\"http://wiki.gnucash.org/wiki/Subversion\">SVN Access</a></li>\n";
echo "<li><a href=\"http://www.gnucash.org/trans/\">Language Translations</a></li>\n";
echo "</ul>\n";
?>
