<!-- MENU:START -->
<?php
$self = $_SERVER["HTTP_HOST"];
if(ereg("lists.gnucash.org",$self)) {
	$home = "http://www.gnucash.org";
}
else {
$home = "";
}

echo "<div id=\"news\"><div class=\"othernews\">";
include($toppath."/www/externals/en/menu-general.phtml");
echo "</div>\n<div class=\"othernews\">\n";
include($toppath."/www/externals/en/menu-documentation.phtml");
echo "</div>\n<div class=\"othernews\">\n";
include($toppath."/www/externals/en/menu-help.phtml");
echo "</div>\n<div class=\"othernews\">\n";
include($toppath."/www/externals/en/menu-downloads.phtml");
echo "</div>\n<div class=\"othernews\">\n";
include($toppath."/www/externals/en/menu-developer.phtml");
# highlighted menu entry:
echo "</div>\n<div class=\"highlight\">\n";
include($toppath."/www/externals/en/menu-other.phtml");
echo "</div>\n<div class=\"othernews\">\n";
include($toppath."/www/externals/en/menu-search.phtml");
echo "</div>\n";
echo "</div>\n";
?>

<!-- MENU:END -->
