<span class="linktop">
<img class="dot" src="/images/webding.png" alt="marker">
<b>General Information</b>
</span>
<ul>
<li><a href="/en/index.phtml">Home / News </a></li>
<li><a href="/en/features.phtml">Features</a></li>
<li><a href="/en/screenshots.phtml">Screenshots</a></li>
<li><a href="/en/donations.phtml">Donations</a></li>
<li><a href="/en/contribute.phtml">How To Help</a></li>
<li><a href="/en/required.phtml">Software Dependencies</a></li>
</ul>