<!-- MENU:START -->

<table border=0 cellpadding=4 cellspacing=0 width=100%>
<tr>
  <td><img border=0 src=/images/webding.png> <a href="/en/">Home</a></td>
</tr>
<tr>
  <td bgcolor=#cacaf7>
  <img border=0 src=/images/webding.png> <b>General Information</b>

<?php include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-general.phtml"); ?>

  </td>
</tr>
<tr>
  <td>
  <img border=0 src=/images/webding.png> <b>Downloads</b>

<?php include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-downloads.phtml"); ?>

</tr>
<tr>
  <td>
  <img border=0 src=/images/webding.png> <b>Developer Information</b>

<?php include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-developer.phtml"); ?>

</tr>
<tr>
  <td>
  <img border=0 src=/images/webding.png> <b>Other Information</b>

<?php include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-other.phtml"); ?>

</tr>
<tr>
  <td>
  <img border=0 src=/images/webding.png> <b>Documentation</b>

<?php include($GLOBALS['DOCUMENT_ROOT']."/en/menu/menu-documentation.phtml"); ?>

</tr>
</table>

<!-- MENU:END -->
