  <table border=0 cellpadding=0 cellspacing=6>
  <tr>
  <td><img src="/images/spacer.gif" height=1 width=2></td>
  <td>
    <font size=-1>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/en/index.phtml">Home / News </a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/en/features.phtml">Features</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/en/screenshots.phtml">Screenshots</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/en/roadmap.phtml">The Road Ahead</a><br>

<!--
    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/en/quiz.phtml">User Survey</a><br>
-->
 
    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/en/required.phtml">Software Requirements</a><br>
 
  </td>
  </tr>
  </table>
