<span class="linktop">
<img class="dot" src="/images/webding.png" alt="marker">
<b>Downloads</b></span>
<ul>
<li><a href="http://www.gnucash.org/pub/">USA (master site)</a></li>
<li><a href="http://ftp.at.gnucash.org/pub/gnucash/">Europe</a></li>
<li><a href="http://sourceforge.net/project/showfiles.php?group_id=192">SourceForge</a></li>
<li><a href="ftp://planetmirror.com/pub/gnucash/">Australia</a></li>
</ul>
