  <table border=0 cellpadding=0 cellspacing=6>
  </tr>
  <td><img src="/images/spacer.gif" height=1 width=2></td>
  <td>
    <font size=-1>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/en/links.phtml">Related Financial software</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/en/articles.phtml">GnuCash in the news</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/en/promote.phtml">Promote GnuCash</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/en/history.phtml">History</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="http://www.gnumatic.com/">Corporate Backing</a><br>

  </td>
  </tr>
  </table>
