  <table border=0 cellpadding=0 cellspacing=6>
  </tr>
  <td><img src="/images/spacer.gif" height=1 width=2></td>
  <td>
    <font size=1>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/docs/C/index.html">English</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/docs/es/">Espagnol</a><br>
    
    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/docs/fr/index.html">Français</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/docs/pt_PT/">Portuguese</a><br>
    
  </td>
  </tr>
  </table>
