  <table border=0 cellpadding=0 cellspacing=6>
  <tr>
  <td><img src="/images/spacer.gif" height=1 width=2 alt="spacer"></td>
  <td>
    <font size=-1>

    <img src="/images/webding.png" height=8 width=8 border=0 alt="dot">&nbsp;
    <a href="/en/links.phtml">Related Financial Software</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0 alt="dot">&nbsp;
    <a href="/en/articles.phtml">GnuCash in the News</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0 alt="dot">&nbsp;
    <a href="/en/promote.phtml">GnuCash Banners!</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0 alt="dot">&nbsp;
    <a href="/en/history.phtml">History &amp; Credits</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0 alt="dot">&nbsp;
    <a href="/en/quiz-results.phtml">Survey Results</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0 alt="dot">&nbsp;
    <a href="/en/sizing.phtml">Sizing</a><br>
    
    <img src="/images/webding.png" height=8 width=8 border=0 alt="dot">&nbsp;
    <a href="http://www.gnucash.org/en/rss-feed.phtml"><img src="/images/rss.gif" align="center"></a>

    </font>

  </td>
  </tr>
  </table>
