<span class="linktop"><img class="dot"
src="/images/webding.png" alt="marker">
<b>Documentation</b></span>
<ul><li>
<a href="http://www.gnucash.org/docs/v1.8/C/gnucash-guide">
Concepts Guide</a></li>
<li>
<a href="http://www.gnucash.org/docs/v1.8/C/gnucash-help/help.html">
Help Manual</a>
<a href="http://www.gnucash.org/docs/v1.8/de_DE/gnucash-help/help.html">
[de]</a></li>
<li><a href="/en/sql.phtml">SQL HOWTO</a></li>
<li><a href="/en/docs.phtml">more...</a></li>

</ul>
