  <table border=0 cellpadding=0 cellspacing=6>
  <tr>
  <td><img src="/images/spacer.gif" height=1 width=2></td>
  <td>
    <font size=-1>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/docs/C/gnucash-guide">Tutorial/Concepts (English)</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/docs/C/gnucash-help/help.html">Help Manual (English)</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/docs/de_DE/gnucash-help/help.html">GnuCash Hilfe (Deutsch)</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/docs/es/">Espagnol</a><br>
    
    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/docs/fr/">Français</a><br>

    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="/docs/pt_PT/">Português</a><br>
    
    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="http://www.aerospacesoftware.com/GNU_Cash_for_Business_users_Howto_Guide.html"">GnuCash for Business Users</a> (<a href="http://www.linas.org/mirrors/www.aerospacesoftware.com/2003.06.21/GNU_Cash_for_Business_users_Howto_Guide.html">mirror</a>)<br>
    
    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="http://www.ncsysadmin.org/july2001/ncsa-gnucash-talk.html">Joe Mack's Tutorial</a><br>
    
    <img src="/images/webding.png" height=8 width=8 border=0>&nbsp;
    <a href="http://www.object-refinery.com/gnucash/index.html">Dave Gilbert's User Guide (PDF)</a><br>

  </td>
  </tr>
  </table>
