<div class="tblborder">
   <table class="tbllimit" cellpadding=5 cellspacing=1>
   <colgroup><col width="25%"><col width="50%"></colgroup>
   <tr>
     <td class="tblheader"><b>Name</b></td>
     <td class="tblheader"><b>Description</b></td>
   </tr>
   <tr>
   <td colspan=2><B>Business, ERP Projects</B>
     </td> </tr>
   <tr style="background-color:white">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
       	<a href="http://sourceforge.net/projects/gnupos/">GnuPOS</a>
   </td><td>
	GPL'ed Point-of-Sale system.
   </td></tr>

   <tr class="divider">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
       	<a href="http://sourceforge.net/projects/mercator">Mercator</a>
   </td><td>
	Java-based Point-of-Sale system.
   </td></tr>

   <tr style="background-color:white">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
       	<a href="http://www.bananahead.com/pos/index.html">BananaheadPOS</a>
   </td><td>
	Web-based GPL'ed Point-of-Sale system.
   </td></tr>

   <tr class="divider">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
       	<a href="http://www.gnue.org/">Gnu Enterprise</a>
   </td><td>
	The premier Gnu/GPL project aiming to create an 
	ERP system for small, medium and large businesses.   
	This is an ambitious project, but its the show-stopper of the bunch.
   </td></tr>

   <tr style="background-color:white">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <A HREF="http://sql-ledger.com/">SQL Ledger</a>
   </td><td>
	 An advanced, GPL'ed, web-based business accounting package.
   </td></tr>

   <tr class="divider">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.zelerate.org/">
		 Zelerate AllCommerce</a>
   </td><td>
         A GPL'ed e-commerce package.  Provides modules for 
         content creation, inventory management, product ordering, 
	 statistical analysis, shipping and merchandising. 
   </td></tr>

   <tr style="background-color:white">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.openadaptor.org/">Open Adaptor</a>
   </td><td>
	 A Java/XML based set of utilities to access and convert 
	 between many different (financial & business) data formats.  
	 Support for Oracle, Sybase, TIBCO, XML, Fix, Swift, and HTML.
   </td></tr>

   <tr class="divider">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.ios-online.de/Linux-Kontor/">Linux-Kontor</a>
   </td><td>
	 A business accounting package that uses Java and SQL databases.
   </td></tr>
	 
   <tr style="background-color:white">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://obelisk.dhs.org">Obelisk</a>
   </td><td>
	Business Accounting project
   </td></tr>

   <tr class="divider">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.sisd.com/freeside/">Freeside</a>
   </td><td>
	 An open source billing and account administration package for ISP's.
   </td></tr>

   <tr style="background-color:white">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.freepm.org/">FreePM Free Practice Management</a>
   </td><td>
	 FreePM is an open source physicans office management &amp; electronic
	 medical record application.
   </td></tr>
   </table>
</div>

