<div class="tblborder">
   <table class="tbllimit" cellpadding=5 cellspacing=1>
   <colgroup><col width="25%"><col width="50%"></colgroup>
   <tr>
     <td class="tblheader"><b>Name</b></td>
     <td class="tblheader"><b>Description</b></td>
   </tr>
   <tr class="tblbanner">
     <td colspan=2><B>XML and Other Data Formats</B>
     </td>
   </tr>
   <tr>
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.semper.org/">Secure Electronic Marketplace for Europe</a>
   </td><td>
	 SEMPER is a European R&amp;D project in the area of secure 
	 electronic commerce over open networks.
   </td></tr>

   <tr class="divider">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://ganges.cs.tcd.ie/mepeirce/Project/oninternet.html">
	Payment mechanisms designed for the Internet</a>
   </td><td>
	Provides a treasure-trove of links for zillions of standards and proposals.
   </td></tr>

   <tr>
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.cloanto.com/specs/seriff.html">SERIFF</a>
   </td><td>
	 Simple Exchange Rate Information File Format.  Completely *.ini-centric 
	 in layout and design, but otherwise seemingly quite complete.
   </td></tr>

   <tr class="divider">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.cosource.com/cgi-bin/cos.pl/wish/info/339">
	Quicken File Reader</a>
   </td><td>
	RFP at Cosource is willing to pay $25,000 for a file reader that can 
	read Quicken files natively.
   </td></tr>

   <tr>
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.ifxforum.org">IFX Forum</a>
   </td><td>
	 XML-based financial-info exchange protocol developed by various banks.
   </td></tr>

   <tr class="divider">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.ofx.net/">Open Financial Exchange</a>
   </td><td>
	 A consortium backed by Intuit, CheckFree and Microsoft to advance 
	 on-line banking. Primarily a definition of OFX, an XML-based protocol 
	 for the exchange of banking info and on-line bill-pay.
   </td></tr>

   <tr>
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.ietf.org/html.charters/trade-charter.html">
	Open Trading Protocol</a>
   </td><td>
	 IETF Proposed Standard for an XML-based internet commerce protocol. 
	 Offers support for offering goods &amp; services, pruchases, 
	 invoice presentation, payment and payment receipts.  Version 1 
	 has been around for years and currently exists as an informational RFC.
	 Version 2 is in development and slated to become a draft in Summer 2001.
   </td></tr>

   <tr class="divider">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.fpml./org">FpML - Financial Product Markup Language</a>
   </td><td>
	 XML-based protocol for the exchange and trading of financial instruments.
   </td></tr>

   <tr>
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <!-- <a href="http://www.europay.ch/products/systems/dta/dta-en.html">DTA</a> -->
	 <!-- <a href="http://www.sic.ch/en/c6_2.htm">DTA</a> -->
	 <a href="http://www.sic.ch/dl_tkicch_dta.pdf">DTA</a>
   </td><td>
	 (Daten Traeger Austausch) is an online banking format used in 
	 Switzerland by --all-- Swiss banks.  The format is open.  See also the 
	 dtaus software on metalab.unc.edu or mirrors.
   </td></tr>

   <tr class="divider">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.hbci.de/english/index.html">HBCI</a>
   </td><td>
         Home Banking Computer Interface -- a banking protocol used widely 
	 by German banks.
   </td></tr>

   <tr>
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.smbxml.org">Small Business XML</a>
   </td><td>
	 Publicly-documented XML DTD for conducting small & medium-sized 
	 business transactions.
   </td></tr>

   <tr class="divider">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.openapplications.org/">Open Applications Group</a>
   </td><td>
	 Specs for XML-based business software interoperability.  Includes 
	 XML specs for request-for-quote, shipping, &amp; numerous other projects.
   </td></tr>

   <tr>
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.compassgl.org/newhometest/990305fr1.html">
	OMG General Ledger (GL) Facility</a>
   </td><td>
	 The Compass submission for the OMG (CORBA) General Ledger.
   </td></tr>

   <tr class="divider">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.xfrml.org/">
	XFRML, XML-based Financial Reporting Markup Language</a>
   </td><td>
	 Quote from their site: <i>XFRML is a framework that will allow the 
	 financial community a standards-based method to prepare, publish in a 
	 variety of formats, exchange and analyze financial reports and the 
	 information they contain.</i> 
   </td></tr>

   <tr>
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.ietf.org/rfc/rfc2371.txt">
	TIP- Transaction Internet Protocol</a>
   </td><td>
         The Transaction Internet Protocol (RFC 2371) defines a simple 
	 transactional two-phase-commit protocol that can be used for 
	 transactional messaging.  For example, if you want to withdraw
	 $100 from an account on computer A and deposit that money into 
	 an account one computer B, and make sure that you haven't 'lost'
	 or 'gained' the money in transit, you need a transactional protocol.
   </td></tr>
   </table>
</div>

