<div>
<small>
The following URL's are inactive, obsolete or otherwise wasting
away, but are here for historical interest, in part to document
the way things used to be. Of archeological, nostalgic use
only.
</small>
</div>

<div class="tblborder">
   <table class="tbllimit" cellpadding=5 cellspacing=1>
   <colgroup><col width="25%"><col width="50%"></colgroup>
   <tr>
     <td class="tblheader"><b>Name</b></td>
     <td class="tblheader"><b>Description</b></td>
   </tr>
   <tr class="tblbanner">
   <td colspan=2><B>Historical References</B>
     </td> </tr>
   <tr>
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.cs.hmc.edu/~rclark/xacc/">X-Accountant Home Page</a>
   </td><td>
	 This was the original site for the GPL'ed accounting 
	 package that eventually evolved into GnuCash. Robin Clark wrote 
	 the first version while at school at Harvey Mudd College.
   </td></tr>
	 
   <tr class="divider">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.dnaco.net/~bcooper/watermark/index.html">WaterMark</a>
   </td><td>
	 Gnome/KDE personal finance project page.  Watermark and 
	 GnoMoney were proposed about the same time, and there was talk 
	 of joining forces with X-Accountant.
   </td></tr>

   <tr>
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.im.lcs.mit.edu/~magnus/ml/">Maxwell's Lemur</a>
   </td><td>
	 GTK based table widget
   </td></tr>

   <tr class="divider">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.telly.org/freemoney/">FreeMoney</a>
   </td><td>
	 Linux small-business accounting s/w.  A proposal to build a 
	 business package backed by SQL.
   </td></tr>
   </table>
</div>

