<div class="tblborder">
   <table class="tbllimit" cellpadding=5 cellspacing=1>
   <colgroup><col width="25%"><col width="50%"></colgroup>
   <tr>
     <td class="tblheader"><b>Name</b></td>
     <td class="tblheader"><b>Description</b></td>
   </tr>
   <tr class="tblbanner">
   <td colspan=2><B>Utilities</B>
   </td> </tr>
      <tr>
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	<A HREF="http://gnucashtoqif.sourceforge.net/">gnucashtoqif</a>
   </td><td>
	 Java tool for converting GnuCash XML files to QIF.
   </td></tr>

      <tr class="divider">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	<A HREF="http://nicolas.marchildon.net/gnu_qif/">gnu_qif</a>
   </td><td>
	 Java tool for converting other financial formats to QIF.
   </td></tr>

      <tr>
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	<A HREF="http://www-cad.eecs.berkeley.edu/~gooch/mymdump.html">MYMdump</a>
   </td><td>
	 MYM Managing Your Money to QIF Converter.
   </td></tr>

      <tr class="divider">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.snaught.com/gbonds/">GBonds</a>
   </td><td>
	 Gnome desktop tool for tracking U.S. Savings Bonds.
   </td></tr>

   </table>
</div>

