<% ns_adp_include [ns_info pageroot]/en/components/header.adp "Other Financial Software" %>
<% ns_adp_include [ns_info pageroot]/en/menu/menu-other-main.adp %>
<% prepare_form_variables %>

<td valign=top>
<h1>Related Financial Software</h1>
<font size=-1>

<table>
<tr><td>
<b>Select a section:</b></td>
<td>
<form method=post>
<select name=links>
  <option value=1>General References</option>
  <option value=2>Utilities</option>
  <option value=3>Palm Computing</option>
  <option value=4>Stock Trading & Technical Analysis</option>
  <option value=5>Quote Sources, Tools</option>
  <option value=6>Business, ERP Projects</option>
  <option value=7>XML and Other Data Formats</option>
  <option value=8>Miscellaneous</option>
  <option value=9>Historical References</option>
	<option value=10>Gnucash Review & Rating Sites</option>
</select>
<input type=submit value=Go>
</td>
</table>
</form>

<% 
  if [info exists ::links] {
    ns_adp_include [ns_info pageroot]/en/links/links-${::links}.adp
  }
%>

</font>

</td>


<% ns_adp_include [ns_info pageroot]/en/components/footer.adp %>
