

<table border=0 cellpadding=1 cellspacing=0 width="100%">
  <tr>
  <td valign=middle align=center bgcolor=#666699>
   <table border=0 cellpadding=5 cellspacing=1 bgcolor=#cacaf7 width="100%">
   <tr>
     <td bgcolor=#666699 width=25%><font color=#ffffff><b>Name</b></td>
     <td bgcolor=#666699 width=50%><font color=#ffffff><b>Description</b></td>
   </tr>
   <tr>
	   <td colspan=2>
<B>Palm Computing</B><BR>
     </td>
	 </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <A HREF="http://sourceforge.net/projects/pm2qif/">pm2qif PocketMoney to QIF Converter</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		  A set of perl scripts to convert PocketMoney DB files to QIF files.  PocketMoney is a popular Palm shareware accounting package.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <A HREF="http://sourceforge.net/projects/palmcoins/">PalmCoins</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 A GPL'ed accounting program for the PalmOS
		 </td>
   </tr>
   </table>
</tr>
</table>
