
<table border=0 cellpadding=1 cellspacing=0 width="100%">
  <tr>
  <td valign=middle align=center bgcolor=#666699>
   <table border=0 cellpadding=5 cellspacing=1 bgcolor=#cacaf7 width="100%">
   <tr>
     <td bgcolor=#666699 width=25%><font color=#ffffff><b>Name</b></td>
     <td bgcolor=#666699 width=50%><font color=#ffffff><b>Description</b></td>
   </tr>
   <tr>
	   <td colspan=2>
<B>Quote Sources, Tools</B><BR>
     </td>
	 </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://finance-quote.sourceforge.net/">Finance::Quote</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Perl module for getting stock price and currency exchange rate data from a variety of web sources.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://getquote.giammy.com/">GetQuote</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 A command-line tool for getting stock quotes. Implemented in C.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.datek.com/">Datek</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Free data streaming.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://freerealtime.com">FreeRealTime</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Free data streaming.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.money.net">MoneyNet</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Free data streaming.
		 </td>
   </tr>
   </table>
</tr>
</table>
