
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-header.phtml"); ?>

   <tr>
     <td colspan=2>
<B>XML and Other Data Formats</B><BR>
     </td>
   </tr>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <a href="http://www.semper.org/">Secure Electronic Marketplace for Europe</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
		 SEMPER is a European R&amp;D project in the area of secure 
		 electronic commerce over open networks.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <a href="http://ganges.cs.tcd.ie/mepeirce/Project/oninternet.html">Payment 
		 mechanisms designed for the Internet</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
		 Provides a treasure-trove of links for zillions of standards and proposals.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <a href="http://www.cloanto.com/specs/seriff.html">SERIFF</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
		 Simple Exchange Rate Information File Format.  Completely *.ini-centric 
		 in layout and design, but otherwise seemingly quite complete.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <a href="http://www.cosource.com/cgi-bin/cos.pl/wish/info/339">Quicken 
		 File Reader</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
		 RFP at Cosource is willing to pay $25,000 for a file reader that can 
		 read Quicken files natively.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <a href="http://www.ifxforum.org">IFX Forum</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
		 XML-based financial-info exchange protocol developed by various banks.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <a href="http://www.ofx.net/">Open Financial Exchange</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
		 A consortium backed by Intuit, CheckFree and Microsoft do advance 
		 on-line banking. Primarily a definition of OFX, an XML-based protocol 
		 for the exchange of banking info and on-line bill-pay.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <a href="http://http://www.otp.org/">Open Trading Protocol</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
		 An XML-based message protocol for payment, invoice presentation, 
		 and payment receipts.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <a href="http://www.fpml./org">FpML - Financial Product Markup Language</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
		 XML-based protocol for the exchange and trading of financial instruments.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <a href="http://www.europay.ch/products/systems/dta/dta-en.html">DTA</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
		 (Daten Traeger Austausch) is an online banking format used in 
		 Switzerland by --all-- Swiss banks.  The format is open.  See also the 
		 dtaus software on metalab.unc.edu or mirrors.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <a href="http://www.hbci.de/english/index.html">HBCI</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
	         Home Banking Computer Interface -- a banking protocol used widely 
		 by German banks.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <a href="http://www.smbxml.org">Small Business XML</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
		 Publicly-documented XML DTD for conducting small & medium-sized 
		 business transactions.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <a href="http://www.openapplications.org/">Open Applications Group</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
		 Specs for XML-based business software interoperability.  Includes 
		 XML specs for request-for-quote, shipping, & numerous other projects.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <a href="http://www.compassgl.org/newhometest/990305fr1.html">OMG General 
		 Ledger (GL) Facility</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
		 The Compass submission for the OMG (CORBA) General Ledger.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <a href="http://www.xfrml.org/">XFRML, XML-based Financial Reporting 
		 Markup Language</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
		 Quote from their site: <i>XFRML is a framework that will allow the 
		 financial community a standards-based method to prepare, publish in a 
		 variety of formats, exchange and analyze financial reports and the 
		 information they contain.</i> 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <a href="http://www.ietf.org/rfc/rfc2371.txt">TIP- Transaction Internet 
		 Protocol</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
	         The Transaction Internet Protocol (RFC 2371) difines a simple 
		 transactional two-phase-commit protocol that can be used for 
		 transactional messaging.  For example, if you want to withdraw
		 $100 from an account on computer A and deposit that money into 
		 an account one computer B, and make sure that you haven't 'lost'
		 or 'gained' the money in transit, you need a transactional protocol.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>
   </table>
</tr>
</table>
