
<font size=-1>
The following URL's are inactive, obsolete or otherwise wasting
away, but are here for historical interest, in part to document
the way things used to be. Of archeological, nostalgic use
only.
</font>

<br><br>

<table border=0 cellpadding=1 cellspacing=0 width="100%">
  <tr>
  <td valign=middle align=center bgcolor=#666699>
   <table border=0 cellpadding=5 cellspacing=1 bgcolor=#cacaf7 width="100%">
   <tr>
     <td bgcolor=#666699 width=25%><font color=#ffffff><b>Name</b></td>
     <td bgcolor=#666699 width=50%><font color=#ffffff><b>Description</b></td>
   </tr>
   <tr>
	   <td colspan=2>
<B>Historical References</B><BR>
     </td>
	 </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www3.hmc.edu/~rclark/xacc/">X-Accountant Home Page</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 This was the original site for the GPL'ed accounting package that eventually evolved into GnuCash. Robin Clark wrote the first version while at school at Harvey Mudd College.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.dnaco.net/~bcooper/watermark/index.html">WaterMark</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Gnome/KDE personal finance project page.  Watermark and GnoMoney were proposed about the same time, and there was talk of joining forces with X-Accountant.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.im.lcs.mit.edu/~magnus/ml/">Maxwell's Lemur</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 GTK based table widget
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.telly.org/freemoney/">FreeMoney</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Linux small-business accounting s/w.  A proposal to build a business package backed by SQL.
		 </td>
   </tr>
   </table>
</tr>
</table>
