
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-header.phtml"); ?>
   <tr> <td colspan=2>
<B>Business, ERP Projects</B><BR>
     </td> </tr>
     
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
         	<a href="http://www.gnue.org/">Gnu Enterprise</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
     		The premier Gnu/GPL project aiming to create an 
		ERP system for small, medium and large businesses.   
		This is an ambitious project, but its the show-stopper of the bunch.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <A HREF="http://sql-ledger.com/">SQL Ledger</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
		 An advanced, GPL'ed, web-based business accounting package.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <a href="http://www.zelerate.org/">
		 Zelerate AllCommerce</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
	         A GPL'ed e-commerce package.  Provides modules for 
	         content creation, inventory management, product ordering, 
		 statistical analysis, shipping and merchandising. 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <a href="http://www.openadaptor.org/">Open Adaptor</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
		 A Java/XML based set of utilities to access and convert 
		 between many different (financial & business) data formats.  
		 Support for Oracle, Sybase, TIBCO, XML, Fix, Swift, and HTML.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <a href="http://www.ios-online.de/Linux-Kontor/">Linux-Kontor</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
		 A business accounting package that uses Java and SQL databases.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <a href="http://obelisk.dhs.org">Obelisk</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
      		Business Accounting project
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <a href="http://www.sisd.com/freeside/">Freeside</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
		 An open source billing and account administration package for ISP's.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <a href="http://www.freepm.org/">FreePM Free Practice Management</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
		 FreePM is an open source physicans office management &amp; electronic
		 medical record application.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>
   </table>
</tr>
</table>
