<div class="tblborder">
   <table class="tbllimit" cellpadding=5 cellspacing=1>
   <colgroup><col width="25%"><col width="50%"></colgroup>
   <tr>
     <td class="tblheader"><b>Name</b></td>
     <td class="tblheader"><b>Description</b></td>
   </tr>
   <tr class="tblbanner">
   <td colspan=2><B>Miscellaneous</B></td>
   </tr>
   <tr>
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.unixrealm.com/downloads/">Unixrealm</a>
   </td><td>
	 Gnome and GnuCash binaries for Solaris.
   </td></tr>

   <tr class="divider">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.ibm.com/java/sanfrancisco">IBM San Francisco</a>
   </td><td>
	 Business and Financial Java classes.
   </td></tr>
	 
   <tr>
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.integrion.com/">Integrion</a>
   </td><td>
	 A 16-bank + IBM consortium aimed at building an on-line banking 
	 infrastructure.  Currently deployed by some rather large banks.
   </td></tr>

   <tr class="divider">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.sun.com/980224/javapos/">Java Point of Sale</a>
   </td><td>
	 &nbsp;
   </td></tr>

   <tr>
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.pango.org/">Pango</a>
   </td><td>
	 Internationalized text rendering for gtk.
   </td></tr>
	 
   <tr class="divider">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="ftp://ftp.gnu.org/pub/gnu/plotutils/">Gnu Plotutils</a>
   </td><td>
	 A graphing/plotting package.
   </td></tr>
	 
   <tr>
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
       	<a href="http://www.im.lcs.mit.edu/~magnus/ml/">GTK grid widget</a>
   </td><td>
	 May be better than Clint, gtktable
   </td></tr>
	 
   <tr class="divider">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.didx.com/xml-builder.html">XML Builder</a>
   </td><td>
	 Allows GUI screens to be described using XML markup. See also mozilla.org's xpfe.
   </td></tr>
	 
   <tr>
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.engelschall.com/sw/eperl">Embedded Perl</a>
   </td><td>
	 Allows perl to be embedded into html pages to create dynamic content.
   </td></tr>
	 
   <tr class="divider">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.ispras.ru/~knizhnik/gigabase.html">GigaBASE</a>
   </td><td>
	 Embeddable SQL database.
   </td></tr>
   </table>
</div>

