
<table border=0 cellpadding=1 cellspacing=0 width="100%">
  <tr>
  <td valign=middle align=center bgcolor=#666699>
   <table border=0 cellpadding=5 cellspacing=1 bgcolor=#cacaf7 width="100%">
   <tr>
     <td bgcolor=#666699 width=25%><font color=#ffffff><b>Name</b></td>
     <td bgcolor=#666699 width=50%><font color=#ffffff><b>Description</b></td>
   </tr>
   <tr>
	   <td colspan=2>
<B>Miscellaneous</B><BR>
     </td>
	 </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.pango.org/">Pango</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Internationalized text rendering for gtk.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.semper.org/">Secure Electronic Marketplace for Europe</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 SEMPER is a European R&amp;D project in the area of secure electronic commerce over open networks.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.transaction.net/money/">How Money Works</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 &nbsp;
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.sabotage.net/security/ecash/lucre/"> -lucre</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 A publicly available version of e-cash.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.ibm.com/java/sanfrancisco">IBM San Francisco</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Business and Financial Java classes.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.integrion.com/">Integrion</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 A 16-bank + IBM consortium aimed at building up on-line banking infrastructure. Mostly aimed at mainframes, middle-ware, high transaction volumes and data integrity.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.sun.com/980224/javapos/">Java Point of Sale</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 &nbsp;
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="ftp://ftp.gnu.org/pub/gnu/plotutils/">Gnu Plotutils</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Needed for building the graphing portions of the code.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
         <a href="http://www.im.lcs.mit.edu/~magnus/ml/">GTK grid widget</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 May be better than Clint, gtktable
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.didx.com/xml-builder.html">XML Builder</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Aollows GUI screens to be described using XML markup. See also mozilla.org's xpfe.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
		 <a href="http://www.engelschall.com/sw/eperl">Embedded Perl</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 &nbsp;
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.ispras.ru/~knizhnik/gigabase.html">GigaBASE</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Embeddable SQL database.
		 </td>
   </tr>
   </table>
</tr>
</table>
