
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-header.phtml"); ?>

   <tr>
     <td colspan=2>
<B>General References</B><BR>
     </td>
     </tr>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <a href="http://www.transaction.net/money/">How Money Works</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
	         Money doesn't have to be a national currency: it can be frequent flyer
		 miles, bartered hours, and other things.  This page reviews the very
		 idea of money, and lists the characteristics of different types of money.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <a href="http://www.e-gold.com/e-gold.asp?cid=281678">E-Gold</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
		 E-gold is an electronic currency.  Unlike a national currency, its 
		 privately issued, and backed by gold reserves.  Unlike a credit card,
		 its a bit more anonymous, but not quite as anonymous as cash.
		 Slowly growing in popularity.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <a href="http://www.iasc.org.uk/frame/cen2.htm">International Accounting 
		 Standards</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
		 International Accounting Standards Committee.  Dry, but a good source
		 of the technical and legal documents that define accounting rules.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <a href="http://cbbrowne.com/info/finances.html">CBBrowne's Finances, 
		 Linux, and Stuff</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
		 Christopher Browne reviews a number of financial applications for Linux.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <a href="http://www.linuxlinks.com/Software/Financial/">LinuxLinks 
		 Financial Software</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
		 An extensive list of free and commercial programs.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>
  </table>
</tr>
</table>
