
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-header.phtml"); ?>
   <tr> <td colspan=2>
<B>Electronic Money</B><BR>
     </td> </tr>
     
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
         	<a href="http://www.e-gold.com/e-gold.asp?cid=281678">E-Gold</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
	        E-Gold is a tradeable currency backed by gold and other 
		precious metal deposits.  One way to think of e-gold is as
		a mutual fund for gold.  However, it is no ordinary mutual fund,
		and behaves a lot more like a currency: that is, you can very easily
		give very tiny (or large) amounts of e-gold to other people. 
		There is no minimum balance requirement: you can maintain a 
		balance of pennies.  There is a service fee, but it is minimal.
		E-Gold was designed and is really meant to be used as a (convertible)
		currency backed by hard assets.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>

   </table>
</tr>
</table>
