<div class="tblborder">
   <table class="tbllimit" cellpadding=5 cellspacing=1>
   <colgroup><col width="25%"><col width="50%"></colgroup>
   <tr>
     <td class="tblheader"><b>Name</b></td>
     <td class="tblheader"><b>Description</b></td>
   </tr>
   <tr class="tblbanner">
   <td colspan=2><B>Palm Computing</B>
   </td> </tr>
   <tr>
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
       	<A HREF="http://sourceforge.net/projects/pm2qif/">
	pm2qif PocketMoney to QIF Converter</a>
   </td><td>
	  A set of perl scripts to convert PocketMoney DB files to QIF 
	  files.  PocketMoney is a popular Palm shareware accounting package.
   </td></tr>

   <tr class="divider">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <A HREF="http://sourceforge.net/projects/freecoins/">FreeCoins</a>
   </td><td>
	 A GPL'ed accounting program for the PalmOS
   </td></tr>
   </table>
</div>

