
<table border=0 cellpadding=1 cellspacing=0 width="100%">
  <tr>
  <td valign=middle align=center bgcolor=#666699>
   <table border=0 cellpadding=5 cellspacing=1 bgcolor=#cacaf7 width="100%">
   <tr>
     <td bgcolor=#666699 width=25%><font color=#ffffff><b>Name</b></td>
     <td bgcolor=#666699 width=50%><font color=#ffffff><b>Description</b></td>
   </tr>
   <tr>
     <td colspan=2>
<B>Quote Sources, Tools</B><BR>
     </td>
   </tr>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <a href="http://finance-quote.sourceforge.net/">Finance::Quote</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
		 Perl module for getting stock price and currency exchange rate data 
		 from a variety of web sources.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <a href="http://getquote.giammy.com/">GetQuote</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
		 A command-line tool for getting stock quotes. Implemented in C.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <a href="http://www.datek.com/">Datek</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
		 Free data streaming.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <a href="http://www.financialweb.com/mktIndex.asp">FinancialWeb</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
		 Free data streaming.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <a href="http://freerealtime.com">FreeRealTime</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
		 Free data streaming.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <a href="http://money.go.com">GoMoney - ABC News</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
		 Free data streaming.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <a href="http://www.marketwatch.com/tools/quotes/basic.asp?siteid=mktw">CBS
		 MarketWatch</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
		 Free data streaming.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
		 <a href="http://www.money.net">MoneyNet</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
		 Free data streaming.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>
   </table>
</tr>
</table>
