
<table border=0 cellpadding=1 cellspacing=0 width="100%">
  <tr>
  <td valign=middle align=center bgcolor=#666699>
   <table border=0 cellpadding=5 cellspacing=1 bgcolor=#cacaf7 width="100%">
   <tr>
     <td bgcolor=#666699 width=25%><font color=#ffffff><b>Name</b></td>
     <td bgcolor=#666699 width=50%><font color=#ffffff><b>Description</b></td>
   </tr>
   <tr>
	   <td colspan=2>
<B>Business, ERP Projects</B><BR>
     </td>
	 </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
         <a href="http://www.gnue.org/">Gnu Enterprise</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
     The premier Gnu/GPL project aiming to create an ERP system for small, medium and large businesses.   This is an ambitious project, but its the show-stopper of the bunch.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <A HREF="http://sql-ledger.com/">SQL Ledger</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 An advanced, GPL'ed, web-based business accounting package.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.openadaptor.org/">Open Adaptor</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 A Java/XML based set of utilities to access and convert between many different (financial & business) data formats.  Support for Oracle, Sybase, TIBCO, XML, Fix, Swift, and HTML.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.ios-online.de/Linux-Kontor/">Linux-Kontor</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 An industrial accounting package that uses Java and SQL databases.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://obelisk.dhs.org">Obelisk</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
      Business Accounting project
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.sisd.com/freeside/">Freeside</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 An open source billing and account administration package for ISP's.
		 </td>
   </tr>
   </table>
</tr>
</table>
