<div class="tblborder">
   <table class="tbllimit" cellpadding=5 cellspacing=1>
   <colgroup><col width="25%"><col width="50%"></colgroup>
   <tr>
     <td class="tblheader"><b>Name</b></td>
     <td class="tblheader"><b>Description</b></td>
   </tr>
   <tr class="tblbanner">
     <td colspan=2><B>General References</B></td>
   </tr>
   <tr>
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	<a href="http://www.transaction.net/money/">How Money Works</a>
   </td><td>
	Money doesn't have to be a national currency: it can be frequent flyer
	miles, bartered hours, and other things.  This page reviews the very
	idea of money, and lists the characteristics of different types of money.
   </td></tr>
	 
   <tr style="background-color:#ececff">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.e-gold.com/e-gold.asp?cid=281678">E-Gold</a>
   </td><td>
	 E-gold is an electronic currency.  Unlike a national currency, its 
	 privately issued, and backed by gold reserves.  Unlike a credit card,
	 its a bit more anonymous, but not quite as anonymous as cash.
	 Slowly growing in popularity.
   </td></tr>

   <tr style="background-color:#ffffff">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.iasc.org.uk/frame/cen2.htm">International Accounting 
		 Standards</a>
   </td><td>
	 International Accounting Standards Committee.  Dry, but a good source
	 of the technical and legal documents that define accounting rules.
   </td></tr>

   <tr style="background-color:#ececff">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://cbbrowne.com/info/finances.html">CBBrowne's Finances, 
	 Linux, and Stuff</a>
   </td><td>
	 Christopher Browne reviews a number of financial applications for Linux.
   </td></tr>

   <tr style="background-color:#ffffff">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.linuxlinks.com/Software/Financial/">LinuxLinks 
	 Financial Software</a>
   </td><td>
	 An extensive list of free and commercial programs.
   </td></tr>
  </table>
</div>
