<div class="tblborder">
   <table class="tbllimit" cellpadding=5 cellspacing=1>
   <colgroup><col width="25%"><col width="50%"></colgroup>
   <tr>
     <td class="tblheader"><b>Name</b></td>
     <td class="tblheader"><b>Description</b></td>
   </tr>
   <tr class="tblbanner">
   <td colspan=2><B>Stock Trading &amp; Technical Analysis</B>
   </td> </tr>
      <tr>
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://avidus.sourceforge.net/">Avidus</a>
   </td><td>
	 Stock technical analysis &amp; graphing program.  GTK based.
   </td></tr>

   <tr class="divider">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://ffts.sourceforge.net/">FFTS Finicky Financial Trading System</a>
   </td><td>
	 Tracks trades, provides risk reports.  A 'front office' trading system.
   </td></tr>

   <tr>
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.freemarket-project.org/">FreeMarket</a>
   </td><td>
	 Stock technical analysis and graphing program.  Supports Easy 
	 Language TradeStation scripts.  Server supports Datek live data 
	 feeds.  This website is quite beautiful, and is aimed at building 
	 a whole user community around it.  
   </td></tr>

   <tr class="divider">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://gchartman.sourceforge.net/">gChartman</a>
   </td><td>
	 A gtk/gnome program for technical stock charting.
   </td></tr>

   <tr>
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.geniustrader.org/">Genius Trader</a>
   </td><td>
	 Stock graphing and analysis tool. Based on Perl and Tk.
   </td></tr>

   <tr class="divider">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href=" http://download.gnome.org/GNOME/unstable/sources/gnome-chart/">
	GnomeChart</a>
   </td><td>
	 Gnome stock grapher, based on Guppi.
   </td></tr>

   <tr>
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://gstalker.sourceforge.net/">gstalker</a>
   </td><td>
	 GTK/Gnome stock grapher.
   </td></tr>

   <tr class="divider">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.centercube.com/GtkPortfolio/news.html">GtkPortfolio</a>
   </td><td>
	 A portfolio tracking tool.
   </td></tr>

   <tr>
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://kstocks.sourceforge.net/">KStocks</a>
   </td><td>
	 KDE based stock graphing tool. Still primitive.
   </td></tr>

   <tr class="divider">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://eiffel-mas.sourceforge.net/">MAS Market Analysis System</a>
   </td><td>
	 Client-server. Supports large variety of complex 
	 technical indicators. Has Linux, MSWindows clients.
   </td></tr>

   <tr>
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://tree.sourceforge.net/">TREE</a>
   </td><td>
	 A historical price database server.  Feeds itself with 
	 live capture of streaming data.
   </td></tr>

   <tr class="divider">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.daveware.com/linuxrapid.html">Xrapid</a>
   </td><td>
	  Stock technical analysis.
   </td></tr>
   </table>
</div>

