
<table border=0 cellpadding=1 cellspacing=0 width="100%">
  <tr>
  <td valign=middle align=center bgcolor=#666699>
   <table border=0 cellpadding=5 cellspacing=1 bgcolor=#cacaf7 width="100%">
   <tr>
     <td bgcolor=#666699 width=25%><font color=#ffffff><b>Name</b></td>
     <td bgcolor=#666699 width=50%><font color=#ffffff><b>Description</b></td>
   </tr>
   <tr>
	   <td colspan=2>
<B>Stock Trading & Technical Analysis</B><BR>
     </td>
	 </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://avidus.sourceforge.net/">Avidus</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Stock technical analysis & graphing program.  GTK based.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://ffts.sourceforge.net/">FFTS Finicky Financial Trading System</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Tracks trades, provides risk reports.  A 'front office' trading system.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.freemarket-project.org/">FreeMarket</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Stock technical analysis and graphing program.  Supports Easy Language TradeStation scripts.  Server supports Datek live data feeds.  This website is quite beautiful, and is aimed at building a whole user community around it.  
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://gchartman.sourceforge.net/">gChartman</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 A gtk/gnome program for technical stock charting.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://prope.insa-lyon.fr/~rhertzog/geniustrader/">Genius Trader</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Stock graphing tool. Based on Perl and Tk.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://gstalker.sourceforge.net/">gstalker</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 GTK/Gnome stock grapher.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.centercube.com/GtkPortfolio/news.html">GtkPortfolio</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 A portfolio tracking tool.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://kstocks.sourceforge.net/">KStocks</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 KDE based stock graphing tool. Still primitive.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://eiffel-mas.sourceforge.net/">MAS Market Analysis System</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Client-server.  Supports large variety of complex technical indicators.  Has Linux, MSWindows clients.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://tree.sourceforge.net/">TREE</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 A historical price database server.  Feeds itself with live capture of streaming data.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.daveware.com/linuxrapid.html">Xrapid</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		  Stock technical analysis.
		 </td>
   </tr>
   </table>
</tr>
</table>
