
<table border=0 cellpadding=1 cellspacing=0 width="100%">
  <tr>
  <td valign=middle align=center bgcolor=#666699>
   <table border=0 cellpadding=5 cellspacing=1 bgcolor=#cacaf7 width="100%">
   <tr>
     <td bgcolor=#666699 width=25%><font color=#ffffff><b>Name</b></td>
     <td bgcolor=#666699 width=50%><font color=#ffffff><b>Description</b></td>
   </tr>
   <tr>
	   <td colspan=2>
<B>General References</B><BR>
     </td>
	 </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				   <a href="http://www.gldialtone.com/links.htm">GL Dialtone's awesome Links</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Provides an extensive list of link to web-ledgers, accounting software, business/asp services, electronic billing and the like.  <a href="http://www.gldialtone.com/">General Ledger Dialtone</a> itself provides an extensive information and a discussion forum for forward-thinking accounting ideas.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.iasc.org.uk/frame/cen2.htm">International Accounting Standards</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
				 International Accounting Standards Committee
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.hex.net/~cbbrowne/finances.html">CBBrowne's Finances, Linux, and Stuff</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Reviews a number of financial applications for Linux.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.linuxlinks.com/Software/Financial/">LinuxLinks Financial Software</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 An extensive list of free and commercial programs.
		 </td>
   </tr>
	 </table>
</tr>
</table>
