
<table border=0 cellpadding=1 cellspacing=0 width="100%">
  <tr>
  <td valign=middle align=center bgcolor=#666699>
   <table border=0 cellpadding=5 cellspacing=1 bgcolor=#cacaf7 width="100%">
   <tr>
     <td bgcolor=#666699 width=25%><font color=#ffffff><b>Name</b></td>
     <td bgcolor=#666699 width=50%><font color=#ffffff><b>Description</b></td>
   </tr>
   <tr>
	   <td colspan=2>
<B>XML and Other Data Formats</B><BR>
     </td>
	 </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://ganges.cs.tcd.ie/mepeirce/Project/oninternet.html">Payment mechanisms designed for the Internet</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Provides a treasure-trove of links for zillions of standards and proposals.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.cloanto.com/specs/seriff.html">SERIFF</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Simple Exchange Rate Information File Format.  Completely *.ini-centric in layout and design, but otherwise seemingly quite complete.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.cosource.com/cgi-bin/cos.pl/wish/info/339">Quicken File Reader</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 RFP at Cosource is willing to pay $25,000 for a file reader.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.ifxforum.org">IFX Forum</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 XML-based financial-info exchange protocol developed by various banks.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.ofx.net/">Open Financial Exchange</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 A consortium backed by Intuit, CheckFree and Microsoft do advance on-line banking. Primarily a definition of OFX, an XML-based protocol for the exchange of banking info and on-line bill-pay.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://http://www.otp.org/">Open Trading Protocol</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 An XML-based message protocol for payment, invoice presentation, and payment receipts.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.fpml./org">FpML -  Financial Product Markup Language</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 XML-based protocol for the exchange and trading of financial instruments.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.europay.ch/products/systems/dta/dta-en.html">DTA</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 (Daten Traeger Austausch) is an online banking format used in Switzerland by --all-- Swiss banks.  The format is open.  See also the dtaus software on metalab.unc.edu or mirrors.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.smbxml.org">Small Business XML</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Publicly-documented XML DTD for conducting small & medium-sized business transactions.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.openapplications.org/">Open Applications Group</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Specs for XML-based business software interoperability.  Includes XML specs for request-for-quote, shipping, & numerous other projects.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.compassgl.org/newhometest/990305fr1.html">OMG General Ledger (GL) Facility</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 The Compass submission for the OMG (CORBA) General Ledger.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.xfrml.org/">XFRML, XML-based Financial Reporting Markup Language</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Quote from their site: <i>XFRML is a framework that will allow the financial community a standards-based method to prepare, publish in a variety of formats, exchange and analyze financial reports and the information they contain.</i> 
		 </td>
   </tr>
   </table>
</tr>
</table>
