
<?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-header.phtml"); ?>
   <tr> <td colspan=2>
<B>Electronic Money Systems</B><BR>
     </td> </tr>
     
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
         	<a href="http://www.thecomicreader.com/html/icst/icst-5/icst-5.html">I Can't Stop Thinking #5</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
	        A little comic strip that explains micropayments.
		See also 
		<a href="http://www.thecomicreader.com/html/icst/icst-5/rc-184.jpg">page 184</a> and 
		<a href="http://www.thecomicreader.com/html/icst/icst-5/rc-185.jpg">page 185</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
         	<a href="http://www.webfunds.org/">WebFunds</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
	        WebFunds is an Open Source project to create an 
		<a href="http://webfunds.org/guide/show_time/index.html">
		extensible payments system</a>,  i.e. e-Money and e-Wallets.
		The concept of the 'value' of the money is embodied in a 'Ricardian 
		Contract', using strong crypto to authenticate.  The system has been 
		used with real money, although only small amounts of money appear to 
		be in circulation (approx $100,000 USD as of this writing).
		The project has been running for over five years, and is now in its 
		third revision.  Java-based. 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
         	<a href="http://www.e-gold.com/e-gold.asp?cid=281678">E-Gold</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
	        E-Gold is a tradeable currency backed by gold and other 
		precious metal deposits.  One way to think of e-gold is as
		a mutual fund for gold.  However, it is no ordinary mutual fund,
		and behaves a lot more like a currency: that is, you can very easily
		give very tiny (or large) amounts of e-gold to other people. 
		There is no minimum balance requirement: you can maintain a 
		balance of pennies.  There is a service fee, but it is minimal.
		E-Gold was designed and is really meant to be used as a (convertible)
		currency backed by hard assets.
		<p>
		Pluses:  dozens of market makers make it easy to convert to and from 
		e-gold; you are not dependent on one corporation for conversion.
		Simple open-source programming API.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
         	<a href="http://www.ezcmoney.com/">EZCmoney</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
	 	EZCmoney is an electronic merchant payment system.  Consumers can
		deposit money in an EZCmoney account, and then tell a merchant thier
		account number.  Transaction approval happens by email.  
		Customer-to-customer transactions are not currently supported.
		EZCmoney claims to provide a level of security that credit-card 
		based shopping does not.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
         	<a href="http://www.webmoney.com/">WebMoney</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
	        No obvious way to redeem.  No programming interfaces
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-start.phtml"); ?>
         	<a href="http://www.goldmoney.com/">GoldMoney</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-middle.phtml"); ?>
	        ?
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/en/components/links-end.phtml"); ?>

   </table>
</tr>
</table>
