<div>
    <h2>Gnucash Review &amp; Rating Sites</h2>
    Sites that rate, review, rank or publicize gnucash.

    <ul>
    <li><a href="http://freshmeat.net/projects/gnucash/?highlight=gnucash">Freshmeat</a>

    <li>ZD Net <a href="http://www.appwatch.com/Linux/App/571/data.html">
        AppWatch</a> will email a notification to you when a new version
        of gnucash is out. Also lists a 'popularity index'.
    <li><a href="http://www.icewalk.com/softlib/app/app_00056.html">IceWalkers</a>      
        lists lots of open-source projects.
    <li><a href="http://linux.davecentral.com/6044_officeacct.html">Dave 
        Central</a>.  
    <li><a href="http://www.linuxberg.com/x11html/preview/9340.html">Tucows</a>
    <li><a href="http://www.softseek.com/Linux/Home_Family_and_Leisure/Home_Finance/Review_42842_index.html">
	Softseek</a>
    </ul>
</div>
