<div class="tblborder">
   <table class="tbllimit" cellpadding=5 cellspacing=1>
   <colgroup><col width="25%"><col width="50%"></colgroup>
   <tr>
     <td class="tblheader"><b>Name</b></td>
     <td class="tblheader"><b>Description</b></td>
   </tr>
   <tr class="tblbanner">
   <td colspan=2><B>Quote Sources, Tools</B>
   </td>
   </tr>
   <tr>
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://finance-quote.sourceforge.net/">Finance::Quote</a>
   </td><td>
	 Perl module for getting stock price and currency exchange rate data 
	 from a variety of web sources.
   </td></tr>

   <tr class="divider">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://getquote.giammy.com/">GetQuote</a>
   </td><td>
	 A command-line tool for getting stock quotes. Implemented in C.
   </td></tr>

   <tr>
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.marketwatch.com/tools/quotes/basic.asp?siteid=mktw">
	CBS MarketWatch</a>
   </td><td>
	 Free data streaming.
   </td></tr>
	 
   <tr class="divider">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.datek.com/">Datek</a>
   </td><td>
	 Free data streaming.
   </td></tr>

   <tr>
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://quicken.excite.com/investments/quotes/">Excite - Quicken</a>
   </td><td>
	 Free data streaming.
   </td></tr>

   <tr class="divider">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.financialweb.com/mktIndex.asp">FinancialWeb</a>
   </td><td>
	 Free data streaming.
   </td></tr>

   <tr>
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://freerealtime.com">FreeRealTime</a>
   </td><td>
	 Free data streaming.
   </td></tr>

   <tr class="divider">
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://money.go.com">GoMoney - ABC News</a>
   </td><td>
	 Free data streaming.
   </td></tr>
	 
   <tr>
   <td><img src="/images/icons/document.txt.gif" width=16 height=16 
	alt="document icon">
	 <a href="http://www.money.net">MoneyNet</a>
   </td><td>
	 Free data streaming.
   </td></tr>
   </table>
</div>

