
    <h2>Sitios que Reviram &amp; Avaliaram o GnuCash</h2>
    Sítios que avaliaram, reviram, compararam ou fizeram publicidade ao gnucash.

    <ul>
    <li><a href="http://freshmeat.net/projects/gnucash/?highlight=gnucash">Freshmeat</a>
        
    <li>ZD Net <a href="http://www.appwatch.com/Linux/App/571/data.html">
        AppWatch</a> enviar-lhe-á por email uma notificação quando uma nova versão
        do gnucash sair. Também lista um 'índice de popularidade'.
    <li><a href="http://www.icewalk.com/softlib/app/app_00056.html">IceWalkers</a>      
        lista imensos projectos de código aberto.
    <li><a href="http://linux.davecentral.com/6044_officeacct.html">Dave 
        Central</a>.  
    <li><a href="http://www.linuxberg.com/x11html/preview/9340.html">Tucows</a>
    <li><a href="http://www.softseek.com/Linux/Home_Family_and_Leisure/Home_Finance/Review_42842_index.html">Softseek</a>
    </ul>
