
<table border=0 cellpadding=1 cellspacing=0 width="100%">
  <tr>
  <td valign=middle align=center bgcolor=#666699>
   <table border=0 cellpadding=5 cellspacing=1 bgcolor=#cacaf7 width="100%">
   <tr>
     <td bgcolor=#666699 width=25%><font color=#ffffff><b>Nome</b></td>
     <td bgcolor=#666699 width=50%><font color=#ffffff><b>Descrição</b></td>
   </tr>
   <tr>
     <td colspan=2>
<B>XML e Outros Formatos de Dados</B><BR>
     </td>
   </tr>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://www.semper.org/">Mercado Electrónico Seguro para a Europa</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 SEMPER é um projecto Europeu de I&amp;D na área do comércio electrónico 
		 seguro sobre redes abertas.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://ganges.cs.tcd.ie/mepeirce/Project/oninternet.html">Mecanismos 
		 de pagamento desenhados para a Internet</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 Disponibiliza uma arca do tesouro de links para ziliões de standards e propostas.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://www.cloanto.com/specs/seriff.html">SERIFF</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 Simple Exchange Rate Information File Format (Formato de Ficheiro de Informação Símples de Taxas de Câmbio).  Completamente centrado em *.ini 
		 tanto na disposição como desenho, mas de qualquer modo bastante completo.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://www.cosource.com/cgi-bin/cos.pl/wish/info/339">Leitor de 
		 Ficheiros Quicken</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 RFP na Cosource está disposto a pagar $25,000 por um leitor de ficheiros que 
		 consiga ler nativamente os ficheiros Quicken.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://www.ifxforum.org">Forum IFX</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 Protocolo de troca de informação financeira baseado em XML desenvolvido por vários bancos.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://www.ofx.net/">Mercado Financeiro Aberto</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 Um consórsio apoiado pela Intuit, CheckFree e Microsoft para desenvolver 
		 a banca on-line. Principalmente a definição do OFX, um protocolo baseado em XML 
		 para a troca de informação bancária e cobrança de facturas on-line.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://http://www.otp.org/">Protocolo de Troca Aberta</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 Um protocolo de mensagens baseado em XML para pagamento, apresentação de facturas, 
		 e recibos de pagamento.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://www.fpml./org">FpML - Linguagem por Etiquetas de Produtos Financeiros</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 Protocolo baseado em XML para a troca de instrumentos financeiros.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://www.europay.ch/products/systems/dta/dta-en.html">DTA</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 (Daten Traeger Austausch) é um formato de banca online banking utilizado 
		 na Suiça por --todos-- os bancos Suiços.  O formato é aberto.  Veja também a 
		 aplicação dtaus no metalab.unc.edu ou réplicas.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://www.hbci.de/english/index.html">HBCI</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
	         Home Banking Computer Interface (Interface por Computador de Home Banking) -- um protocolo de banking 
		 amplamente utilizado por bancos Alemães.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://www.smbxml.org">XML de Pequenas Empresas</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 DTD de XML documentado publicamente para a execução de pequenas e médias 
		 transacções de negócios.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://www.openapplications.org/">Grupo de Aplicações Abertas</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 Especificações para interoperbilidade baseada em XML de aplicações de negócios.  
		 Inclui especificações XML para pedidos de cotação, envio, & numerosos outros projectos.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://www.compassgl.org/newhometest/990305fr1.html">Disponibilização 
		 do Plano de COntas OMG</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 A proposta da Compass para o Plano de Contas OMG (CORBA).
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://www.xfrml.org/">XFRML, Linguagem baseada em XML para 
		 Relatórios Financeiros</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 Citação da página deles: <i>XFRML é uma estrutura que irá permitir à 
		 comunidade financeira um método baseado em standards de preparar, publicar 
		 numa variedade de formatos, trocar e analisar relatórios financeiros e a 
		 informação que eles contêm.</i> 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>
   </table>
</tr>
</table>
