
<table border=0 cellpadding=1 cellspacing=0 width="100%">
  <tr>
  <td valign=middle align=center bgcolor=#666699>
   <table border=0 cellpadding=5 cellspacing=1 bgcolor=#cacaf7 width="100%">
   <tr>
     <td bgcolor=#666699 width=25%><font color=#ffffff><b>Nome</b></td>
     <td bgcolor=#666699 width=50%><font color=#ffffff><b>Descrição</b></td>
   </tr>
   <tr>
     <td colspan=2>
<B>Variados</B><BR>
     </td>
   </tr>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://www.unixrealm.com/downloads/">Unixrealm</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 Binários Gnome e GnuCash para Solaris.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://www.sabotage.net/security/ecash/lucre/"> -lucre</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 Uma versão publicamente disponível do e-cash.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://www.ibm.com/java/sanfrancisco">IBM San Francisco</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 Classes Java de Negócios e Finanças.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://www.integrion.com/">Integrion</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 Um consórcio formado por mais de 16 bancos e a IBM com o objectivo de construir uma 
		 infra-estrutura de banca on-line.  Actualmente disponível nalguns grandes bancos.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://www.sun.com/980224/javapos/">Java Point of Sale Ponto de Venda)</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 &nbsp;
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://www.pango.org/">Pango</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 Renderização de texto internacionalizado para gtk.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="ftp://ftp.gnu.org/pub/gnu/plotutils/">Gnu Plotutils</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 Um pacote de grafismo e plotagem.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
         	<a href="http://www.im.lcs.mit.edu/~magnus/ml/">GTK grid widget</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 Pode ser melhor que o Clint, para gtk
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://www.didx.com/xml-builder.html">XML Builder</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 Permite que ecrãs de Interface ráfico sejam descritos em XML. Veja também o xpfe no mozilla.org.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://www.engelschall.com/sw/eperl">Perl Embebido</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 Permite embeber perl em páginas html para criar conteúdo dinâmico.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://www.ispras.ru/~knizhnik/gigabase.html">GigaBASE</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 Base de dados SQL embebível.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>
   </table>
</tr>
</table>
