
<table border=0 cellpadding=1 cellspacing=0 width="100%">
  <tr>
  <td valign=middle align=center bgcolor=#666699>
   <table border=0 cellpadding=5 cellspacing=1 bgcolor=#cacaf7 width="100%">
   <tr>
     <td bgcolor=#666699 width=25%><font color=#ffffff><b>Nome</b></td>
     <td bgcolor=#666699 width=50%><font color=#ffffff><b>Descrição</b></td>
   </tr>
   <tr>
	   <td colspan=2>
<B>Corretagem de Acções & Análise Técnica</B><BR>
     </td>
	 </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://avidus.sourceforge.net/">Avidus</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Aplicação de análise técnica & chartismo de acções.  Baseada em GTK.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://ffts.sourceforge.net/">FFTS Finicky Financial Trading System</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Acompanha transacções, disponibiliza relatórios de risco.  Um sistema de corretagem 'front office'.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.freemarket-project.org/">FreeMarket</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Aplicação de análise técnica & chartismo de acções.  Suporta scripts Easy Language TradeStation.  O servidor suporta leitura de dados em tempo real Datek.  Este sitio web é muito bonito, e o seu objectivo é construir à sua volta uma completa comunidade de utilizadores.  
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://gchartman.sourceforge.net/">gChartman</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Uma aplicação gtk/gnome para chartismo técnico de acções.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://prope.insa-lyon.fr/~rhertzog/geniustrader/">Genius Trader</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Ferramenta de chartismo de acções. Baseada em Perl e Tk.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://gstalker.sourceforge.net/">gstalker</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Chartismo de acções em GTK/Gnome.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.centercube.com/GtkPortfolio/news.html">GtkPortfolio</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Ferramenta de acompanhamento do portfólio.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://kstocks.sourceforge.net/">KStocks</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Ferramenta de chartismo de acções baseada em KDE. Ainda primitiva.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://eiffel-mas.sourceforge.net/">MAS Market Analysis System</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Cliente-servidor.  Suporta uma grande variedade de indicadores técnicos comlexos.  Tem clientes para Linux, MSWindows.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://tree.sourceforge.net/">TREE</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Um servidor de base de dados de histórico de preços.  Actualiza-se automaticamente através da captura de um stream de dados.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.daveware.com/linuxrapid.html">Xrapid</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		  Análise técnica de acções.
		 </td>
   </tr>
   </table>
</tr>
</table>
