
<table border=0 cellpadding=1 cellspacing=0 width="100%">
  <tr>
  <td valign=middle align=center bgcolor=#666699>
   <table border=0 cellpadding=5 cellspacing=1 bgcolor=#cacaf7 width="100%">
   <tr>
     <td bgcolor=#666699 width=25%><font color=#ffffff><b>Nome</b></td>
     <td bgcolor=#666699 width=50%><font color=#ffffff><b>Descrição</b></td>
   </tr>
   <tr>
     <td colspan=2>
<B>Fontes de Cotações, Ferramentas</B><BR>
     </td>
   </tr>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://finance-quote.sourceforge.net/">Finance::Quote</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 Módulo em Perl para obter preços de acções e taxas de câmbio 
		 a partir de uma variedade de fontes na web.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://getquote.giammy.com/">GetQuote</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 Uma ferramenta de linha de comando para obter cotações de acções. Implementada em C.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://www.marketwatch.com/tools/quotes/basic.asp?siteid=mktw">CBS
		 MarketWatch</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 Stream de dados gratuito.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://www.datek.com/">Datek</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 Stream de dados gratuito.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://quicken.excite.com/investments/quotes/">Excite - Quicken</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 Stream de dados gratuito.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://www.financialweb.com/mktIndex.asp">FinancialWeb</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 Stream de dados gratuito.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://freerealtime.com">FreeRealTime</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 Stream de dados gratuito.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://money.go.com">GoMoney - ABC News</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 Stream de dados gratuito.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://www.money.net">MoneyNet</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 Stream de dados gratuito.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>
   </table>
</tr>
</table>
