
<table border=0 cellpadding=1 cellspacing=0 width="100%">
  <tr>
  <td valign=middle align=center bgcolor=#666699>
   <table border=0 cellpadding=5 cellspacing=1 bgcolor=#cacaf7 width="100%">
   <tr>
     <td bgcolor=#666699 width=25%><font color=#ffffff><b>Nome</b></td>
     <td bgcolor=#666699 width=50%><font color=#ffffff><b>Descrição</b></td>
   </tr>
   <tr>
     <td colspan=2>
<B>Referências Genéricas</B><BR>
     </td>
     </tr>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://www.gldialtone.com/links.htm">Links maravilhosos GL Dialtone'</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 Disponibiliza uma listagem extensa de links para planos de contas web, aplicações de contabilidade, 
		 serviços empresarias/asp, facturação electrónica e afins.  
		 A própria <a href="http://www.gldialtone.com/">General Ledger Dialtone</a> 
		 disponibiliza vasta informação e um forum de discussão 
		 para ideis inovadoras de contabilidade.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://www.transaction.net/money/">Como Funciona o Dinheiro</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
	         Dinheiro não tem de ser uma moeda nacional: podem ser milhas de passageiro
		 frequente, horas de trabalho, e outras coisas.  Esta página revê a própria
		 ideia de dinheiro, e lista as características dos diferentes tipos de dinheiro.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://www.e-gold.com/e-gold.asp?cid=281678">E-Gold</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 E-gold é uma moeda electrónica.  Ao contrário de uma moeda nacional, é 
		 emitida privadamente, e suportada por reservas em ouro.  Ao contrário de um cartão de crédito,
		 é um pouco mais anónimo, mas não tão anónimo como o dinheiro.
		 A crescer em popularidade lentamente.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://www.iasc.org.uk/frame/cen2.htm">Standards Internacionais 
		 de Contabilidade</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 Comité dos Standards Internacionais de Contabilidade.  Seco, mas uma boa fonte
		 para documentos técnicos e legais que definem as regras contabilísticas.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://www.hex.net/~cbbrowne/finances.html">Finanças, Linux 
		 e Outras do CBBrowne</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 O Christopher Browne analisa uma série de aplicações financeiras para o Linux.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-start.phtml"); ?>
		 <a href="http://www.linuxlinks.com/Software/Financial/">Aplicações 
		 Financeiras LinuxLinks</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-middle.phtml"); ?>
		 Uma vasta lista de aplicações livres e comerciais.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/pt_PT/components/links-end.phtml"); ?>
  </table>
</tr>
</table>
