
<font size=-1>
Os URLs seguintes estão desactivos, obsoletos ou de qualquer outra forma
a desperdiçar espaço, mas encontram-se aqui por interesse historico, em parte para documentar
a forma como as coisas costumavam ser. Apenas para utilização arqueológica ou
nostálgica.
</font>

<br><br>

<table border=0 cellpadding=1 cellspacing=0 width="100%">
  <tr>
  <td valign=middle align=center bgcolor=#666699>
   <table border=0 cellpadding=5 cellspacing=1 bgcolor=#cacaf7 width="100%">
   <tr>
     <td bgcolor=#666699 width=25%><font color=#ffffff><b>Nome</b></td>
     <td bgcolor=#666699 width=50%><font color=#ffffff><b>Descrição</b></td>
   </tr>
   <tr>
	   <td colspan=2>
<B>Referências Históricas</B><BR>
     </td>
	 </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www3.hmc.edu/~rclark/xacc/">Página Principal do X-Accountant</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Esta era a página original do pacote de contabilidade em licença GPL que eventualmente evoluiu para o GnuCash. Robin Clark escreveu a primeira versão enquanto estudante no Harvey Mudd College.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.dnaco.net/~bcooper/watermark/index.html">WaterMark</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Página do projecto de finanças pessoais em Gnome/KDE.  Watermark e GnoMoney foram propostos simultaneamente, e houve uma discussão sobre unirem esforços com o X-Accountant.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.im.lcs.mit.edu/~magnus/ml/">Maxwell's Lemur</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Widget de tabela baseado em GTK 
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.telly.org/freemoney/">FreeMoney</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Aplicação de contabilidade para pequenas empresas para Linux.  Uma proposta para construir um pacote empresarial apoiado por SQL.
		 </td>
   </tr>
   </table>
</tr>
</table>
