
<table border=0 cellpadding=1 cellspacing=0 width="100%">
  <tr>
  <td valign=middle align=center bgcolor=#666699>
   <table border=0 cellpadding=5 cellspacing=1 bgcolor=#cacaf7 width="100%">
   <tr>
     <td bgcolor=#666699 width=25%><font color=#ffffff><b>Nome</b></td>
     <td bgcolor=#666699 width=50%><font color=#ffffff><b>Descrição</b></td>
   </tr>
   <tr>
	   <td colspan=2>
<B>Empresas, Projectos ERP</B><BR>
     </td>
	 </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
         <a href="http://www.gnue.org/">Gnu Enterprise</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
     O principal projecto Gnu/GPL com o objectivo de criar um sistema ERP para pequenas, médas e grandes empresas.   Este é um projecto ambicioso, mas é a estrela no panorama.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <A HREF="http://sql-ledger.com/">SQL Ledger</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Um avançado pacote de contabilidade empresarial baseado na web, com licença GPL.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.openadaptor.org/">Open Adaptor</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Um conjunto de utilitários baseados em Java/XML para aceder e converter entre muitos diferentes formatos de dados (financeiros & empresariais).  Suporte para Oracle, Sybase, TIBCO, XML, Fix, Swift, e HTML.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.ios-online.de/Linux-Kontor/">Linux-Kontor</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Um pacote de contabilidade industrial que utiliza Java e bases de dados SQL.
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://obelisk.dhs.org">Obelisk</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
      Projecto de Contabilidade Empresarial
		 </td>
   </tr>
   <tr bgcolor=#ffffff>
     <td valign=top>
       <table border=0 cellpadding=0 cellspacing=0>
       <tr>
         <td valign=top><img src=/images/icons/document.txt.gif width=16 height=16 border=0>&nbsp;</td>
				 <td>
				 <a href="http://www.sisd.com/freeside/">Freeside</a>
				 </td>
       </tr>
       </table>
     </td>
     <td valign=top>
		 Um pacote em código aberto de administração financeira e facturação para Fornecedores de Internet.
		 </td>
   </tr>
   </table>
</tr>
</table>
