
<?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-header.phtml"); ?>
   <tr> <td colspan=2>
<B>Business, ERP Projects</B><BR>
     </td> </tr>
     
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-start.phtml"); ?>
         	<a href="http://sourceforge.net/projects/gnupos/">GnuPOS</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-middle.phtml"); ?>
     		GPL'ed Point-of-Sale systeem.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-start.phtml"); ?>
         	<a href="http://sourceforge.net/projects/mercator">Mercator</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-middle.phtml"); ?>
     		Java-based Point-of-Sale systeem.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-start.phtml"); ?>
         	<a href="http://www.bananahead.com/pos/index.html">BananaheadPOS</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-middle.phtml"); ?>
     		Web-based GPL'ed Point-of-Sale systeem.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-start.phtml"); ?>
         	<a href="http://www.gnue.org/">Gnu Enterprise</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-middle.phtml"); ?>
     		Het eerste Gnu/GPL project gericht op het creeren van een 
		ERP systeem voor kleine, middelgrote en grote bedrijven.   
		Dit is een ambitieus project.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-start.phtml"); ?>
		 <A HREF="http://sql-ledger.com/">SQL Register</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-middle.phtml"); ?>
		 Een geavanceer, GPL'ed, web-based zakelijk boekhoudpakket.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-start.phtml"); ?>
		 <a href="http://www.zelerate.org/">
		 Zelerate AllCommerce</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-middle.phtml"); ?>
	         A GPL'ed e-commerce package.  Provides modules for 
	         content creation, inventory management, product ordering, 
		 statistical analysis, shipping and merchandising. 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-start.phtml"); ?>
		 <a href="http://www.openadaptor.org/">Open Adaptor</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-middle.phtml"); ?>
		 Een Java/XML based set van toepassingen voor toegang tot en conversie van 
                 vele verschillende (financiele & zakelijke) data formaten.  
		 Ondersteund Oracle, Sybase, TIBCO, XML, Fix, Swift, en HTML.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-start.phtml"); ?>
		 <a href="http://www.ios-online.de/Linux-Kontor/">Linux-Kontor</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-middle.phtml"); ?>
		 Een zakelijk boekhoudpakket dat gebruik maakt van Java en SQL databases.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-start.phtml"); ?>
		 <a href="http://obelisk.dhs.org">Obelisk</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-middle.phtml"); ?>
      		Zakelijk boekhoudproject
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-start.phtml"); ?>
		 <a href="http://www.sisd.com/freeside/">Freeside</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-middle.phtml"); ?>
		 An open source billing and account administration package for ISP's.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-start.phtml"); ?>
		 <a href="http://www.freepm.org/">FreePM Free Practice Management</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-middle.phtml"); ?>
		 FreePM is an open source toepassing voor medisch office management &amp;
                 electronische medische documenten.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-end.phtml"); ?>
   </table>
</tr>
</table>
