
<font size=-1>
The following URL's are inactive, obsolete or otherwise wasting
away, but are here for historical interest, in part to document
the way things used to be. Of archeological, nostalgic use
only.
</font>

<br><br>

<?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-header.phtml"); ?>


	 
   <tr> <td colspan=2>
<B>Historical References</B><BR>
     </td> </tr>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-start.phtml"); ?>
		 <a href="http://www.cs.hmc.edu/~rclark/xacc/">X-Accountant Home Page</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-middle.phtml"); ?>
		 This was the original site for the GPL'ed accounting 
		 package that eventually evolved into GnuCash. Robin Clark wrote 
		 the first version while at school at Harvey Mudd College.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-start.phtml"); ?>
		 <a href="http://www.dnaco.net/~bcooper/watermark/index.html">WaterMark</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-middle.phtml"); ?>
		 Gnome/KDE personal finance project page.  Watermark and 
		 GnoMoney were proposed about the same time, and there was talk 
		 of joining forces with X-Accountant.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-start.phtml"); ?>
		 <a href="http://www.im.lcs.mit.edu/~magnus/ml/">Maxwell's Lemur</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-middle.phtml"); ?>
		 GTK based table widget
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-start.phtml"); ?>
		 <a href="http://www.telly.org/freemoney/">FreeMoney</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-middle.phtml"); ?>
		 Linux small-business accounting s/w.  A proposal to build a 
		 business package backed by SQL.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-end.phtml"); ?>
   </table>
</tr>
</table>
