
<?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-header.phtml"); ?>

   <tr>
     <td colspan=2>
<B>Referenties</B><BR>
     </td>
     </tr>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-start.phtml"); ?>
		 <a href="http://www.gldialtone.com/links.htm">GL Dialtone's Links</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-middle.phtml"); ?>
		 heeft een uitgebreide lijst met links naar web-registers, boekhoudsoftware,
                 zakelijke services, electronisch betalen, en dergelijke.  
		 <a href="http://www.gldialtone.com/">General Ledger Dialtone</a> vermeldt uitgebreide informatie en een discussieforum voor vooruitstrevende boekhoudideeen.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-start.phtml"); ?>
		 <a href="http://www.transaction.net/money/">Hoe Geld Werkt</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-middle.phtml"); ?>
	         Geld hoeft niet per se in valuta uitgedrukt te worden. Denk ook eens aan uw airmiles, spaarpunten, etc. Deze pagina verschaft een overzicht over de diverse karakteristieken van de verschillende vormen van geld.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-start.phtml"); ?>
		 <a href="http://www.e-gold.com/e-gold.asp?cid=281678">E-Gold</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-middle.phtml"); ?>
		 E-gold is electronische vorm van geld. In tegenstelling tot nationale valuta wordt het door privepersonen uitgegeven en is er een goudvoorraad die garant staat. Het is echter anoniemer dan een credit card, maar niet zo anoniem als contant geld. Het groeit langzaam aan populariteit.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-start.phtml"); ?>
		 <a href="http://www.iasc.org.uk/frame/cen2.htm">Internationale Boekhoudstandaards</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-middle.phtml"); ?>
		 Internationaal Accounting Standards Committee.  Droog, maar een goede informatiebron voor technische en juridische documenten die de boekhoudregels definieren.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-start.phtml"); ?>
		 <a href="http://cbbrowne.com/info/finances.html">CBBrowne's Finances, 
		 Linux, and Stuff</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-middle.phtml"); ?>
		 Christopher Browne beschrijft een aantal financiele applicaties voor Linux.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-end.phtml"); ?>

	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-start.phtml"); ?>
		 <a href="http://www.linuxlinks.com/Software/Financial/">LinuxLinks 
		 Financial Software</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-middle.phtml"); ?>
		 Een uitgebriede lijst van gratis en commerciele programmas.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-end.phtml"); ?>
  </table>
</tr>
</table>
