
<?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-header.phtml"); ?>

   <tr><td colspan=2>
<B>Palm Computing</B><BR>
   </td> </tr>
   
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-start.phtml"); ?>
         	<A HREF="http://sourceforge.net/projects/pm2qif/">pm2qif PocketMoney 
		to QIF Converter</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-middle.phtml"); ?>
		  A set of perl scripts to convert PocketMoney DB files to QIF 
		  files.  PocketMoney is a popular Palm shareware accounting package.
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-end.phtml"); ?>
	 
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-start.phtml"); ?>
		 <A HREF="http://sourceforge.net/projects/freecoins/">FreeCoins</a>
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-middle.phtml"); ?>
		 A GPL'ed accounting program for the PalmOS
	 <?php include($GLOBALS['DOCUMENT_ROOT']."/nl/components/links-end.phtml"); ?>
   </table>
</tr>
</table>
