<html>
<head>
<link rel="stylesheet" href="../www/externals/old-gnucash.css" type="text/css">
<title>GnuCash - <?php echo $title; ?></title>
</head>

<body bgcolor=#ffffff topmargin="0" leftmargin="0" marginwidth="0" marginheight="0"> 

<table border=0 cellpadding=3 cellspacing=0 width="100%">
<tr>
<td valign=bottom colspan=2 bgcolor=#666699><img src="../www/images/gnucash_logo1.png"></td>
<td align=right valign=bottom bgcolor=#666699 width=45%><font size=-1 color=#ffffff>
Idioma: 
<a class=nav href=/en/>Inglês</a> 
| <a class=nav href=http://www.hthoma.de/projekte/gnucash/index.html>Alemão</a>
 (<a class=nav href=/de/>réplica</a>) 
| <a class=nav href=/fr/>Francês</a>
| <a class=nav href=/nl/>Nederlands</a>
| <b>Português</b>
 (<a class=nav href="http://www.au.gnucash.org/pt_PT/">réplica</a>) 
&nbsp;</font></td>
</tr>
</table>

<table border=0 cellpadding=3 cellspacing=0 width="90%">
<tr>
<td valign=top width=1% bgcolor=#ffffff>
<img src="../www/images/spacer.gif" width="200" height="1"><br>
